/**
 * @author: chenmin
 * @date: 2011-11-02
 * @desc: constants definition: request type, data limitations
 */

Downsha.Constants = {
  CLIP_ACTION_FULL_PAGE : "CLIP_ACTION_FULL_PAGE",
  CLIP_ACTION_ARTICLE : "CLIP_ACTION_ARTICLE",
  CLIP_ACTION_SELECTION : "CLIP_ACTION_SELECTION",
  CLIP_ACTION_URL : "CLIP_ACTION_URL",
  
  PREVIEW_NUDGE_PREVIOUS_SIBLING : "PREVIEW_NUDGE_PREVIOUS_SIBLING",
  PREVIEW_NUDGE_NEXT_SIBLING : "PREVIEW_NUDGE_NEXT_SIBLING",
  PREVIEW_NUDGE_PARENT : "PREVIEW_NUDGE_PARENT",
  PREVIEW_NUDGE_CHILD : "PREVIEW_NUDGE_CHILD",
  
  SERVICE_PATH : "http://ysync.downsha.com/clipper/",  //"http://localhost/"
  
  CLIP_NOTE_CONTENT_LEN_MAX : 10 * 1048576 // 10MB
};
