var Downsha=Downsha||{};Downsha.inherit=function(a,b,c){"function"==typeof b.constructor?(a.prototype=new b,a.prototype.constructor=a,a.parent=b.prototype):(a.prototype=b,a.prototype.constructor=a,a.parent=b);if(c)for(var d in b.prototype.constructor)"parent"!=d&&"prototype"!=d&&"javaClass"!=d&&b.constructor[d]!=b.prototype.constructor[d]&&(a.prototype.constructor[d]=b.prototype.constructor[d]);"function"==typeof a.prototype.handleInheritance&&a.prototype.handleInheritance.apply(a,[a,b,c])};
Downsha.inherits=function(a,b){for(var c=a;c&&"undefined"!=typeof c.parent;){if(c.parent.constructor==b)return!0;c=c.parent.constructor}return!1};Downsha.mixin=function(a,b,c){var a="function"==typeof a?a.prototype:a,d;for(d in b.prototype){var e=to=d;"object"==typeof c&&c&&"undefined"!=typeof c[d]&&(to=c[d]);a[to]=b.prototype[e]}};
Downsha.extendObject=function(a,b,c){if("object"==typeof b&&null!=b)for(var d in b)if(c&&"object"==typeof b[d]&&null!=b[d]&&"object"==typeof a[d]&&null!=a[d])Downsha.extendObject(a[d],b[d],c);else try{a[d]=b[d]}catch(e){}};Downsha.hasOwnProperty=function(a,b){if("object"==typeof a){if(a.hasOwnProperty(b))return!0;for(var c=null,c=a;c=c.__proto__;)if(c.hasOwnProperty(b))return!0}return!1};Downsha.DefiningMixin=function(){};
Downsha.DefiningMixin._getTargetFor=function(a){return"function"==typeof a&&a==a.prototype.constructor?a.prototype:a};Downsha.DefiningMixin.prototype.__defineBoolean__=function(a,b,c,d){var e="_"+a,f=a.substring(0,1).toUpperCase()+a.substring(1),g=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);g[e]=b?!0:!1;if(!c){var h="is"+f;g[h]=function(){return this[e]};this.__defineGetter__(a,g[h])}d||(f="set"+f,g[f]=function(a){this[e]=a?!0:!1},this.__defineSetter__(a,g[f]))};
Downsha.DefiningMixin.prototype.__defineFloat__=function(a,b,c,d){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!1,parseFloat,c,d)};Downsha.DefiningMixin.prototype.__definePositiveFloat__=function(a,b,c,d){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!0,parseFloat,c,d)};
Downsha.DefiningMixin.prototype.__defineInteger__=function(a,b,c,d){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!1,parseInt,c,d)};Downsha.DefiningMixin.prototype.__definePositiveInteger__=function(a,b,c,d){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!0,parseInt,c,d)};
Downsha.DefiningMixin.prototype._createNumericDefinition_=function(a,b,c,d,e,f,g){var h=b.substring(0,1).toUpperCase()+b.substring(1),j="_"+b,c="number"==typeof c?c:null;a||(a=this);a[j]=c;f||(f="get"+h,a[f]=function(){return this[j]},this.__defineGetter__(b,a[f]));g||(g="set"+h,a[g]=d?function(a){this[j]=e(a);if(isNaN(this[j])||this[j]<0)this[j]=c}:function(a){this[j]=e(a);isNaN(this[j])&&(this[j]=c)},this.__defineSetter__(b,a[g]))};
Downsha.DefiningMixin.prototype.__defineString__=function(a,b,c,d){var b=b?b:null,e=a.substring(0,1).toUpperCase()+a.substring(1),f="_"+a,g=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);g[f]=b;if(!c){var h="get"+e;g[h]=function(){return this[f]};this.__defineGetter__(a,g[h])}d||(e="set"+e,g[e]=function(a){this[f]="string"==typeof a?a:a?""+a:b},this.__defineSetter__(a,g[e]))};
Downsha.DefiningMixin.prototype.__defineType__=function(a,b,c,d,e){var c=c?c:null,f="_"+a,g=a.substring(0,1).toUpperCase()+a.substring(1),h=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);h[f]=c;if(!d){var j="get"+g;h[j]=function(){return this[f]};this.__defineGetter__(a,h[j])}e||(g="set"+g,h[g]=function(a){if("string"==typeof b&&a&&a.constructor.name==b)this[f]=a;else if("function"==typeof b&&a instanceof b)this[f]=a;else{if(a)throw Error("Expected "+("string"==typeof b?b:b.name)+" but got "+
typeof a);this[f]=c}},this.__defineSetter__(a,h[g]))};
Downsha.Logger=function(a,b,c){this.__defineGetter__("level",this.getLevel);this.__defineSetter__("level",this.setLevel);this.__defineGetter__("scope",this.getScope);this.__defineSetter__("scope",this.setScope);this.__defineGetter__("scopeName",this.getScopeName);this.__defineGetter__("scopeNameAsPrefix",this.getScopeNameAsPrefix);this.__defineGetter__("useTimestamp",this.isUseTimestamp);this.__defineSetter__("useTimestamp",this.setUseTimestamp);this.__defineGetter__("usePrefix",this.isUsePrefix);
this.__defineSetter__("usePrefix",this.setUsePrefix);this.__defineGetter__("enabled",this.isEnabled);this.__defineSetter__("enabled",this.setEnabled);this.scope=a||arguments.callee.caller;this.level=b;if("undefined"!=typeof c&&c instanceof Downsha.LoggerImpl)this.impl=c;else{var d=Downsha.LoggerImplFactory.getImplementationFor(navigator);this.impl=d instanceof Array?new Downsha.LoggerChainImpl(this,d):new d(this)}};Downsha.Logger.LOG_LEVEL_DEBUG=0;Downsha.Logger.LOG_LEVEL_INFO=1;
Downsha.Logger.LOG_LEVEL_WARN=2;Downsha.Logger.LOG_LEVEL_ERROR=3;Downsha.Logger.LOG_LEVEL_EXCEPTION=4;Downsha.Logger.LOG_LEVEL_OFF=5;Downsha.Logger.GLOBAL_LEVEL=Downsha.Logger.LOG_LEVEL_ERROR;Downsha.Logger.DEBUG_PREFIX="[DEBUG] ";Downsha.Logger.INFO_PREFIX="[INFO] ";Downsha.Logger.WARN_PREFIX="[WARN] ";Downsha.Logger.ERROR_PREFIX="[ERROR] ";Downsha.Logger.EXCEPTION_PREFIX="[EXCEPTION] ";Downsha.Logger._instances={};
Downsha.Logger.getInstance=function(a){var a=a||arguments.callee.caller,b="function"==typeof a?a.name:a.constructor.name;"undefined"==typeof this._instances[b]&&(this._instances[b]=new Downsha.Logger(a));return this._instances[b]};Downsha.Logger.setInstance=function(a){this._instance=a};Downsha.Logger.destroyInstance=function(a){a=a||arguments.callee.caller;delete this._instances["function"==typeof a?a.name:a.constructor.name]};
Downsha.Logger.setGlobalLevel=function(a){a=parseInt(a);if(!isNaN(a)&&(Downsha.Logger.GLOBAL_LEVEL=a,this._instances))for(var b in this._instances)this._instances[b].setLevel(a)};Downsha.Logger.setLevel=function(a){if(this._instances)for(var b in this._instances)this._instances[b].setLevel(a)};Downsha.Logger.enableImplementor=function(a){if(this._instances)for(var b in this._instances)this._instances[b].enableImplementor(a);a&&(a.protoEnabled=!0)};
Downsha.Logger.disableImplementor=function(a){if(this._instances)for(var b in this._instances)this._instances[b].disableImplementor(a);a&&(a.protoEnabled=!1)};Downsha.Logger.prototype._level=0;Downsha.Logger.prototype._scope=null;Downsha.Logger.prototype._usePrefix=!0;Downsha.Logger.prototype._useTimestamp=!0;Downsha.Logger.prototype._enabled=!0;Downsha.Logger.prototype.getImplementor=function(a){return a?this.impl.answerImplementorInstance(a):this.impl};
Downsha.Logger.prototype.enableImplementor=function(a){if(a){if(a=this.getImplementor(a))a.enabled=!0}else this.impl.enabled=!0};Downsha.Logger.prototype.disableImplementor=function(a){if(a){if(a=this.getImplementor(a))a.enabled=!1}else this.impl.enabled=!1};Downsha.Logger.prototype.setLevel=function(a){this._level=parseInt(a);isNaN(this._level)&&(this._level=Downsha.Logger.GLOBAL_LEVEL)};Downsha.Logger.prototype.getLevel=function(){return this._level};
Downsha.Logger.prototype.setScope=function(a){"function"==typeof a?this._scope=a:"object"==typeof a&&null!=a&&(this._scope=a.constructor)};Downsha.Logger.prototype.getScope=function(){return this._scope};Downsha.Logger.prototype.getScopeName=function(){return this.scope?this.scope.name:""};Downsha.Logger.prototype.getScopeNameAsPrefix=function(){var a=this.scopeName;return a?"["+a+"] ":""};
Downsha.Logger.prototype._padNumber=function(a,b){a=parseInt(a);isNaN(a)&&(a=0);for(var c=0<=a?!0:!1,d=""+Math.abs(a);d.length<b;)d="0"+d;c||(d="-"+d);return d};
Downsha.Logger.prototype.getPrefix=function(a){var b="";if(this.useTimestamp)var c=new Date,d=c.getFullYear(),e=this._padNumber(c.getMonth()+1,2),f=this._padNumber(c.getDate(),2),g=this._padNumber(c.getHours(),2),h=this._padNumber(c.getMinutes(),2),j=this._padNumber(c.getSeconds(),2),c=this._padNumber(c.getMilliseconds(),3),b=b+(d+"/"+e+"/"+f+" "+g+":"+h+":"+j+"."+c+" ");this.usePrefix&&(b+=a);return b+=this.scopeNameAsPrefix};Downsha.Logger.prototype.isUsePrefix=function(){return this._usePrefix};
Downsha.Logger.prototype.setUsePrefix=function(a){this._usePrefix=a?!0:!1};Downsha.Logger.prototype.isUseTimestamp=function(){return this._useTimestamp};Downsha.Logger.prototype.setUseTimestamp=function(a){this._useTimestamp=a?!0:!1};Downsha.Logger.prototype.isEnabled=function(){return this._enabled};Downsha.Logger.prototype.setEnabled=function(a){this._enabled=a?!0:!1};Downsha.Logger.prototype.isDebugEnabled=function(){return this.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_DEBUG};
Downsha.Logger.prototype.dump=function(a){this.enabled&&this.impl.enabled&&this.impl.dir(a)};Downsha.Logger.prototype.dir=function(a){this.enabled&&this.impl.enabled&&this.impl.dir(a)};Downsha.Logger.prototype.trace=function(){this.enabled&&this.impl.enabled&&this.impl.trace()};Downsha.Logger.prototype.alert=function(a){this.enabled&&this.impl.enabled&&this.impl.alert(a)};
Downsha.Logger.prototype.debug=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_DEBUG&&this.impl.debug(this.getPrefix(this.constructor.DEBUG_PREFIX)+a)};Downsha.Logger.prototype.info=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_INFO&&this.impl.info(this.getPrefix(this.constructor.INFO_PREFIX)+a)};
Downsha.Logger.prototype.warn=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_WARN&&this.impl.warn(this.getPrefix(this.constructor.WARN_PREFIX)+a)};Downsha.Logger.prototype.error=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_ERROR&&this.impl.error(this.getPrefix(this.constructor.ERROR_PREFIX)+a)};
Downsha.Logger.prototype.exception=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_EXCEPTION&&this.impl.exception(this.getPrefix(this.constructor.EXCEPTION_PREFIX)+a)};Downsha.Logger.prototype.clear=function(){this.impl.clear()};
Downsha.LoggerImpl=function(a){this.__defineGetter__("logger",this.getLogger);this.__defineSetter__("logger",this.setLogger);this.__defineGetter__("enabled",this.isEnabled);this.__defineSetter__("enabled",this.setEnabled);this.__defineGetter__("protoEnabled",this.isProtoEnabled);this.__defineSetter__("protoEnabled",this.setProtoEnabled);this.initialize(a)};Downsha.LoggerImpl.ClassRegistry=[];Downsha.LoggerImpl.isResponsibleFor=function(){return!1};Downsha.LoggerImpl.prototype.handleInheritance=function(a){Downsha.LoggerImpl.ClassRegistry.push(a)};
Downsha.LoggerImpl.prototype._logger=null;Downsha.LoggerImpl.prototype._enabled=!1;Downsha.LoggerImpl.prototype.initialize=function(a){this.logger=a};Downsha.LoggerImpl.prototype.answerImplementorInstance=function(a){if(this.constructor==a)return this};Downsha.LoggerImpl.prototype.isEnabled=function(){return this._enabled};Downsha.LoggerImpl.prototype.setEnabled=function(a){this._enabled=a?!0:!1};Downsha.LoggerImpl.prototype.isProtoEnabled=function(){return this.constructor.prototype._enabled};
Downsha.LoggerImpl.prototype.setProtoEnabled=function(a){this.constructor.prototype._enabled=a?!0:!1};Downsha.LoggerImpl.prototype.getLogger=function(){return this._logger};Downsha.LoggerImpl.prototype.setLogger=function(a){a instanceof Downsha.Logger&&(this._logger=a)};Downsha.LoggerImpl.prototype.dir=function(){};Downsha.LoggerImpl.prototype.trace=function(){};Downsha.LoggerImpl.prototype.debug=function(){};Downsha.LoggerImpl.prototype.info=function(){};Downsha.LoggerImpl.prototype.warn=function(){};
Downsha.LoggerImpl.prototype.error=function(){};Downsha.LoggerImpl.prototype.exception=function(){};Downsha.LoggerImpl.prototype.alert=function(){};Downsha.LoggerImpl.prototype.clear=function(){};Downsha.LoggerChainImpl=function(a,b){this.initialize(a,b)};Downsha.inherit(Downsha.LoggerChainImpl,Downsha.LoggerImpl,!0);Downsha.LoggerChainImpl.prototype._impls=null;Downsha.LoggerChainImpl.prototype._enabled=!0;
Downsha.LoggerChainImpl.prototype.initialize=function(a,b){Downsha.LoggerChainImpl.parent.initialize.apply(this,[a]);var c=[].concat(b);this._impls=[];for(var d=0;d<c.length;d++)this._impls.push(new c[d](a))};Downsha.LoggerChainImpl.prototype.answerImplementorInstance=function(a){for(var b=0;b<this._impls.length;b++){var c=this._impls[b].answerImplementorInstance(a);if(c)return c}};Downsha.LoggerChainImpl.prototype.dir=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].dir(a)};
Downsha.LoggerChainImpl.prototype.trace=function(){for(var a=0;a<this._impls.length;a++)this._impls[a].enabled&&this._impls[a].trace(obj)};Downsha.LoggerChainImpl.prototype.debug=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].debug(a)};Downsha.LoggerChainImpl.prototype.info=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].info(a)};
Downsha.LoggerChainImpl.prototype.warn=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].warn(a)};Downsha.LoggerChainImpl.prototype.error=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].error(a)};Downsha.LoggerChainImpl.prototype.exception=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].exception(a)};
Downsha.LoggerChainImpl.prototype.alert=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].alert(a)};Downsha.LoggerChainImpl.prototype.clear=function(){for(var a=0;a<this._impls.length;a++)this._impls[a].enabled&&this._impls[a].clear()};
Downsha.LoggerImplFactory={getImplementationFor:function(a){for(var b=Downsha.LoggerImpl.ClassRegistry,c=[],d=0;d<b.length;d++)"function"==typeof b[d]&&"function"==typeof b[d].isResponsibleFor&&b[d].isResponsibleFor(a)&&c.push(b[d]);return 0==c.length?Downsha.LoggerImpl:1==c.length?c[0]:c}};Downsha.WebKitLoggerImpl=function(a){this.initialize(a)};Downsha.inherit(Downsha.WebKitLoggerImpl,Downsha.LoggerImpl,!0);Downsha.WebKitLoggerImpl.isResponsibleFor=function(a){return 0<=a.userAgent.toLowerCase().indexOf("AppleWebKit/")};
Downsha.WebKitLoggerImpl.prototype._enabled=!0;Downsha.WebKitLoggerImpl.prototype.dir=function(a){console.group(this.logger.scopeName);console.dir(a);console.groupEnd()};Downsha.WebKitLoggerImpl.prototype.trace=function(){console.group(this.logger.scopeName);console.trace();console.groupEnd()};Downsha.WebKitLoggerImpl.prototype.alert=function(a){alert(a)};Downsha.WebKitLoggerImpl.prototype.debug=function(a){console.debug(a)};Downsha.WebKitLoggerImpl.prototype.info=function(a){console.info(a)};
Downsha.WebKitLoggerImpl.prototype.warn=function(a){console.warn(a)};Downsha.WebKitLoggerImpl.prototype.error=function(a){console.error(a)};Downsha.WebKitLoggerImpl.prototype.exception=function(a){console.error(a);this.trace()};Downsha.ChromeExtensionLoggerImpl=function(a){this.initialize(a)};Downsha.inherit(Downsha.ChromeExtensionLoggerImpl,Downsha.WebKitLoggerImpl,!0);Downsha.ChromeExtensionLoggerImpl.isResponsibleFor=function(a){return 0<=a.userAgent.toLowerCase().indexOf("chrome/")};
Downsha.ChromeExtensionLoggerImpl.prototype._enabled=!0;Downsha.Utils=new function(){};Downsha.Utils.extendObject=function(a,b,c,d){if("object"==typeof a&&null!=a&&"object"==typeof b&&null!=b)for(var e in b)"undefined"==typeof a[e]||d?a[e]=b[e]:c&&arguments.callee.apply(this,[a[e],b[e],c,d])};
Downsha.Utils.importConstructs=function(a,b,c){for(var c=c instanceof Array?c:[c],d=0;d<c.length;d++)for(var e=c[d].split("."),f=b,g=a,h=0;h<e.length;h++)h==e.length-1?"undefined"==typeof f[e[h]]?f[e[h]]=g[e[h]]:Downsha.Utils.extendObject(f[e[h]],g[e[h]],!0):(g=g[e[h]],"undefined"==typeof f[e[h]]&&(f[e[h]]={}),f=f[e[h]])};
Downsha.Utils.separateString=function(a,b){if("string"!=typeof a)return a;"string"!=typeof b&&(b=",");for(var c=a.split(b),d=[],e=0;e<c.length;e++)if("string"==typeof c[e]){var f=Downsha.Utils.trim(c[e]);f&&0<f.length&&d.push(f)}return d};Downsha.Utils.trim=function(a){return"string"!=typeof a?a:a.replace(/^\s+/,"").replace(/\s+$/,"")};Downsha.Utils.shortenString=function(a,b,c){a+="";a.length>b&&(a=a.substring(0,Math.max(0,b-("string"==typeof c?c.length:0))),"string"==typeof c&&(a+=c));return a};
Downsha.Utils.htmlEntities=function(a){return $("<div/>").text(a).html()};Downsha.Utils.urlPath=function(a){return"string"==typeof a&&(a=a.replace(/^[^:]+:\/+([^\/]+)/,""),0==a.indexOf("/"))?a.replace(/^(\/[^\?\#]*).*$/,"$1"):""};Downsha.Utils.urlDomain=function(a,b){return"string"==typeof a?a.replace(RegExp("^[^:]+:/+([^/"+(b?"":":")+"]+).*$"),"$1"):a};
Downsha.Utils.urlTopDomain=function(a){var b=a;"string"==typeof a&&(b=Downsha.Utils.urlDomain(a),0==b.toLowerCase().indexOf("www.")&&(b=b.substring(4)));return b};Downsha.Utils.urlPath=function(a){return"string"==typeof a?a.replace(/^[^:]+:\/\/[^/]+([^&?]*).*$/,"$1"):""};
Downsha.Utils.urlQueryValue=function(a,b){if("string"==typeof b&&"string"==typeof a&&0<=b.indexOf("?")){for(var c=b.split(/[\?\#\&]+/).slice(1),d=a.toLowerCase(),e=[],f=0;f<c.length;f++){var g=c[f].split("=",2);g[0].toLowerCase()==d&&(g=g[1]?g[1].replace(/\+/g," "):g[1],e.push(decodeURIComponent(g)))}if(0<e.length)return e[e.length-1]}return null};Downsha.Utils.urlProto=function(a){if("string"==typeof a){var b=-1;if(0<(b=a.indexOf(":/")))return a.substring(0,b).toLowerCase()}return null};
Downsha.Utils.absoluteUrl=function(a,b){0==a.indexOf("//")?a=b.replace(/^([^:]+):.*$/,"$1")+":"+a:0==a.indexOf("/")?a=b.replace(/^(.*:\/\/[^\/]+).*$/,"$1")+a:(a.match(/^\.+\//),a="/"==b.charAt(b.length-1)?b+a:b+"/"+a);return a};Downsha.Utils.urlSuffix="...";
Downsha.Utils.shortUrl=function(a,b){var c=a;"string"==typeof a&&(0==c.indexOf("file:")?(c=decodeURIComponent(c.replace(/^file:.*\/([^\/]+)$/,"$1")),"number"==typeof b&&!isNaN(b)&&c.length>b&&(c=c.substring(0,b),c+=""+Downsha.Utils.urlSuffix)):(c=c.replace(/^([a-zA-Z]+:\/+)?([^\/]+).*$/,"$2"),"number"==typeof b&&!isNaN(b)&&c.length>b?(c=c.substring(0,b),c+=""+Downsha.Utils.urlSuffix):2<a.substring(a.indexOf(c)+c.length).length&&(c+="/"+Downsha.Utils.urlSuffix)));return c};
Downsha.Utils.getDocumentWidth=function(a){a||(a=document);return a.width?a.width:a.body&&a.documentElement&&a.documentElement.scrollWidth?a.documentElement.scrollWidth:a.body&&a.body.scrollWidth?a.body.scrollWidth:0};Downsha.Utils.getDocumentHeight=function(a){a||(a=document);return a.height?a.height:a.body&&a.body.scrollHeight&&a.documentElement&&a.documentElement.scrollHeight?Math.max(a.documentElement.scrollHeight,a.body.scrollHeight):a.body&&a.body.scrollHeight?a.body.scrollHeight:0};
Downsha.Utils.findEmbeds=function(a){var b=[];try{var c=a.getElementsByTagName("object");if(c&&0<c.length)for(var d=0;d<c.length;d++)b.push(c[d]);var e=a.getElementsByTagName("embed");if(e&&0<e.length)for(d=0;d<e.length;d++)b.push(e[d])}catch(f){}return b};
Downsha.Utils.findDocuments=function(a){var b=[];try{var c=a.getElementsByTagName("frame");if(c&&0<c.length)for(var d=0;d<c.length;d++)c[d].contentDocument?b.push(c[d].contentDocument):c[d].contentWindow&&c[d].contentWindow.document?b.push(c[d].contentWindow.document):c[d].document&&b.push(c[d].document);var e=a.getElementsByTagName("iframe");if(e&&0<e.length)for(d=0;d<e.length;d++)e[d].contentDocument?b.push(e[d].contentDocument):e[d].contentWindow&&e[d].contentWindow.document?b.push(e[d].contentWindow.document):
e[d].document&&b.push(e[d].document)}catch(f){}return b};Downsha.Utils.getDocumentHead=function(a){return a.head?a.head:a.getElementsByTagName("head")?a.getElementsByTagName("head")[0]:a.documentElement?a.documentElement:a.body&&a.body.parentNode?a.body.parentNode:null};Downsha.Utils.makeAbsoluteClientRect=function(a,b){b||(b=window);return{top:a.top+b.pageYOffset,bottom:a.bottom+b.pageYOffset,left:a.left+b.pageXOffset,right:a.right+b.pageXOffset,width:a.width,height:a.height}};
Downsha.Utils.getAbsoluteBoundingClientRect=function(a){var b=a&&a.nodeType==Node.TEXT_NODE?a.parentElement?a.parentElement:a.parentNode:a;if(!b)return null;a=a instanceof Range?a.commonAncestorContainer.ownerDocument.defaultView:a.ownerDocument.defaultView;return Downsha.Utils.makeAbsoluteClientRect(b.getBoundingClientRect(),a)};Downsha.Utils.getElementForNode=function(a){return a&&a.nodeType==Node.ELEMENT_NODE?a:a.parentElement?a.parentElement:null};
Downsha.Utils.addElementClass=function(a,b){if(a&&b){var c=a.getAttribute("class");c?(c=c.split(/\s+/),0>c.indexOf(b)&&c.push(b),a.setAttribute("class",c.join(" "))):a.setAttribute("class",b)}};Downsha.Utils.removeElementClass=function(a,b){if(b){var c=a.getAttribute("class");if(c){var c=c.split(/\s+/),d=-1;0<=(d=c.indexOf(b))&&c.splice(d,1);a.setAttribute("class",c.join(" "))}}};Downsha.Utils.XML_ESCAPE_CHAR_MAP={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"};
Downsha.Utils.escapeXML=function(a){for(var a=a.split(""),b=0;b<a.length;b++)Downsha.Utils.XML_ESCAPE_CHAR_MAP[a[b]]&&(a[b]=Downsha.Utils.XML_ESCAPE_CHAR_MAP[a[b]]);return a.join("")};
Downsha.Utils.escapeURL=function(a){for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);if(128>d)b+=String.fromCharCode(d);else if(2048>d)var e=d>>6|192,f=d&63|128,b=b+("%"+e.toString(16).toUpperCase()),b=b+("%"+f.toString(16).toUpperCase());else 65536>d&&(e=d>>12|224,f=d>>6&63|128,d=d&63|128,b+="%"+e.toString(16).toUpperCase(),b+="%"+f.toString(16).toUpperCase(),b+="%"+d.toString(16).toUpperCase())}return b};
Downsha.Utils.rectIntersection=function(a,b){if(!(b.left>a.right||b.right<a.left||b.top>a.bottom||b.bottom<a.top)){var c={left:Math.max(a.left,b.left),top:Math.max(a.top,b.top),right:Math.min(a.right,b.right),bottom:Math.min(a.bottom,b.bottom)};c.width=c.right-c.left;c.height=c.bottom-c.top;return c}};Downsha.Utils.rectsEqual=function(a,b){return a.left==b.left&&a.right==b.right&&a.top==b.top&&a.bottom==b.bottom?!0:!1};
Downsha.Utils.expandRect=function(a,b){a.left="number"==typeof a.left?Math.min(a.left,b.left):b.left;a.top="number"==typeof a.top?Math.min(a.top,b.top):b.top;a.right="number"==typeof a.right?Math.max(a.right,b.right):b.right;a.bottom="number"==typeof a.bottom?Math.max(a.bottom,b.bottom):b.bottom};
Downsha.Utils.errorDescription=function(a){var b=null;if(a instanceof FileError){var c=a.code;if("number"==typeof c)for(var d in FileError){if(0<d.toLowerCase().indexOf("_err")&&FileError[d]==a.code){b="FileError: "+c+" ("+d+")";break}}else b="FileError: "+c}else a.message?b=a.message:"undefined"!=typeof a.code&&(b=(a.constructor&&a.constructor.name?a.constructor.name:""+a)+" code: "+a.code);return b};
Downsha.UUID={generateQuad:function(){return(65536*(1+Math.random())|0).toString(16).substring(1)},generateGuid:function(){return this.generateQuad()+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+this.generateQuad()+this.generateQuad()}};Downsha.Utils=Downsha.Utils||new function(){};Downsha.Utils.MIN_ARTICLE_RATIO=0.0625;Downsha.Utils.MIN_ARTICLE_AREA=3E4;Downsha.Utils.MAX_ARTICLE_XOFFSET_RATIO=0.6;
Downsha.Utils.querySelectors=function(a,b){var c=null;if(!a)return c;for(var b=b||document,d=0;d<a.length;d++){c=a[d];if(":root"===c)return b;if(c=b.querySelector(c))break}return c};
Downsha.Utils.getArticleNode=function(a,b){a=a||document;if(!a)return null;var c=null;if(b&&b.a){var d=Downsha.Utils.querySelectors(b.a,a);d&&(c=d)}if(!c){var d=["jpeg","jpg","gif","png"],e=a.location.href.replace(/^.*\.(\w+)$/,"$1");e&&-1!=d.indexOf(e)&&(d=a.querySelector("body > img"))&&(c=d)}if(!c&&"frameset"==a.body.nodeName.toLowerCase()){for(var e=a.getElementsByTagName("frame"),d=null,f=0,g=0,h=0;h<e.length;h++)e[h].width&&e[h].height&&(f=e[h].width*e[h].height,f>g&&(d=e[h],g=f));d&&d.contentDocument&&
d.contentDocument.documentElement&&(c=d.contentDocument.documentElement)}c||(d=new ExtractContentJS.LayeredExtractor,d.addHandler(d.factory.getHandler("Heuristics")),d=d.extract(a),d.isSuccess&&(d=d.content.asNode(),c=Downsha.Utils.getElementForNode(d)));return c};Downsha.Utils.isArticleSane=function(a,b,c){if(a&&b&&c){var d=c.width*c.height;if(!(c.top>b*Downsha.Utils.MAX_ARTICLE_XOFFSET_RATIO)&&!(d<Downsha.Utils.MIN_ARTICLE_AREA&&d<a*b*Downsha.Utils.MIN_ARTICLE_RATIO))return!0}return!1};
Downsha.Utils.MESSAGE_ATTR="message";Downsha.Utils.PLACEHOLDER_ATTR="placeholder";Downsha.Utils.TITLE_ATTR="title";Downsha.Utils.MESSAGE_DATA_ATTR="messagedata";Downsha.Utils.LOCALIZED_ATTR="localized";Downsha.Utils.BADGE_NORMAL_COLOR=[255,0,0,255];Downsha.Utils.BADGE_UPLOADING_COLOR=[255,255,0,255];Downsha.Utils.updateBadge=function(a,b){Downsha.Utils.clearBadge(b);Downsha.Utils.setBadgeTitle(chrome.i18n.getMessage("BrowserActionTitle"),b)};
Downsha.Utils.clearBadge=function(a){var b={text:""};"number"==typeof a?this.doInSpecifiedTab(a,function(){b.tabId=a;chrome.browserAction.setBadgeText(b)}):this.clearAllBadges()};Downsha.Utils.clearAllBadges=function(){this.doInEveryNormalTab(function(a){chrome.browserAction.setBadgeText({tabId:a.id,text:""})},!0)};
Downsha.Utils.setBadgeBackgroundColor=function(a,b){var c={color:a};"number"==typeof b?this.doInSpecifiedTab(b,function(){c.tabId=b;chrome.browserAction.setBadgeBackgroundColor(c)}):this.doInEveryNormalTab(function(a){c.tabId=a.id;chrome.browserAction.setBadgeBackgroundColor(c)},!0)};
Downsha.Utils.setBadgeText=function(a,b){if(a){var c={text:""+a};"number"==typeof b?this.doInSpecifiedTab(b,function(){c.tabId=b;chrome.browserAction.setBadgeText(c)}):this.doInEveryNormalTab(function(a){c.tabId=a.id;chrome.browserAction.setBadgeText(c)},!0)}else null==a&&Downsha.Utils.clearBadge(b)};
Downsha.Utils.setBadgeTitle=function(a,b){if(a){var c={title:""+a};"number"==typeof b?this.doInSpecifiedTab(b,function(){c.tabId=b;chrome.browserAction.setTitle(c)}):this.doInEveryNormalTab(function(a){c.tabId=a.id;chrome.browserAction.setTitle(c)},!0)}else null==a&&Downsha.Utils.clearBadgeTitle(b)};
Downsha.Utils.clearBadgeTitle=function(a){var b={title:""};"number"==typeof a?this.doInSpecifiedTab(a,function(){b.tabId=a;chrome.browserAction.setTitle(b)}):this.doInEveryNormalTab(function(a){b.tabId=a.id;chrome.browserAction.setTitle(b)},!0)};Downsha.Utils.doInSpecifiedTab=function(a,b){"number"==typeof a&&chrome.tabs.get(a,function(a){"undefined"!=typeof a&&null!=a&&b()})};
Downsha.Utils.doInEveryNormalTab=function(a,b){chrome.windows.getAll({populate:!0},function(c){for(var d=0;d<c.length;d++)if("normal"==c[d].type)for(var e=0;e<c[d].tabs.length;e++)(!b||c[d].tabs[e].selected)&&a(c[d].tabs[e],c[d])})};
Downsha.Utils.localizeBlock=function(a){a.attr(Downsha.Utils.MESSAGE_ATTR)&&Downsha.Utils.localizeElement(a);for(var a=a.find("["+Downsha.Utils.MESSAGE_ATTR+"], ["+Downsha.Utils.PLACEHOLDER_ATTR+"], ["+Downsha.Utils.TITLE_ATTR+"]"),b=0;b<a.length;b++){var c=$(a.get(b));Downsha.Utils.localizeElement(c)}};Downsha.Utils.extractLocalizationField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.MESSAGE_ATTR)?a.attr(Downsha.Utils.MESSAGE_ATTR):null};
Downsha.Utils.extractLocalizationDataField=function(a){if("function"==typeof a.attr&&a.attr(Downsha.Utils.MESSAGE_DATA_ATTR)){a=a.attr(Downsha.Utils.MESSAGE_DATA_ATTR);try{a=eval(a)}catch(b){}a instanceof Array||(a=[a]);return a}return null};Downsha.Utils.extractLocalizationPlaceholderField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.PLACEHOLDER_ATTR)?a.attr(Downsha.Utils.PLACEHOLDER_ATTR):null};
Downsha.Utils.extractLocalizationTitleField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.TITLE_ATTR)?a.attr(Downsha.Utils.TITLE_ATTR):null};
Downsha.Utils.localizeElement=function(a,b){if(b||!(a.attr(Downsha.Utils.LOCALIZED_ATTR)&&"true"==a.attr(Downsha.Utils.LOCALIZED_ATTR))){var c=Downsha.Utils.extractLocalizationField(a),d=Downsha.Utils.extractLocalizationPlaceholderField(a),e=Downsha.Utils.extractLocalizationTitleField(a),f=Downsha.Utils.extractLocalizationDataField(a),g=!1;"string"==typeof c&&""!=c&&(c=f?chrome.i18n.getMessage(c,f):chrome.i18n.getMessage(c),"INPUT"==a.prop("tagName")?a.val(c):a.html(c),g=!0);"string"==typeof d&&""!=
d&&(c=chrome.i18n.getMessage(d),a.attr(Downsha.Utils.PLACEHOLDER_ATTR,c),g=!0);"string"==typeof e&&""!=e&&(c=chrome.i18n.getMessage(e),a.attr(Downsha.Utils.TITLE_ATTR,c),g=!0);g&&a.attr(Downsha.Utils.LOCALIZED_ATTR,"true")}};Downsha.Utils.notifyExtension=function(a,b){chrome.windows.getCurrent(function(c){chrome.tabs.getSelected(c.id,function(c){var c={tab:c,id:chrome.i18n.getMessage("@@extension_id")},e=b||function(){};chrome.extension.onRequest.dispatch(a,c,e);chrome.extension.sendRequest(a,e)})})};
Downsha.Utils._setDesktopNotificationAttributes=function(a,b){if(a&&"object"==typeof b&&b)for(var c in b)a[c]=b[c]};Downsha.Utils.notifyDesktop=function(a,b,c,d){var e=webkitNotifications.createNotification("images/downsha48.png",a,b);this._setDesktopNotificationAttributes(e,d);e.show();"number"==typeof c&&setTimeout(function(){e.cancel()},c);return e};
Downsha.Utils.notifyDesktopWithHTML=function(a,b,c){var d=webkitNotifications.createHTMLNotification(a);this._setDesktopNotificationAttributes(d,c);d.show();"number"==typeof b&&setTimeout(function(){d.cancel()},b);return d};Downsha.Utils.openWindow=function(a){chrome.extension.getBackgroundPage().Downsha.chromeExtension.openWindow(a)};
Downsha.Utils.getPostData=function(a){"undefined"==typeof a&&(a=window.location.search.replace(/^\?/,""));var b={};if(a)for(var a=a.split("&"),c=0;c<a.length;c++){var d=a[c].split("="),e=unescape(d[0]);if(d=d[1]?unescape(d[1]):null)try{b[e]=JSON.parse(d)}catch(f){b[e]=d}else b[e]=d}return b};
Downsha.Utils.isForbiddenUrl=function(a){return"string"==typeof a&&(0<=a.toLowerCase().indexOf("chrome.google.com/extensions")||0<=a.toLowerCase().indexOf("chrome.google.com/webstore")||0<=a.toLowerCase().indexOf("ext.chrome.360.cn"))||"string"==typeof a&&!a.toLowerCase().match(/^https?:\/\//)?!0:!1};
Downsha.Utils.getTextSize=function(a){var b=$("<div></div>");b.text(a);b.css({position:"absolute",top:"0px",left:"0px",padding:"0px",margin:"0px",display:"block",zIndex:"0",color:"rgba(0, 0, 0, 0)",background:"rgba(0, 0, 0, 0)"});$("body").append(b);a={width:b.width(),height:b.height()};b.remove();return a};
Downsha.Utils.updateSelectElementWidth=function(a,b){var c=a instanceof jQuery?a:$(a),d=c.val();"function"==typeof b&&(d=b(d));var e=parseInt(c.css("paddingLeft")),f=parseInt(c.css("paddingRight")),e=(!isNaN(e)?e:0)+(!isNaN(f)?f:0),d=Downsha.Utils.getTextSize(d).width,d=(d?d:0)+e+10;c.css({minWidth:d+"px",width:d+"px"})};
Downsha.Utils.resizeElement=function(a,b,c){var a=a instanceof jQuery?a:$(a),d={},e={};if(b&&"number"==typeof b.width){var f=parseInt(a.css("paddingLeft")),g=parseInt(a.css("paddingRight")),f=(!isNaN(f)?f:0)+(!isNaN(g)?g:0);e.width=b.width+f;d.minWidth=e.width+"px";d.width=e.width+"px"}b&&"number"==typeof b.height&&(f=parseInt(a.css("paddingTop")),g=parseInt(a.css("paddingBottom")),f=(!isNaN(f)?f:0)+(!isNaN(g)?g:0),e.height=b.height+f,d.minHeight=e.height+"px",css.height=e.height+"px");a.css(d);"function"==
typeof c&&c(a,e)};Downsha.Utils.BAD_FAV_ICON_URLS=["http://localhost/favicon.ico"];
Downsha.Utils.createUrlClipContent=function(a,b,c){a=a?Downsha.Utils.escapeXML(a):"";b='<a title="'+a+'" style="font-size: 12pt; line-height: 18px; display: inline;" href="'+b+'">'+b+"</a>";return b="string"==typeof c&&0<c.length&&0>Downsha.Utils.BAD_FAV_ICON_URLS.indexOf(c.toLowerCase())?'<span><img title="'+a+'" style="display:inline;border: none; width: 16px; height: 16px; padding: 0px; margin: 0px 8px -2px 0px;" src="'+c+'"/>'+b+"</span>":"<span>"+b+"</span>"};
Downsha.Utils.getNodeString=function(a){var b=null;if("object"!=typeof a||null==a)b="[null]";else if(a&&a.nodeType==Node.TEXT_NODE)b="string"==typeof a.nodeValue&&0<a.nodeValue.length?a.nodeName+" "+a.nodeValue:a.nodeName+" [empty]";else if(a&&a.nodeType==Node.ELEMENT_NODE){for(var b="<"+a.nodeName,a=a.attributes,c=0;c<a.length;c++)a[c]&&a[c].name&&a[c].specified&&(b=a[c].value?b+(" "+a[c].name+'="'+a[c].value+'"'):b+(" "+a[c].name));b+=">"}else b="node","string"==typeof a.nodeName&&0<a.nodeName.length&&
(b+=" name: "+a.nodeName),"number"==typeof a.nodeType&&(b+=" type: "+a.nodeType),"string"==typeof a.nodeValue&&0<a.nodeValue.length&&(b+=" value: "+a.nodeValue);return b};Downsha.Semaphore=function(a){this.__defineGetter__("excessSignals",this.getExcessSignals);this.initialize(a)};Downsha.inherit(Downsha.Semaphore,Array);Downsha.Semaphore.mutex=function(){var a=new Downsha.Semaphore;a.signal();return a};Downsha.Semaphore.prototype._excessSignals=0;
Downsha.Semaphore.prototype.initialize=function(a){this._excessSignals=parseInt(a);isNaN(this._excessSignals)&&(this._excessSignals=0)};Downsha.Semaphore.prototype.getExcessSignals=function(){return this._excessSignals};Downsha.Semaphore.prototype.hasExcessSignals=function(){return 0<this._excessSignals?!0:!1};Downsha.Semaphore.prototype.signal=function(){0==this.length?this._excessSignals++:this._processNext()};
Downsha.Semaphore.prototype.wait=function(){0<this._excessSignals&&(this._excessSignals--,this._processNext())};Downsha.Semaphore.prototype.critical=function(a){var b=this,c=function(){try{a()}catch(c){throw b.signal(),c;}};c._semaOrigFn=a;this.push(c);this.wait()};Downsha.Semaphore.prototype.wave=function(){0<this.length&&this.shift()};Downsha.Semaphore.prototype.waveAll=function(){0<this.length&&this.splice(0,this.length)};
Downsha.Semaphore.prototype.waveEach=function(a){for(var b=0;b<this.length;)a(this[b]._semaOrigFn)?this.splice(b,1):b++};Downsha.Semaphore.prototype._processNext=function(){if(0<this.length){var a=this.shift();"function"==typeof a&&a()}};Downsha.Semaphore.prototype.toString=function(){return this._excessSignals+":["+this.join(",")+"]"};
Downsha.XORCrypt={DELIMIT:":",LENGTH:128,_padString:function(a){var b=0;if(128>a.length)for(var c=a.length;128>=c;c++)a=String.fromCharCode(this._randomForChar())+a,b++;return b+this.DELIMIT+a},_randomForChar:function(){for(var a=0,b=0;33>a||126<a;)a=parseInt(150*Math.random()),b++;return a},_randomNonZero:function(){for(var a=0;0==(a=parseInt(100*Math.random())););return a},_shiftString:function(a){for(var b=this._randomNonZero()+100,c=[],d=0;d<a.length;d++)c.push(String.fromCharCode(a.charCodeAt(d)+
b));return b+this.DELIMIT+c.join("")},_unshiftString:function(a){var b=parseInt(a.substring(0,a.indexOf(this.DELIMIT))),c=[];if(!isNaN(b))for(var d=(b+"").length+this.DELIMIT.length;d<a.length;d++)c.push(String.fromCharCode(a.charCodeAt(d)-b));return c.join("")},encrypt:function(a,b){for(var b=b+"",c=this._padString(this._shiftString(a+"")),d=[],e=0;e<c.length;e++){for(var f=c.charCodeAt(e),g=0;g<b.length;g++)f^=b.charCodeAt(g);d.push(String.fromCharCode(f+100))}return d.join("")},decrypt:function(a,
b){for(var a=a+"",b=b+"",c=[],d=0;d<a.length;d++){for(var e=a.charCodeAt(d)-100,f=b.length-1;0<=f;f--)e^=b.charCodeAt(f);c.push(String.fromCharCode(e))}c=c.join("");d=parseInt(c.substring(0,c.indexOf(this.DELIMIT)));return!isNaN(d)?this._unshiftString(c.substring((""+d).length+this.DELIMIT.length+d)):""}};Downsha.Constants=Downsha.Constants||{};
Downsha.Constants.RequestType={UNKNOWN:0,LOGOUT:1001,LOGIN:1002,LOGIN_ERROR:1003,LOGIN_SUCCESS:1004,POPUP_STARTED:2001,POPUP_ENDED:2002,PAGE_CLIP_SUCCESS:3001,PAGE_CLIP_FAILURE:3002,PAGE_CLIP_CONTENT_SUCCESS:3003,PAGE_CLIP_CONTENT_FAILURE:3004,PAGE_CLIP_CONTENT_TOO_BIG:3005,CONTEXT_PAGE_CLIP_SUCCESS:3101,CONTEXT_PAGE_CLIP_FAILURE:3102,CONTEXT_PAGE_CLIP_CONTENT_SUCCESS:3103,CONTEXT_PAGE_CLIP_CONTENT_FAILURE:3104,CONTEXT_PAGE_CLIP_CONTENT_TOO_BIG:3105,CONTENT_SCRIPT_LOAD_TIMEOUT:4001,FETCH_STYLE_SHEET_RULES:4002,
CLIP_ACTION_FULL_PAGE:5001,CLIP_ACTION_ARTICLE:5002,CLIP_ACTION_SELECTION:5003,CLIP_ACTION_URL:5004,PREVIEW_CLIP_ACTION_CLEAR:6001,PREVIEW_CLIP_ACTION_FULL_PAGE:6002,PREVIEW_CLIP_ACTION_ARTICLE:6003,PREVIEW_CLIP_ACTION_SELECTION:6004,PREVIEW_CLIP_ACTION_URL:6005,PREVIEW_NUDGE:6101,PREVIEW_NUDGE_PREVIOUS_SIBLING:6102,PREVIEW_NUDGE_NEXT_SIBLING:6103,PREVIEW_NUDGE_PARENT:6104,PREVIEW_NUDGE_CHILD:6105,PAGE_INFO:7001,FETCH_ARTICLE_RULES:8001};
Downsha.Constants.Limits={DSTP_USER_NAME_LEN_MIN:6,DSTP_USER_NAME_LEN_MAX:16,DSTP_USER_NAME_REGEX:"^[A-Za-z0-9._\\-\\u4e00-\\u9fa5]{6,16}$",DSTP_USER_EMAIL_LEN_MIN:6,DSTP_USER_EMAIL_LEN_MAX:255,DSTP_USER_EMAIL_REGEX:"^\\w+((-\\w+)|(\\.\\w+))*\\@[A-Za-z0-9]+((\\.|-)[A-Za-z0-9]+)*\\.[A-Za-z0-9]+$",DSTP_USER_PWD_LEN_MIN:6,DSTP_USER_PWD_LEN_MAX:16,DSTP_USER_PWD_REGEX:"^[A-Za-z0-9.~!@#$%^&*()+=_-]{6,16}$",DSTP_NOTE_TITLE_LEN_MIN:0,DSTP_NOTE_TITLE_LEN_MAX:127,DSTP_NOTE_TITLE_REGEX:"^$|^[^\\s\\r\\n\\t]([^\\n\\r\\t]{0,253}[^\\s\\r\\n\\t])?$",
DSTP_TAG_NAME_LEN_MIN:1,DSTP_TAG_NAME_LEN_MAX:100,DSTP_TAG_NAME_REGEX:"^[^,\\s\\r\\n\\t]([^,\\n\\r\\t]{0,98}[^,\\s\\r\\n\\t])?$",DSTP_NOTE_TAGS_MIN:0,DSTP_NOTE_TAGS_MAX:100,SERVICE_DOMAIN_LEN_MIN:1,SERVICE_DOMAIN_LEN_MAX:256,CLIP_NOTE_CONTENT_LEN_MAX:5242880};if("undefined"==typeof ExtractContentJS)var ExtractContentJS={};"undefined"==typeof ExtractContentJS.Lib&&(ExtractContentJS.Lib={});
ExtractContentJS.Lib.Util=function(){var a={BenchmarkTimer:function(){var a=function(){var a=new Date,b=0,b=a.getHours(),b=b*60+a.getMinutes(),b=b*60+a.getSeconds();return b=b*1E3+a.getMilliseconds()},c=function(){var c={elapsed:0,reset:function(){c.elapsed=0;return c},start:function(){c.msec=a();return c},stop:function(){c.elapsed=c.elapsed+(a()-c.msec);return c}};return c.start()},d={timers:{},get:function(a){d.timers[a]||(d.timers[a]=new c);return d.timers[a]},reset:function(a){return d.get(a).reset()},
start:function(a){return d.get(a).start()},stop:function(a){return d.get(a).stop()}};return d},Token:function(a){var c={hiragana:/[\u3042-\u3093\u304C-\u307C\u3041-\u3087\u308E\u3063\u30FC]/,katakana:/[\u30A2-\u30F3\u30AC-\u30DC\u30A1-\u30E7\u30EE\u30C3\u30FC]/,kanji:{test:function(a){return"\u4e00"<=a&&a<="\u9fa0"||a==="\u3005"}},alphabet:/[a-zA-Z]/,digit:/[0-9]/},d=function(a){var b={},d;for(d in c)c[d].test(a)&&(b[d]=c[d]);return b},e={first:d(a.charAt(0)),last:d(a.charAt(a.length-1)),isTokenized:function(a,
b){var c=a.length?a.charAt(a.length-1):"",d=b.length?b.charAt(0):"",i=function(a,b){if(a.length)for(var c in b)if(b[c].test(a))return false;return true};return i(c,e.first)&&i(d,e.last)}};return e},inherit:function(a,c){var d=a||{},e;for(e in c)typeof d[e]=="undefined"&&(d[e]=c[e]);return d},countMatch:function(a,c){return a.split(c).length-1},countMatchTokenized:function(b,c){for(var d=0,e=null,f=new a.Token(c),g=b.split(c),h=g.length,j=0;j<h;j++){e&&f.isTokenized(e,g[j])&&d++;e=g[j]}return d},indexOfTokenized:function(b,
c){var d=b.indexOf(c);if(d>=0){var e=new a.Token(c),f=d>1?b.substr(d-1,1):"",g=b.substr(d+c.length,1);if(e.isTokenized(f,g))return d}return-1},dump:function(a){if(typeof a=="undefined")return"undefined";if(typeof a=="string")return'"'+a+'"';if(typeof a!="object")return""+a;if(a===null)return"null";if(a instanceof Array)return"["+a.map(function(){return"obj"}).join(",")+"]";var c=[],d;for(d in a)c.push(d+":obj");return"{"+c.join(",")+"}"}};return a}();
ExtractContentJS.Lib.A=function(){var a={};a.indexOf=Array.indexOf||function(a,c){var d=2,e=a.length,d=Number(arguments[d++])||0,d=d<0?Math.ceil(d):Math.floor(d);for(d<0&&(d=d+e);d<e;d++)if(d in a&&a[d]===c)return d;return-1};a.filter=Array.filter||function(a,c){var d=2,e=a.length;if(typeof c!="function")throw new TypeError("A.filter: not a function");for(var f=[],d=arguments[d++],g=0;g<e;g++)if(g in a){var h=a[g];c.call(d,h,g,a)&&f.push(h)}return f};a.forEach=Array.forEach||function(a,c){var d=2,
e=a.length;if(typeof c!="function")throw new TypeError("A.forEach: not a function");for(var d=arguments[d++],f=0;f<e;f++)f in a&&c.call(d,a[f],f,a)};a.every=Array.every||function(a,c){var d=2,e=a.length;if(typeof c!="function")throw new TypeError("A.every: not a function");for(var d=arguments[d++],f=0;f<e;f++)if(f in a&&!c.call(d,a[f],f,a))return false;return true};a.map=Array.map||function(a,c){var d=2,e=a.length;if(typeof c!="function")throw new TypeError("A.map: not a function");for(var f=Array(e),
d=arguments[d++],g=0;g<e;g++)g in a&&(f[g]=c.call(d,a[g],g,a));return f};a.some=Array.some||function(a,c){var d=2,e=a.length;if(typeof c!="function")throw new TypeError("A.some: not a function");for(var d=arguments[d++],f=0;f<e;f++)if(f in a&&c.call(d,a[f],f,a))return true;return false};a.reduce=Array.reduce||function(a,c){var d=2,e=a.length;if(typeof c!="function")throw TypeError("A.reduce: not a function ");var f=0;if(arguments.length>d)var g=arguments[d++];else{do{if(f in a){g=a[f++];break}if(++f>=
e)throw new TypeError("A.reduce: empty array");}while(1)}for(;f<e;f++)f in a&&(g=c.call(null,g,a[f],f,a));return g};a.zip=function(a){if(a[0]instanceof Array){for(var c=a[0].length,d=a.length,e=Array(c),f=0;f<c;f++){e[f]=[];for(var g=0;g<d;g++)e[f].push(a[g][f])}return e}return[]};a.first=function(a){return a?a[0]:null};a.last=function(a){return a?a[a.length-1]:null};a.push=function(a,c){return Array.prototype.push.apply(a,c)};return a}();
ExtractContentJS.Lib.DOM=function(){var a=ExtractContentJS.Lib.A,b={getElementStyle:function(a,b){var e=a.style?a.style[b]:null;if(!e){var f=a.ownerDocument.defaultView;if(f&&f.getComputedStyle){try{var g=f.getComputedStyle(a,null)}catch(h){return null}b=b.replace(/([A-Z])/g,"-$1").toLowerCase();e=g?g.getPropertyValue(b):null}else a.currentStyle&&(e=a.currentStyle[b])}return e},text:function(a){return typeof a.textContent!="undefined"?a.textContent:a.nodeName=="#text"?a.nodeValue:typeof a.innerText!=
"undefined"?a.innerText:null},ancestors:function(a){for(var b=a.ownerDocument.body,e=[];a!=b;){e.push(a);a=a.parentNode}e.push(b);return e},commonAncestor:function(a,d){for(var e=b.ancestors(a).reverse(),f=b.ancestors(d).reverse(),g=null,h=0;e[h]&&f[h]&&e[h]==f[h];h++)g=e[h];return g},countMatchTagAttr:function(c,d,e,f){var g=function(a){return a.test(c[e])};if((c.tagName||"").toLowerCase()==d&&a.some(f,g))return 1;for(var g=0,h=c.childNodes,j=0,i=h.length;j<i;j++)g=g+b.countMatchTagAttr(h[j],d,e,
f);return g},matchTag:function(c,d){return a.some(d,function(a){return typeof a=="string"?a==(c.tagName||"").toLowerCase():a instanceof Array?a[0]==(c.tagName||"").toLowerCase()&&b.matchAttr(c,a[1]):false})},matchAttr:function(c,d){var e=function(d,f){if(typeof d=="string")return d==f;if(d instanceof RegExp)return d.test(f);if(d instanceof Array)return a.some(d,function(a){return e(a,f)});if(d instanceof Object)for(var g in d){var h=c[g];if(h&&b.matchAttr(h,d[g]))return true}return false},f;for(f in d){var g=
c[f],h=d[f];if(g)return e(h,g)}return false},matchStyle:function(c,d){var e=function(b,c){return typeof b=="string"?b==c:b instanceof RegExp?b.test(c):b instanceof Array?a.some(b,function(a){return e(a,c)}):false},f;for(f in d)if(e(d[f],b.getElementStyle(c,f)))return true;return false}};return b}();"undefined"==typeof ExtractContentJS&&(ExtractContentJS={});
(function(a){var b=a.Lib.Util,c=a.Lib.A,d=a.Lib.DOM,e=b.inherit(function(a,b,c,e){var f=c||{},g=e||1048576;return{node:a,depth:b||0,inside:f,statistics:function(){var b=(d.text(a)||"").replace(/\s+/g," "),c=b.length;return{text:b.substr(0,g),noLinkText:f.link||f.form?"":b,listTextLength:f.list?c:0,noListTextLength:f.list?0:c,linkCount:f.link?1:0,listCount:f.li?1:0,linkListCount:f.li&&f.link?1:0}}}},{commonAncestor:function(){var a=c.map(arguments,function(a){return a.node});return a.length<2?a[0]:
c.reduce(a,function(a,b){return d.commonAncestor(a,b)})},mergeStatistics:function(a,b){var c={},d;for(d in a)c[d]=a[d]+b[d];return c}}),f=function(a){var a=c.filter(a,function(a){a=d.text(a.node)||"";a=a.replace(/\s+/g,"");return a.length!=0}),b={score:0,leaves:a,commonAncestor:function(){return e.commonAncestor.apply(null,b.leaves)}};return b},g=function(a){var b={_content:a,asLeaves:function(){return b._content},asNode:function(){if(b._node)return b._node;b._node=e.commonAncestor.apply(null,b._content);
return b._node},asTextFragment:function(){if(b._textFragment)return b._textFragment;if(b._content.length<1)return"";b._textFragment=c.reduce(b._content,function(a,b){var c=d.text(b.node),c=c.replace(/^\s+/g,"").replace(/\s+$/g,""),c=c.replace(/\s+/g," ");return a+c},"");return b._textFragment},asText:function(){if(b._text)return b._text;var a=b.asNode();b._text=a?d.text(a):"";return b._text},toString:function(){return b.asTextFragment()}};return b};a.LayeredExtractor=function(b,c){var d={handler:b||
[],filter:c||{},factory:{getHandler:function(b){return typeof a.LayeredExtractor.Handler!="undefined"?new a.LayeredExtractor.Handler[b]:null}},addHandler:function(a){typeof a!="undefined"&&d.handler.push(a);return d},filterFor:function(){},extract:function(a){for(var b=a.location.href,c={title:a.title,url:a.location.href},e=d.handler.length,f=0;f<e;f++){var h=d.handler[f].extract(a,b,c);if(h){var j=d.filterFor(b);j&&(h=j.filter(h));h=new g(h);if(h.toString().length){c.content=h;c.isSuccess=true;c.engine=
c.engine||d.handler[f];break}}}return c}};return d};a.LayeredExtractor.Handler={};a.LayeredExtractor.Handler.Heuristics=function(a,g){var i={name:"Heuristics",content:[],opt:b.inherit(a,{threshold:60,minLength:30,factor:{decay:0.75,noBody:0.72,continuous:1.16},punctuationWeight:10,minNoLink:8,noListRatio:0.2,limit:{leaves:800,recursion:20,text:1048576},debug:false}),pat:b.inherit(g,{sep:["div","center","td","h1","h2"],waste:[/Copyright|All\s*Rights?\s*Reserved?/i],affiliate:[/amazon[a-z0-9\.\/\-\?&]+-22/i],
list:["ul","dl","ol"],li:["li","dd"],a:["a"],form:["form"],noContent:["frameset"],ignore:["iframe","img","script","style","select","noscript",["div",{id:[/more/,/menu/,/side/,/navi/],className:[/more/,/menu/,/side/,/navi/]}]],ignoreStyle:{display:"none",visibility:"hidden"},punctuations:/[\u3002\u3001\uFF0E\uFF0C\uFF01\uFF1F]|\.[^A-Za-z0-9]|,[^0-9]|!|\?/})},l=b.inherit(function(a){var g=new f(a);g.eliminateLinks=function(){var a=c.map(g.leaves,function(a){return a.statistics()});if(!a.length)return"";
var a=a.length==1?a[0]:c.reduce(a,function(a,b){return e.mergeStatistics(a,b)}),b=a.noLinkText.length,d=a.listTextLength;if(b<i.opt.minNoLink*a.linkCount)return"";var f=a.linkListCount/(a.listCount||1);return b<i.opt.noListRatio*f*f*d?"":a.noLinkText};g.noBodyRate=function(){var a=0;g.leaves.length>0&&(a=a+c.reduce(g.leaves,function(a,b){return a+d.countMatchTagAttr(b.node,"a","href",i.pat.affiliate)},0));return a=a/2+c.reduce(i.pat.waste,function(a,c){return a+b.countMatch(g._nolink,c)},0)};g.calcScore=
function(a,c){g._nolink=g.eliminateLinks();if(g._nolink.length<i.opt.minLength)return 0;var d=b.countMatch(g._nolink,i.pat.punctuations),d=d*i.opt.punctuationWeight,d=d+g._nolink.length,d=d*a,e=g.noBodyRate(),d=d*Math.pow(i.opt.factor.noBody,e);g._c=g.score=d;g._c1=d*c;return d};g.isAccepted=function(){return g._c>i.opt.threshold};g.isContinuous=function(){return g._c1>i.opt.threshold};g.merge=function(a){g.score=g.score+a._c1;g.depth=Math.min(g.depth,a.depth);c.push(g.leaves,a.leaves);return g};
return g},{split:function(a){var b=[],c=[],f=0,g=i.opt.limit.text,h=function(a){if(a&&c.length){b.push(new l(c));c=[]}},j=function(a,k,m){if(f>=i.opt.limit.leaves||k>=i.opt.limit.recursion||a.nodeName=="#comment"||d.matchTag(a,i.pat.ignore)||d.matchStyle(a,i.pat.ignoreStyle))return b;for(var l=a.childNodes,n=i.pat.sep,q=l.length,m={form:m.form||d.matchTag(a,i.pat.form),link:m.link||d.matchTag(a,i.pat.a),list:m.list||d.matchTag(a,i.pat.list),li:m.li||d.matchTag(a,i.pat.li)},p=0;p<q;p++){var r=l[p],
s=d.matchTag(r,n);h(s);j(r,k+1,m);h(s)}if(!q){f++;c.push(new e(a,k,m,g))}return b};j(a,0,{});h(true);return b}});i.extract=function(a){if(c.some(i.pat.noContent,function(b){return a.getElementsByTagName(b).length!=0}))return i;for(var b=1,d=1,e=[],f=l.split(a.body),g,h=f.length,j=0;j<h;j++){var k=f[j];g&&(d=d/i.opt.factor.continuous);if(k.calcScore(b,d)){b=b*i.opt.factor.decay;if(k.isAccepted()){if(k.isContinuous()&&g)g.merge(k);else{g=k;e.push(k)}d=i.opt.factor.continuous}else g||(b=1)}}i.blocks=
e.sort(function(a,b){return b.score-a.score});if(b=c.first(i.blocks))i.content=b.leaves;return i.content};return i};a.LayeredExtractor.Handler.GoogleAdSection=function(a){var d={name:"GoogleAdSection",content:[],state:[],opt:b.inherit(a,{limit:{leaves:800,recursion:20},debug:false})},g=/google_ad_section_start\(weight=ignore\)/i,l=/google_ad_section_start/i,n=/google_ad_section_end/i;d.inSection=function(){return c.last(d.state)==2};d.ignore=function(){d.state.push(1)};d.section=function(){d.state.push(2)};
d.end=function(){d.state.length&&d.state.pop()};d.parse=function(a,b){var c=b||0;if(a.nodeName=="#comment")g.test(a.nodeValue)?d.ignore():l.test(a.nodeValue)?d.section():n.test(a.nodeValue)&&d.end();else if(!(d.content.length>=d.opt.limit.leaves)&&!(c>=d.opt.limit.recursion)){for(var f=a.childNodes,h=f.length,o=0;o<h;o++)d.parse(f[o],c+1);!h&&d.inSection()&&d.content.push(new e(a,c))}};d.extract=function(a){d.parse(a);d.blocks=[new f(d.content)];return d.content};return d}})(ExtractContentJS);
Downsha.RequestMessage=function(a,b){this.initialize(a,b)};Downsha.RequestMessage.fromObject=function(a){var b=new Downsha.RequestMessage;if(typeof a=="object"&&a!=null){if(typeof a.code!="undefined")b.code=a.code;if(typeof a.message!="undefined")b.message=a.message}return b};Downsha.RequestMessage.prototype._code=0;Downsha.RequestMessage.prototype._message=null;Downsha.RequestMessage.prototype._callback=null;
Downsha.RequestMessage.prototype.initialize=function(a,b){this.__defineGetter__("code",this.getCode);this.__defineSetter__("code",this.setCode);this.__defineGetter__("message",this.getMessage);this.__defineSetter__("message",this.setMessage);this.__defineGetter__("callback",this.getCallback);this.__defineSetter__("callback",this.setCallback);this.code=a;this.message=b};Downsha.RequestMessage.prototype.getCode=function(){return this._code};
Downsha.RequestMessage.prototype.setCode=function(a){this._code=parseInt(a);if(isNaN(this._code))this._code=0};Downsha.RequestMessage.prototype.getMessage=function(){return this._message};Downsha.RequestMessage.prototype.setMessage=function(a){this._message=a};Downsha.RequestMessage.prototype.getCallback=function(){return this._callback};Downsha.RequestMessage.prototype.setCallback=function(a){if(typeof a=="function"||a==null)this._callback=a};
Downsha.RequestMessage.prototype.send=function(){chrome.extension.sendRequest({code:this.code,message:this.message})};Downsha.RequestMessage.prototype.isEmpty=function(){return this.code?false:true};
(function(){var a=null,b=false;Downsha.SelectionFinder=function(c){this.document=this.initDocument=c;a=Downsha.Logger.getInstance();a.level==Downsha.Logger.LOG_LEVEL_DEBUG&&(b=true)};Downsha.SelectionFinder.prototype.initDocument=null;Downsha.SelectionFinder.prototype.document=null;Downsha.SelectionFinder.prototype.selection=null;Downsha.SelectionFinder.prototype.reset=function(){this.document=this.initDocument;this.selection=null};Downsha.SelectionFinder.prototype.hasSelection=function(){var a=this.getRange();
return a&&(a.startContainer!=a.endContainer||a.startContainer==a.endContainer&&a.startOffset!=a.endOffset)?true:false};Downsha.SelectionFinder.prototype.find=function(a){a=this._findSelectionInDocument(this.document,a);this.document=a.document;this.selection=a.selection};Downsha.SelectionFinder.prototype.getRange=function(){if(!this.selection||this.selection.rangeCount==0)return null;if(typeof this.selection.getRangeAt=="function")return this.selection.getRangeAt(0);var a=this.document.createRange();
a.setStart(this.selection.anchorNode,this.selection.anchorOffset);a.setEnd(this.selection.focusNode,this.selection.focusOffset);return a};Downsha.SelectionFinder.prototype.getCommonAncestorContainer=function(){var a=this.getRange();if(a&&a.commonAncestorContainer){for(a=a.commonAncestorContainer;a&&a.nodeType!=Node.ELEMENT_NODE;)a=a.parentElement;return a}return null};Downsha.SelectionFinder.prototype._findSelectionInDocument=function(c,d){var e=null;typeof c.getSelection=="function"?e=c.getSelection():
c.selection&&typeof c.selection.createRange=="function"&&(e=c.selection.createRange());if(e&&e.rangeCount==0&&d){var f=Downsha.Utils.findDocuments(c);if(f.length>0){b&&a.debug("find selection range empty, trying frames, count: "+f.length);for(var g=0;g<f.length;g++)if(f[g]){b&&a.debug("trying nested doc: "+f[g]);var h=this._findSelectionInDocument(f[g],d);if(h.selection.rangeCount>0)return h}}}return{document:c,selection:e}}})();
(function(){Downsha.AbstractStyleScript=function(){Downsha.Logger.getInstance();this.initialize()};Downsha.AbstractStyleScript.prototype.initialize=function(){var a=this.getInitialStyleSheetUrls();a&&a.length>0&&this.injectStyleSheets(a)};Downsha.AbstractStyleScript.prototype.getInitialStyleSheetUrls=function(){return[]};Downsha.AbstractStyleScript.prototype.injectStyleSheets=function(a){for(var b=Downsha.Utils.getDocumentHead(document),c=0;c<a.length;c++){var d=a[c],e=document.createElement("link");
e.setAttribute("rel","stylesheet");e.setAttribute("type","text/css");e.setAttribute("href",d);b&&b.appendChild(e)}}})();
(function(){var a=null;Downsha.PageInfoScript=function(b){a=Downsha.Logger.getInstance();this.initialize(b)};Downsha.inherit(Downsha.PageInfoScript,Downsha.AbstractStyleScript);Downsha.PageInfoScript._instance=null;Downsha.PageInfoScript.getInstance=function(){if(!this._instance)this._instance=new Downsha.PageInfoScript;return this._instance};Downsha.PageInfoScript.removeInstance=function(){this._instance=null};Downsha.PageInfoScript.prototype.window=null;Downsha.PageInfoScript.prototype._sema=null;
Downsha.PageInfoScript.prototype._articleRules=null;Downsha.PageInfoScript.prototype.initialize=function(a){this.window=a?a:window;Downsha.PageInfoScript.parent.initialize.apply(this,[]);this._sema=Downsha.Semaphore.mutex();this.fetchArticleRules();this.__defineGetter__("articleRules",this.getArticleRules)};Downsha.PageInfoScript.prototype.getArticleRules=function(){return this._articleRules};Downsha.PageInfoScript.prototype.fetchArticleRules=function(){a.debug("PageInfoScript.fetchArticleRules");
var b=this;this._articleRules||this._sema.critical(function(){chrome.extension.sendRequest(new Downsha.RequestMessage(Downsha.Constants.RequestType.FETCH_ARTICLE_RULES,this.window.document.location.href),function(a){b._articleRules=a&&a.rules?a.rules:{};b._sema.signal()})})};Downsha.PageInfoScript.prototype.profile=function(){var a=this;this._sema.critical(function(){a._profile();a._sema.signal()})};Downsha.PageInfoScript.prototype._profile=function(){a.debug("PageInfoScript._profile");this.profilePage();
this.profileSelection();this.profileArticle();this.notifyWithPageInfo()};Downsha.PageInfoScript.prototype.profilePage=function(){this.documentWidth=Downsha.Utils.getDocumentWidth(this.window.document);this.documentHeight=Downsha.Utils.getDocumentHeight(this.window.document);this.documentLength=0;try{this.documentLength=this.window.document.body.textContent.length}catch(b){a.warn("Could not determine document's text length")}this.containsImages=false;try{var c=this.window.document.getElementsByTagName("IMG");
if(c&&c.length>0)this.containsImages=true}catch(d){a.warn("Could not determine whether document contains images")}};Downsha.PageInfoScript.prototype.profileSelection=function(){a.debug("PageInfoScript.profileSelection");var b=new Downsha.SelectionFinder(this.window.document);b.find(true);this.selection=b.hasSelection()?true:false};Downsha.PageInfoScript.prototype.profileArticle=function(){a.debug("PageInfoScript.profileArticle");var b=Downsha.Utils.getArticleNode(this.window.document,this.articleRules);
if(b){this.article=true;if(b=Downsha.Utils.getAbsoluteBoundingClientRect(b))this.articleBoundingClientRect=b}};Downsha.PageInfoScript.prototype.notifyWithPageInfo=function(){a.debug(this.toString());chrome.extension.sendRequest(new Downsha.RequestMessage(Downsha.Constants.RequestType.PAGE_INFO,{pageInfo:this}))};Downsha.PageInfoScript.prototype.toJSON=function(){return{documentWidth:this.documentWidth,documentHeight:this.documentHeight,documentLength:this.documentLength,containsImages:this.containsImages,
selection:this.selection,article:this.article,articleBoundingClientRect:this.articleBoundingClientRect}};Downsha.PageInfoScript.prototype.toString=function(){return"PageInfoScript [document] "+this.documentWidth+"*"+this.documentHeight+" length: "+this.documentLength+" contain image: "+this.containsImages+" [selection] "+(this.selection?"yes":"no")+" [article] "+(this.article?this.articleBoundingClientRect.width+"*"+this.articleBoundingClientRect.height:"no")}})();
