var Downsha=Downsha||{};Downsha.inherit=function(a,b,d){"function"==typeof b.constructor?(a.prototype=new b,a.prototype.constructor=a,a.parent=b.prototype):(a.prototype=b,a.prototype.constructor=a,a.parent=b);if(d)for(var c in b.prototype.constructor)"parent"!=c&&"prototype"!=c&&"javaClass"!=c&&b.constructor[c]!=b.prototype.constructor[c]&&(a.prototype.constructor[c]=b.prototype.constructor[c]);"function"==typeof a.prototype.handleInheritance&&a.prototype.handleInheritance.apply(a,[a,b,d])};
Downsha.inherits=function(a,b){for(var d=a;d&&"undefined"!=typeof d.parent;){if(d.parent.constructor==b)return!0;d=d.parent.constructor}return!1};Downsha.mixin=function(a,b,d){var a="function"==typeof a?a.prototype:a,c;for(c in b.prototype){var e=to=c;"object"==typeof d&&d&&"undefined"!=typeof d[c]&&(to=d[c]);a[to]=b.prototype[e]}};
Downsha.extendObject=function(a,b,d){if("object"==typeof b&&null!=b)for(var c in b)if(d&&"object"==typeof b[c]&&null!=b[c]&&"object"==typeof a[c]&&null!=a[c])Downsha.extendObject(a[c],b[c],d);else try{a[c]=b[c]}catch(e){}};Downsha.hasOwnProperty=function(a,b){if("object"==typeof a){if(a.hasOwnProperty(b))return!0;for(var d=null,d=a;d=d.__proto__;)if(d.hasOwnProperty(b))return!0}return!1};Downsha.DefiningMixin=function(){};
Downsha.DefiningMixin._getTargetFor=function(a){return"function"==typeof a&&a==a.prototype.constructor?a.prototype:a};Downsha.DefiningMixin.prototype.__defineBoolean__=function(a,b,d,c){var e="_"+a,f=a.substring(0,1).toUpperCase()+a.substring(1),g=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);g[e]=b?!0:!1;if(!d){var h="is"+f;g[h]=function(){return this[e]};this.__defineGetter__(a,g[h])}c||(f="set"+f,g[f]=function(b){this[e]=b?!0:!1},this.__defineSetter__(a,g[f]))};
Downsha.DefiningMixin.prototype.__defineFloat__=function(a,b,d,c){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!1,parseFloat,d,c)};Downsha.DefiningMixin.prototype.__definePositiveFloat__=function(a,b,d,c){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!0,parseFloat,d,c)};
Downsha.DefiningMixin.prototype.__defineInteger__=function(a,b,d,c){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!1,parseInt,d,c)};Downsha.DefiningMixin.prototype.__definePositiveInteger__=function(a,b,d,c){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!0,parseInt,d,c)};
Downsha.DefiningMixin.prototype._createNumericDefinition_=function(a,b,d,c,e,f,g){var h=b.substring(0,1).toUpperCase()+b.substring(1),i="_"+b,d="number"==typeof d?d:null;a||(a=this);a[i]=d;f||(f="get"+h,a[f]=function(){return this[i]},this.__defineGetter__(b,a[f]));g||(g="set"+h,a[g]=c?function(b){this[i]=e(b);if(isNaN(this[i])||this[i]<0)this[i]=d}:function(b){this[i]=e(b);isNaN(this[i])&&(this[i]=d)},this.__defineSetter__(b,a[g]))};
Downsha.DefiningMixin.prototype.__defineString__=function(a,b,d,c){var b=b?b:null,e=a.substring(0,1).toUpperCase()+a.substring(1),f="_"+a,g=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);g[f]=b;if(!d){var h="get"+e;g[h]=function(){return this[f]};this.__defineGetter__(a,g[h])}c||(e="set"+e,g[e]=function(a){this[f]="string"==typeof a?a:a?""+a:b},this.__defineSetter__(a,g[e]))};
Downsha.DefiningMixin.prototype.__defineType__=function(a,b,d,c,e){var d=d?d:null,f="_"+a,g=a.substring(0,1).toUpperCase()+a.substring(1),h=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);h[f]=d;if(!c){var i="get"+g;h[i]=function(){return this[f]};this.__defineGetter__(a,h[i])}e||(g="set"+g,h[g]=function(a){if("string"==typeof b&&a&&a.constructor.name==b)this[f]=a;else if("function"==typeof b&&a instanceof b)this[f]=a;else{if(a)throw Error("Expected "+("string"==typeof b?b:b.name)+" but got "+
typeof a);this[f]=d}},this.__defineSetter__(a,h[g]))};
Downsha.Logger=function(a,b,d){this.__defineGetter__("level",this.getLevel);this.__defineSetter__("level",this.setLevel);this.__defineGetter__("scope",this.getScope);this.__defineSetter__("scope",this.setScope);this.__defineGetter__("scopeName",this.getScopeName);this.__defineGetter__("scopeNameAsPrefix",this.getScopeNameAsPrefix);this.__defineGetter__("useTimestamp",this.isUseTimestamp);this.__defineSetter__("useTimestamp",this.setUseTimestamp);this.__defineGetter__("usePrefix",this.isUsePrefix);
this.__defineSetter__("usePrefix",this.setUsePrefix);this.__defineGetter__("enabled",this.isEnabled);this.__defineSetter__("enabled",this.setEnabled);this.scope=a||arguments.callee.caller;this.level=b;if("undefined"!=typeof d&&d instanceof Downsha.LoggerImpl)this.impl=d;else{var c=Downsha.LoggerImplFactory.getImplementationFor(navigator);this.impl=c instanceof Array?new Downsha.LoggerChainImpl(this,c):new c(this)}};Downsha.Logger.LOG_LEVEL_DEBUG=0;Downsha.Logger.LOG_LEVEL_INFO=1;
Downsha.Logger.LOG_LEVEL_WARN=2;Downsha.Logger.LOG_LEVEL_ERROR=3;Downsha.Logger.LOG_LEVEL_EXCEPTION=4;Downsha.Logger.LOG_LEVEL_OFF=5;Downsha.Logger.GLOBAL_LEVEL=Downsha.Logger.LOG_LEVEL_ERROR;Downsha.Logger.DEBUG_PREFIX="[DEBUG] ";Downsha.Logger.INFO_PREFIX="[INFO] ";Downsha.Logger.WARN_PREFIX="[WARN] ";Downsha.Logger.ERROR_PREFIX="[ERROR] ";Downsha.Logger.EXCEPTION_PREFIX="[EXCEPTION] ";Downsha.Logger._instances={};
Downsha.Logger.getInstance=function(a){var a=a||arguments.callee.caller,b="function"==typeof a?a.name:a.constructor.name;"undefined"==typeof this._instances[b]&&(this._instances[b]=new Downsha.Logger(a));return this._instances[b]};Downsha.Logger.setInstance=function(a){this._instance=a};Downsha.Logger.destroyInstance=function(a){a=a||arguments.callee.caller;delete this._instances["function"==typeof a?a.name:a.constructor.name]};
Downsha.Logger.setGlobalLevel=function(a){a=parseInt(a);if(!isNaN(a)&&(Downsha.Logger.GLOBAL_LEVEL=a,this._instances))for(var b in this._instances)this._instances[b].setLevel(a)};Downsha.Logger.setLevel=function(a){if(this._instances)for(var b in this._instances)this._instances[b].setLevel(a)};Downsha.Logger.enableImplementor=function(a){if(this._instances)for(var b in this._instances)this._instances[b].enableImplementor(a);a&&(a.protoEnabled=!0)};
Downsha.Logger.disableImplementor=function(a){if(this._instances)for(var b in this._instances)this._instances[b].disableImplementor(a);a&&(a.protoEnabled=!1)};Downsha.Logger.prototype._level=0;Downsha.Logger.prototype._scope=null;Downsha.Logger.prototype._usePrefix=!0;Downsha.Logger.prototype._useTimestamp=!0;Downsha.Logger.prototype._enabled=!0;Downsha.Logger.prototype.getImplementor=function(a){return a?this.impl.answerImplementorInstance(a):this.impl};
Downsha.Logger.prototype.enableImplementor=function(a){if(a){if(a=this.getImplementor(a))a.enabled=!0}else this.impl.enabled=!0};Downsha.Logger.prototype.disableImplementor=function(a){if(a){if(a=this.getImplementor(a))a.enabled=!1}else this.impl.enabled=!1};Downsha.Logger.prototype.setLevel=function(a){this._level=parseInt(a);isNaN(this._level)&&(this._level=Downsha.Logger.GLOBAL_LEVEL)};Downsha.Logger.prototype.getLevel=function(){return this._level};
Downsha.Logger.prototype.setScope=function(a){"function"==typeof a?this._scope=a:"object"==typeof a&&null!=a&&(this._scope=a.constructor)};Downsha.Logger.prototype.getScope=function(){return this._scope};Downsha.Logger.prototype.getScopeName=function(){return this.scope?this.scope.name:""};Downsha.Logger.prototype.getScopeNameAsPrefix=function(){var a=this.scopeName;return a?"["+a+"] ":""};
Downsha.Logger.prototype._padNumber=function(a,b){a=parseInt(a);isNaN(a)&&(a=0);for(var d=0<=a?!0:!1,c=""+Math.abs(a);c.length<b;)c="0"+c;d||(c="-"+c);return c};
Downsha.Logger.prototype.getPrefix=function(a){var b="";if(this.useTimestamp)var d=new Date,c=d.getFullYear(),e=this._padNumber(d.getMonth()+1,2),f=this._padNumber(d.getDate(),2),g=this._padNumber(d.getHours(),2),h=this._padNumber(d.getMinutes(),2),i=this._padNumber(d.getSeconds(),2),d=this._padNumber(d.getMilliseconds(),3),b=b+(c+"/"+e+"/"+f+" "+g+":"+h+":"+i+"."+d+" ");this.usePrefix&&(b+=a);return b+=this.scopeNameAsPrefix};Downsha.Logger.prototype.isUsePrefix=function(){return this._usePrefix};
Downsha.Logger.prototype.setUsePrefix=function(a){this._usePrefix=a?!0:!1};Downsha.Logger.prototype.isUseTimestamp=function(){return this._useTimestamp};Downsha.Logger.prototype.setUseTimestamp=function(a){this._useTimestamp=a?!0:!1};Downsha.Logger.prototype.isEnabled=function(){return this._enabled};Downsha.Logger.prototype.setEnabled=function(a){this._enabled=a?!0:!1};Downsha.Logger.prototype.isDebugEnabled=function(){return this.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_DEBUG};
Downsha.Logger.prototype.dump=function(a){this.enabled&&this.impl.enabled&&this.impl.dir(a)};Downsha.Logger.prototype.dir=function(a){this.enabled&&this.impl.enabled&&this.impl.dir(a)};Downsha.Logger.prototype.trace=function(){this.enabled&&this.impl.enabled&&this.impl.trace()};Downsha.Logger.prototype.alert=function(a){this.enabled&&this.impl.enabled&&this.impl.alert(a)};
Downsha.Logger.prototype.debug=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_DEBUG&&this.impl.debug(this.getPrefix(this.constructor.DEBUG_PREFIX)+a)};Downsha.Logger.prototype.info=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_INFO&&this.impl.info(this.getPrefix(this.constructor.INFO_PREFIX)+a)};
Downsha.Logger.prototype.warn=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_WARN&&this.impl.warn(this.getPrefix(this.constructor.WARN_PREFIX)+a)};Downsha.Logger.prototype.error=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_ERROR&&this.impl.error(this.getPrefix(this.constructor.ERROR_PREFIX)+a)};
Downsha.Logger.prototype.exception=function(a){this.enabled&&this.impl.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_EXCEPTION&&this.impl.exception(this.getPrefix(this.constructor.EXCEPTION_PREFIX)+a)};Downsha.Logger.prototype.clear=function(){this.impl.clear()};
Downsha.LoggerImpl=function(a){this.__defineGetter__("logger",this.getLogger);this.__defineSetter__("logger",this.setLogger);this.__defineGetter__("enabled",this.isEnabled);this.__defineSetter__("enabled",this.setEnabled);this.__defineGetter__("protoEnabled",this.isProtoEnabled);this.__defineSetter__("protoEnabled",this.setProtoEnabled);this.initialize(a)};Downsha.LoggerImpl.ClassRegistry=[];Downsha.LoggerImpl.isResponsibleFor=function(){return!1};Downsha.LoggerImpl.prototype.handleInheritance=function(a){Downsha.LoggerImpl.ClassRegistry.push(a)};
Downsha.LoggerImpl.prototype._logger=null;Downsha.LoggerImpl.prototype._enabled=!1;Downsha.LoggerImpl.prototype.initialize=function(a){this.logger=a};Downsha.LoggerImpl.prototype.answerImplementorInstance=function(a){if(this.constructor==a)return this};Downsha.LoggerImpl.prototype.isEnabled=function(){return this._enabled};Downsha.LoggerImpl.prototype.setEnabled=function(a){this._enabled=a?!0:!1};Downsha.LoggerImpl.prototype.isProtoEnabled=function(){return this.constructor.prototype._enabled};
Downsha.LoggerImpl.prototype.setProtoEnabled=function(a){this.constructor.prototype._enabled=a?!0:!1};Downsha.LoggerImpl.prototype.getLogger=function(){return this._logger};Downsha.LoggerImpl.prototype.setLogger=function(a){a instanceof Downsha.Logger&&(this._logger=a)};Downsha.LoggerImpl.prototype.dir=function(){};Downsha.LoggerImpl.prototype.trace=function(){};Downsha.LoggerImpl.prototype.debug=function(){};Downsha.LoggerImpl.prototype.info=function(){};Downsha.LoggerImpl.prototype.warn=function(){};
Downsha.LoggerImpl.prototype.error=function(){};Downsha.LoggerImpl.prototype.exception=function(){};Downsha.LoggerImpl.prototype.alert=function(){};Downsha.LoggerImpl.prototype.clear=function(){};Downsha.LoggerChainImpl=function(a,b){this.initialize(a,b)};Downsha.inherit(Downsha.LoggerChainImpl,Downsha.LoggerImpl,!0);Downsha.LoggerChainImpl.prototype._impls=null;Downsha.LoggerChainImpl.prototype._enabled=!0;
Downsha.LoggerChainImpl.prototype.initialize=function(a,b){Downsha.LoggerChainImpl.parent.initialize.apply(this,[a]);var d=[].concat(b);this._impls=[];for(var c=0;c<d.length;c++)this._impls.push(new d[c](a))};Downsha.LoggerChainImpl.prototype.answerImplementorInstance=function(a){for(var b=0;b<this._impls.length;b++){var d=this._impls[b].answerImplementorInstance(a);if(d)return d}};Downsha.LoggerChainImpl.prototype.dir=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].dir(a)};
Downsha.LoggerChainImpl.prototype.trace=function(){for(var a=0;a<this._impls.length;a++)this._impls[a].enabled&&this._impls[a].trace(obj)};Downsha.LoggerChainImpl.prototype.debug=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].debug(a)};Downsha.LoggerChainImpl.prototype.info=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].info(a)};
Downsha.LoggerChainImpl.prototype.warn=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].warn(a)};Downsha.LoggerChainImpl.prototype.error=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].error(a)};Downsha.LoggerChainImpl.prototype.exception=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].exception(a)};
Downsha.LoggerChainImpl.prototype.alert=function(a){for(var b=0;b<this._impls.length;b++)this._impls[b].enabled&&this._impls[b].alert(a)};Downsha.LoggerChainImpl.prototype.clear=function(){for(var a=0;a<this._impls.length;a++)this._impls[a].enabled&&this._impls[a].clear()};
Downsha.LoggerImplFactory={getImplementationFor:function(a){for(var b=Downsha.LoggerImpl.ClassRegistry,d=[],c=0;c<b.length;c++)"function"==typeof b[c]&&"function"==typeof b[c].isResponsibleFor&&b[c].isResponsibleFor(a)&&d.push(b[c]);return 0==d.length?Downsha.LoggerImpl:1==d.length?d[0]:d}};Downsha.WebKitLoggerImpl=function(a){this.initialize(a)};Downsha.inherit(Downsha.WebKitLoggerImpl,Downsha.LoggerImpl,!0);Downsha.WebKitLoggerImpl.isResponsibleFor=function(a){return 0<=a.userAgent.toLowerCase().indexOf("AppleWebKit/")};
Downsha.WebKitLoggerImpl.prototype._enabled=!0;Downsha.WebKitLoggerImpl.prototype.dir=function(a){console.group(this.logger.scopeName);console.dir(a);console.groupEnd()};Downsha.WebKitLoggerImpl.prototype.trace=function(){console.group(this.logger.scopeName);console.trace();console.groupEnd()};Downsha.WebKitLoggerImpl.prototype.alert=function(a){alert(a)};Downsha.WebKitLoggerImpl.prototype.debug=function(a){console.debug(a)};Downsha.WebKitLoggerImpl.prototype.info=function(a){console.info(a)};
Downsha.WebKitLoggerImpl.prototype.warn=function(a){console.warn(a)};Downsha.WebKitLoggerImpl.prototype.error=function(a){console.error(a)};Downsha.WebKitLoggerImpl.prototype.exception=function(a){console.error(a);this.trace()};Downsha.ChromeExtensionLoggerImpl=function(a){this.initialize(a)};Downsha.inherit(Downsha.ChromeExtensionLoggerImpl,Downsha.WebKitLoggerImpl,!0);Downsha.ChromeExtensionLoggerImpl.isResponsibleFor=function(a){return 0<=a.userAgent.toLowerCase().indexOf("chrome/")};
Downsha.ChromeExtensionLoggerImpl.prototype._enabled=!0;Downsha.Utils=new function(){};Downsha.Utils.extendObject=function(a,b,d,c){if("object"==typeof a&&null!=a&&"object"==typeof b&&null!=b)for(var e in b)"undefined"==typeof a[e]||c?a[e]=b[e]:d&&arguments.callee.apply(this,[a[e],b[e],d,c])};
Downsha.Utils.importConstructs=function(a,b,d){for(var d=d instanceof Array?d:[d],c=0;c<d.length;c++)for(var e=d[c].split("."),f=b,g=a,h=0;h<e.length;h++)h==e.length-1?"undefined"==typeof f[e[h]]?f[e[h]]=g[e[h]]:Downsha.Utils.extendObject(f[e[h]],g[e[h]],!0):(g=g[e[h]],"undefined"==typeof f[e[h]]&&(f[e[h]]={}),f=f[e[h]])};
Downsha.Utils.separateString=function(a,b){if("string"!=typeof a)return a;"string"!=typeof b&&(b=",");for(var d=a.split(b),c=[],e=0;e<d.length;e++)if("string"==typeof d[e]){var f=Downsha.Utils.trim(d[e]);f&&0<f.length&&c.push(f)}return c};Downsha.Utils.trim=function(a){return"string"!=typeof a?a:a.replace(/^\s+/,"").replace(/\s+$/,"")};Downsha.Utils.shortenString=function(a,b,d){a+="";a.length>b&&(a=a.substring(0,Math.max(0,b-("string"==typeof d?d.length:0))),"string"==typeof d&&(a+=d));return a};
Downsha.Utils.htmlEntities=function(a){return $("<div/>").text(a).html()};Downsha.Utils.urlPath=function(a){return"string"==typeof a&&(a=a.replace(/^[^:]+:\/+([^\/]+)/,""),0==a.indexOf("/"))?a.replace(/^(\/[^\?\#]*).*$/,"$1"):""};Downsha.Utils.urlDomain=function(a,b){return"string"==typeof a?a.replace(RegExp("^[^:]+:/+([^/"+(b?"":":")+"]+).*$"),"$1"):a};
Downsha.Utils.urlTopDomain=function(a){var b=a;"string"==typeof a&&(b=Downsha.Utils.urlDomain(a),0==b.toLowerCase().indexOf("www.")&&(b=b.substring(4)));return b};Downsha.Utils.urlPath=function(a){return"string"==typeof a?a.replace(/^[^:]+:\/\/[^/]+([^&?]*).*$/,"$1"):""};
Downsha.Utils.urlQueryValue=function(a,b){if("string"==typeof b&&"string"==typeof a&&0<=b.indexOf("?")){for(var d=b.split(/[\?\#\&]+/).slice(1),c=a.toLowerCase(),e=[],f=0;f<d.length;f++){var g=d[f].split("=",2);g[0].toLowerCase()==c&&(g=g[1]?g[1].replace(/\+/g," "):g[1],e.push(decodeURIComponent(g)))}if(0<e.length)return e[e.length-1]}return null};Downsha.Utils.urlProto=function(a){if("string"==typeof a){var b=-1;if(0<(b=a.indexOf(":/")))return a.substring(0,b).toLowerCase()}return null};
Downsha.Utils.absoluteUrl=function(a,b){0==a.indexOf("//")?a=b.replace(/^([^:]+):.*$/,"$1")+":"+a:0==a.indexOf("/")?a=b.replace(/^(.*:\/\/[^\/]+).*$/,"$1")+a:(a.match(/^\.+\//),a="/"==b.charAt(b.length-1)?b+a:b+"/"+a);return a};Downsha.Utils.urlSuffix="...";
Downsha.Utils.shortUrl=function(a,b){var d=a;"string"==typeof a&&(0==d.indexOf("file:")?(d=decodeURIComponent(d.replace(/^file:.*\/([^\/]+)$/,"$1")),"number"==typeof b&&!isNaN(b)&&d.length>b&&(d=d.substring(0,b),d+=""+Downsha.Utils.urlSuffix)):(d=d.replace(/^([a-zA-Z]+:\/+)?([^\/]+).*$/,"$2"),"number"==typeof b&&!isNaN(b)&&d.length>b?(d=d.substring(0,b),d+=""+Downsha.Utils.urlSuffix):2<a.substring(a.indexOf(d)+d.length).length&&(d+="/"+Downsha.Utils.urlSuffix)));return d};
Downsha.Utils.getDocumentWidth=function(a){a||(a=document);return a.width?a.width:a.body&&a.documentElement&&a.documentElement.scrollWidth?a.documentElement.scrollWidth:a.body&&a.body.scrollWidth?a.body.scrollWidth:0};Downsha.Utils.getDocumentHeight=function(a){a||(a=document);return a.height?a.height:a.body&&a.body.scrollHeight&&a.documentElement&&a.documentElement.scrollHeight?Math.max(a.documentElement.scrollHeight,a.body.scrollHeight):a.body&&a.body.scrollHeight?a.body.scrollHeight:0};
Downsha.Utils.findEmbeds=function(a){var b=[];try{var d=a.getElementsByTagName("object");if(d&&0<d.length)for(var c=0;c<d.length;c++)b.push(d[c]);var e=a.getElementsByTagName("embed");if(e&&0<e.length)for(c=0;c<e.length;c++)b.push(e[c])}catch(f){}return b};
Downsha.Utils.findDocuments=function(a){var b=[];try{var d=a.getElementsByTagName("frame");if(d&&0<d.length)for(var c=0;c<d.length;c++)d[c].contentDocument?b.push(d[c].contentDocument):d[c].contentWindow&&d[c].contentWindow.document?b.push(d[c].contentWindow.document):d[c].document&&b.push(d[c].document);var e=a.getElementsByTagName("iframe");if(e&&0<e.length)for(c=0;c<e.length;c++)e[c].contentDocument?b.push(e[c].contentDocument):e[c].contentWindow&&e[c].contentWindow.document?b.push(e[c].contentWindow.document):
e[c].document&&b.push(e[c].document)}catch(f){}return b};Downsha.Utils.getDocumentHead=function(a){return a.head?a.head:a.getElementsByTagName("head")?a.getElementsByTagName("head")[0]:a.documentElement?a.documentElement:a.body&&a.body.parentNode?a.body.parentNode:null};Downsha.Utils.makeAbsoluteClientRect=function(a,b){b||(b=window);return{top:a.top+b.pageYOffset,bottom:a.bottom+b.pageYOffset,left:a.left+b.pageXOffset,right:a.right+b.pageXOffset,width:a.width,height:a.height}};
Downsha.Utils.getAbsoluteBoundingClientRect=function(a){var b=a&&a.nodeType==Node.TEXT_NODE?a.parentElement?a.parentElement:a.parentNode:a;if(!b)return null;a=a instanceof Range?a.commonAncestorContainer.ownerDocument.defaultView:a.ownerDocument.defaultView;return Downsha.Utils.makeAbsoluteClientRect(b.getBoundingClientRect(),a)};Downsha.Utils.getElementForNode=function(a){return a&&a.nodeType==Node.ELEMENT_NODE?a:a.parentElement?a.parentElement:null};
Downsha.Utils.addElementClass=function(a,b){if(a&&b){var d=a.getAttribute("class");d?(d=d.split(/\s+/),0>d.indexOf(b)&&d.push(b),a.setAttribute("class",d.join(" "))):a.setAttribute("class",b)}};Downsha.Utils.removeElementClass=function(a,b){if(b){var d=a.getAttribute("class");if(d){var d=d.split(/\s+/),c=-1;0<=(c=d.indexOf(b))&&d.splice(c,1);a.setAttribute("class",d.join(" "))}}};Downsha.Utils.XML_ESCAPE_CHAR_MAP={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"};
Downsha.Utils.escapeXML=function(a){for(var a=a.split(""),b=0;b<a.length;b++)Downsha.Utils.XML_ESCAPE_CHAR_MAP[a[b]]&&(a[b]=Downsha.Utils.XML_ESCAPE_CHAR_MAP[a[b]]);return a.join("")};
Downsha.Utils.escapeURL=function(a){for(var b="",d=0;d<a.length;d++){var c=a.charCodeAt(d);if(128>c)b+=String.fromCharCode(c);else if(2048>c)var e=c>>6|192,f=c&63|128,b=b+("%"+e.toString(16).toUpperCase()),b=b+("%"+f.toString(16).toUpperCase());else 65536>c&&(e=c>>12|224,f=c>>6&63|128,c=c&63|128,b+="%"+e.toString(16).toUpperCase(),b+="%"+f.toString(16).toUpperCase(),b+="%"+c.toString(16).toUpperCase())}return b};
Downsha.Utils.rectIntersection=function(a,b){if(!(b.left>a.right||b.right<a.left||b.top>a.bottom||b.bottom<a.top)){var d={left:Math.max(a.left,b.left),top:Math.max(a.top,b.top),right:Math.min(a.right,b.right),bottom:Math.min(a.bottom,b.bottom)};d.width=d.right-d.left;d.height=d.bottom-d.top;return d}};Downsha.Utils.rectsEqual=function(a,b){return a.left==b.left&&a.right==b.right&&a.top==b.top&&a.bottom==b.bottom?!0:!1};
Downsha.Utils.expandRect=function(a,b){a.left="number"==typeof a.left?Math.min(a.left,b.left):b.left;a.top="number"==typeof a.top?Math.min(a.top,b.top):b.top;a.right="number"==typeof a.right?Math.max(a.right,b.right):b.right;a.bottom="number"==typeof a.bottom?Math.max(a.bottom,b.bottom):b.bottom};
Downsha.Utils.errorDescription=function(a){var b=null;if(a instanceof FileError){var d=a.code;if("number"==typeof d)for(var c in FileError){if(0<c.toLowerCase().indexOf("_err")&&FileError[c]==a.code){b="FileError: "+d+" ("+c+")";break}}else b="FileError: "+d}else a.message?b=a.message:"undefined"!=typeof a.code&&(b=(a.constructor&&a.constructor.name?a.constructor.name:""+a)+" code: "+a.code);return b};
Downsha.UUID={generateQuad:function(){return(65536*(1+Math.random())|0).toString(16).substring(1)},generateGuid:function(){return this.generateQuad()+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+this.generateQuad()+this.generateQuad()}};Downsha.Utils=Downsha.Utils||new function(){};Downsha.Utils.MIN_ARTICLE_RATIO=0.0625;Downsha.Utils.MIN_ARTICLE_AREA=3E4;Downsha.Utils.MAX_ARTICLE_XOFFSET_RATIO=0.6;
Downsha.Utils.querySelectors=function(a,b){var d=null;if(!a)return d;for(var b=b||document,c=0;c<a.length;c++){d=a[c];if(":root"===d)return b;if(d=b.querySelector(d))break}return d};
Downsha.Utils.getArticleNode=function(a,b){a=a||document;if(!a)return null;var d=null;if(b&&b.a){var c=Downsha.Utils.querySelectors(b.a,a);c&&(d=c)}if(!d){var c=["jpeg","jpg","gif","png"],e=a.location.href.replace(/^.*\.(\w+)$/,"$1");e&&-1!=c.indexOf(e)&&(c=a.querySelector("body > img"))&&(d=c)}if(!d&&"frameset"==a.body.nodeName.toLowerCase()){for(var e=a.getElementsByTagName("frame"),c=null,f=0,g=0,h=0;h<e.length;h++)e[h].width&&e[h].height&&(f=e[h].width*e[h].height,f>g&&(c=e[h],g=f));c&&c.contentDocument&&
c.contentDocument.documentElement&&(d=c.contentDocument.documentElement)}d||(c=new ExtractContentJS.LayeredExtractor,c.addHandler(c.factory.getHandler("Heuristics")),c=c.extract(a),c.isSuccess&&(c=c.content.asNode(),d=Downsha.Utils.getElementForNode(c)));return d};Downsha.Utils.isArticleSane=function(a,b,d){if(a&&b&&d){var c=d.width*d.height;if(!(d.top>b*Downsha.Utils.MAX_ARTICLE_XOFFSET_RATIO)&&!(c<Downsha.Utils.MIN_ARTICLE_AREA&&c<a*b*Downsha.Utils.MIN_ARTICLE_RATIO))return!0}return!1};
Downsha.Utils.MESSAGE_ATTR="message";Downsha.Utils.PLACEHOLDER_ATTR="placeholder";Downsha.Utils.TITLE_ATTR="title";Downsha.Utils.MESSAGE_DATA_ATTR="messagedata";Downsha.Utils.LOCALIZED_ATTR="localized";Downsha.Utils.BADGE_NORMAL_COLOR=[255,0,0,255];Downsha.Utils.BADGE_UPLOADING_COLOR=[255,255,0,255];Downsha.Utils.updateBadge=function(a,b){Downsha.Utils.clearBadge(b);Downsha.Utils.setBadgeTitle(chrome.i18n.getMessage("BrowserActionTitle"),b)};
Downsha.Utils.clearBadge=function(a){var b={text:""};"number"==typeof a?this.doInSpecifiedTab(a,function(){b.tabId=a;chrome.browserAction.setBadgeText(b)}):this.clearAllBadges()};Downsha.Utils.clearAllBadges=function(){this.doInEveryNormalTab(function(a){chrome.browserAction.setBadgeText({tabId:a.id,text:""})},!0)};
Downsha.Utils.setBadgeBackgroundColor=function(a,b){var d={color:a};"number"==typeof b?this.doInSpecifiedTab(b,function(){d.tabId=b;chrome.browserAction.setBadgeBackgroundColor(d)}):this.doInEveryNormalTab(function(b){d.tabId=b.id;chrome.browserAction.setBadgeBackgroundColor(d)},!0)};
Downsha.Utils.setBadgeText=function(a,b){if(a){var d={text:""+a};"number"==typeof b?this.doInSpecifiedTab(b,function(){d.tabId=b;chrome.browserAction.setBadgeText(d)}):this.doInEveryNormalTab(function(b){d.tabId=b.id;chrome.browserAction.setBadgeText(d)},!0)}else null==a&&Downsha.Utils.clearBadge(b)};
Downsha.Utils.setBadgeTitle=function(a,b){if(a){var d={title:""+a};"number"==typeof b?this.doInSpecifiedTab(b,function(){d.tabId=b;chrome.browserAction.setTitle(d)}):this.doInEveryNormalTab(function(b){d.tabId=b.id;chrome.browserAction.setTitle(d)},!0)}else null==a&&Downsha.Utils.clearBadgeTitle(b)};
Downsha.Utils.clearBadgeTitle=function(a){var b={title:""};"number"==typeof a?this.doInSpecifiedTab(a,function(){b.tabId=a;chrome.browserAction.setTitle(b)}):this.doInEveryNormalTab(function(a){b.tabId=a.id;chrome.browserAction.setTitle(b)},!0)};Downsha.Utils.doInSpecifiedTab=function(a,b){"number"==typeof a&&chrome.tabs.get(a,function(a){"undefined"!=typeof a&&null!=a&&b()})};
Downsha.Utils.doInEveryNormalTab=function(a,b){chrome.windows.getAll({populate:!0},function(d){for(var c=0;c<d.length;c++)if("normal"==d[c].type)for(var e=0;e<d[c].tabs.length;e++)(!b||d[c].tabs[e].selected)&&a(d[c].tabs[e],d[c])})};
Downsha.Utils.localizeBlock=function(a){a.attr(Downsha.Utils.MESSAGE_ATTR)&&Downsha.Utils.localizeElement(a);for(var a=a.find("["+Downsha.Utils.MESSAGE_ATTR+"], ["+Downsha.Utils.PLACEHOLDER_ATTR+"], ["+Downsha.Utils.TITLE_ATTR+"]"),b=0;b<a.length;b++){var d=$(a.get(b));Downsha.Utils.localizeElement(d)}};Downsha.Utils.extractLocalizationField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.MESSAGE_ATTR)?a.attr(Downsha.Utils.MESSAGE_ATTR):null};
Downsha.Utils.extractLocalizationDataField=function(a){if("function"==typeof a.attr&&a.attr(Downsha.Utils.MESSAGE_DATA_ATTR)){a=a.attr(Downsha.Utils.MESSAGE_DATA_ATTR);try{a=eval(a)}catch(b){}a instanceof Array||(a=[a]);return a}return null};Downsha.Utils.extractLocalizationPlaceholderField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.PLACEHOLDER_ATTR)?a.attr(Downsha.Utils.PLACEHOLDER_ATTR):null};
Downsha.Utils.extractLocalizationTitleField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.TITLE_ATTR)?a.attr(Downsha.Utils.TITLE_ATTR):null};
Downsha.Utils.localizeElement=function(a,b){if(b||!(a.attr(Downsha.Utils.LOCALIZED_ATTR)&&"true"==a.attr(Downsha.Utils.LOCALIZED_ATTR))){var d=Downsha.Utils.extractLocalizationField(a),c=Downsha.Utils.extractLocalizationPlaceholderField(a),e=Downsha.Utils.extractLocalizationTitleField(a),f=Downsha.Utils.extractLocalizationDataField(a),g=!1;"string"==typeof d&&""!=d&&(d=f?chrome.i18n.getMessage(d,f):chrome.i18n.getMessage(d),"INPUT"==a.prop("tagName")?a.val(d):a.html(d),g=!0);"string"==typeof c&&""!=
c&&(d=chrome.i18n.getMessage(c),a.attr(Downsha.Utils.PLACEHOLDER_ATTR,d),g=!0);"string"==typeof e&&""!=e&&(d=chrome.i18n.getMessage(e),a.attr(Downsha.Utils.TITLE_ATTR,d),g=!0);g&&a.attr(Downsha.Utils.LOCALIZED_ATTR,"true")}};Downsha.Utils.notifyExtension=function(a,b){chrome.windows.getCurrent(function(d){chrome.tabs.getSelected(d.id,function(d){var d={tab:d,id:chrome.i18n.getMessage("@@extension_id")},e=b||function(){};chrome.extension.onRequest.dispatch(a,d,e);chrome.extension.sendRequest(a,e)})})};
Downsha.Utils._setDesktopNotificationAttributes=function(a,b){if(a&&"object"==typeof b&&b)for(var d in b)a[d]=b[d]};Downsha.Utils.notifyDesktop=function(a,b,d,c){var e=webkitNotifications.createNotification("images/downsha48.png",a,b);this._setDesktopNotificationAttributes(e,c);e.show();"number"==typeof d&&setTimeout(function(){e.cancel()},d);return e};
Downsha.Utils.notifyDesktopWithHTML=function(a,b,d){var c=webkitNotifications.createHTMLNotification(a);this._setDesktopNotificationAttributes(c,d);c.show();"number"==typeof b&&setTimeout(function(){c.cancel()},b);return c};Downsha.Utils.openWindow=function(a){chrome.extension.getBackgroundPage().Downsha.chromeExtension.openWindow(a)};
Downsha.Utils.getPostData=function(a){"undefined"==typeof a&&(a=window.location.search.replace(/^\?/,""));var b={};if(a)for(var a=a.split("&"),d=0;d<a.length;d++){var c=a[d].split("="),e=unescape(c[0]);if(c=c[1]?unescape(c[1]):null)try{b[e]=JSON.parse(c)}catch(f){b[e]=c}else b[e]=c}return b};
Downsha.Utils.isForbiddenUrl=function(a){return"string"==typeof a&&(0<=a.toLowerCase().indexOf("chrome.google.com/extensions")||0<=a.toLowerCase().indexOf("chrome.google.com/webstore")||0<=a.toLowerCase().indexOf("ext.chrome.360.cn"))||"string"==typeof a&&!a.toLowerCase().match(/^https?:\/\//)?!0:!1};
Downsha.Utils.getTextSize=function(a){var b=$("<div></div>");b.text(a);b.css({position:"absolute",top:"0px",left:"0px",padding:"0px",margin:"0px",display:"block",zIndex:"0",color:"rgba(0, 0, 0, 0)",background:"rgba(0, 0, 0, 0)"});$("body").append(b);a={width:b.width(),height:b.height()};b.remove();return a};
Downsha.Utils.updateSelectElementWidth=function(a,b){var d=a instanceof jQuery?a:$(a),c=d.val();"function"==typeof b&&(c=b(c));var e=parseInt(d.css("paddingLeft")),f=parseInt(d.css("paddingRight")),e=(!isNaN(e)?e:0)+(!isNaN(f)?f:0),c=Downsha.Utils.getTextSize(c).width,c=(c?c:0)+e+10;d.css({minWidth:c+"px",width:c+"px"})};
Downsha.Utils.resizeElement=function(a,b,d){var a=a instanceof jQuery?a:$(a),c={},e={};if(b&&"number"==typeof b.width){var f=parseInt(a.css("paddingLeft")),g=parseInt(a.css("paddingRight")),f=(!isNaN(f)?f:0)+(!isNaN(g)?g:0);e.width=b.width+f;c.minWidth=e.width+"px";c.width=e.width+"px"}b&&"number"==typeof b.height&&(f=parseInt(a.css("paddingTop")),g=parseInt(a.css("paddingBottom")),f=(!isNaN(f)?f:0)+(!isNaN(g)?g:0),e.height=b.height+f,c.minHeight=e.height+"px",css.height=e.height+"px");a.css(c);"function"==
typeof d&&d(a,e)};Downsha.Utils.BAD_FAV_ICON_URLS=["http://localhost/favicon.ico"];
Downsha.Utils.createUrlClipContent=function(a,b,d){a=a?Downsha.Utils.escapeXML(a):"";b='<a title="'+a+'" style="font-size: 12pt; line-height: 18px; display: inline;" href="'+b+'">'+b+"</a>";return b="string"==typeof d&&0<d.length&&0>Downsha.Utils.BAD_FAV_ICON_URLS.indexOf(d.toLowerCase())?'<span><img title="'+a+'" style="display:inline;border: none; width: 16px; height: 16px; padding: 0px; margin: 0px 8px -2px 0px;" src="'+d+'"/>'+b+"</span>":"<span>"+b+"</span>"};
Downsha.Utils.getNodeString=function(a){var b=null;if("object"!=typeof a||null==a)b="[null]";else if(a&&a.nodeType==Node.TEXT_NODE)b="string"==typeof a.nodeValue&&0<a.nodeValue.length?a.nodeName+" "+a.nodeValue:a.nodeName+" [empty]";else if(a&&a.nodeType==Node.ELEMENT_NODE){for(var b="<"+a.nodeName,a=a.attributes,d=0;d<a.length;d++)a[d]&&a[d].name&&a[d].specified&&(b=a[d].value?b+(" "+a[d].name+'="'+a[d].value+'"'):b+(" "+a[d].name));b+=">"}else b="node","string"==typeof a.nodeName&&0<a.nodeName.length&&
(b+=" name: "+a.nodeName),"number"==typeof a.nodeType&&(b+=" type: "+a.nodeType),"string"==typeof a.nodeValue&&0<a.nodeValue.length&&(b+=" value: "+a.nodeValue);return b};Downsha.Semaphore=function(a){this.__defineGetter__("excessSignals",this.getExcessSignals);this.initialize(a)};Downsha.inherit(Downsha.Semaphore,Array);Downsha.Semaphore.mutex=function(){var a=new Downsha.Semaphore;a.signal();return a};Downsha.Semaphore.prototype._excessSignals=0;
Downsha.Semaphore.prototype.initialize=function(a){this._excessSignals=parseInt(a);isNaN(this._excessSignals)&&(this._excessSignals=0)};Downsha.Semaphore.prototype.getExcessSignals=function(){return this._excessSignals};Downsha.Semaphore.prototype.hasExcessSignals=function(){return 0<this._excessSignals?!0:!1};Downsha.Semaphore.prototype.signal=function(){0==this.length?this._excessSignals++:this._processNext()};
Downsha.Semaphore.prototype.wait=function(){0<this._excessSignals&&(this._excessSignals--,this._processNext())};Downsha.Semaphore.prototype.critical=function(a){var b=this,d=function(){try{a()}catch(d){throw b.signal(),d;}};d._semaOrigFn=a;this.push(d);this.wait()};Downsha.Semaphore.prototype.wave=function(){0<this.length&&this.shift()};Downsha.Semaphore.prototype.waveAll=function(){0<this.length&&this.splice(0,this.length)};
Downsha.Semaphore.prototype.waveEach=function(a){for(var b=0;b<this.length;)a(this[b]._semaOrigFn)?this.splice(b,1):b++};Downsha.Semaphore.prototype._processNext=function(){if(0<this.length){var a=this.shift();"function"==typeof a&&a()}};Downsha.Semaphore.prototype.toString=function(){return this._excessSignals+":["+this.join(",")+"]"};
Downsha.XORCrypt={DELIMIT:":",LENGTH:128,_padString:function(a){var b=0;if(128>a.length)for(var d=a.length;128>=d;d++)a=String.fromCharCode(this._randomForChar())+a,b++;return b+this.DELIMIT+a},_randomForChar:function(){for(var a=0,b=0;33>a||126<a;)a=parseInt(150*Math.random()),b++;return a},_randomNonZero:function(){for(var a=0;0==(a=parseInt(100*Math.random())););return a},_shiftString:function(a){for(var b=this._randomNonZero()+100,d=[],c=0;c<a.length;c++)d.push(String.fromCharCode(a.charCodeAt(c)+
b));return b+this.DELIMIT+d.join("")},_unshiftString:function(a){var b=parseInt(a.substring(0,a.indexOf(this.DELIMIT))),d=[];if(!isNaN(b))for(var c=(b+"").length+this.DELIMIT.length;c<a.length;c++)d.push(String.fromCharCode(a.charCodeAt(c)-b));return d.join("")},encrypt:function(a,b){for(var b=b+"",d=this._padString(this._shiftString(a+"")),c=[],e=0;e<d.length;e++){for(var f=d.charCodeAt(e),g=0;g<b.length;g++)f^=b.charCodeAt(g);c.push(String.fromCharCode(f+100))}return c.join("")},decrypt:function(a,
b){for(var a=a+"",b=b+"",d=[],c=0;c<a.length;c++){for(var e=a.charCodeAt(c)-100,f=b.length-1;0<=f;f--)e^=b.charCodeAt(f);d.push(String.fromCharCode(e))}d=d.join("");c=parseInt(d.substring(0,d.indexOf(this.DELIMIT)));return!isNaN(c)?this._unshiftString(d.substring((""+c).length+this.DELIMIT.length+c)):""}};Downsha.Constants=Downsha.Constants||{};
Downsha.Constants.RequestType={UNKNOWN:0,LOGOUT:1001,LOGIN:1002,LOGIN_ERROR:1003,LOGIN_SUCCESS:1004,POPUP_STARTED:2001,POPUP_ENDED:2002,PAGE_CLIP_SUCCESS:3001,PAGE_CLIP_FAILURE:3002,PAGE_CLIP_CONTENT_SUCCESS:3003,PAGE_CLIP_CONTENT_FAILURE:3004,PAGE_CLIP_CONTENT_TOO_BIG:3005,CONTEXT_PAGE_CLIP_SUCCESS:3101,CONTEXT_PAGE_CLIP_FAILURE:3102,CONTEXT_PAGE_CLIP_CONTENT_SUCCESS:3103,CONTEXT_PAGE_CLIP_CONTENT_FAILURE:3104,CONTEXT_PAGE_CLIP_CONTENT_TOO_BIG:3105,CONTENT_SCRIPT_LOAD_TIMEOUT:4001,FETCH_STYLE_SHEET_RULES:4002,
CLIP_ACTION_FULL_PAGE:5001,CLIP_ACTION_ARTICLE:5002,CLIP_ACTION_SELECTION:5003,CLIP_ACTION_URL:5004,PREVIEW_CLIP_ACTION_CLEAR:6001,PREVIEW_CLIP_ACTION_FULL_PAGE:6002,PREVIEW_CLIP_ACTION_ARTICLE:6003,PREVIEW_CLIP_ACTION_SELECTION:6004,PREVIEW_CLIP_ACTION_URL:6005,PREVIEW_NUDGE:6101,PREVIEW_NUDGE_PREVIOUS_SIBLING:6102,PREVIEW_NUDGE_NEXT_SIBLING:6103,PREVIEW_NUDGE_PARENT:6104,PREVIEW_NUDGE_CHILD:6105,PAGE_INFO:7001,FETCH_ARTICLE_RULES:8001};
Downsha.Constants.Limits={DSTP_USER_NAME_LEN_MIN:6,DSTP_USER_NAME_LEN_MAX:16,DSTP_USER_NAME_REGEX:"^[A-Za-z0-9._\\-\\u4e00-\\u9fa5]{6,16}$",DSTP_USER_EMAIL_LEN_MIN:6,DSTP_USER_EMAIL_LEN_MAX:255,DSTP_USER_EMAIL_REGEX:"^\\w+((-\\w+)|(\\.\\w+))*\\@[A-Za-z0-9]+((\\.|-)[A-Za-z0-9]+)*\\.[A-Za-z0-9]+$",DSTP_USER_PWD_LEN_MIN:6,DSTP_USER_PWD_LEN_MAX:16,DSTP_USER_PWD_REGEX:"^[A-Za-z0-9.~!@#$%^&*()+=_-]{6,16}$",DSTP_NOTE_TITLE_LEN_MIN:0,DSTP_NOTE_TITLE_LEN_MAX:127,DSTP_NOTE_TITLE_REGEX:"^$|^[^\\s\\r\\n\\t]([^\\n\\r\\t]{0,253}[^\\s\\r\\n\\t])?$",
DSTP_TAG_NAME_LEN_MIN:1,DSTP_TAG_NAME_LEN_MAX:100,DSTP_TAG_NAME_REGEX:"^[^,\\s\\r\\n\\t]([^,\\n\\r\\t]{0,98}[^,\\s\\r\\n\\t])?$",DSTP_NOTE_TAGS_MIN:0,DSTP_NOTE_TAGS_MAX:100,SERVICE_DOMAIN_LEN_MIN:1,SERVICE_DOMAIN_LEN_MAX:256,CLIP_NOTE_CONTENT_LEN_MAX:5242880};if("undefined"==typeof ExtractContentJS)var ExtractContentJS={};"undefined"==typeof ExtractContentJS.Lib&&(ExtractContentJS.Lib={});
ExtractContentJS.Lib.Util=function(){var a={BenchmarkTimer:function(){var b=function(){var b=new Date,a=0,a=b.getHours(),a=a*60+b.getMinutes(),a=a*60+b.getSeconds();return a=a*1E3+b.getMilliseconds()},a=function(){var a={elapsed:0,reset:function(){a.elapsed=0;return a},start:function(){a.msec=b();return a},stop:function(){a.elapsed=a.elapsed+(b()-a.msec);return a}};return a.start()},c={timers:{},get:function(b){c.timers[b]||(c.timers[b]=new a);return c.timers[b]},reset:function(b){return c.get(b).reset()},
start:function(b){return c.get(b).start()},stop:function(b){return c.get(b).stop()}};return c},Token:function(b){var a={hiragana:/[\u3042-\u3093\u304C-\u307C\u3041-\u3087\u308E\u3063\u30FC]/,katakana:/[\u30A2-\u30F3\u30AC-\u30DC\u30A1-\u30E7\u30EE\u30C3\u30FC]/,kanji:{test:function(b){return"\u4e00"<=b&&b<="\u9fa0"||b==="\u3005"}},alphabet:/[a-zA-Z]/,digit:/[0-9]/},c=function(b){var c={},e;for(e in a)a[e].test(b)&&(c[e]=a[e]);return c},e={first:c(b.charAt(0)),last:c(b.charAt(b.length-1)),isTokenized:function(b,
a){var d=b.length?b.charAt(b.length-1):"",c=a.length?a.charAt(0):"",j=function(b,a){if(b.length)for(var d in a)if(a[d].test(b))return false;return true};return j(d,e.first)&&j(c,e.last)}};return e},inherit:function(b,a){var c=b||{},e;for(e in a)typeof c[e]=="undefined"&&(c[e]=a[e]);return c},countMatch:function(b,a){return b.split(a).length-1},countMatchTokenized:function(b,d){for(var c=0,e=null,f=new a.Token(d),g=b.split(d),h=g.length,i=0;i<h;i++){e&&f.isTokenized(e,g[i])&&c++;e=g[i]}return c},indexOfTokenized:function(b,
d){var c=b.indexOf(d);if(c>=0){var e=new a.Token(d),f=c>1?b.substr(c-1,1):"",g=b.substr(c+d.length,1);if(e.isTokenized(f,g))return c}return-1},dump:function(b){if(typeof b=="undefined")return"undefined";if(typeof b=="string")return'"'+b+'"';if(typeof b!="object")return""+b;if(b===null)return"null";if(b instanceof Array)return"["+b.map(function(){return"obj"}).join(",")+"]";var a=[],c;for(c in b)a.push(c+":obj");return"{"+a.join(",")+"}"}};return a}();
ExtractContentJS.Lib.A=function(){var a={};a.indexOf=Array.indexOf||function(b,a){var c=2,e=b.length,c=Number(arguments[c++])||0,c=c<0?Math.ceil(c):Math.floor(c);for(c<0&&(c=c+e);c<e;c++)if(c in b&&b[c]===a)return c;return-1};a.filter=Array.filter||function(b,a){var c=2,e=b.length;if(typeof a!="function")throw new TypeError("A.filter: not a function");for(var f=[],c=arguments[c++],g=0;g<e;g++)if(g in b){var h=b[g];a.call(c,h,g,b)&&f.push(h)}return f};a.forEach=Array.forEach||function(b,a){var c=2,
e=b.length;if(typeof a!="function")throw new TypeError("A.forEach: not a function");for(var c=arguments[c++],f=0;f<e;f++)f in b&&a.call(c,b[f],f,b)};a.every=Array.every||function(b,a){var c=2,e=b.length;if(typeof a!="function")throw new TypeError("A.every: not a function");for(var c=arguments[c++],f=0;f<e;f++)if(f in b&&!a.call(c,b[f],f,b))return false;return true};a.map=Array.map||function(b,a){var c=2,e=b.length;if(typeof a!="function")throw new TypeError("A.map: not a function");for(var f=Array(e),
c=arguments[c++],g=0;g<e;g++)g in b&&(f[g]=a.call(c,b[g],g,b));return f};a.some=Array.some||function(b,a){var c=2,e=b.length;if(typeof a!="function")throw new TypeError("A.some: not a function");for(var c=arguments[c++],f=0;f<e;f++)if(f in b&&a.call(c,b[f],f,b))return true;return false};a.reduce=Array.reduce||function(b,a){var c=2,e=b.length;if(typeof a!="function")throw TypeError("A.reduce: not a function ");var f=0;if(arguments.length>c)var g=arguments[c++];else{do{if(f in b){g=b[f++];break}if(++f>=
e)throw new TypeError("A.reduce: empty array");}while(1)}for(;f<e;f++)f in b&&(g=a.call(null,g,b[f],f,b));return g};a.zip=function(b){if(b[0]instanceof Array){for(var a=b[0].length,c=b.length,e=Array(a),f=0;f<a;f++){e[f]=[];for(var g=0;g<c;g++)e[f].push(b[g][f])}return e}return[]};a.first=function(b){return b?b[0]:null};a.last=function(b){return b?b[b.length-1]:null};a.push=function(b,a){return Array.prototype.push.apply(b,a)};return a}();
ExtractContentJS.Lib.DOM=function(){var a=ExtractContentJS.Lib.A,b={getElementStyle:function(b,a){var e=b.style?b.style[a]:null;if(!e){var f=b.ownerDocument.defaultView;if(f&&f.getComputedStyle){try{var g=f.getComputedStyle(b,null)}catch(h){return null}a=a.replace(/([A-Z])/g,"-$1").toLowerCase();e=g?g.getPropertyValue(a):null}else b.currentStyle&&(e=b.currentStyle[a])}return e},text:function(b){return typeof b.textContent!="undefined"?b.textContent:b.nodeName=="#text"?b.nodeValue:typeof b.innerText!=
"undefined"?b.innerText:null},ancestors:function(b){for(var a=b.ownerDocument.body,e=[];b!=a;){e.push(b);b=b.parentNode}e.push(a);return e},commonAncestor:function(a,c){for(var e=b.ancestors(a).reverse(),f=b.ancestors(c).reverse(),g=null,h=0;e[h]&&f[h]&&e[h]==f[h];h++)g=e[h];return g},countMatchTagAttr:function(d,c,e,f){var g=function(b){return b.test(d[e])};if((d.tagName||"").toLowerCase()==c&&a.some(f,g))return 1;for(var g=0,h=d.childNodes,i=0,j=h.length;i<j;i++)g=g+b.countMatchTagAttr(h[i],c,e,
f);return g},matchTag:function(d,c){return a.some(c,function(a){return typeof a=="string"?a==(d.tagName||"").toLowerCase():a instanceof Array?a[0]==(d.tagName||"").toLowerCase()&&b.matchAttr(d,a[1]):false})},matchAttr:function(d,c){var e=function(c,f){if(typeof c=="string")return c==f;if(c instanceof RegExp)return c.test(f);if(c instanceof Array)return a.some(c,function(b){return e(b,f)});if(c instanceof Object)for(var g in c){var h=d[g];if(h&&b.matchAttr(h,c[g]))return true}return false},f;for(f in c){var g=
d[f],h=c[f];if(g)return e(h,g)}return false},matchStyle:function(d,c){var e=function(b,d){return typeof b=="string"?b==d:b instanceof RegExp?b.test(d):b instanceof Array?a.some(b,function(b){return e(b,d)}):false},f;for(f in c)if(e(c[f],b.getElementStyle(d,f)))return true;return false}};return b}();"undefined"==typeof ExtractContentJS&&(ExtractContentJS={});
(function(a){var b=a.Lib.Util,d=a.Lib.A,c=a.Lib.DOM,e=b.inherit(function(b,a,d,e){var f=d||{},g=e||1048576;return{node:b,depth:a||0,inside:f,statistics:function(){var a=(c.text(b)||"").replace(/\s+/g," "),d=a.length;return{text:a.substr(0,g),noLinkText:f.link||f.form?"":a,listTextLength:f.list?d:0,noListTextLength:f.list?0:d,linkCount:f.link?1:0,listCount:f.li?1:0,linkListCount:f.li&&f.link?1:0}}}},{commonAncestor:function(){var b=d.map(arguments,function(b){return b.node});return b.length<2?b[0]:
d.reduce(b,function(b,a){return c.commonAncestor(b,a)})},mergeStatistics:function(b,a){var d={},c;for(c in b)d[c]=b[c]+a[c];return d}}),f=function(b){var b=d.filter(b,function(b){b=c.text(b.node)||"";b=b.replace(/\s+/g,"");return b.length!=0}),a={score:0,leaves:b,commonAncestor:function(){return e.commonAncestor.apply(null,a.leaves)}};return a},g=function(b){var a={_content:b,asLeaves:function(){return a._content},asNode:function(){if(a._node)return a._node;a._node=e.commonAncestor.apply(null,a._content);
return a._node},asTextFragment:function(){if(a._textFragment)return a._textFragment;if(a._content.length<1)return"";a._textFragment=d.reduce(a._content,function(b,a){var d=c.text(a.node),d=d.replace(/^\s+/g,"").replace(/\s+$/g,""),d=d.replace(/\s+/g," ");return b+d},"");return a._textFragment},asText:function(){if(a._text)return a._text;var b=a.asNode();a._text=b?c.text(b):"";return a._text},toString:function(){return a.asTextFragment()}};return a};a.LayeredExtractor=function(b,d){var c={handler:b||
[],filter:d||{},factory:{getHandler:function(b){return typeof a.LayeredExtractor.Handler!="undefined"?new a.LayeredExtractor.Handler[b]:null}},addHandler:function(b){typeof b!="undefined"&&c.handler.push(b);return c},filterFor:function(){},extract:function(b){for(var a=b.location.href,d={title:b.title,url:b.location.href},e=c.handler.length,f=0;f<e;f++){var h=c.handler[f].extract(b,a,d);if(h){var i=c.filterFor(a);i&&(h=i.filter(h));h=new g(h);if(h.toString().length){d.content=h;d.isSuccess=true;d.engine=
d.engine||c.handler[f];break}}}return d}};return c};a.LayeredExtractor.Handler={};a.LayeredExtractor.Handler.Heuristics=function(a,g){var j={name:"Heuristics",content:[],opt:b.inherit(a,{threshold:60,minLength:30,factor:{decay:0.75,noBody:0.72,continuous:1.16},punctuationWeight:10,minNoLink:8,noListRatio:0.2,limit:{leaves:800,recursion:20,text:1048576},debug:false}),pat:b.inherit(g,{sep:["div","center","td","h1","h2"],waste:[/Copyright|All\s*Rights?\s*Reserved?/i],affiliate:[/amazon[a-z0-9\.\/\-\?&]+-22/i],
list:["ul","dl","ol"],li:["li","dd"],a:["a"],form:["form"],noContent:["frameset"],ignore:["iframe","img","script","style","select","noscript",["div",{id:[/more/,/menu/,/side/,/navi/],className:[/more/,/menu/,/side/,/navi/]}]],ignoreStyle:{display:"none",visibility:"hidden"},punctuations:/[\u3002\u3001\uFF0E\uFF0C\uFF01\uFF1F]|\.[^A-Za-z0-9]|,[^0-9]|!|\?/})},k=b.inherit(function(a){var g=new f(a);g.eliminateLinks=function(){var b=d.map(g.leaves,function(b){return b.statistics()});if(!b.length)return"";
var b=b.length==1?b[0]:d.reduce(b,function(b,a){return e.mergeStatistics(b,a)}),a=b.noLinkText.length,c=b.listTextLength;if(a<j.opt.minNoLink*b.linkCount)return"";var f=b.linkListCount/(b.listCount||1);return a<j.opt.noListRatio*f*f*c?"":b.noLinkText};g.noBodyRate=function(){var a=0;g.leaves.length>0&&(a=a+d.reduce(g.leaves,function(b,a){return b+c.countMatchTagAttr(a.node,"a","href",j.pat.affiliate)},0));return a=a/2+d.reduce(j.pat.waste,function(a,d){return a+b.countMatch(g._nolink,d)},0)};g.calcScore=
function(a,d){g._nolink=g.eliminateLinks();if(g._nolink.length<j.opt.minLength)return 0;var c=b.countMatch(g._nolink,j.pat.punctuations),c=c*j.opt.punctuationWeight,c=c+g._nolink.length,c=c*a,e=g.noBodyRate(),c=c*Math.pow(j.opt.factor.noBody,e);g._c=g.score=c;g._c1=c*d;return c};g.isAccepted=function(){return g._c>j.opt.threshold};g.isContinuous=function(){return g._c1>j.opt.threshold};g.merge=function(b){g.score=g.score+b._c1;g.depth=Math.min(g.depth,b.depth);d.push(g.leaves,b.leaves);return g};
return g},{split:function(b){var a=[],d=[],f=0,g=j.opt.limit.text,h=function(b){if(b&&d.length){a.push(new k(d));d=[]}},i=function(b,l,k){if(f>=j.opt.limit.leaves||l>=j.opt.limit.recursion||b.nodeName=="#comment"||c.matchTag(b,j.pat.ignore)||c.matchStyle(b,j.pat.ignoreStyle))return a;for(var u=b.childNodes,y=j.pat.sep,v=u.length,k={form:k.form||c.matchTag(b,j.pat.form),link:k.link||c.matchTag(b,j.pat.a),list:k.list||c.matchTag(b,j.pat.list),li:k.li||c.matchTag(b,j.pat.li)},t=0;t<v;t++){var w=u[t],
x=c.matchTag(w,y);h(x);i(w,l+1,k);h(x)}if(!v){f++;d.push(new e(b,l,k,g))}return a};i(b,0,{});h(true);return a}});j.extract=function(b){if(d.some(j.pat.noContent,function(a){return b.getElementsByTagName(a).length!=0}))return j;for(var a=1,c=1,e=[],f=k.split(b.body),g,h=f.length,i=0;i<h;i++){var p=f[i];g&&(c=c/j.opt.factor.continuous);if(p.calcScore(a,c)){a=a*j.opt.factor.decay;if(p.isAccepted()){if(p.isContinuous()&&g)g.merge(p);else{g=p;e.push(p)}c=j.opt.factor.continuous}else g||(a=1)}}j.blocks=
e.sort(function(b,a){return a.score-b.score});if(a=d.first(j.blocks))j.content=a.leaves;return j.content};return j};a.LayeredExtractor.Handler.GoogleAdSection=function(a){var c={name:"GoogleAdSection",content:[],state:[],opt:b.inherit(a,{limit:{leaves:800,recursion:20},debug:false})},g=/google_ad_section_start\(weight=ignore\)/i,k=/google_ad_section_start/i,l=/google_ad_section_end/i;c.inSection=function(){return d.last(c.state)==2};c.ignore=function(){c.state.push(1)};c.section=function(){c.state.push(2)};
c.end=function(){c.state.length&&c.state.pop()};c.parse=function(b,a){var d=a||0;if(b.nodeName=="#comment")g.test(b.nodeValue)?c.ignore():k.test(b.nodeValue)?c.section():l.test(b.nodeValue)&&c.end();else if(!(c.content.length>=c.opt.limit.leaves)&&!(d>=c.opt.limit.recursion)){for(var f=b.childNodes,h=f.length,s=0;s<h;s++)c.parse(f[s],d+1);!h&&c.inSection()&&c.content.push(new e(b,d))}};c.extract=function(b){c.parse(b);c.blocks=[new f(c.content)];return c.content};return c}})(ExtractContentJS);
Downsha.RequestMessage=function(a,b){this.initialize(a,b)};Downsha.RequestMessage.fromObject=function(a){var b=new Downsha.RequestMessage;if(typeof a=="object"&&a!=null){if(typeof a.code!="undefined")b.code=a.code;if(typeof a.message!="undefined")b.message=a.message}return b};Downsha.RequestMessage.prototype._code=0;Downsha.RequestMessage.prototype._message=null;Downsha.RequestMessage.prototype._callback=null;
Downsha.RequestMessage.prototype.initialize=function(a,b){this.__defineGetter__("code",this.getCode);this.__defineSetter__("code",this.setCode);this.__defineGetter__("message",this.getMessage);this.__defineSetter__("message",this.setMessage);this.__defineGetter__("callback",this.getCallback);this.__defineSetter__("callback",this.setCallback);this.code=a;this.message=b};Downsha.RequestMessage.prototype.getCode=function(){return this._code};
Downsha.RequestMessage.prototype.setCode=function(a){this._code=parseInt(a);if(isNaN(this._code))this._code=0};Downsha.RequestMessage.prototype.getMessage=function(){return this._message};Downsha.RequestMessage.prototype.setMessage=function(a){this._message=a};Downsha.RequestMessage.prototype.getCallback=function(){return this._callback};Downsha.RequestMessage.prototype.setCallback=function(a){if(typeof a=="function"||a==null)this._callback=a};
Downsha.RequestMessage.prototype.send=function(){chrome.extension.sendRequest({code:this.code,message:this.message})};Downsha.RequestMessage.prototype.isEmpty=function(){return this.code?false:true};
(function(){var a=null,b=false;Downsha.SelectionFinder=function(d){this.document=this.initDocument=d;a=Downsha.Logger.getInstance();a.level==Downsha.Logger.LOG_LEVEL_DEBUG&&(b=true)};Downsha.SelectionFinder.prototype.initDocument=null;Downsha.SelectionFinder.prototype.document=null;Downsha.SelectionFinder.prototype.selection=null;Downsha.SelectionFinder.prototype.reset=function(){this.document=this.initDocument;this.selection=null};Downsha.SelectionFinder.prototype.hasSelection=function(){var b=this.getRange();
return b&&(b.startContainer!=b.endContainer||b.startContainer==b.endContainer&&b.startOffset!=b.endOffset)?true:false};Downsha.SelectionFinder.prototype.find=function(b){b=this._findSelectionInDocument(this.document,b);this.document=b.document;this.selection=b.selection};Downsha.SelectionFinder.prototype.getRange=function(){if(!this.selection||this.selection.rangeCount==0)return null;if(typeof this.selection.getRangeAt=="function")return this.selection.getRangeAt(0);var b=this.document.createRange();
b.setStart(this.selection.anchorNode,this.selection.anchorOffset);b.setEnd(this.selection.focusNode,this.selection.focusOffset);return b};Downsha.SelectionFinder.prototype.getCommonAncestorContainer=function(){var b=this.getRange();if(b&&b.commonAncestorContainer){for(b=b.commonAncestorContainer;b&&b.nodeType!=Node.ELEMENT_NODE;)b=b.parentElement;return b}return null};Downsha.SelectionFinder.prototype._findSelectionInDocument=function(d,c){var e=null;typeof d.getSelection=="function"?e=d.getSelection():
d.selection&&typeof d.selection.createRange=="function"&&(e=d.selection.createRange());if(e&&e.rangeCount==0&&c){var f=Downsha.Utils.findDocuments(d);if(f.length>0){b&&a.debug("find selection range empty, trying frames, count: "+f.length);for(var g=0;g<f.length;g++)if(f[g]){b&&a.debug("trying nested doc: "+f[g]);var h=this._findSelectionInDocument(f[g],c);if(h.selection.rangeCount>0)return h}}}return{document:d,selection:e}}})();Downsha.Scroller=function(){this.initialize()};
Downsha.Scroller.prototype.initialize=function(){this.initialPoint={x:window.pageXOffset,y:window.pageYOffset}};Downsha.Scroller.scrollTo=function(a,b,d,c){d||(d=300);c||(c=10);this._instance&&this._instance.abort();this._instance=new Downsha.Scroller;this._instance.scrollTo({x:a,y:b},d,c)};Downsha.Scroller.prototype.scrollTo=function(a,b,d){this.endPoint=a;this.step=0;this.calculatePath(b,d);var c=this;this.proc=setInterval(function(){c.doScroll()||c.abort()},d)};
Downsha.Scroller.prototype.calculatePath=function(a,b){this.path=[];for(var d=this.initialPoint.x,c=this.initialPoint.y,e=this.endPoint.x,f=this.endPoint.y,g=Math.PI*b/a,h=-(Math.PI/2);h<Math.PI/2;h=h+g){var i=(1+Math.sin(h))/2;this.path.push({x:d+i*(e-d),y:c+i*(f-c)})}};Downsha.Scroller.prototype.doScroll=function(){var a=this.path[++this.step];if(!a)return false;window.scrollTo(a.x,a.y);return true};Downsha.Scroller.prototype.abort=function(){if(this.proc){clearInterval(this.proc);this.proc=null}};
Downsha.NodeRect=function(){this.__defineGetter__("width",this.getWidth);this.__defineGetter__("height",this.getHeight)};Downsha.NodeRect.fromNode=function(a){var b=null,b=a.ownerDocument.createRange();a.childNodes.length==0?b.selectNode(a):b.selectNodeContents(a);(b=b.getBoundingClientRect())&&(b=Downsha.NodeRect.fromObject(b));return b};
Downsha.NodeRect.fromObject=function(a){var b=new Downsha.NodeRect;if(a)for(var d=["left","top","right","bottom"],c=0;c<d.length;c++)a[d[c]]&&(b[d[c]]=a[d[c]]);return b};Downsha.NodeRect.prototype.left=0;Downsha.NodeRect.prototype.top=0;Downsha.NodeRect.prototype.right=0;Downsha.NodeRect.prototype.bottom=0;Downsha.NodeRect.prototype.getWidth=function(){return this.right-this.left};Downsha.NodeRect.prototype.getHeight=function(){return this.bottom-this.top};
Downsha.NodeRect.prototype.toString=function(){return""+this.left+":"+this.top+"x"+this.right+":"+this.bottom+" ("+this.width+"x"+this.height+")"};Downsha.ClipStyle=function(a,b){this.__defineGetter__("styleFilter",this.getFilter);this.__defineSetter__("styleFilter",this.setFilter);this.initialize(a,b)};Downsha.ClipStyle.stylePrefix=function(a){if(typeof a=="string"){var b=0;if((b=a.indexOf("-"))>0)return a.substring(0,b)}return a};
Downsha.ClipStyle.findFontFaceRules=function(a){for(var a=(a||document).styleSheets,b=[],d=0;d<a.length;d++){var c=a[d];if(c.cssRules)for(var e=0;e<c.cssRules.length;e++){var f=c.cssRules[e];f instanceof CSSFontFaceRule&&b.push(f)}}return b};Downsha.ClipStyle.PERIMETERS=["top","right","bottom","left"];Downsha.ClipStyle.PERIMETER_PROPS={margin:null,padding:null};
Downsha.ClipStyle.PERIMETER_EXTRA_PROPS={border:["width","style","color"],"border-top":["width","style","color"],"border-right":["width","style","color"],"border-bottom":["width","style","color"],"border-left":["width","style","color"],outline:["width","style","color"]};Downsha.ClipStyle.prototype.length=0;Downsha.ClipStyle.prototype._filter=null;
Downsha.ClipStyle.prototype.initialize=function(a,b){this.styleFilter=b;if(a instanceof CSSRuleList||a instanceof Array){if(a.length>0)for(var d=0;d<a.length;d++)this.addStyle(a[d].style)}else a instanceof CSSStyleRule?this.addStyle(a.style):a instanceof CSSStyleDeclaration?this.addStyle(a):typeof a=="object"&&a!=null&&this.addStyle(a)};
Downsha.ClipStyle.prototype._addPerimeterStyle=function(a,b){var d=b.replace(/\s+/," ").split(" ");d.length==1?d=d.concat(d,d,d):d.length==2?d=d.concat(d[0],d[1]):d.length==3?d=d.concat(d[1]):d.length==0&&(d=["auto","auto","auto","auto"]);for(var c=0;c<Downsha.ClipStyle.PERIMETERS.length;c++)this._addSimpleStyle(a+"-"+Downsha.ClipStyle.PERIMETERS[c],d[c])};
Downsha.ClipStyle.prototype._addPerimeterExtraStyle=function(a,b){var d=Downsha.ClipStyle.PERIMETER_EXTRA_PROPS[a];if(d instanceof Array)for(var c=b.replace(/\s+/g," ").split(" "),e=RegExp(Downsha.ClipStyle.PERIMETERS.join("|"),"i"),e=a.match(e)?true:false,f=0;f<Downsha.ClipStyle.PERIMETERS.length;f++){for(var g=0;g<d.length;g++){var h=a+(e?"":"-"+Downsha.ClipStyle.PERIMETERS[f])+"-"+d[g];c[g]&&this._addSimpleStyle(h,c[g])}if(e)break}};
Downsha.ClipStyle.prototype._addSimpleStyle=function(a,b){typeof this[a]=="undefined"&&this.length++;this[a]=b};
Downsha.ClipStyle.prototype.addStyle=function(a){if(a instanceof CSSStyleDeclaration&&a.length>0)for(var b=0;b<a.length;b++){var d=a[b];if(!this.styleFilter||this.styleFilter(d,a.getPropertyValue(d))){var c=a.getPropertyValue(d);typeof Downsha.ClipStyle.PERIMETER_PROPS[d]!="undefined"?this._addPerimeterStyle(d,c):typeof Downsha.ClipStyle.PERIMETER_EXTRA_PROPS[d]!="undefined"?this._addPerimeterExtraStyle(d,c):this._addSimpleStyle(d,c)}}else if(a instanceof Downsha.ClipStyle)for(d in a){if(typeof this.constructor.prototype[d]==
"undefined"&&(!this.styleFilter||this.styleFilter(d,a[d]))){c=a[d];typeof Downsha.ClipStyle.PERIMETER_PROPS[d]!="undefined"?this._addPerimeterStyle(d,c):typeof Downsha.ClipStyle.PERIMETER_EXTRA_PROPS[d]!="undefined"?this._addPerimeterExtraStyle(d,c):this._addSimpleStyle(d,c)}}else if(typeof a=="object"&&a!=null)for(d in a)if((!this.styleFilter||this.styleFilter(d,a[d]))&&typeof a[d]!="function"&&typeof this.constructor.prototype[d]=="undefined"){c=a[d];typeof Downsha.ClipStyle.PERIMETER_PROPS[d]!=
"undefined"?this._addPerimeterStyle(d,c):typeof Downsha.ClipStyle.PERIMETER_EXTRA_PROPS[d]!="undefined"?this._addPerimeterExtraStyle(d,c):this._addSimpleStyle(d,c)}};
Downsha.ClipStyle.prototype.removeStyle=function(a,b){function d(a,d){if(typeof c[a]!="undefined"&&typeof c.constructor.prototype[a]=="undefined"&&(typeof b=="function"||c[a]==d))(typeof b!="function"||typeof b=="function"&&b(a,c[a],d))&&delete c[a]&&c.length--}var c=this;if(a instanceof CSSStyleDeclaration&&a.length>0)for(var e=0;e<a.length;e++){var f=a[e];d(f,a.getPropertyValue(f))}else if(a instanceof Downsha.ClipStyle&&a.length>0)for(f in a)d(f,a[f]);else if(a instanceof Array)for(e=0;e<a.length;e++)d(a[e],
this[a[e]]);else typeof a=="string"&&d(a,this[a])};Downsha.ClipStyle.prototype.removeStyleIgnoreValue=function(a){this.removeStyle(a,function(){return true})};Downsha.ClipStyle.styleInArray=function(a,b){if(typeof a!="string"||!(b instanceof Array))return false;for(var d=-1,c=a.toLowerCase(),e=(d=c.indexOf("-"))>0?c.substring(0,d):c,d=0;d<b.length;d++)if(b[d]==c||b[d]==e)return true;return false};
Downsha.ClipStyle.prototype.deriveStyle=function(a,b,d){this.removeStyle(a,function(a,e,f){return d instanceof Array&&Downsha.ClipStyle.styleInArray(a,d)?false:typeof b[a]!="undefined"&&e==f})};Downsha.ClipStyle.prototype.setFilter=function(a){if(typeof a=="function")this._filter=a;else if(a==null)this._filter=null};Downsha.ClipStyle.prototype.getFilter=function(){return this._filter};
Downsha.ClipStyle.prototype.mergeStyle=function(a,b){if(a instanceof Downsha.ClipStyle&&a.length>0){var d=true,c;for(c in a)if(!(typeof this.constructor.prototype[c]!="undefined"||typeof this.__lookupSetter__(c)!="undefined"))if((d=typeof this[c]=="undefined")||b){this[c]=a[c];d&&this.length++}}};Downsha.ClipStyle.prototype.clone=function(){var a=new Downsha.ClipStyle,b;for(b in this)typeof this.constructor.prototype[b]=="undefined"&&(a[b]=this[b]);a.length=this.length;return a};
Downsha.ClipStyle.prototype.toString_background=function(a){var b="";typeof this["background-color"]!="undefined"&&this["background-color"]!="rgba(0, 0, 0, 0)"&&(b=b+("background: "+this["background-color"]));if(typeof this["background-image"]!="undefined"&&this["background-image"]!="none"){b=b+(" "+this["background-image"]);typeof this["background-position"]!="undefined"&&(b=b+(" "+this["background-position"]));typeof this["background-repeat"]!="undefined"&&(b=b+(" "+this["background-repeat"]))}if(a){a["background-color"]=
null;a["background-image"]=null;a["background-position"]=null;a["background-repeat"]=null}b.length==0?b=b+"background:none;":b.length>0&&b.charAt(b.length-1)!=";"&&(b=b+";");return b};Downsha.ClipStyle.prototype.toString_outline=function(a){var b=this._toPerimeterExtraString("outline");if(a){a["outline-style"]=null;a["outline-width"]=null;a["outline-color"]=null}b.length>0&&b.charAt(b.length-1)!=";"?b=b+";":b.length==0&&(b="outline:none;");return b};
Downsha.ClipStyle.prototype.toString_margin=function(a){var b=this._toPerimeterString("margin");if(a){a["margin-top"]=null;a["margin-right"]=null;a["margin-bottom"]=null;a["margin-left"]=null}b.length>0&&b.charAt(b.length-1)!=";"?b=b+";":b.length==0&&(b="margin:none;");return b};
Downsha.ClipStyle.prototype.toString_padding=function(a){var b=this._toPerimeterString("padding");if(a){a["padding-top"]=null;a["padding-right"]=null;a["padding-bottom"]=null;a["padding-left"]=null}b.length>0&&b.charAt(b.length-1)!=";"?b=b+";":b.length==0&&(b="padding:none;");return b};
Downsha.ClipStyle.prototype.toString_border=function(a){var b=this._toPerimeterExtraString("border");if(a){a["border-top-width"]=null;a["border-top-style"]=null;a["border-top-color"]=null;a["border-right-width"]=null;a["border-right-style"]=null;a["border-right-color"]=null;a["border-bottom-width"]=null;a["border-bottom-style"]=null;a["border-bottom-color"]=null;a["border-left-width"]=null;a["border-left-style"]=null;a["border-left-color"]=null}b.length>0&&b.charAt(b.length-1)!=";"&&(b=b+";");if(b.length==
0||b.indexOf("none")>=0)b="border:none;";return b};
Downsha.ClipStyle.prototype.toString=function(a){var b="",d={};if(a){b=b+this.toString_background(d);b=b+this.toString_border(d);b=b+this.toString_margin(d);b=b+this.toString_outline(d);b=b+this.toString_padding(d)}else{if(this["background-image"]){b=b+("background-image:"+this["background-image"]+";");d["background-image"]=true}b=b+("background-repeat:"+(this["background-repeat-x"]?this["background-repeat-x"]:"initial")+" "+(this["background-repeat-y"]?this["background-repeat-y"]:"initial")+";");
d["background-repeat-x"]=true;d["background-repeat-y"]=true;d["background-repeat"]=true}if(this.length>0)for(var c in this)typeof this[c]!="string"||typeof this.constructor.prototype[c]!="undefined"||this[c].length==0||typeof d[c]!="undefined"||(b=b+(c+":"+this[c]+";"));return b};
Downsha.ClipStyle.prototype._toPerimeterString=function(a){for(var b=[],d=true,c=false,e="",f=0;f<Downsha.ClipStyle.PERIMETERS.length;f++){b[f]=this[a+"-"+Downsha.ClipStyle.PERIMETERS[f]];b[f]?e=e+(a+"-"+Downsha.ClipStyle.PERIMETERS[f]+":"+b[f]+";"):c=true;f>0&&d&&b[f]!=b[f-1]&&(d=false)}if(c)return e;d?b=[b[0]]:b[0]==b[2]&&b[1]==b[3]&&(b=[b[0],b[1]]);return a+":"+b.join(" ")+";"};
Downsha.ClipStyle.prototype._toPerimeterExtraString=function(a){for(var b=[],d=true,c="",e=0;e<Downsha.ClipStyle.PERIMETERS.length;e++){var f=a+"-"+Downsha.ClipStyle.PERIMETERS[e],g=Downsha.ClipStyle.PERIMETER_EXTRA_PROPS[f]||Downsha.ClipStyle.PERIMETER_EXTRA_PROPS[a];if(g instanceof Array){for(var h="",i="",j=false,k=0;k<g.length;k++){var l=f+"-"+g[k];if(this[l]){h=h+(this[l]+(k==g.length-1?"":" "));i=i+(l+":"+this[l]+";")}else{j=true;d=false}}if(j)c=c+i;else{b[e]=h;c=c+(f+":"+h+";")}}if(e>0&&d&&
(!b[e]||b[e]!=b[e-1]))d=false}return d?a+":"+b[0]+";":c};Downsha.ClipStyle.prototype.toJSON=function(){var a={};if(this.length>0)for(var b in this)typeof this[b]!="string"||typeof this.constructor.prototype[b]!="undefined"||this[b].length==0||(a[b]=this[b]);return a};Downsha.ClipStylingStrategy=function(a){this.initialize(a)};Downsha.ClipStylingStrategy.DEFAULT_FILTER=function(a,b){return b&&a!="orphans"&&a!="widows"&&a!="speak"&&a.indexOf("page-break")!=0&&a.indexOf("pointer-events")!=0};
Downsha.ClipStylingStrategy.prototype.initialize=function(a){this.window=a};Downsha.ClipStylingStrategy.prototype.styleForNode=function(){return null};Downsha.ClipStylingStrategy.prototype.getNodeView=function(a){a=a.ownerDocument;return a.defaultView?a.defaultView:this.window};
Downsha.ClipStylingStrategy.prototype.getNodeStyle=function(a,b,d){d=typeof d=="function"?d:Downsha.ClipStylingStrategy.DEFAULT_FILTER;if(a&&typeof a.nodeType=="number"&&a.nodeType==1){var c=this.getNodeView(a),e=typeof c.getMatchedCSSRules=="function"?true:false;if(b)return style=new Downsha.ClipStyle(c.getComputedStyle(a,""),d);if(e)return style=new Downsha.ClipStyle(c.getMatchedCSSRules(a,""),d)}a=new Downsha.ClipStyle;a.setFilter(d);return a};
Downsha.ClipStylingStrategy.prototype.getFontFaceRules=function(){return Downsha.ClipStyle.findFontFaceRules()};Downsha.ClipStylingStrategy.prototype.cleanUp=function(){return true};Downsha.ClipStylingStrategy.prototype.styleForFloatClearingNode=function(){return null};Downsha.ClipTextStylingStrategy=function(a){this.initialize(a)};Downsha.inherit(Downsha.ClipTextStylingStrategy,Downsha.ClipStylingStrategy);
Downsha.ClipTextStylingStrategy.FORMAT_NODE_NAMES={b:null,big:null,em:null,i:null,small:null,strong:null,sub:null,sup:null,ins:null,del:null,s:null,strike:null,u:null,code:null,kbd:null,samp:null,tt:null,"var":null,pre:null,listing:null,plaintext:null,xmp:null,abbr:null,acronym:null,address:null,bdo:null,blockquote:null,q:null,cite:null,dfn:null};Downsha.ClipTextStylingStrategy.STYLE_ATTRS={font:null,text:null,color:null};Downsha.ClipTextStylingStrategy.COLOR_THRESH=50;
Downsha.ClipTextStylingStrategy.prototype.isFormatNode=function(a){return a&&a.nodeType==1&&typeof Downsha.ClipTextStylingStrategy.FORMAT_NODE_NAMES[a.nodeName.toLowerCase()]!="undefined"};Downsha.ClipTextStylingStrategy.prototype.hasTextNodes=function(a){if(a&&a.nodeType==1&&a.childNodes.length>0)for(var b=0;b<a.childNodes.length;b++)if(a.childNodes[b].nodeType==3)return true;return false};
Downsha.ClipTextStylingStrategy.prototype.styleFilter=function(a){a=Downsha.ClipStyle.stylePrefix(a.toLowerCase());if(typeof Downsha.ClipTextStylingStrategy.STYLE_ATTRS[a]!="undefined")return true};
Downsha.ClipTextStylingStrategy.prototype.styleForNode=function(a){var b=null;if(this.isFormatNode(a)||this.hasTextNodes(a))b=this.getNodeStyle(a,true,this.styleFilter);if(b&&b.color){var d=b.color.replace(/[^0-9,\s]+/g,"").replace(/[,\s]+/g," ").split(/\s+/),c=parseInt(d[0]),c=isNaN(c)?0:c,e=parseInt(d[1]),e=isNaN(e)?0:c,f=parseInt(d[2]),f=isNaN(f)?0:f;if(c+e+f>(255-Downsha.ClipTextStylingStrategy.COLOR_THRESH)*3){c=Math.max(0,c-Downsha.ClipTextStylingStrategy.COLOR_THRESH);e=Math.max(0,e-Downsha.ClipTextStylingStrategy.COLOR_THRESH);
f=Math.max(0,f-Downsha.ClipTextStylingStrategy.COLOR_THRESH)}b.color=d.length==4?"rgba("+[c,e,f,1].join(", ")+")":"rgb("+[c,e,f].join(", ")+")"}if(b&&!b.direction)(a=this.getNodeStyle(a,true))&&a.direction&&a.direction!="ltr"&&b._addSimpleStyle("direction",a.direction);return b};
(function(){var a=null;Downsha.ClipFullStylingStrategy=function(b){a=Downsha.Logger.getInstance();this.initialize(b)};Downsha.inherit(Downsha.ClipFullStylingStrategy,Downsha.ClipStylingStrategy);Downsha.ClipFullStylingStrategy.SKIP_UNDEFINED_PROPS={widows:null,orphans:null,"pointer-events":null,speak:null};Downsha.ClipFullStylingStrategy.SKIP_NONINHERENT_AUTO_PROPS={left:"auto",right:"auto","float":"auto",clear:"auto","image-rendering":"auto","z-index":"auto","color-rendering":"auto","shapre-rendering":"auto",
"page-break-before":"auto","page-break-after":"auto","page-break-inside":"auto"};Downsha.ClipFullStylingStrategy.LIST_NODES={UL:null,OL:null,LI:null};Downsha.ClipFullStylingStrategy.NODE_PROPS={BR:["clear","padding","margin","line-height","border","white-space"]};Downsha.ClipFullStylingStrategy.TEXT_NODES={A:null,B:null,BIG:null,EM:null,I:null,SMALL:null,STRONG:null,SUB:null,SUP:null,INS:null,DEL:null,S:null,STRIKE:null,U:null,CODE:null,KBD:null,SAMP:null,TT:null,VAR:null,PRE:null,LISTING:null,PLAINTEXT:null,
XMP:null,ABBR:null,ACRONYM:null,ADDRESS:null,BDO:null,BLOCKQUOTE:null,Q:null,CITE:null,DFN:null};Downsha.ClipFullStylingStrategy.prototype.styleForNode=function(b,d,c){var e=this.getNodeStyle(b,false),f=e.height,g=this.getNodeStyle(b,true),h=b.style,i=b==d?true:false;if(i){g["font-size"]&&e._addSimpleStyle("font-size",g["font-size"]);g["font-family"]&&e._addSimpleStyle("font-family",g["font-family"]);e._addSimpleStyle("margin","0px");e.position?e.position="relative":e._addSimpleStyle("position","relative");
if(!c){var j=this._inhBackgroundForNode(b,true);j.length>0&&e.mergeStyle(j,false);var k=this._inhFontForNode(b,true);k.length>0&&e.mergeStyle(k,false);if(b.nodeName!="HTML"&&b.nodeName!="BODY"&&j["background-image"]){a.debug("Setting fixed width because it's not a top-level tag and has background-image");g.width&&g.width!="0px"&&e._addSimpleStyle("width",g.width);f&&g.height&&g.height!="0px"&&e._addSimpleStyle("height",g.height)}e["float"]&&e.removeStyle("float")}}if(!c&&b.childElementCount!=b.childNodes.length){j=
false;for(k=0;k<b.childNodes.length;k++)if(b.childNodes[k].nodeType==Node.TEXT_NODE){j=true;break}if(j&&g["font-size"]){a.debug("Adding font-size to text node without font-size spec");e._addSimpleStyle("font-size",g["font-size"])}}if(b.nodeName=="CANVAS"&&typeof b.toDataURL=="function")e._addSimpleStyle("background-image","url("+b.toDataURL()+")");else if(b.nodeName=="OBJECT"||b.nodeName=="EMBED"){e._addSimpleStyle("width",g.width);e._addSimpleStyle("min-width",g.width);e._addSimpleStyle("max-width",
g.width);e._addSimpleStyle("height",g.height);e._addSimpleStyle("min-height",g.height);e._addSimpleStyle("max-height",g.height);e._addSimpleStyle("display",g.display);e._addSimpleStyle("overflow",g.hidden)}if(!c&&(i||b.parentElement==d)&&e.position=="absolute"){b=b.getBoundingClientRect();i=parseInt(g["margin-left"]);c=parseInt(g["margin-top"]);i=b.left-(isNaN(i)?0:i);b=b.top-(isNaN(c)?0:c);if(typeof d._downsha_absolute_xOffset=="number"&&typeof d._downsha_absolute_yOffset=="number"){i=Math.max(0,
i-d._downsha_absolute_xOffset);b=Math.max(0,b-d._downsha_absolute_yOffset);e._addSimpleStyle("left",i+"px");e._addSimpleStyle("top",b+"px")}else{d._downsha_absolute_xOffset=i;d._downsha_absolute_yOffset=b;e._addSimpleStyle("top","0px");e._addSimpleStyle("left","0px")}e.removeStyle("right");e.removeStyle("bottom")}for(d=0;d<h.length;d++)e._addSimpleStyle(h[d],h.getPropertyValue(h[d]));f&&e.height&&g.height&&(e.height=g.height);!e.direction&&g.direction&&g.direction!="ltr"&&e._addSimpleStyle("direction",
g.direction);return e};Downsha.ClipFullStylingStrategy.prototype._hasTextOnlyChildren=function(b){if(b){if(b.childElementCount!=0)for(var a=b.childElementCount,c=0;c<a;c++)if(typeof this.constructor.TEXT_NODES[b.children[c]]=="undefined")return false;return true}return false};Downsha.ClipFullStylingStrategy.prototype._mergeBoundingRects=function(b,a){b.left=Math.min(b.left,a.left);b.right=Math.max(b.right,a.right);b.top=Math.min(b.top,a.top);b.bottom=Math.max(b.bottom,a.bottom);b.width=b.right-b.left;
b.height=b.bottom-b.top};Downsha.ClipFullStylingStrategy.prototype._inhBackgroundForNode=function(b,d){a.debug("ClipFullStylingStrategy._inhBackgroundForNode");for(var c=b.parentNode,e=[],f=[],g=["background-repeat-x","background-repeat-y","background-position-x","background-position-y","background-origin","background-size"],h=this.window.document.body.parentElement?this.window.document.body.parentElement:this.window.document.body;c;){f.push(c);e.push(this.getNodeStyle(c,true,function(b,a){return b==
"background-color"||b=="background-image"&&a!="none"||g.indexOf(b)>=0||b=="opacity"||b=="filter"?true:false}));if(!d||c==h)break;else c=c.parentElement}a.debug("Retracted "+e.length+" styles");for(var c=new Downsha.ClipStyle,i=h=0;i<e.length;i++){var j=e[i],k=f[i];a.dir(j);if(j["background-color"]&&j["background-color"]!="transparent"&&!j["background-color"].match(/rgba\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*,\s*0\s*\)/)&&!c["background-color"]){a.debug("Setting background-color: "+j["background-color"]);
h=i;c._addSimpleStyle("background-color",j["background-color"])}if(j["background-image"]&&!c["background-image"]&&(i==h||!c["background-color"])){a.debug("Adding background-image: "+j["background-image"]);c._addSimpleStyle("background-image",j["background-image"]);for(var l=0;l<g.length;l++){var m=g[l];if(j[m]&&m.indexOf("background-repeat")<0){a.debug("Adding "+m);c._addSimpleStyle(m,j[m])}}l=j["background-repeat-x"]&&j["background-repeat-x"]!="initial"?j["background-repeat-x"]:"no-repeat";m=j["background-repeat-y"]&&
j["background-repeat=y"]!="initial"?j["background-repeat-y"]:"no-repeat";c._addSimpleStyle("background-repeat-x",l);c._addSimpleStyle("background-repeat-y",l);c._addSimpleStyle("background-repeat",l+" "+m);if(k){a.debug("Dettermining background image offset");m=k.getBoundingClientRect();a.debug("bgNodeRect left: "+m.left+"; top: "+m.top);var n=b.getBoundingClientRect();a.debug("nodeRect left: "+n.left+"; top: "+n.top);l=n.top-m.top;n=n.left-m.left;a.debug("xDelta: "+n+"; yDelta: "+l);var o=this.getNodeView(k).getComputedStyle(k),
k=o.getPropertyValue("background-position-x"),r=o.getPropertyValue("background-position-y");a.debug("bg position: "+k+" "+r);var q=0,o=0,q=k.indexOf("%")>0?m.width*(parseInt(k)/100):parseInt(k),o=r.indexOf("%")>0?m.height*(parseInt(r)/100):parseInt(r);isNaN(q)&&(q=0);isNaN(o)&&(o=0);a.debug("origPosX: "+q+"; origPosY: "+o);m=0-n+q;l=0-l+o;a.debug("xOffset: "+m+"; yOffset: "+l);c._addSimpleStyle("background-position",m+"px "+l+"px")}}j.opacity&&!c.opacity&&!isNaN(parseFloat(j.opacity))&&(typeof c.opacity==
"undefined"||parseFloat(j.opacity)<parseFloat(c.opacity))&&c._addSimpleStyle("opacity",j.opacity);j.filter&&!c.filter&&(typeof c.filter=="undefined"||parseFloat(j.filter.replace(/[^0-9]+/g,""))<parseFloat(c.filter.replace(/[^0-9]+/g,"")))&&c._addSimpleStyle("filter",j.filter)}return c};Downsha.ClipFullStylingStrategy.prototype._inhFontForNode=function(b,d){for(var c=b.parentNode,e=[],f=[],g=["font-family","color","line-height"];c;){f.push(c);e.push(this.getNodeStyle(c,true,function(b){return g.indexOf(b)>=
0?true:false}));if(!d||c==this.window.document.body)break;else c=c.parentElement}c=new Downsha.ClipStyle;for(f=0;f<e.length;f++)for(var h=e[f],i=0;i<g.length;i++)if(!c[g[i]]&&h[g[i]]){a.debug("Adding "+g[i]+": "+h[g[i]]);c._addSimpleStyle(g[i],h[g[i]])}return c};Downsha.ClipFullStylingStrategy.prototype.cleanUp=function(){if(this._dirty)for(var b=this.window.document.getElementsByTagName("*"),a=0;a<b.length;a++)delete b[a][this.constructor.COMPUTED_STYLE_KEY];return true};Downsha.ClipFullStylingStrategy.prototype.styleForFloatClearingNode=
function(b){if(b){b=new Downsha.ClipStyle;b._addSimpleStyle("clear","both");b._addSimpleStyle("width","0px");b._addSimpleStyle("height","0px");return b}return null}})();
(function(){var a=null;Downsha.ContentVeil=function(b){a=Downsha.Logger.getInstance();this.initialize(b)};Downsha.ContentVeil.prototype.window=null;Downsha.ContentVeil.prototype.VEIL_ID="downshaContentVeil";Downsha.ContentVeil.prototype.VEIL_CLASS="downshaContentVeil";Downsha.ContentVeil.prototype.FILL_STYLE="rgba(0, 0, 0, 0.8)";Downsha.ContentVeil.prototype.FILL_HIGHLIGHT_STYLE="rgba(255, 255, 255, 0.3)";Downsha.ContentVeil.prototype.STROKE_STYLE="rgba(255, 255, 255, 0.9)";Downsha.ContentVeil.prototype.STROKE_WIDTH=
6;Downsha.ContentVeil.prototype.STROKE_CAP="round";Downsha.ContentVeil.prototype.STROKE_JOIN="round";Downsha.ContentVeil.prototype.ELEMENT_STYLE={position:"absolute",top:"0px",left:"0px",zIndex:"9999999999999990"};Downsha.ContentVeil.prototype.EMBED_TRANS_MARKER="downshaTransparent";Downsha.ContentVeil.prototype.EMBED_TRANS_PREVIEW_MARKER="downshaEmbedTransparent";Downsha.ContentVeil.prototype.initialize=function(b){this.window=b?b:window;this.veil=this.createVeilElement()};Downsha.ContentVeil.prototype.createVeilElement=
function(){var b=document.createElement("CANVAS");b.setAttribute("id",this.VEIL_ID);b.setAttribute("class",this.VEIL_CLASS);b.height=this.getBodyHeight();b.width=this.getBodyWidth();for(var a in this.ELEMENT_STYLE)b.style[a]=this.ELEMENT_STYLE[a];return b};Downsha.ContentVeil.prototype.revealElement=function(b){this.revealRect(Downsha.Utils.getAbsoluteBoundingClientRect(b))};Downsha.ContentVeil.prototype.getStrokeWidthForRect=function(b,a){var c=Math.max(2,Math.min(b.bottom-b.top,b.right-b.left)/
8);return c=Math.min(a&&a.lineWidth?a.lineWidth:this.STROKE_WIDTH,c)};Downsha.ContentVeil.prototype.revealRect=function(b,a,c){this._revealRect=b;var e=this.getVeilContext(),f=0;a&&(f=c&&typeof c.lineWidth=="number"?c.lineWidth:this.getStrokeWidthForRect(b,c));var g=b.left-f,h=b.top-f,i=b.right-b.left+f*2,b=b.bottom-b.top+f*2;e.clearRect(g,h,i,b);e.fillStyle=c&&c.fillStyle?c.fillStyle:this.FILL_HIGHLIGHT_STYLE;e.fillRect(g,h,i,b);if(a){e.lineWidth=f;e.strokeStyle=c&&c.strokeStyle?c.strokeStyle:this.STROKE_STYLE;
e.lineCap=c&&c.lineCap?c.lineCap:this.STROKE_CAP;e.lineJoin=c&&c.lineJoin?c.lineJoin:this.STROKE_JOIN;e.strokeRect(g,h,i,b)}};Downsha.ContentVeil.prototype.clearRect=function(b){var a=this.getVeilContext(),c=b.left,e=b.top,f=b.right-b.left,b=b.bottom-b.top;a.clearRect(c,e,f,b);a.fillStyle=this.FILL_STYLE;a.fillRect(c,e,f,b)};Downsha.ContentVeil.prototype.resetVeil=function(){var b=this.getVeilContext();b.clearRect(0,0,this.getBodyWidth(),this.getBodyHeight());b.fillStyle=this.FILL_STYLE;b.lineWidth=
0;b.moveTo(0,0);b.beginPath();b.lineTo(this.getBodyWidth(),0);b.lineTo(this.getBodyWidth(),this.getBodyHeight());b.lineTo(0,this.getBodyHeight());b.lineTo(0,0);b.closePath();b.fill()};Downsha.ContentVeil.prototype.getVeilElement=function(){if(!this._veil){this._veil=this.window.document.getElementById(this.VEIL_ID);if(!this._veil)this._veil=this.createVeilElement()}return this._veil};Downsha.ContentVeil.prototype.getVeilContext=function(){if(!this._veilContext)this._veilContext=this.getVeilElement().getContext("2d");
return this._veilContext};Downsha.ContentVeil.prototype.removeVeilElement=function(){this._veil&&this._veil.parentElement.removeChild(this._veil)};Downsha.ContentVeil.prototype.getDefaultVeilParentElement=function(){return this.window.document.body.parentElement?this.window.document.body.parentElement:this.window.document.body};Downsha.ContentVeil.prototype.show=function(){this.hideEmbeds(this.window.document,true);var b=this.getVeilElement();if(!b.parentElement){var a=this.getDefaultVeilParentElement();
a&&a.appendChild(b)}b.style.display=""};Downsha.ContentVeil.prototype.hide=function(){this.unhideEmbeds(this.window.document,true);this.getVeilElement().style.display="none"};Downsha.ContentVeil.prototype.clear=function(){this.clearEmbeds(this.window.document,true)};Downsha.ContentVeil.prototype.getBodyHeight=function(){return this.window.document.documentElement.scrollHeight};Downsha.ContentVeil.prototype.getBodyWidth=function(){return this.window.document.documentElement.scrollWidth};Downsha.ContentVeil.prototype.hideEmbeds=
function(b,d){var c=Downsha.Utils.findEmbeds(b);if(c&&c.length>0){a.debug("ContentVeil.hideEmbeds find "+c.length+" <object> and <embed> nodes");for(var e=b.defaultView?b.defaultView:this.window,f=0;f<c.length;f++){var g=c[f];if(typeof g[this.EMBED_TRANS_MARKER]!="undefined")this._hideEmbed(g);else{var h=e.getComputedStyle(g,""),i=h.getPropertyValue("display"),h=h.getPropertyValue("visibility");if(!(i=="none"||h=="hidden")){if(this._revealRect){i=Downsha.Utils.getAbsoluteBoundingClientRect(g);if(i.top>=
this._revealRect.top&&i.left>=this._revealRect.left&&i.bottom<=this._revealRect.bottom&&i.right<=this._revealRect.right)continue}h=i=null;Downsha.ElementSerializerFactory&&(h=Downsha.ElementSerializerFactory.getImplementationFor(g));if(h){var j=(new Downsha.ClipFullStylingStrategy(e)).styleForNode(g,g.parentElement,false);if(h=(new h(g,j)).serialize()){j=g.getBoundingClientRect();i=b.createElement("div");i[this.EMBED_TRANS_PREVIEW_MARKER]=g;i.style.cssText="display: none; position: absolute, margin: 0px; padding: 0px;";
if(j)i.style.cssText=i.style.cssText+("left: "+j.left+"px; top: "+j.top+"px; width: "+j.width+"px; height: "+j.height+"px;");i.innerHTML=h;i.setAttribute("class",this.EMBED_TRANS_PREVIEW_MARKER);g.parentElement.insertBefore(i,g)}}h=g.classList?Array.prototype.slice.call(g.classList,0):[];h.push(this.EMBED_TRANS_MARKER);g.setAttribute("class",h.join(" "));g[this.EMBED_TRANS_MARKER]=i;this._hideEmbed(g)}}}}if(d)if((c=Downsha.Utils.findDocuments(b))&&c.length>0){a.debug("ContentVeil.hideEmbeds find "+
c.length+" <frame> and <iframe> nodes");for(f=0;f<c.length;f++)c[f]&&this.hideEmbeds(c[f],d)}};Downsha.ContentVeil.prototype.unhideEmbeds=function(b,d){var c=b.getElementsByClassName(this.EMBED_TRANS_MARKER);if(c&&c.length>0){a.debug("ContentVeil.unhideEmbeds find "+c.length+" <object> and <embed> nodes");for(var e=0;e<c.length;e++)c[e]&&this._unhideEmbed(c[e])}if(d)if((c=Downsha.Utils.findDocuments(b))&&c.length>0){a.debug("ContentVeil.unhideEmbeds find "+c.length+" <frame> and <iframe> nodes");
for(e=0;e<c.length;e++)c[e]&&this.unhideEmbeds(c[e],d)}};Downsha.ContentVeil.prototype.clearEmbeds=function(b,d){var c=b.getElementsByClassName(this.EMBED_TRANS_MARKER);if(c&&c.length>0){a.debug("ContentVeil.clearEmbeds find "+c.length+" <object> and <embed> nodes");for(var e=0;e<c.length;e++)c[e]&&this._clearEmbed(c[e])}if(d)if((c=Downsha.Utils.findDocuments(b))&&c.length>0){a.debug("ContentVeil.clearEmbeds find "+c.length+" <frame> and <iframe> nodes");for(e=0;e<c.length;e++)c[e]&&this.clearEmbeds(c[e],
d)}};Downsha.ContentVeil.prototype._hideEmbed=function(b){var a=b[this.EMBED_TRANS_MARKER];if(a)a.style.display="block";b.style.visibility="hidden"};Downsha.ContentVeil.prototype._unhideEmbed=function(b){var a=b[this.EMBED_TRANS_MARKER];if(a)a.style.display="none";b.style.visibility="visible"};Downsha.ContentVeil.prototype._clearEmbed=function(b){var a=b[this.EMBED_TRANS_MARKER];a&&a.parentElement&&a.parentElement.removeChild(a);b.style.visibility="visible";var a=b.classList?Array.prototype.slice.call(b.classList,
0):[],c=-1;(c=a.indexOf(this.EMBED_TRANS_MARKER)>=0)&&a.splice(c,1);a.length>0?b.setAttribute("class",a.join(" ")):b.removeAttribute("class");delete b[this.EMBED_TRANS_MARKER]}})();
(function(){Downsha.AbstractStyleScript=function(){Downsha.Logger.getInstance();this.initialize()};Downsha.AbstractStyleScript.prototype.initialize=function(){var a=this.getInitialStyleSheetUrls();a&&a.length>0&&this.injectStyleSheets(a)};Downsha.AbstractStyleScript.prototype.getInitialStyleSheetUrls=function(){return[]};Downsha.AbstractStyleScript.prototype.injectStyleSheets=function(a){for(var b=Downsha.Utils.getDocumentHead(document),d=0;d<a.length;d++){var c=a[d],e=document.createElement("link");
e.setAttribute("rel","stylesheet");e.setAttribute("type","text/css");e.setAttribute("href",c);b&&b.appendChild(e)}}})();
(function(){var a=null;Downsha.ContentPreviewScript=function(b){a=Downsha.Logger.getInstance();this.initialize(b)};Downsha.inherit(Downsha.ContentPreviewScript,Downsha.AbstractStyleScript);Downsha.ContentPreviewScript._instance=null;Downsha.ContentPreviewScript.getInstance=function(){if(!this._instance)this._instance=new Downsha.ContentPreviewScript;return this._instance};Downsha.ContentPreviewScript.removeInstance=function(){this._instance=null};Downsha.ContentPreviewScript.prototype.window=null;
Downsha.ContentPreviewScript.prototype._contentVeil=null;Downsha.ContentPreviewScript.prototype._selectionFinder=null;Downsha.ContentPreviewScript.prototype.PREVIEW_CONTENT_ID="downshaPreviewContainer";Downsha.ContentPreviewScript.prototype.PREVIEW_CONTENT_CLASS="downshaPreviewContainer";Downsha.ContentPreviewScript.prototype.PREVIEW_CONTENT_URL_CLASS="downshaPreviewUrlContainer";Downsha.ContentPreviewScript.prototype.PREVIEW_ARTICLE_CLASS="downshaPreviewArticleContainer";Downsha.ContentPreviewScript.prototype.TEXT_NODE_WRAP_TAG=
"SPAN";Downsha.ContentPreviewScript.prototype.TEXT_NODE_WRAP_STYLE="display: inline; position: relative; padding: 0px; margin: 0px; float: none; visibility: visible; float: none;";Downsha.ContentPreviewScript.prototype.SELECTION_CTX_ATTRS={fillStyle:"rgba(255, 255, 0, 0.3)"};Downsha.ContentPreviewScript.prototype.PREVIEW_CTX_ATTRS={fillStyle:"rgba(255, 255, 255, 0)",strokeStyle:"rgba(255, 255, 0, 0.3)"};Downsha.ContentPreviewScript.prototype.PREVIEW_PARENT_CTX_ATTRS={fillStyle:"rgba(0, 3, 0, 0.8)",
lineWidth:4,strokeStyle:"rgba(33, 133, 33, 0.4)"};Downsha.ContentPreviewScript.prototype.PREVIEW_NEXT_CTX_ATTRS={fillStyle:"rgba(0, 0, 0, 0.6)",lineWidth:1,strokeStyle:"rgba(255, 255, 255, 0.2)"};Downsha.ContentPreviewScript.prototype.PREVIEW_PREV_CTX_ATTRS=Downsha.ContentPreviewScript.prototype.PREVIEW_NEXT_CTX_ATTRS;Downsha.ContentPreviewScript.prototype.SELECTION_MIN_SIZE=8;Downsha.ContentPreviewScript.prototype.PREVIEW_URL_DELAY_TIME=100;Downsha.ContentPreviewScript.prototype.PREVIEW_SCROLL_TOTAL_TIME=
120;Downsha.ContentPreviewScript.prototype.PREVIEW_SCROLL_STEP_INTERVAL=20;Downsha.ContentPreviewScript.prototype.DOCUMENT_PREVIEW_KEY="DownshaPreviewNode";Downsha.ContentPreviewScript.prototype.rangeMarker="_downsha_range_";Downsha.ContentPreviewScript.prototype._children=null;Downsha.ContentPreviewScript.prototype._parents=null;Downsha.ContentPreviewScript.prototype._sema=null;Downsha.ContentPreviewScript.prototype._articleRules=null;Downsha.ContentPreviewScript.prototype.initialStyleSheetUrls=
["chrome-extension://"+chrome.i18n.getMessage("@@extension_id")+"/css/contentpreview.css"];Downsha.ContentPreviewScript.prototype.initialize=function(b){this.window=b?b:window;this.__defineGetter__("contentVeil",this.getContentVeil);this.__defineGetter__("selectionFinder",this.getSelectionFinder);this._children=[];this._parents=[];Downsha.ContentPreviewScript.parent.initialize.apply(this,[]);this._sema=Downsha.Semaphore.mutex();this.fetchArticleRules();this.__defineGetter__("articleRules",this.getArticleRules)};
Downsha.ContentPreviewScript.prototype.getArticleRules=function(){return this._articleRules};Downsha.ContentPreviewScript.prototype.fetchArticleRules=function(){a.debug("ContentPreviewScript.fetchArticleRules");var b=this;this._articleRules||this._sema.critical(function(){chrome.extension.sendRequest(new Downsha.RequestMessage(Downsha.Constants.RequestType.FETCH_ARTICLE_RULES,this.window.document.location.href),function(a){b._articleRules=a&&a.rules?a.rules:{};b._sema.signal()})})};Downsha.ContentPreviewScript.prototype.getInitialStyleSheetUrls=
function(){return this.initialStyleSheetUrls};Downsha.ContentPreviewScript.prototype._doPreview=function(b){var a=this;this._sema.critical(function(){b();a._sema.signal()})};Downsha.ContentPreviewScript.prototype.previewFullPage=function(){var b=this;this._doPreview(function(){b._previewFullPage()})};Downsha.ContentPreviewScript.prototype.previewSelection=function(){var b=this;this._doPreview(function(){b._previewSelection()})};Downsha.ContentPreviewScript.prototype.previewArticle=function(){var b=
this;this._doPreview(function(){b._previewArticle()})};Downsha.ContentPreviewScript.prototype.previewURL=function(b,a,c){var e=this;this._doPreview(function(){e._previewURL(b,a,c)})};Downsha.ContentPreviewScript.prototype._previewFullPage=function(){a.debug("ContentPreviewScript._previewFullPage");this.clear()};Downsha.ContentPreviewScript.prototype._previewSelection=function(){a.debug("ContentPreviewScript._previewSelection");this.clear();var b=this.getSelectionRange();if(b){var d=this;this.contentVeil.resetVeil();
for(var c=b.commonAncestorContainer==b.startContainer&&b.startContainer==b.endContainer?b.commonAncestorContainer.parentNode:b.commonAncestorContainer,e=b.getClientRects(),f=[],g={},h=this.window.document.createTreeWalker(c,NodeFilter.SHOW_ELEMENT+NodeFilter.SHOW_TEXT,function(a){if(a==c&&a!=b.startContainer)return NodeFilter.FILTER_SKIP;if(a!=b.startContainer&&a==b.endContainer){var e=0;if(a.nodeType==Node.ELEMENT_NODE){for(var e=a.childNodes,h=0;h<e.length;h++)if(e[h]&&e[h].nodeType==Node.ELEMENT_NODE){h++;
break}e=h}if(b.endOffset<=e)return NodeFilter.FILTER_REJECT}e=d.window.document.createRange();e.selectNode(a);h=e.getBoundingClientRect();if(a==b.startContainer||a==b.endContainer||e.compareBoundaryPoints(Range.START_TO_START,b)>=0&&e.compareBoundaryPoints(Range.END_TO_END,b)<=0){a._downsha_nodeRect=Downsha.NodeRect.fromNode(a);f.push(a);h&&Downsha.Utils.expandRect(g,h);return NodeFilter.FILTER_REJECT}return NodeFilter.FILTER_SKIP},false);h.nextNode(););(h=b.endContainer.nodeType==Node.TEXT_NODE?
b.endContainer.parentNode.getBoundingClientRect():b.endContainer.getBoundingClientRect())&&(h=Downsha.NodeRect.fromObject(h));for(var i=0;i<e.length;i++){var j=Downsha.NodeRect.fromObject(e[i]);if(!(j.width*j.height<=0)){for(var k=[],l=0;l<f.length;l++){var m=f[l]._downsha_nodeRect,n=m?Downsha.Utils.rectIntersection(j,m):null;if(n)if(m&&Downsha.Utils.rectsEqual(m,j))k.push(j);else{n=Downsha.NodeRect.fromObject(n);k.push(n)}}if(!(b.endContainer.nodeType==Node.TEXT_NODE&&b.endOffset<b.endContainer.textContent.length&&
Downsha.Utils.rectsEqual(j,h))&&k.length>0)for(j=0;j<k.length;j++){l=k[j];l.left>=g.left&&l.top>=g.top&&l.right<=g.right&&l.bottom<=g.bottom&&this.outlineRect(Downsha.Utils.makeAbsoluteClientRect(l,this.window),false,this.SELECTION_CTX_ATTRS)}}}}else{a.debug("Could not find selection");this.previewFullPage()}};Downsha.ContentPreviewScript.prototype._previewArticle=function(){a.debug("ContentPreviewScript._previewArticle");this.clear();this.contentVeil.resetVeil();var b=this.getRememberedPreview();
if(b)this.outlinePreviewElement(b,true);else if(b=Downsha.Utils.getArticleNode(this.window.document,this.articleRules)){this.rememberPreview(b);this.outlinePreviewElement(b,true)}};Downsha.ContentPreviewScript.prototype._previewURL=function(b,d,c){a.debug("ContentPreviewScript._previewURL");this.clear();this.contentVeil.resetVeil();this.contentVeil.show();var b=b?b:this.window.document.title,d=d?d:this.window.location.href,e=this.createContentElement(Downsha.Utils.createUrlClipContent(b,d,c?c:null)),
f=this;setTimeout(function(){f.showContentElement();var b=f.window.getComputedStyle(e,""),a=parseInt(b.getPropertyValue("width")),b=parseInt(b.getPropertyValue("height"));if(a&&b){e.style.marginLeft=0-a/2+"px";e.style.marginTop=0-b/2+"px"}},this.PREVIEW_URL_DELAY_TIME)};Downsha.ContentPreviewScript.prototype.getPreviousElementSibling=function(b){for(b=b.previousElementSibling;b;){var a=b.textContent.trim().length>0||b.getElementsByTagName("IMG").length>0?b.getBoundingClientRect():null;if((a?a.width*
a.height:0)>0)return b;b=b.previousElementSibling}return null};Downsha.ContentPreviewScript.prototype.getNextElementSibling=function(b){for(b=b.nextElementSibling;b;){var a=b.textContent.trim().length>0||b.getElementsByTagName("IMG").length>0?b.getBoundingClientRect():null;if((a?a.width*a.height:0)>0)return b;b=b.nextElementSibling}return null};Downsha.ContentPreviewScript.prototype.getParentElement=function(b){for(var a=b?b.getBoundingClientRect():null,a=a?a.width*a.height:0,b=b.parentElement;b;){var c=
b.getBoundingClientRect(),c=c?c.width*c.height:0;if(c>0&&c!=a)return b;b=b.parentElement}return null};Downsha.ContentPreviewScript.prototype.getChildElement=function(b){var a=this._parents.indexOf(b);if(a>=0)return this._children[a];a=(a=b.getBoundingClientRect())?a.width*a.height:0;if(b.children.length>0)for(var b=document.createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,false),c=null;c=b.nextNode();){var e=c.textContent.trim().length>0||c.getElementsByTagName("IMG").length>0?c.getBoundingClientRect():
null,e=e?e.width*e.height:0;if(e>0&&e!=a)return c}return null};Downsha.ContentPreviewScript.prototype.nudgePreview=function(b){var a=this.getRememberedPreview();if(a){var c=null;switch(b){case Downsha.Constants.RequestType.PREVIEW_NUDGE_PREVIOUS_SIBLING:c=this.getPreviousElementSibling(a);break;case Downsha.Constants.RequestType.PREVIEW_NUDGE_NEXT_SIBLING:c=this.getNextElementSibling(a);break;case Downsha.Constants.RequestType.PREVIEW_NUDGE_PARENT:c=this.getParentElement(a);break;case Downsha.Constants.RequestType.PREVIEW_NUDGE_CHILD:c=
this.getChildElement(a)}if(c){this.forgetPreview(a);this.contentVeil.resetVeil();this.outlinePreviewElement(c,true);this.rememberPreview(c);if(b==Downsha.Constants.RequestType.PREVIEW_NUDGE_PARENT){b=this._parents.indexOf(c);if(b>=0){this._parents.splice(b,1);this._children.splice(b,1)}this._parents[this._children.push(a)-1]=c}}}};Downsha.ContentPreviewScript.prototype.rememberPreview=function(b){this.forgetPreview();Downsha.Utils.addElementClass(b,this.PREVIEW_ARTICLE_CLASS)};Downsha.ContentPreviewScript.prototype.forgetPreview=
function(){var b=document.getElementsByClassName(this.PREVIEW_ARTICLE_CLASS);if(b&&b.length>0)for(var a=0;a<b.length;a++)Downsha.Utils.removeElementClass(b[a],this.PREVIEW_ARTICLE_CLASS)};Downsha.ContentPreviewScript.prototype.getRememberedPreview=function(){var a=document.getElementsByClassName(this.PREVIEW_ARTICLE_CLASS);if(a&&a.length>0)return a[0]};Downsha.ContentPreviewScript.prototype.createContentElement=function(b){a.debug("ContentPreviewScript.createContentElement");var d=this.window.document,
c=d.getElementById(this.PREVIEW_CONTENT_ID);if(!c){c=d.createElement("div");c.setAttribute("id",this.PREVIEW_CONTENT_ID);c.setAttribute("class",this.PREVIEW_CONTENT_CLASS+" "+this.PREVIEW_CONTENT_URL_CLASS);c.style.display="none";(d.body.parentElement||d.body).appendChild(c)}c.innerHTML=b;return c};Downsha.ContentPreviewScript.prototype.removeContentElement=function(){a.debug("ContentPreviewScript.removeContentElement");var b=this.window.document.getElementById(this.PREVIEW_CONTENT_ID);b&&b.parentElement&&
b.parentElement.removeChild(b)};Downsha.ContentPreviewScript.prototype.getContentElement=function(){return this.window.document.getElementById(this.PREVIEW_CONTENT_ID)};Downsha.ContentPreviewScript.prototype.showContentElement=function(){a.debug("ContentPreviewScript.showContentElement");var b=this.getContentElement();if(b)b.style.display=""};Downsha.ContentPreviewScript.prototype.hideContentElement=function(){a.debug("ContentPreviewScript.hideContentElement");var b=this.getContentElement();if(b)b.style.display=
"none"};Downsha.ContentPreviewScript.prototype.clear=function(){a.debug("ContentPreviewScript.clear");if(this._contentVeil){this.contentVeil.hide();this.contentVeil.clear()}this.removeContentElement();var b=this.window.document.querySelectorAll("*[class~=_downshaPreviewRect]");if(b)for(var d=0;d<b.length;d++){delete b[d]._downshaPreviewRect;b[d].className=b[d].className.replace(/\s*\b_downshaPreviewRect\b/,"")}};Downsha.ContentPreviewScript.prototype.clearRect=function(b){a.debug("ContentPreviewScript.clearRect");
this._contentVeil&&this.contentVeil.clearRect(b)};Downsha.ContentPreviewScript.prototype.outlinePreviewElement=function(a,d){var c=a._downshaPreviewRect;if(!c){for(var c=Downsha.Utils.getAbsoluteBoundingClientRect(a),e=a.getElementsByTagName("*"),f=0;f<e.length;f++){var g=e[f],h=g._downshaPreviewRect;if(!h){h=Downsha.Utils.getAbsoluteBoundingClientRect(g);if(g.childElementCount==0)g._downshaPreviewRect=h}h&&(h.bottom<0&&h.top<0||h.left<0&&h.right<0||h.width*h.height<=1||getComputedStyle(g).position==
"fixed"||getComputedStyle(g).position=="absolute"||getComputedStyle(g).display!="none"&&Downsha.Utils.expandRect(c,h))}c.width=c.right-c.left;c.height=c.bottom-c.top;a._downshaPreviewRect=c;a.className=a.className+" _downshaPreviewRect"}this.outlineRect(c,true,this.PREVIEW_CTX_ATTRS);d&&c&&Downsha.Scroller.scrollTo(c.left-this.window.innerWidth/2,c.top-this.window.innerHeight/2,this.PREVIEW_SCROLL_TOTAL_TIME,this.PREVIEW_SCROLL_STEP_INTERVAL)};Downsha.ContentPreviewScript.prototype.outlineRect=function(b,
d,c){a.debug("ContentPreviewScript.outlineRect");if(b){var e={left:b.left,top:b.top,right:b.right,bottom:b.bottom,width:b.width,height:b.height};if(d){var f=c&&typeof c.lineWidth=="number"?c.lineWidth:this.contentVeil.getStrokeWidthForRect(e,c);if(typeof f=="number"){e.left=e.left-f;e.right=e.right+f;e.top=e.top-f;e.bottom=e.bottom+f;e.width=e.right-e.left;e.height=e.bottom-e.top}}this.contentVeil.clearRect(e);this.contentVeil.revealRect(b,d,c);this.contentVeil.show()}};Downsha.ContentPreviewScript.prototype.getContentVeil=
function(){if(!this._contentVeil)this._contentVeil=new Downsha.ContentVeil(this.window);return this._contentVeil};Downsha.ContentPreviewScript.prototype.getSelectionBoundingClientRect=function(){var b=this.getSelectionRange();if(!b||!b.commonAncestorContainer){a.debug("No selection range found");return null}var d=b.commonAncestorContainer.ownerDocument.defaultView,d=Downsha.Utils.makeAbsoluteClientRect(b.getBoundingClientRect(),d),b=this._isolateRangeEndPoints(b);if(!b||b.length!=2)return d;if(b[0]===
b[1])return Downsha.Utils.makeAbsoluteClientRect(b[0].getBoundingClientRect());b=Downsha.Utils.makeAbsoluteClientRect(this._mergeRects(b[0].getBoundingClientRect(),b[1].getBoundingClientRect()));this._shrinkYRect(d,b);return d};Downsha.ContentPreviewScript.prototype.getSelectionFinder=function(){if(!this._selectionFinder)this._selectionFinder=new Downsha.SelectionFinder(this.window.document);return this._selectionFinder};Downsha.ContentPreviewScript.prototype.getSelectionRange=function(){this.selectionFinder.find(true);
return this.selectionFinder.hasSelection()?this.selectionFinder.getRange():null};Downsha.ContentPreviewScript.prototype._isolateRangeEndPoints=function(a){var d=[];if(a.startContainer.parentNode===a.endContainer.parentNode){var c=document.createElement(this.TEXT_NODE_WRAP_TAG);c.style.cssText=this.TEXT_NODE_WRAP_STYLE;a.surroundContents(c);d[0]=c;d[1]=c;a.selectNodeContents(c)}else{d=[];if(a.startContainer.nodeType==Node.TEXT_NODE&&a.startOffset>0){var c=document.createTextNode(a.startContainer.textContent.substring(0,
a.startOffset)),e=document.createTextNode(a.startContainer.textContent.substring(a.startOffset)),f=document.createElement(this.TEXT_NODE_WRAP_TAG);f.style.cssText=this.TEXT_NODE_WRAP_STYLE;a.startContainer.parentNode.replaceChild(f,a.startContainer);f.appendChild(e);f.parentNode.insertBefore(c,f);d[0]=f;a.setStartBefore(e)}else d[0]=a.startContainer.nodeType==Node.TEXT_NODE?a.startContainer.parentNode:a.startContainer;if(a.endContainer.nodeType==Node.TEXT_NODE&&a.endOffset<a.endContainer.textContent.length){e=
document.createTextNode(a.endContainer.textContent.substring(0,a.endOffset));c=document.createElement(this.TEXT_NODE_WRAP_TAG);c.style.cssText=this.TEXT_NODE_WRAP_STYLE;c.appendChild(e);var g=document.createTextNode(a.endContainer.textContent.substring(a.endOffset)),f=document.createElement(this.TEXT_NODE_WRAP_TAG);f.style.cssText=this.TEXT_NODE_WRAP_STYLE;f.appendChild(g);a.endContainer.parentNode.replaceChild(f,a.endContainer);f.parentNode.insertBefore(c,f);d[1]=c;a.setEndAfter(e)}else{d[1]=a.endContainer;
if(a.endOffset==0){for(c=a.endContainer;c;)if(c.previousSibling){c=c.previousSibling;break}else if(c.parentElement)c=c.parentElement;c&&(d[1]=c)}}}c=getSelection();c.removeAllRanges();c.addRange(a);return d};Downsha.ContentPreviewScript.prototype._mergeRects=function(a,d){var c={};c.top=Math.min(a.top,d.top);c.bottom=Math.max(a.bottom,d.bottom);c.left=Math.min(a.left,d.left);c.right=Math.max(a.right,d.right);c.width=c.right-c.left;c.height=c.bottom-c.top;return c};Downsha.ContentPreviewScript.prototype._shrinkYRect=
function(a,d){a.top=Math.max(a.top,d.top);a.bottom=Math.min(a.bottom,d.bottom);a.height=a.bottom-a.top;return a}})();
