var Downsha=Downsha||{};
Downsha.inherit=function(a,b,c){b.constructor==Function?(a.prototype=new b,a.prototype.constructor=a,a.prototype.parent=b.prototype):(a.prototype=b,a.prototype.constructor=a,a.prototype.parent=b);a.constructor.parent=b;if(c)for(var d in b.prototype.constructor)"parent"!=d&&"prototype"!=d&&b.constructor[d]!=b.prototype.constructor[d]&&"undefined"==typeof a.prototype.constructor[d]&&(a.prototype.constructor[d]=b.prototype.constructor[d]);"function"==typeof a.handleInheritance&&a.handleInheritance.apply(a,
arguments);"function"==typeof a.prototype.handleInheritance&&a.prototype.handleInheritance.apply(a,arguments)};Downsha.inherits=function(a,b){return"undefined"!=typeof a.prototype.parent&&a.prototype.parent.constructor==b};Downsha.mixin=function(a,b,c){var a="function"==typeof a?a.prototype:a,d;for(d in b.prototype){var e=to=d;"object"==typeof c&&c&&"undefined"!=typeof c[d]&&(to=c[d]);a[to]=b.prototype[e]}};
Downsha.extendObject=function(a,b,c){if("object"==typeof b&&null!=b)for(var d in b)if(c&&"object"==typeof b[d]&&null!=b[d]&&"object"==typeof a[d]&&null!=a[d])Downsha.extendObject(a[d],b[d],c);else try{a[d]=b[d]}catch(e){}};Downsha.hasOwnProperty=function(a,b){if("object"==typeof a){if(a.hasOwnProperty(b))return!0;for(var c=null,c=a;c=c.__proto__;)if(c.hasOwnProperty(b))return!0}return!1};Downsha.DefiningMixin=function(){};
Downsha.DefiningMixin._getTargetFor=function(a){return"function"==typeof a&&a==a.prototype.constructor?a.prototype:a};Downsha.DefiningMixin.prototype.__defineBoolean__=function(a,b,c,d){var e="_"+a,f=a.substring(0,1).toUpperCase()+a.substring(1),g=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);g[e]=b?!0:!1;if(!c){var h="is"+f;g[h]=function(){return this[e]};this.__defineGetter__(a,g[h])}d||(f="set"+f,g[f]=function(a){this[e]=a?!0:!1},this.__defineSetter__(a,g[f]))};
Downsha.DefiningMixin.prototype.__defineFloat__=function(a,b,c,d){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!1,parseFloat,c,d)};Downsha.DefiningMixin.prototype.__definePositiveFloat__=function(a,b,c,d){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!0,parseFloat,c,d)};
Downsha.DefiningMixin.prototype.__defineInteger__=function(a,b,c,d){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!1,parseInt,c,d)};Downsha.DefiningMixin.prototype.__definePositiveInteger__=function(a,b,c,d){this._createNumericDefinition_(Downsha.DefiningMixin._getTargetFor(arguments.callee.caller),a,b,!0,parseInt,c,d)};
Downsha.DefiningMixin.prototype._createNumericDefinition_=function(a,b,c,d,e,f,g){var h=b.substring(0,1).toUpperCase()+b.substring(1),i="_"+b,c="number"==typeof c?c:null;a||(a=this);a[i]=c;f||(f="get"+h,a[f]=function(){return this[i]},this.__defineGetter__(b,a[f]));g||(g="set"+h,a[g]=d?function(a){this[i]=e(a);if(isNaN(this[i])||this[i]<0)this[i]=c}:function(a){this[i]=e(a);isNaN(this[i])&&(this[i]=c)},this.__defineSetter__(b,a[g]))};
Downsha.DefiningMixin.prototype.__defineString__=function(a,b,c,d){var b=b?b:null,e=a.substring(0,1).toUpperCase()+a.substring(1),f="_"+a,g=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);g[f]=b;if(!c){var h="get"+e;g[h]=function(){return this[f]};this.__defineGetter__(a,g[h])}d||(e="set"+e,g[e]=function(a){this[f]="string"==typeof a?a:a?""+a:b},this.__defineSetter__(a,g[e]))};
Downsha.DefiningMixin.prototype.__defineType__=function(a,b,c,d,e){var c=c?c:null,f="_"+a,g=a.substring(0,1).toUpperCase()+a.substring(1),h=Downsha.DefiningMixin._getTargetFor(arguments.callee.caller);h[f]=c;if(!d){var i="get"+g;h[i]=function(){return this[f]};this.__defineGetter__(a,h[i])}e||(g="set"+g,h[g]=function(a){if("string"==typeof b&&a&&a.constructor.name==b)this[f]=a;else if("function"==typeof b&&a instanceof b)this[f]=a;else{if(a)throw Error("Expected "+("string"==typeof b?b:b.name)+" but got "+
typeof a+" "+a.toSource());this[f]=c}},this.__defineSetter__(a,h[g]))};Downsha.DownshaError=function(a,b,c){this.__defineGetter__("errorCode",this.getErrorCode);this.__defineSetter__("errorCode",this.setErrorCode);this.__defineGetter__("modelName",this.getModelName);this.initialize(a,b,c)};Downsha.DownshaError.CLASS_FIELD="javaClass";Downsha.DownshaError.ERROR_CODE_FIELD="errorCode";Downsha.DownshaError.MESSAGE_FIELD="message";Downsha.DownshaError.PARAMETER_FIELD="parameter";
Downsha.DownshaError.javaClass="com.downsha.web.DownshaError";Downsha.DownshaError.prototype._modelName=null;Downsha.DownshaError.prototype._errorCode=null;Downsha.DownshaError.prototype.message=null;Downsha.DownshaError.prototype.parameter=null;
Downsha.DownshaError.prototype.handleInheritance=function(){"string"==typeof this.prototype.constructor[Downsha.DownshaError.CLASS_FIELD]&&(Downsha.DownshaError.Registry[this.prototype.constructor[Downsha.DownshaError.CLASS_FIELD]]=this);this.prototype.constructor.modelName=this.prototype.constructor.toString().replace(/\n/g,"").replace(/^.*function\s+([^\(]+).*$/,"$1")};
Downsha.DownshaError.prototype.getModelName=function(){return this.constructor.toString().replace(/\n/g,"").replace(/^.*function\s+([^\(]+).*$/,"$1")};
Downsha.DownshaError.prototype.initialize=function(a,b,c){if(a&&"object"==typeof a){if("undefined"!=typeof a[Downsha.DownshaError.ERROR_CODE_FIELD]&&(this.errorCode=a[Downsha.DownshaError.ERROR_CODE_FIELD]),"undefined"!=typeof a[Downsha.DownshaError.MESSAGE_FIELD]&&(this.message=a[Downsha.DownshaError.MESSAGE_FIELD]),"undefined"!=typeof a[Downsha.DownshaError.PARAMETER_FIELD])this.parameter=a[Downsha.DownshaError.PARAMETER_FIELD]}else if("undefined"!=typeof a&&(this.errorCode=a),"undefined"!=typeof b&&
(this.message=b),"undefined"!=typeof c)this.parameter=c;this.constructor.modelName=this.modelName};Downsha.DownshaError.prototype.setErrorCode=function(a){this._errorCode=isNaN(parseInt(a))?null:parseInt(a)};Downsha.DownshaError.prototype.getErrorCode=function(){return this._errorCode};Downsha.DownshaError.prototype.getClassName=function(){return"undefined"!=typeof this.constructor[Downsha.DownshaError.CLASS_FIELD]?this.constructor[Downsha.DownshaError.CLASS_FIELD]:null};
Downsha.DownshaError.prototype.getShortClassName=function(){var a=this.getClassName();"string"==typeof a&&(a=a.split("."),a=a[a.length-1]);return a};Downsha.DownshaError.prototype.toString=function(){var a=this.getShortClassName();return null==a?"Downsha.DownshaError":a+" ("+this.errorCode+") ["+this.parameter+"]"+("string"==typeof this.message?this.message:"")};Downsha.DownshaError.Registry={};
Downsha.DownshaError.responsibleConstructor=function(a){return"function"==typeof Downsha.DownshaError.Registry[a]?Downsha.DownshaError.Registry[a]:Downsha.DownshaError};Downsha.DownshaError.fromObject=function(a){return a instanceof Downsha.DownshaError?a:"object"==typeof a&&a?Downsha.DownshaError.unmarshall(a):new Downsha.DownshaError};
Downsha.DownshaError.unmarshall=function(a){var b=null;if("object"!=typeof a||!a)return a;if(b="string"==typeof a[Downsha.DownshaError.CLASS_FIELD]&&"function"==typeof Downsha.DownshaError.Registry[a[Downsha.DownshaError.CLASS_FIELD]]?new Downsha.DownshaError.Registry[a[Downsha.DownshaError.CLASS_FIELD]]:new this)if(a.errorCode&&(b.errorCode=a.errorCode),a.message&&(b.message=a.message),a.parameter)b.parameter=a.parameter;return b};Downsha.Exception=function(a,b){this.initialize(a,b,null)};
Downsha.Exception.javaClass="java.lang.Exception";Downsha.inherit(Downsha.Exception,Downsha.DownshaError);Downsha.Exception.prototype._errorCode=0;Downsha.DSTPSystemException=function(a,b){this.initialize(a,b)};Downsha.DSTPSystemException.javaClass="com.downsha.edam.error.DSTPSystemException";Downsha.inherit(Downsha.DSTPSystemException,Downsha.Exception);Downsha.DSTPUserException=function(a,b,c){this.initialize(a,b,c)};Downsha.DSTPUserException.javaClass="com.downsha.edam.error.DSTPUserException";
Downsha.inherit(Downsha.DSTPUserException,Downsha.Exception);Downsha.DSTPResponseException=function(a,b){this.initialize(a,b)};Downsha.DSTPResponseException.javaClass="com.downsha.edam.error.DSTPResponseException";Downsha.inherit(Downsha.DSTPResponseException,Downsha.DownshaError);Downsha.ValidationError=function(a,b,c){this.initialize(a,b,c)};Downsha.ValidationError.GLOBAL_PARAMETER="__stripes_global_error";Downsha.ValidationError.javaClass="net.sourceforge.stripes.validation.ValidationError";
Downsha.inherit(Downsha.ValidationError,Downsha.DownshaError);Downsha.ValidationError.prototype.isGlobal=function(){return null==this.parameter||this.parameter==Downsha.ValidationError.GLOBAL_PARAMETER};Downsha.SimpleError=function(a){this.initialize(null,a,null)};Downsha.SimpleError.javaClass="net.sourceforge.stripes.validation.SimpleError";Downsha.inherit(Downsha.SimpleError,Downsha.ValidationError);Downsha.ScopedLocalizableError=function(a,b,c){this.initialize(a,b,c)};
Downsha.ScopedLocalizableError.javaClass="net.sourceforge.stripes.validation.ScopedLocalizableError";Downsha.inherit(Downsha.ScopedLocalizableError,Downsha.SimpleError);Downsha.DSTPScopedError=function(a,b,c){this.initialize(a,b,c)};Downsha.DSTPScopedError.javaClass="com.downsha.web.Downsha.DSTPScopedError";Downsha.inherit(Downsha.DSTPScopedError,Downsha.ScopedLocalizableError);Downsha.Constants=Downsha.Constants||{};Downsha.Constants.REQUEST_TYPE="type";Downsha.Constants.REQUEST_MESSAGE="message";
Downsha.Constants.IS_WINDOWS=-1!=navigator.platform.indexOf("Win");Downsha.Constants.SLASH=Downsha.Constants.IS_WINDOWS?"\\":"/";
Downsha.Constants.RequestType={UNKNOWN:0,LOGOUT:1001,LOGIN:1002,LOGIN_ERROR:1003,LOGIN_SUCCESS:1004,POPUP_STARTED:2001,POPUP_ENDED:2002,PAGE_CLIP_SUCCESS:3001,PAGE_CLIP_FAILURE:3002,PAGE_CLIP_CONTENT_SUCCESS:3003,PAGE_CLIP_CONTENT_FAILURE:3004,PAGE_CLIP_CONTENT_TOO_BIG:3005,CONTEXT_PAGE_CLIP_SUCCESS:3101,CONTEXT_PAGE_CLIP_FAILURE:3102,CONTEXT_PAGE_CLIP_CONTENT_SUCCESS:3103,CONTEXT_PAGE_CLIP_CONTENT_FAILURE:3104,CONTEXT_PAGE_CLIP_CONTENT_TOO_BIG:3105,CONTENT_SCRIPT_LOAD_TIMEOUT:4001,FETCH_STYLE_SHEET_RULES:4002,
CLIP_ACTION_FULL_PAGE:5001,CLIP_ACTION_ARTICLE:5002,CLIP_ACTION_SELECTION:5003,CLIP_ACTION_URL:5004,PREVIEW_CLIP_ACTION_CLEAR:6001,PREVIEW_CLIP_ACTION_FULL_PAGE:6002,PREVIEW_CLIP_ACTION_ARTICLE:6003,PREVIEW_CLIP_ACTION_SELECTION:6004,PREVIEW_CLIP_ACTION_URL:6005,PREVIEW_NUDGE:6101,PREVIEW_NUDGE_PREVIOUS_SIBLING:6102,PREVIEW_NUDGE_NEXT_SIBLING:6103,PREVIEW_NUDGE_PARENT:6104,PREVIEW_NUDGE_CHILD:6105,PAGE_INFO:7001};
Downsha.Constants.Limits={DSTP_USER_NAME_LEN_MIN:6,DSTP_USER_NAME_LEN_MAX:16,DSTP_USER_NAME_REGEX:"^[A-Za-z0-9._\\-\\u4e00-\\u9fa5]{6,16}$",DSTP_USER_EMAIL_LEN_MIN:6,DSTP_USER_EMAIL_LEN_MAX:255,DSTP_USER_EMAIL_REGEX:"^\\w+((-\\w+)|(\\.\\w+))*\\@[A-Za-z0-9]+((\\.|-)[A-Za-z0-9]+)*\\.[A-Za-z0-9]+$",DSTP_USER_PWD_LEN_MIN:6,DSTP_USER_PWD_LEN_MAX:16,DSTP_USER_PWD_REGEX:"^[A-Za-z0-9.~!@#$%^&*()+=_-]{6,16}$",DSTP_NOTE_TITLE_LEN_MIN:0,DSTP_NOTE_TITLE_LEN_MAX:127,DSTP_NOTE_TITLE_REGEX:"^$|^[^\\s\\r\\n\\t]([^\\n\\r\\t]{0,253}[^\\s\\r\\n\\t])?$",
DSTP_TAG_NAME_LEN_MIN:1,DSTP_TAG_NAME_LEN_MAX:100,DSTP_TAG_NAME_REGEX:"^[^,\\s\\r\\n\\t]([^,\\n\\r\\t]{0,98}[^,\\s\\r\\n\\t])?$",DSTP_NOTE_TAGS_MIN:0,DSTP_NOTE_TAGS_MAX:100,SERVICE_DOMAIN_LEN_MIN:1,SERVICE_DOMAIN_LEN_MAX:256,CLIP_NOTE_CONTENT_LEN_MAX:5242880};
(function(){Downsha.Logger=function(a,b,c){this.__defineGetter__("level",this.getLevel);this.__defineSetter__("level",this.setLevel);this.__defineGetter__("scope",this.getScope);this.__defineSetter__("scope",this.setScope);this.__defineGetter__("scopeName",this.getScopeName);this.__defineGetter__("scopeNameAsPrefix",this.getScopeNameAsPrefix);this.__defineGetter__("useTimestamp",this.isUseTimestamp);this.__defineSetter__("useTimestamp",this.setUseTimestamp);this.__defineGetter__("usePrefix",this.isUsePrefix);
this.__defineSetter__("usePrefix",this.setUsePrefix);this.scope=a||arguments.callee.caller;this.level=b;this.impl="undefined"!=typeof c&&c instanceof Downsha.LoggerImpl?c:Downsha.LoggerImplFactory.getImplementationFor(navigator);this.enabled=this.impl.enabled};Downsha.Logger.LOG_LEVEL_DEBUG=0;Downsha.Logger.LOG_LEVEL_INFO=1;Downsha.Logger.LOG_LEVEL_WARN=2;Downsha.Logger.LOG_LEVEL_ERROR=3;Downsha.Logger.LOG_LEVEL_EXCEPTION=4;Downsha.Logger.LOG_LEVEL_OFF=5;Downsha.Logger.GLOBAL_LEVEL=Downsha.Logger.LOG_LEVEL_ERROR;
Downsha.Logger.DEBUG_PREFIX="[DEBUG] ";Downsha.Logger.INFO_PREFIX="[INFO] ";Downsha.Logger.WARN_PREFIX="[WARN] ";Downsha.Logger.ERROR_PREFIX="[ERROR] ";Downsha.Logger.EXCEPTION_PREFIX="[EXCEPTION] ";Downsha.Logger._instances={};Downsha.Logger.getInstance=function(a){var a=a||arguments.callee.caller,b="function"==typeof a?a.name:a.constructor.name;"undefined"==typeof this._instances[b]&&(this._instances[b]=new Downsha.Logger(a));return this._instances[b]};Downsha.Logger.destroyInstance=function(a){a=
a||arguments.callee.caller;delete this._instances["function"==typeof a?a.name:a.constructor.name]};Downsha.Logger.prototype._level=null;Downsha.Logger.prototype._scope=null;Downsha.Logger.prototype._usePrefix=!0;Downsha.Logger.prototype._useTimestamp=!0;Downsha.Logger.prototype.setLevel=function(a){this._level=parseInt(a);isNaN(this._level)&&(this._level=Downsha.Logger.GLOBAL_LEVEL)};Downsha.Logger.prototype.getLevel=function(){return this._level};Downsha.Logger.prototype.setScope=function(a){"function"==
typeof a?this._scope=a:"object"==typeof a&&null!=a&&(this._scope=a.constructor)};Downsha.Logger.prototype.getScope=function(){return this._scope};Downsha.Logger.prototype.getScopeName=function(){return this.scope?this.scope.name:""};Downsha.Logger.prototype.getScopeNameAsPrefix=function(){var a=this.scopeName;return a?"["+a+"] ":""};Downsha.Logger.prototype._padNumber=function(a,b){a=parseInt(a);isNaN(a)&&(a=0);for(var c=0<=a?!0:!1,d=""+Math.abs(a);d.length<b;)d="0"+d;c||(d="-"+d);return d};Downsha.Logger.prototype.getPrefix=
function(a){var b="";if(this.useTimestamp)var c=new Date,d=c.getFullYear(),e=this._padNumber(c.getMonth()+1,2),f=this._padNumber(c.getDate(),2),g=this._padNumber(c.getHours(),2),h=this._padNumber(c.getMinutes(),2),i=this._padNumber(c.getSeconds(),2),c=this._padNumber(c.getMilliseconds(),3),b=b+(d+"/"+e+"/"+f+" "+g+":"+h+":"+i+"."+c+" ");this.usePrefix&&(b+=a);return b+=this.scopeNameAsPrefix};Downsha.Logger.prototype.isUsePrefix=function(){return this._usePrefix};Downsha.Logger.prototype.setUsePrefix=
function(a){this._usePrefix=a?!0:!1};Downsha.Logger.prototype.isUseTimestamp=function(){return this._useTimestamp};Downsha.Logger.prototype.setUseTimestamp=function(a){this._useTimestamp=a?!0:!1};Downsha.Logger.prototype.isEnabled=function(){return this.impl.enabled};Downsha.Logger.prototype.dir=function(a){this.enabled&&this.impl.dir(a)};Downsha.Logger.prototype.trace=function(){this.enabled&&this.impl.trace()};Downsha.Logger.prototype.debug=function(a){this.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_DEBUG&&
this.impl.debug(this.getPrefix(this.constructor.DEBUG_PREFIX)+a)};Downsha.Logger.prototype.info=function(a){this.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_INFO&&this.impl.info(this.getPrefix(this.constructor.INFO_PREFIX)+a)};Downsha.Logger.prototype.warn=function(a){this.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_WARN&&this.impl.warn(this.getPrefix(this.constructor.WARN_PREFIX)+a)};Downsha.Logger.prototype.error=function(a){this.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_ERROR&&this.impl.error(this.getPrefix(this.constructor.ERROR_PREFIX)+
a)};Downsha.Logger.prototype.exception=function(a){this.enabled&&this.level<=Downsha.Logger.LOG_LEVEL_EXCEPTION&&this.impl.exception(this.getPrefix(this.constructor.EXCEPTION_PREFIX)+a)};Downsha.Logger.prototype.alert=function(a){this.enabled&&this.impl.alert(a)};Downsha.Logger.prototype.clear=function(){this.impl.clear()};Downsha.Logger.prototype.enableAlerts=function(a){a||(a=this.level);this.impl.enableAlerts(a)};Downsha.Logger.prototype.disableAlerts=function(){this.impl.disableAlerts()};Downsha.Logger.prototype.isDebugEnabled=
function(){return this.level==Downsha.Logger.LOG_LEVEL_DEBUG};Downsha.LoggerImpl=function(){};Downsha.LoggerImpl.prototype.enabled=!1;Downsha.LoggerImpl.prototype.dir=function(){};Downsha.LoggerImpl.prototype.trace=function(){};Downsha.LoggerImpl.prototype.debug=function(){};Downsha.LoggerImpl.prototype.info=function(){};Downsha.LoggerImpl.prototype.warn=function(){};Downsha.LoggerImpl.prototype.error=function(){};Downsha.LoggerImpl.prototype.exception=function(){};Downsha.LoggerImpl.prototype.alert=
function(){};Downsha.LoggerImpl.prototype.enableAlerts=function(){};Downsha.LoggerImpl.prototype.disableAlerts=function(){};Downsha.LoggerImpl.prototype.clear=function(){};Downsha.LoggerImplFactory={getImplementationFor:function(a){return"object"==typeof a&&null!=a&&a.userAgent.match(/Firefox/i)?new Downsha.FirefoxExtensionLoggerImpl:"object"==typeof a&&null!=a&&a.userAgent.match(/(Safari)|(WebKit)/i)?new Downsha.WebKitLoggerImpl:new Downsha.LoggerImpl}}})();
(function(){Downsha.FirefoxExtensionLoggerImpl=function(){this.initialize()};Downsha.FirefoxExtensionLoggerImpl.prototype=new Downsha.LoggerImpl;Downsha.FirefoxExtensionLoggerImpl.prototype.LOG_FILE_NAME="downsha_webclipper.log";Downsha.FirefoxExtensionLoggerImpl.prototype.isLogToFileEnabled=!1;Downsha.FirefoxExtensionLoggerImpl.prototype.fileLogger=null;Downsha.FirefoxExtensionLoggerImpl.prototype.enabled=navigator.userAgent.match(/Firefox/i)?!0:!1;Downsha.FirefoxExtensionLoggerImpl.prototype.alertsEnabled=
!1;Downsha.FirefoxExtensionLoggerImpl.prototype.alertLevel=Downsha.Logger.LOG_LEVEL_OFF;Downsha.FirefoxExtensionLoggerImpl.prototype.service=null;Downsha.FirefoxExtensionLoggerImpl.prototype.initialize=function(){this.service=Components.classes["@mozilla.org/consoleservice;1"].getService(Components.interfaces.nsIConsoleService);this.isLogToFileEnabled&&(this.fileLogger=new Downsha.FileLogger(this.LOG_FILE_NAME))};Downsha.FirefoxExtensionLoggerImpl.prototype.dir=function(a){this._log(a)};Downsha.FirefoxExtensionLoggerImpl.prototype.trace=
function(){};Downsha.FirefoxExtensionLoggerImpl.prototype.debug=function(a){this._log(a)};Downsha.FirefoxExtensionLoggerImpl.prototype.info=function(a){this._log(a)};Downsha.FirefoxExtensionLoggerImpl.prototype.warn=function(a){this._log(a)};Downsha.FirefoxExtensionLoggerImpl.prototype.error=function(a){this._log(a)};Downsha.FirefoxExtensionLoggerImpl.prototype.exception=function(a){this._log(a)};Downsha.FirefoxExtensionLoggerImpl.prototype.alert=function(a){alert(a)};Downsha.FirefoxExtensionLoggerImpl.prototype._log=
function(a){this.service.logStringMessage(a);this.alertsEnabled&&this.alert(a);this.isLogToFileEnabled&&null!=this.fileLogger&&this.fileLogger.writeStr(a)};Downsha.FirefoxExtensionLoggerImpl.prototype.enableAlerts=function(a){this.alertLevel=a;this.alertsEnabled=!0};Downsha.FileLogger=function(a){this.init(a)};Downsha.FileLogger.prototype.logFile=null;Downsha.FileLogger.prototype.init=function(a){this.initOutStrem(a)};Downsha.FileLogger.prototype.initOutStrem=function(a){var b=Components.classes["@mozilla.org/file/directory_service;1"].getService(Components.interfaces.nsIProperties).get("ProfD",
Components.interfaces.nsIFile).path,c=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);c.initWithPath(b+Downsha.Constants.SLASH+a);a=Components.classes["@mozilla.org/network/file-output-stream;1"].createInstance(Components.interfaces.nsIFileOutputStream);a.init(c,26,438,0);c=Components.classes["@mozilla.org/intl/converter-output-stream;1"].createInstance(Components.interfaces.nsIConverterOutputStream);c.init(a,"UTF-8",0,0);this.logFile=c};Downsha.FileLogger.prototype.writeStr=
function(a){this.logFile.writeString([a,"\r\n"].join(""));this.logFile.flush()}})();
(function(){Downsha.getPlatform=function(){null==Downsha._platform&&(Downsha._platform=new Downsha.Platform);return Downsha._platform};Downsha.__defineGetter__("platform",Downsha.getPlatform);Downsha.Platform=function(){Downsha.Logger.getInstance();this.initialize()};Downsha.Platform.prototype.os="";Downsha.Platform.prototype.osMajor=0;Downsha.Platform.prototype.osMinor=0;Downsha.Platform.prototype.osVer="";Downsha.Platform.prototype.browser="";Downsha.Platform.prototype.browserVer="";Downsha.Platform.prototype.userAgent=
"";Downsha.Platform.prototype.initialize=function(){if(0<=navigator.platform.indexOf("Win")){var a=navigator.userAgent.match(/Windows\s*NT\s*(\d+)\.(\d+)/i);a&&(this.osMajor=parseInt(a[1]),this.osMinor=parseInt(a[2]),this.osVer=this.osMajor+"."+this.osMinor);this.os=5==this.osMajor&&0==this.osMinor?"WIN_2K":5==this.osMajor&&1==this.osMinor?"WIN_XP":5==this.osMajor&&2==this.osMinor?"WIN_SERVER_2003":6==this.osMajor&&0==this.osMinor?"WIN_VISTA":6==this.osMajor&&1==this.osMinor?"WIN_7":6==this.osMajor&&
2==this.osMinor?"WIN_8":"WIN"}else if(0<=navigator.platform.indexOf("Mac")){if(a=navigator.userAgent.match(/Mac\s*OS\s*X\s*(\d+)_(\d+)/i))this.osMajor=parseInt(a[1]),this.osMinor=parseInt(a[2]),this.osVer=this.osMajor+"."+this.osMinor;this.os="MAC"}else 0<=navigator.platform.indexOf("Linux")?this.os="LINUX":0<=navigator.platform.indexOf("X11")?this.os="UNIX":0<=navigator.platform.indexOf("iPhone")?this.os="iPhone":0<=navigator.platform.indexOf("iPad")&&(this.os="iPad");this.browser=0<=navigator.userAgent.indexOf("SeaMonkey")?
"SeaMonkey":0<=navigator.userAgent.indexOf("Thunderbird")?"Thunderbird":0<=navigator.userAgent.indexOf("Netscape")?"Netscape":"Firefox";if(a=navigator.userAgent.match(/Firefox\/(\d+\.\d+)/i))this.browserVer=a[1];this.userAgent=navigator.userAgent};Downsha.Platform.prototype.isWin32=function(){return"Win32"==navigator.platform&&0<=navigator.oscpu.toLowerCase().indexOf("windows")};Downsha.Platform.prototype.isMacOS=function(){return"MacIntel"==navigator.platform&&-1!=navigator.oscpu.indexOf("Intel Mac OS X 10")};
Downsha.Platform.prototype.isLinux=function(){return 0<=navigator.platform.toLowerCase().indexOf("linux")};Downsha.Platform.prototype.isFF=function(){return 0<=navigator.userAgent.toLowerCase().indexOf("firefox")};Downsha.Platform.prototype.toJSON=function(){return{OS:this.os,OSVer:this.osVer,BrowName:this.browser,BrowVer:this.browserVer,UserAgent:this.userAgent}}})();
(function(){Downsha.LocalStore=function(a,b){this.initialize(a,b);this.__defineGetter__("length",this.getLength)};Downsha.LocalStore.prototype.initialize=function(a,b){this.storeName="string"==typeof a?a:Downsha.LocalStore.DEFAULT_STORE_NAME;this.impl=b?b:new Downsha.LocalStore.DEFAULT_IMPL;this.impl.store=this};Downsha.LocalStore.prototype.get=function(a){return this.impl.get(a)};Downsha.LocalStore.prototype.put=function(a,b){this.impl.put(a,b)};Downsha.LocalStore.prototype.remove=function(a){this.impl.remove(a)};
Downsha.LocalStore.prototype.clear=function(){this.impl.clear()};Downsha.LocalStore.prototype.getLength=function(){return this.impl.length};Downsha.LocalStore.DEFAULT_STORE_NAME="LocalStore";Downsha.LocalStore.DEFAULT_IMPL=function(){this.initialize();this.__defineGetter__("length",this.getLength)};Downsha.LocalStore.DEFAULT_IMPL.prototype.store=null;Downsha.LocalStore.DEFAULT_IMPL.prototype._cache=null;Downsha.LocalStore.DEFAULT_IMPL.prototype._countDelta=0;Downsha.LocalStore.DEFAULT_IMPL.prototype.initialize=
function(){this._cache={};for(var a=this._countDelta=0;a<this._cache.length;a++)this._countDelta++};Downsha.LocalStore.DEFAULT_IMPL.prototype.clear=function(){this.initialize()};Downsha.LocalStore.DEFAULT_IMPL.prototype.get=function(a){return this._cache[a]};Downsha.LocalStore.DEFAULT_IMPL.prototype.put=function(a,b){this._cache[a]=b};Downsha.LocalStore.DEFAULT_IMPL.prototype.remove=function(a){"undefined"!=typeof this._cache[a]&&delete this._cache[a]};Downsha.LocalStore.DEFAULT_IMPL.prototype.getLength=
function(){var a=0,b;for(b in this._cache)a++;return a-this._countDelta};Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL=function(a){this.initialize(a);this.__defineGetter__("length",this.getLength)};Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.store=null;Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype._cache=null;Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.initialize=function(a){this._cache=a};Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.clear=function(){this._cache.clear()};
Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.get=function(a){return(a=this._cache.getItem(a))?this.unmarshall(a):null};Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.put=function(a,b){this._cache.setItem(a,this.marshall(b))};Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.remove=function(a){this._cache.removeItem(a)};Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.getLength=function(){return this._cache.length};Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.marshall=
function(a){return JSON.stringify(a)};Downsha.LocalStore.HTML5_LOCALSTORAGE_IMPL.prototype.unmarshall=function(a){return JSON.parse(a)};Downsha.LocalStore.SQLITE_IMPL=function(a){this.initialize(a);this.__defineGetter__("length",this.getLength)};Downsha.LocalStore.SQLITE_IMPL.DEFAULT_TABLE_NAME="local_store";Downsha.LocalStore.SQLITE_IMPL.prototype.store=null;Downsha.LocalStore.SQLITE_IMPL.prototype._cache=null;Downsha.LocalStore.SQLITE_IMPL.prototype._keys=null;Downsha.LocalStore.SQLITE_IMPL.prototype._tableName=
null;Downsha.LocalStore.SQLITE_IMPL.prototype.initialize=function(a,b){this._cache=a;this._tableName="string"==typeof b?b:Downsha.LocalStore.SQLITE_IMPL.DEFAULT_TABLE_NAME;this._createTable();this._keys=this._getKeys()};Downsha.LocalStore.SQLITE_IMPL.prototype._getKeys=function(){for(var a=this._cache.createStatement("SELECT key FROM "+this._tableName),b=[];a.executeStep();)b.push(a.row.key);return b};Downsha.LocalStore.SQLITE_IMPL.prototype._createTable=function(a){a&&this._cache.executeSimpleSQL("DROP TABLE "+
this._tableName+" IF EXISTS");this._cache.executeSimpleSQL("CREATE TABLE IF NOT EXISTS "+this._tableName+" (key TEXT PRIMARY KEY, value BLOB)")};Downsha.LocalStore.SQLITE_IMPL.prototype.clear=function(){!1===this._cache.createStatement("DELETE FROM "+this._tableName).executeStep()&&(this._keys=[])};Downsha.LocalStore.SQLITE_IMPL.prototype.get=function(a){var b=this._cache.createStatement("SELECT * FROM "+this._tableName+" where key = :row_key");b.params.row_key=a;a=null;b.executeStep()&&(a=this.unmarshall(b.row.value));
b.reset();return a};Downsha.LocalStore.SQLITE_IMPL.prototype.put=function(a,b){var c="",d=-1,c=0<=(d=this._keys.indexOf(a))?"UPDATE "+this._tableName+" set value = :row_value where key = :row_key":"INSERT INTO "+this._tableName+" (key, value) VALUES(:row_key, :row_value)",e=this.marshall(b),c=this._cache.createStatement(c);c.params.row_key=a;c.params.row_value=e;"undefined"!=typeof c.executeStep()&&0>d&&this._keys.push(a);c.reset()};Downsha.LocalStore.SQLITE_IMPL.prototype.remove=function(a){var b=
-1;if(0<=(b=this._keys.indexOf(a))){var c=this._cache.createStatement("DELETE FROM "+this._tableName+" where key = :row_key");c.params.row_key=a;"undefined"!=typeof c.executeStep()&&this._keys.splice(b,1);c.reset()}};Downsha.LocalStore.SQLITE_IMPL.prototype.getLength=function(){return this._keys.length};Downsha.LocalStore.SQLITE_IMPL.prototype.marshall=function(a){return JSON.stringify(a)};Downsha.LocalStore.SQLITE_IMPL.prototype.unmarshall=function(a){return JSON.parse(a)}})();Downsha.Utils={};
Downsha.Utils.MESSAGE_ATTR="message";Downsha.Utils.LOCALIZED_ATTR="localized";Downsha.Utils.PLACEHOLDER_ATTR="placeholder";Downsha.Utils.TITLE_ATTR="title";Downsha.Utils.MESSAGE_DATA_ATTR="messagedata";Downsha.Utils.localizeBlock=function(a){a.attr(Downsha.Utils.MESSAGE_ATTR)&&Downsha.Utils.localizeElement(a);for(var a=a.find("["+Downsha.Utils.MESSAGE_ATTR+"], ["+Downsha.Utils.PLACEHOLDER_ATTR+"], ["+Downsha.Utils.TITLE_ATTR+"]"),b=0;b<a.length;b++){var c=$(a.get(b));Downsha.Utils.localizeElement(c)}};
Downsha.Utils.localizeElement=function(a,b){if(b||!a.attr(Downsha.Utils.LOCALIZED_ATTR)||!a.attr("true"==Downsha.Utils.LOCALIZED_ATTR)){var c=Downsha.Utils.extractLocalizationField(a),d=Downsha.Utils.extractLocalizationPlaceholderField(a),e=Downsha.Utils.extractLocalizationTitleField(a),f=Downsha.Utils.extractLocalizationDataField(a),g=!1;c&&(c=f?Downsha.chrome.i18n.getMessage(c,f):Downsha.chrome.i18n.getMessage(c),"INPUT"==a.prop("tagName")?a.val(c):a.text(c),g=!0);d&&"string"==typeof d&&(c=Downsha.chrome.i18n.getMessage(d),
a.attr(Downsha.Utils.PLACEHOLDER_ATTR,c),g=!0);e&&"string"==typeof e&&(c=Downsha.chrome.i18n.getMessage(e),a.attr(Downsha.Utils.TITLE_ATTR,c),g=!0);g&&a.attr(Downsha.Utils.LOCALIZED_ATTR,"true")}};Downsha.Utils.extractLocalizationField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.MESSAGE_ATTR)?a.attr(Downsha.Utils.MESSAGE_ATTR):null};
Downsha.Utils.extractLocalizationPlaceholderField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.PLACEHOLDER_ATTR)?a.attr(Downsha.Utils.PLACEHOLDER_ATTR):null};Downsha.Utils.extractLocalizationTitleField=function(a){return"function"==typeof a.attr&&a.attr(Downsha.Utils.TITLE_ATTR)?a.attr(Downsha.Utils.TITLE_ATTR):null};
Downsha.Utils.extractLocalizationDataField=function(a){if("function"==typeof a.attr&&a.attr(Downsha.Utils.MESSAGE_DATA_ATTR)){a=a.attr(Downsha.Utils.MESSAGE_DATA_ATTR);try{a=JSON.parse(a)}catch(b){}a instanceof Array||(a=[a]);return a}return null};Downsha.Utils.getKeyFrom=function(a,b,c,d){d="undefined"!=typeof d?d:null;"object"==typeof a&&("string"==typeof c&&typeof a[b]==c?d=a[b]:"undefined"!=typeof a[b]&&(d=a[b]));return d};
Downsha.Utils.importRegistry=function(a,b){if("object"==typeof b&&null!=b)for(var c in b)Downsha.Utils._importModel(a,b[c])};Downsha.Utils._importModel=function(a,b){"function"==typeof b&&"string"==typeof b.modelName&&(a[b.modelName]=b,"undefined"!=typeof b.prototype.parent&&"function"==typeof b.prototype.parent.constructor&&Downsha.Utils._importModel(a,b.prototype.parent.constructor))};
Downsha.Utils.importConstructs=function(a,b,c){for(var c=c instanceof Array?c:[c],d=0;d<c.length;d++)"undefined"!=typeof a[c[d]]&&(b[c[d]]=a[c[d]])};Downsha.Utils.updateSelectElementWidth=function(a,b){var c=a instanceof jQuery?a:$(a),d=c.val();"function"==typeof b&&(d=b(d));var e=parseInt(c.css("paddingLeft")),f=parseInt(c.css("paddingRight")),e=(!isNaN(e)?e:0)+(!isNaN(f)?f:0),d=Downsha.Utils.getTextSize(d).width,d=(d?d:0)+e+30;c.css({minWidth:d+"px",width:d+"px"})};
Downsha.Utils.resizeElement=function(a,b,c){var a=a instanceof jQuery?a:$(a),d={},e={};if(b&&"number"==typeof b.width){var f=parseInt(a.css("paddingLeft")),g=parseInt(a.css("paddingRight")),f=(!isNaN(f)?f:0)+(!isNaN(g)?g:0);e.width=b.width+f;d.minWidth=e.width+"px";d.width=e.width+"px"}b&&"number"==typeof b.height&&(f=parseInt(a.css("paddingTop")),g=parseInt(a.css("paddingBottom")),f=(!isNaN(f)?f:0)+(!isNaN(g)?g:0),e.height=b.height+f,d.minHeight=e.height+"px",css.height=e.height+"px");a.css(d);"function"==
typeof c&&c(a,e)};Downsha.Utils.getTextSize=function(a){var b=$("<div></div>");b.text(a);b.css({position:"absolute",top:"0px",left:"0px",padding:"0px",margin:"0px",display:"block",zIndex:"0",color:"rgba(0, 0, 0, 0)",background:"rgba(0, 0, 0, 0)"});$("body").append(b);a={width:b.width(),height:b.height()};b.remove();return a};
Downsha.Utils.separateString=function(a,b){if("string"!=typeof a)return a;"string"!=typeof b&&(b=",");for(var c=a.split(b),d=[],e=0;e<c.length;e++)if("string"==typeof c[e]){var f=Downsha.Utils.trim(c[e]);f&&0<f.length&&d.push(f)}return d};Downsha.Utils.trim=function(a){return"string"!=typeof a?a:a.replace(/^\s+/,"").replace(/\s+$/,"")};
Downsha.Utils.isForbiddenUrl=function(a){return"string"==typeof a&&(0<=a.toLowerCase().indexOf("chrome.google.com/extensions")||0<=a.toLowerCase().indexOf("chrome.google.com/webstore"))?!0:"string"==typeof a&&!a.toLowerCase().match(/^https?:\/\//)};Downsha.Utils.urlTopDomain=function(a){var b=a;"string"==typeof a&&(b=Downsha.Utils.urlDomain(a),0==b.toLowerCase().indexOf("www.")&&(b=b.substring(4)));return b};
Downsha.Utils.urlDomain=function(a,b){return"string"==typeof a?a.replace(RegExp("^[^:]+:/+([^/"+(b?"":":")+"]+).*$"),"$1"):a};Downsha.Utils.urlProto=function(a){if("string"==typeof a){var b=-1;if(0<(b=a.indexOf(":/")))return a.substring(0,b).toLowerCase()}return null};
Downsha.Utils.urlQueryValue=function(a,b){if("string"==typeof b&&"string"==typeof a&&0<=b.indexOf("?")){for(var c=b.split(/[\?\#\&]+/).slice(1),d=a.toLowerCase(),e=[],f=0;f<c.length;f++){var g=c[f].split("=",2);g[0].toLowerCase()==d&&(g=g[1]?g[1].replace(/\+/g," "):g[1],e.push(decodeURIComponent(g)))}if(0<e.length)return e[e.length-1]}return null};
Downsha.Utils.urlPath=function(a){return"string"==typeof a&&(a=a.replace(/^[^:]+:\/+([^\/]+)/,""),0==a.indexOf("/"))?a.replace(/^(\/[^\?\#]*).*$/,"$1"):""};Downsha.Utils.absoluteUrl=function(a,b){0==a.indexOf("//")?a=b.replace(/^([^:]+):.*$/,"$1")+":"+a:0==a.indexOf("/")?a=b.replace(/^(.*:\/\/[^\/]+).*$/,"$1")+a:(a.match(/^\.+\//),a="/"==b.charAt(b.length-1)?b+a:b+"/"+a);return a};
Downsha.Utils.getDocumentWidth=function(a){a||(a=document);return a.width?a.width:a.body&&a.documentElement&&a.documentElement.scrollWidth?a.documentElement.scrollWidth:a.body&&a.body.scrollWidth?a.body.scrollWidth:0};Downsha.Utils.getDocumentHeight=function(a){a||(a=document);return a.height?a.height:a.body&&a.body.scrollHeight&&a.documentElement&&a.documentElement.scrollHeight?Math.max(a.documentElement.scrollHeight,a.body.scrollHeight):a.body&&a.body.scrollHeight?a.body.scrollHeight:0};
Downsha.Utils.findEmbeds=function(a){var b=[];try{var c=a.getElementsByTagName("object");if(c&&0<c.length)for(var d=0;d<c.length;d++)b.push(c[d]);var e=a.getElementsByTagName("embed");if(e&&0<e.length)for(d=0;d<e.length;d++)b.push(e[d])}catch(f){}return b};
Downsha.Utils.findDocuments=function(a){var b=[];try{var c=a.getElementsByTagName("frame");if(c&&0<c.length)for(var d=0;d<c.length;d++)c[d].contentDocument?b.push(c[d].contentDocument):c[d].contentWindow&&c[d].contentWindow.document?b.push(c[d].contentWindow.document):c[d].document&&b.push(c[d].document);var e=a.getElementsByTagName("iframe");if(e&&0<e.length)for(d=0;d<e.length;d++)e[d].contentDocument?b.push(e[d].contentDocument):e[d].contentWindow&&e[d].contentWindow.document?b.push(e[d].contentWindow.document):
e[d].document&&b.push(e[d].document)}catch(f){}return b};Downsha.Utils.getDocumentHead=function(a){return a.head?a.head:a.getElementsByTagName("head")?a.getElementsByTagName("head")[0]:a.documentElement?a.documentElement:a.body&&a.body.parentNode?a.body.parentNode:null};Downsha.Utils.makeAbsoluteClientRect=function(a,b){b||(b=window);return{top:a.top+b.pageYOffset,bottom:a.bottom+b.pageYOffset,left:a.left+b.pageXOffset,right:a.right+b.pageXOffset,width:a.width,height:a.height}};
Downsha.Utils.getAbsoluteBoundingClientRect=function(a){var b=a&&a.nodeType==Node.TEXT_NODE?a.parentElement?a.parentElement:a.parentNode:a;if(!b)return null;a=a instanceof Range?a.commonAncestorContainer.ownerDocument.defaultView:a.ownerDocument.defaultView;return Downsha.Utils.makeAbsoluteClientRect(b.getBoundingClientRect(),a)};
Downsha.Utils.expandRect=function(a,b){a.left="number"==typeof a.left?Math.min(a.left,b.left):b.left;a.top="number"==typeof a.top?Math.min(a.top,b.top):b.top;a.right="number"==typeof a.right?Math.max(a.right,b.right):b.right;a.bottom="number"==typeof a.bottom?Math.max(a.bottom,b.bottom):b.bottom};Downsha.Utils.getElementForNode=function(a){return a&&a.nodeType==Node.ELEMENT_NODE?a:a.parentNode?a.parentNode:null};
Downsha.Utils.addElementClass=function(a,b){if(a&&b){var c=a.getAttribute("class");c?(c=c.split(/\s+/),0>c.indexOf(b)&&c.push(b),a.setAttribute("class",c.join(" "))):a.setAttribute("class",b)}};Downsha.Utils.removeElementClass=function(a,b){if(b){var c=a.getAttribute("class");if(c){var c=c.split(/\s+/),d=-1;0<=(d=c.indexOf(b))&&c.splice(d,1);a.setAttribute("class",c.join(" "))}}};Downsha.Utils.XML_ESCAPE_CHAR_MAP={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"};
Downsha.Utils.escapeXML=function(a){for(var a=a.split(""),b=0;b<a.length;b++)Downsha.Utils.XML_ESCAPE_CHAR_MAP[a[b]]&&(a[b]=Downsha.Utils.XML_ESCAPE_CHAR_MAP[a[b]]);return a.join("")};Downsha.Utils.MIN_ARTICLE_RATIO=0.0625;Downsha.Utils.MIN_ARTICLE_AREA=3E4;Downsha.Utils.MAX_ARTICLE_XOFFSET_RATIO=0.6;
Downsha.Utils.isArticleSane=function(a,b,c){if(a&&b&&c){var a=Math.round(a*b),d=Math.round(c.width*c.height);if(!(c.top>b*Downsha.Utils.MAX_ARTICLE_XOFFSET_RATIO)&&!(d<Downsha.Utils.MIN_ARTICLE_AREA&&d<a*Downsha.Utils.MIN_ARTICLE_RATIO))return!0}return!1};Downsha.Utils.BAD_FAV_ICON_URLS=["http://localhost/favicon.ico"];
Downsha.Utils.createUrlClipContent=function(a,b,c){a=a?Downsha.Utils.escapeXML(a):"";b='<a title="'+a+'" style="font-size: 12pt; line-height: 18px; display: inline;" href="'+b+'">'+b+"</a>";return b="string"==typeof c&&0<c.length&&0>Downsha.Utils.BAD_FAV_ICON_URLS.indexOf(c.toLowerCase())?'<span><img title="'+a+'" style="display:inline;border: none; width: 16px; height: 16px; padding: 0px; margin: 0px 8px -2px 0px;" src="'+c+'"/>'+b+"</span>":"<span>"+b+"</span>"};
Downsha.Utils.createUrlClipElement=function(a,b,c,d){var e=function(a,b){var c=a.style,d;for(d in b)"string"==typeof b[d]&&c.setProperty(d,b[d],"important")},b=b?Downsha.Utils.escapeXML(b):"",f=a.createElement("a");f.setAttribute("title",b);f.setAttribute("href",c);e(f,{"font-size":"12pt","line-height":"18px",display:"inline"});c=a.createTextNode(c);f.appendChild(c);c=a.createElement("div");"string"==typeof d&&0<d.length&&0>this.BAD_FAV_ICON_URLS.indexOf(d.toLowerCase())?(a=a.createElement("img"),
a.setAttribute("title",b),a.setAttribute("src",d),e(a,{display:"inline",border:"none",width:"16px",height:"16px",padding:"0px",margin:"0px 8px -2px 0px"}),c.appendChild(a),c.appendChild(f)):(b=a.createElement("span"),b.appendChild(f),c.appendChild(b));return c};Downsha.Utils.urlSuffix="...";
Downsha.Utils.shortUrl=function(a,b){var c=a;"string"==typeof a&&(0==c.indexOf("file:")?(c=decodeURIComponent(c.replace(/^file:.*\/([^\/]+)$/,"$1")),"number"==typeof b&&!isNaN(b)&&c.length>b&&(c=c.substring(0,b),c+=""+Downsha.Utils.urlSuffix)):(c=c.replace(/^([a-zA-Z]+:\/+)?([^\/]+).*$/,"$2"),"number"==typeof b&&!isNaN(b)&&c.length>b?(c=c.substring(0,b),c+=""+Downsha.Utils.urlSuffix):2<a.substring(a.indexOf(c)+c.length).length&&(c+="/"+Downsha.Utils.urlSuffix)));return c};
Downsha.Utils.shortWord=function(a,b){return a.length<=b?a:a.substring(0,b-3)+Downsha.Utils.urlSuffix};Downsha.Utils.isClipTooBig=function(a){return a>=Downsha.Constants.Limits.CLIP_NOTE_CONTENT_LEN_MAX};Downsha.Utils.alert=function(a,b,c){Components.classes["@mozilla.org/embedcomp/prompt-service;1"].getService(Components.interfaces.nsIPromptService).alert(a,b,c)};Downsha.Utils.generateQuad=function(){return(65536*(1+Math.random())|0).toString(16).substring(1)};
Downsha.Utils.generateGuid=function(){return this.generateQuad()+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+"-"+this.generateQuad()+this.generateQuad()+this.generateQuad()};
Downsha.Utils.getNodeString=function(a){var b=null;if("object"!=typeof a||null==a)b="[null]";else if(a&&a.nodeType==Node.TEXT_NODE)b="string"==typeof a.nodeValue&&0<a.nodeValue.length?a.nodeName+" "+a.nodeValue:a.nodeName+" [empty]";else if(a&&a.nodeType==Node.ELEMENT_NODE){for(var b="<"+a.nodeName,a=a.attributes,c=0;c<a.length;c++)a[c]&&a[c].name&&a[c].specified&&(b=a[c].value?b+(" "+a[c].name+'="'+a[c].value+'"'):b+(" "+a[c].name));b+=">"}else b="node","string"==typeof a.nodeName&&0<a.nodeName.length&&
(b+=" name: "+a.nodeName),"number"==typeof a.nodeType&&(b+=" type: "+a.nodeType),"string"==typeof a.nodeValue&&0<a.nodeValue.length&&(b+=" value: "+a.nodeValue);return b};
Downsha.XORCrypt={DELIMIT:":",LENGTH:128,_padString:function(a){var b=0;if(128>a.length)for(var c=a.length;128>=c;c++)a=String.fromCharCode(this._randomForChar())+a,b++;return b+this.DELIMIT+a},_randomForChar:function(){for(var a=0,b=0;33>a||126<a;)a=parseInt(150*Math.random()),b++;return a},_randomNonZero:function(){for(var a=0;0==(a=parseInt(100*Math.random())););return a},_shiftString:function(a){for(var b=this._randomNonZero()+100,c=[],d=0;d<a.length;d++)c.push(String.fromCharCode(a.charCodeAt(d)+
b));return b+this.DELIMIT+c.join("")},_unshiftString:function(a){var b=parseInt(a.substring(0,a.indexOf(this.DELIMIT))),c=[];if(!isNaN(b))for(var d=(b+"").length+this.DELIMIT.length;d<a.length;d++)c.push(String.fromCharCode(a.charCodeAt(d)-b));return c.join("")},encrypt:function(a,b){for(var b=b+"",c=this._padString(this._shiftString(a+"")),d=[],e=0;e<c.length;e++){for(var f=c.charCodeAt(e),g=0;g<b.length;g++)f^=b.charCodeAt(g);d.push(String.fromCharCode(f+100))}return d.join("")},decrypt:function(a,
b){for(var a=a+"",b=b+"",c=[],d=0;d<a.length;d++){for(var e=a.charCodeAt(d)-100,f=b.length-1;0<=f;f--)e^=b.charCodeAt(f);c.push(String.fromCharCode(e))}c=c.join("");d=parseInt(c.substring(0,c.indexOf(this.DELIMIT)));return!isNaN(d)?this._unshiftString(c.substring((""+d).length+this.DELIMIT.length+d)):""}};
(function(){var a=null;Downsha.Chrome=function(){a=Downsha.Logger.getInstance();this.__defineGetter__("version",this.getVersion);this.__defineSetter__("version",this.setVersion);this.__defineGetter__("extension",this.getExtension);this.__defineSetter__("extension",this.setExtension)};Downsha.Chrome.REQUEST_EVENT_DATA_KEY="chromeRequest";Downsha.Chrome.EXTENSION_ID="web_clipper_firefox@downsha.com";Downsha.Chrome.prototype._version=null;Downsha.Chrome.prototype._extension=null;Downsha.Chrome.prototype.tabs=
null;Downsha.Chrome.prototype.i18n=null;Downsha.Chrome.prototype.setVersion=function(){if(!this._version){var a=this;try{AddonManager.getAddonByID(this.constructor.EXTENSION_ID,function(c){if(c&&c.version&&(c=c.version,"string"==typeof c&&""!=c&&(c=c.split("."))))a._version=281474976710656*parseInt(c[0])+4294967296*parseInt(c[1])+65536*parseInt(c[2])+parseInt(c[3])})}catch(c){}}};Downsha.Chrome.prototype.getVersion=function(){return this._version};Downsha.Chrome.prototype.setExtension=function(b){"undefined"==
typeof b.Downsha&&(b.Downsha={});"undefined"==typeof b.Downsha._extension&&(b.Downsha._extension={});this._extension=b.Downsha._extension;var c=this;this._extension&&(this._extension.onRequest=function(b){a.debug("chrome.extension.onRequest");arguments.callee._listeners.forEach(function(c){try{c(b)}catch(f){a.error("On request for listener failed: "+JSON.stringify(f))}})},this._extension.onRequest._listeners=[],this._extension.onRequest.addListener=function(b){a.debug("chrome.extension.addListener");
c._extension.onRequest._listeners.push(b)},this._extension.onRequest.removeListener=function(a){c._extension.onRequest._listeners.forEach(function(b,c,g){b==a&&g.splice(c,1)})},this._extension.sendRequest=function(b){a.debug("chrome.extension.sendRequest");c._extension.onRequest(b)},this._extension.requestEventHandler=function(a){a&&"undefined"!=typeof a[c.constructor.REQUEST_EVENT_DATA_KEY]&&c._extension.sendRequest(a[c.constructor.REQUEST_EVENT_DATA_KEY])})};Downsha.Chrome.prototype.getExtension=
function(){return this._extension};Downsha.Chrome.prototype.getTabIdForHttpChannel=function(a){try{if(a.notificationCallbacks){var c=a.notificationCallbacks.QueryInterface(Components.interfaces.nsIInterfaceRequestor).getInterface(Components.interfaces.nsIDOMWindow).document,d=gBrowser.getBrowserIndexForDocument(c);if(-1!=d)return gBrowser.tabContainer.childNodes[d].linkedPanel}}catch(e){}return null}})();
(function(){Downsha.Chrome.Tabs=function(){Downsha.Logger.getInstance();this.selected=null};Downsha.Chrome.Tabs.prototype.getSelected=function(a,b){if(void 0!=b)b(this.selected);else return this.selected};Downsha.Chrome.Tabs.prototype.create=function(a){var b=top.document.getElementById("content");b.selectedTab=b.addTab(a.url)};Downsha.Chrome.Tabs.prototype.getSelectedTabId=function(){return window.top.getBrowser().selectedTab.linkedPanel}})();
(function(){var a=null;Downsha.Chrome.I18n=function(){a=Downsha.Logger.getInstance();this.stringBundle=null};Downsha.Chrome.I18n.prototype.getMessage=function(b,c){if(this.stringBundle)try{if("undefined"!=typeof c){var d=[].concat(c);return this.stringBundle.formatStringFromName(b,d,d.length)}return this.stringBundle.GetStringFromName(b)}catch(e){a.error("Failed to get string our of stringbundle: "+e+" for key = "+b);return}return b}})();Downsha.DownshaModel=function(a){this.initialize(a)};
Downsha.mixin(Downsha.DownshaModel,Downsha.DefiningMixin);Downsha.DownshaModel.prototype.initialize=function(a){if(null!=a&&"object"==typeof a)for(var b in a){var c="set"+b.substring(0,1).toUpperCase()+b.substring(1);if("function"==typeof this[c])this[c].apply(this,[a[b]]);else if("undefined"!=typeof this[b])try{this[b]=a[b]}catch(d){}}};
Downsha.DownshaModel.prototype.toStorable=function(a){for(var b={},c=this.getStorableProps(),a="string"==typeof a?a:"",d=0;d<c.length;d++)"undefined"!=typeof this[c[d]]&&null!=this[c[d]]&&(b[a+c[d]]=this[c[d]]);return b};Downsha.DownshaModel.prototype.getStorableProps=function(){var a=[],b;for(b in this)null!=this[b]&&0!=b.indexOf("_")&&"modelName"!=b&&("string"==typeof this[b]||"number"==typeof this[b]||"boolean"==typeof this[b])&&a.push(b);return a};Downsha.DownshaModel.prototype.toJSON=function(){return this.toStorable()};
Downsha.DownshaMime={getMimeId:function(a){return"string"==typeof a&&""!=a&&"undefined"!=typeof Downsha.DownshaMime.TABLE[a]?Downsha.DownshaMime.TABLE[a]:0}};Downsha.DownshaMime.TABLE={"application/dsml":5002,"image/gif":2E3,"image/jpeg":2010,"image/pjpeg":2015,"image/jpg":2016,"image/png":2020,"image/x-png":2022,"image/bmp":2030,"image/x-bmp":2031,"image/icon":2070,"image/x-icon":2071,"image/tiff":2090,"application/x-shockwave-flash":4440};
Downsha.DownshaTerm=function(){this.__defineSetter__("osName",this.setOSName);this.__defineGetter__("osName",this.getOSName);this.__defineSetter__("osVersion",this.setOSVersion);this.__defineGetter__("osVersion",this.getOSVersion);this.__defineSetter__("browserName",this.setBrowserName);this.__defineGetter__("browserName",this.getBrowserName);this.__defineSetter__("browserVersion",this.setBrowserVersion);this.__defineGetter__("browserVersion",this.getBrowserVersion);this.__defineSetter__("browserUserAgent",
this.setBrowserUserAgent);this.__defineGetter__("browserUserAgent",this.getBrowserUserAgent)};Downsha.inherit(Downsha.DownshaTerm,Downsha.DownshaModel);Downsha.DownshaTerm.TERM_CLASS={UNKNOWN:0,PC:1,PLUGIN:2,WEB:3,MOBILE:4,PAD:5,TV:6};Downsha.DownshaTerm.TERM_TYPE={IE:2E4,FIREFOX:21E3,CHROME:22E3,SAFARI:23E3,OPERA:24E3,SE360:25E3,SOGOU:25100,EE360:25200,AOYOU:25300,QQ:25400,LIEBAO:25500};Downsha.DownshaTerm.prototype._osName=null;Downsha.DownshaTerm.prototype._osVersion=null;
Downsha.DownshaTerm.prototype._browserName=null;Downsha.DownshaTerm.prototype._browserVersion=null;Downsha.DownshaTerm.prototype._browserUserAgent=null;Downsha.DownshaTerm.prototype.getOSName=function(){return this._osName};Downsha.DownshaTerm.prototype.setOSName=function(a){this._osName=a};Downsha.DownshaTerm.prototype.getOSVersion=function(){return this._osVersion};Downsha.DownshaTerm.prototype.setOSVersion=function(a){this._osVersion=a};Downsha.DownshaTerm.prototype.getBrowserName=function(){return this._browserName};
Downsha.DownshaTerm.prototype.setBrowserName=function(a){this._browserName=a};Downsha.DownshaTerm.prototype.getBrowserVersion=function(){return this._browserVersion};Downsha.DownshaTerm.prototype.setBrowserVersion=function(a){this._browserVersion=a};Downsha.DownshaTerm.prototype.getBrowserUserAgent=function(){return this._browserUserAgent};Downsha.DownshaTerm.prototype.setBrowserUserAgent=function(a){this._browserUserAgent=a};
Downsha.DownshaFile=function(a){this.__defineSetter__("putState",this.setPutState);this.__defineGetter__("putState",this.getPutState);this.__defineSetter__("data",this.setData);this.__defineGetter__("data",this.getData);this.__defineSetter__("cid",this.setCID);this.__defineGetter__("cid",this.getCID);this.__defineSetter__("cindex",this.setCIndex);this.__defineGetter__("cindex",this.getCIndex);this.__defineSetter__("syncNo",this.setSyncNo);this.__defineGetter__("syncNo",this.getSyncNo);this.__defineSetter__("fid",
this.setFID);this.__defineGetter__("fid",this.getFID);this.__defineSetter__("mid",this.setMID);this.__defineGetter__("mid",this.getMID);this.__defineSetter__("mime",this.setMime);this.__defineGetter__("mime",this.getMime);this.__defineSetter__("dataSize",this.setDataSize);this.__defineGetter__("dataSize",this.getDataSize);this.__defineSetter__("wordCount",this.setWordCount);this.__defineGetter__("wordCount",this.getWordCount);this.__defineSetter__("fileTitle",this.setFileTitle);this.__defineGetter__("fileTitle",
this.getFileTitle);this.__defineSetter__("fileName",this.setFileName);this.__defineGetter__("fileName",this.getFileName);this.__defineSetter__("url",this.setUrl);this.__defineGetter__("url",this.getUrl);this.__defineSetter__("creator",this.setCreator);this.__defineGetter__("creator",this.getCreator);this.__defineSetter__("attachFlag",this.setAttachFlag);this.__defineGetter__("attachFlag",this.getAttachFlag);this.__defineSetter__("width",this.setWidth);this.__defineGetter__("width",this.getWidth);
this.__defineSetter__("height",this.setHeight);this.__defineGetter__("height",this.getHeight);this.__defineSetter__("background",this.setBackground);this.__defineGetter__("background",this.getBackground);this.__defineSetter__("createDate",this.setCreateDate);this.__defineGetter__("createDate",this.getCreateDate);this.__defineSetter__("updateDate",this.setUpdateDate);this.__defineGetter__("updateDate",this.getUpdateDate);this.initialize(a)};Downsha.inherit(Downsha.DownshaFile,Downsha.DownshaModel);
Downsha.DownshaFile.PUT_STATE={NOT_EXIST:0,EXIST:1,PARTIAL:2,FAILED:129};Downsha.DownshaFile.prototype._putState=Downsha.DownshaFile.PUT_STATE.NOT_EXIST;Downsha.DownshaFile.prototype._data=null;Downsha.DownshaFile.prototype._cid=0;Downsha.DownshaFile.prototype._cindex=0;Downsha.DownshaFile.prototype._syncNo=0;Downsha.DownshaFile.prototype._fid="";Downsha.DownshaFile.prototype._mid=0;Downsha.DownshaFile.prototype._mime="";Downsha.DownshaFile.prototype._dataSize=0;
Downsha.DownshaFile.prototype._fileTitle="";Downsha.DownshaFile.prototype._fileName="";Downsha.DownshaFile.prototype._url="";Downsha.DownshaFile.prototype._creator="";Downsha.DownshaFile.prototype._attachFlag=0;Downsha.DownshaFile.prototype._wordCount=0;Downsha.DownshaFile.prototype._width=0;Downsha.DownshaFile.prototype._height=0;Downsha.DownshaFile.prototype._background=0;Downsha.DownshaFile.prototype._createDate=0;Downsha.DownshaFile.prototype._updateDate=0;
Downsha.DownshaFile.prototype.getPutState=function(){return this._putState};Downsha.DownshaFile.prototype.setPutState=function(a){this._putState=a};Downsha.DownshaFile.prototype.getData=function(){return this._data};Downsha.DownshaFile.prototype.setData=function(a){this._data=a};Downsha.DownshaFile.prototype.getCID=function(){return this._cid};Downsha.DownshaFile.prototype.setCID=function(a){this._cid=a};Downsha.DownshaFile.prototype.getCIndex=function(){return this._cindex};
Downsha.DownshaFile.prototype.setCIndex=function(a){this._cindex=a};Downsha.DownshaFile.prototype.getSyncNo=function(){return this._syncNo};Downsha.DownshaFile.prototype.setSyncNo=function(a){this._syncNo=a};Downsha.DownshaFile.prototype.getFID=function(){return this._fid};Downsha.DownshaFile.prototype.setFID=function(a){this._fid=a};Downsha.DownshaFile.prototype.getMID=function(){return this._mid};Downsha.DownshaFile.prototype.setMID=function(a){this._mid=a};
Downsha.DownshaFile.prototype.getMime=function(){return this._mime};Downsha.DownshaFile.prototype.setMime=function(a){this._mime=a};Downsha.DownshaFile.prototype.getDataSize=function(){return this._dataSize};Downsha.DownshaFile.prototype.setDataSize=function(a){this._dataSize=a};Downsha.DownshaFile.prototype.getFileTitle=function(){return this._fileTitle};Downsha.DownshaFile.prototype.setFileTitle=function(a){this._fileTitle=a};Downsha.DownshaFile.prototype.getFileName=function(){return this._fileName};
Downsha.DownshaFile.prototype.setFileName=function(a){this._fileName=a};Downsha.DownshaFile.prototype.getUrl=function(){return this._url};Downsha.DownshaFile.prototype.setUrl=function(a){this._url=a};Downsha.DownshaFile.prototype.getCreator=function(){return this._creator};Downsha.DownshaFile.prototype.setCreator=function(a){this._creator=a};Downsha.DownshaFile.prototype.getAttachFlag=function(){return this._attachFlag};Downsha.DownshaFile.prototype.setAttachFlag=function(a){this._attachFlag=a};
Downsha.DownshaFile.prototype.getWordCount=function(){return this._wordCount};Downsha.DownshaFile.prototype.setWordCount=function(a){a=parseInt(a);isNaN(a)||(this._wordCount=a)};Downsha.DownshaFile.prototype.getWidth=function(){return this._width};Downsha.DownshaFile.prototype.setWidth=function(a){a=parseInt(a);isNaN(a)||(this._width=a)};Downsha.DownshaFile.prototype.getHeight=function(){return this._height};
Downsha.DownshaFile.prototype.setHeight=function(a){a=parseInt(a);isNaN(a)||(this._height=a)};Downsha.DownshaFile.prototype.getBackground=function(){return this._background};Downsha.DownshaFile.prototype.setBackground=function(a){a=parseInt(a);isNaN(a)||(this._background=a)};Downsha.DownshaFile.prototype.getCreateDate=function(){return this._createDate};Downsha.DownshaFile.prototype.setCreateDate=function(a){this._createDate=a};Downsha.DownshaFile.prototype.getUpdateDate=function(){return this._updateDate};
Downsha.DownshaFile.prototype.setUpdateDate=function(a){this._updateDate=a};Downsha.DownshaFile.prototype.getFileAbstract=function(){return{CID:this.cid,CIndex:this.cindex,FID:this.fid,MimeID:this.mid,Mime:this.mime}};
Downsha.DownshaFile.prototype.getFileDesc=function(){return{CID:this.cid,CIndex:this.cindex,FileSyncNo:this.syncNo,FID:this.fid,MimeID:this.mid,Mime:this.mime,FileSize:this.dataSize,WordCount:this.wordCount,FileTitle:this.fileTitle,FileName:this.fileName,SrcURL:this.url,Creator:this.creator,AttachFlag:this.attachFlag,CTime:this.createDate,MTime:this.updateDate,MediaAttr:1,Width:this.width,Height:this.height}};
Downsha.DownshaFile.prototype.getFileData=function(){return{CID:this.cid,CIndex:this.cindex,FID:this.fid,FileData:this.data}};
Downsha.DownshaInfo=function(a){this.__defineGetter__("cid",this.getCID);this.__defineSetter__("cid",this.setCID);this.__defineGetter__("dirId",this.getDirId);this.__defineSetter__("dirId",this.setDirId);this.__defineGetter__("title",this.getTitle);this.__defineSetter__("title",this.setTitle);this.__defineGetter__("content",this.getContent);this.__defineSetter__("content",this.setContent);this.__defineGetter__("author",this.getAuthor);this.__defineSetter__("author",this.setAuthor);this.__defineGetter__("absText",
this.getAbsText);this.__defineSetter__("absText",this.setAbsText);this.__defineGetter__("thumbnail",this.getThumbnail);this.__defineSetter__("thumbnail",this.setThumbnail);this.__defineGetter__("url",this.getUrl);this.__defineSetter__("url",this.setUrl);this.__defineGetter__("srcType",this.getSrcType);this.__defineSetter__("srcType",this.setSrcType);this.__defineGetter__("srcDesc",this.getSrcDesc);this.__defineSetter__("srcDesc",this.setSrcDesc);this.__defineGetter__("shareType",this.getShareType);
this.__defineSetter__("shareType",this.setShareType);this.__defineGetter__("shareDate",this.getShareDate);this.__defineSetter__("shareDate",this.setShareDate);this.__defineGetter__("fileCount",this.getFileCount);this.__defineGetter__("totalSize",this.getTotalSize);this.__defineGetter__("mainFID",this.getMainFID);this.__defineSetter__("mainFID",this.setMainFID);this.__defineGetter__("mainMID",this.getMainMID);this.__defineSetter__("mainMID",this.setMainMID);this.__defineGetter__("mainSize",this.getMainSize);
this.__defineSetter__("mainSize",this.setMainSize);this.__defineGetter__("wordCount",this.getWordCount);this.__defineSetter__("wordCount",this.setWordCount);this.__defineGetter__("createDate",this.getCreateDate);this.__defineSetter__("createDate",this.setCreateDate);this.__defineGetter__("updateDate",this.getUpdateDate);this.__defineSetter__("updateDate",this.setUpdateDate);this.__defineType__("files","Array");this.__defineGetter__("length",this.getLength);this.files=[];this.initialize(a)};
Downsha.inherit(Downsha.DownshaInfo,Downsha.DownshaModel);Downsha.DownshaInfo.SRC_TYPE={ORIGINAL:1E4,WEB_CLIP:10100,LOCAL_FILE:10200};Downsha.DownshaInfo.prototype._cid=0;Downsha.DownshaInfo.prototype._dirId=0;Downsha.DownshaInfo.prototype._title="";Downsha.DownshaInfo.prototype._content="";Downsha.DownshaInfo.prototype._author="";Downsha.DownshaInfo.prototype._absText="";Downsha.DownshaInfo.prototype._thumbnail="";Downsha.DownshaInfo.prototype._url="";Downsha.DownshaInfo.prototype._srcType=0;
Downsha.DownshaInfo.prototype._srcDesc="";Downsha.DownshaInfo.prototype._shareType=0;Downsha.DownshaInfo.prototype._shareDate=0;Downsha.DownshaInfo.prototype._fileCount=0;Downsha.DownshaInfo.prototype._totalSize=0;Downsha.DownshaInfo.prototype._mainFID="";Downsha.DownshaInfo.prototype._mainMID=0;Downsha.DownshaInfo.prototype._mainSize=0;Downsha.DownshaInfo.prototype._wordCount=0;Downsha.DownshaInfo.prototype._createDate=0;Downsha.DownshaInfo.prototype._updateDate=0;
Downsha.DownshaInfo.createUrlNote=function(a,b,c){c=Downsha.Utils.createUrlClipContent(a,b,c);return new Downsha.DownshaInfo({title:a,content:c,url:b})};Downsha.DownshaInfo.prototype.getCID=function(){return null!=this._cid?this._cid:0};Downsha.DownshaInfo.prototype.setCID=function(a){a=parseInt(a);if(!isNaN(a)){this._cid=a;for(var b in this.files)this.files[b].cid=a}};Downsha.DownshaInfo.prototype.getDirId=function(){return null!=this._dirId?this._dirId:0};
Downsha.DownshaInfo.prototype.setDirId=function(a){a=parseInt(a);isNaN(a)||(this._dirId=a)};Downsha.DownshaInfo.prototype.cleanTitle=function(a){return"string"==typeof a?a.replace(/[\n\r\t]+/,"").replace(/^\s+/,"").replace(/\s+$/,""):a};Downsha.DownshaInfo.prototype.getTitle=function(){return this._title};Downsha.DownshaInfo.prototype.setTitle=function(a,b){var c=this.cleanTitle(""+a);if((null==c||0==c.length)&&b)c=this.cleanTitle(""+b);this._title=c};Downsha.DownshaInfo.prototype.getContent=function(){return this._content};
Downsha.DownshaInfo.prototype.setContent=function(a){this._content=a};Downsha.DownshaInfo.prototype.getAuthor=function(){return this._author};Downsha.DownshaInfo.prototype.setAuthor=function(a){this._author=a};Downsha.DownshaInfo.prototype.getAbsText=function(){return this._absText};Downsha.DownshaInfo.prototype.setAbsText=function(a){this._absText=a};Downsha.DownshaInfo.prototype.getThumbnail=function(){return this._thumbnail};
Downsha.DownshaInfo.prototype.setThumbnail=function(a){this._thumbnail=a};Downsha.DownshaInfo.prototype.getUrl=function(){return this._url};Downsha.DownshaInfo.prototype.setUrl=function(a){this._url=a};Downsha.DownshaInfo.prototype.getSrcType=function(){return this._srcType};Downsha.DownshaInfo.prototype.setSrcType=function(a){a=parseInt(a);isNaN(a)||(this._srcType=a)};Downsha.DownshaInfo.prototype.getSrcDesc=function(){return this._srcDesc};
Downsha.DownshaInfo.prototype.setSrcDesc=function(a){this._srcDesc=a};Downsha.DownshaInfo.prototype.getShareType=function(){return this._shareType};Downsha.DownshaInfo.prototype.setShareType=function(a){a=parseInt(a);isNaN(a)||(this._shareType=a)};Downsha.DownshaInfo.prototype.getShareDate=function(){return this._shareDate};Downsha.DownshaInfo.prototype.setShareDate=function(a){a=parseInt(a);isNaN(a)||(this._shareDate=a)};Downsha.DownshaInfo.prototype.getFileCount=function(){return this.files.length};
Downsha.DownshaInfo.prototype.getTotalSize=function(){var a=0,b;for(b in this.files)a+=this.files[b].dataSize;return a};Downsha.DownshaInfo.prototype.getMainFID=function(){return this._mainFID};Downsha.DownshaInfo.prototype.setMainFID=function(a){this._mainFID=a};Downsha.DownshaInfo.prototype.getMainMID=function(){return null!=this._mainMID?this._mainMID:0};Downsha.DownshaInfo.prototype.setMainMID=function(a){a=parseInt(a);isNaN(a)||(this._mainMID=a)};
Downsha.DownshaInfo.prototype.getMainSize=function(){return null!=this._mainSize?this._mainSize:0};Downsha.DownshaInfo.prototype.setMainSize=function(a){a=parseInt(a);isNaN(a)||(this._mainSize=a)};Downsha.DownshaInfo.prototype.getWordCount=function(){return null!=this._wordCount?this._wordCount:0};Downsha.DownshaInfo.prototype.setWordCount=function(a){a=parseInt(a);isNaN(a)||(this._wordCount=a)};Downsha.DownshaInfo.prototype.getCreateDate=function(){return this._createDate};
Downsha.DownshaInfo.prototype.setCreateDate=function(a){a=parseInt(a);isNaN(a)||(this._createDate=a)};Downsha.DownshaInfo.prototype.getUpdateDate=function(){return this._updateDate};Downsha.DownshaInfo.prototype.setUpdateDate=function(a){a=parseInt(a);isNaN(a)||(this._updateDate=a)};Downsha.DownshaInfo.prototype.findFileByFID=function(a){return"string"==typeof a&&""!=a&&"undefined"!=typeof this.files[a]?this.files[a]:null};
Downsha.DownshaInfo.prototype.findFileByURL=function(a){for(var b in this.files)if(this.files[b]&&this.files[b].url==a)return this.files[b];return null};Downsha.DownshaInfo.prototype.addFile=function(a){null!=a&&(a instanceof Downsha.DownshaFile?(this.files[a.fid]=a,this.files.length++):"object"==typeof a&&"undefined"!=typeof a.fid&&(this.files[a.fid]=new Downsha.DownshaFile(a),this.files.length++))};
Downsha.DownshaInfo.prototype.getNextUnputFile=function(){var a=null,b=0,c;for(c in this.files)if(this.files[c]&&this.files[c].putState!=Downsha.DownshaFile.PUT_STATE.EXIST&&(0==b||this.files[c].cindex<b))a=this.files[c],b=this.files[c].cindex;return a};
Downsha.DownshaInfo.prototype.getThumbnailFile=function(){var a=null,b=null,c=0,d=c=c=0,e=c=0,f;for(f in this.files)if(b=this.files[f],c=parseInt(b.cindex),!(isNaN(c)||100>c))if(c=parseInt(b.background),isNaN(c)||0==c)currentMID=parseInt(b.mid),isNaN(currentMID)||2E3>currentMID||(c=parseInt(b.width),isNaN(c)||80>c||(d=parseInt(b.height),isNaN(d)||80>d||300<100*c/d||300<100*d/c||(c*=d,c>e&&(a=b,e=c))));return a};
Downsha.DownshaInfo.prototype.getLength=function(){for(var a=0,b=this.getStorableProps(),c=0;c<b.length;c++)this[b[c]]&&(a+=(""+this[b[c]]).length+b[c].length+1);return a+=b.length-1};Downsha.DownshaInfo.prototype.getStorableProps=function(){return"dirId,title,content,author,absText,thumbnail,url,srcType,srcDesc,shareType,shareDate,fileCount,totalSize,mainFID,mainMID,mainSize,wordCount,createDate,updateDate".split(",")};
Downsha.DownshaInfo.prototype.getInfoItem=function(){return{DirID:this.dirId,Title:this.title,Author:this.author,Abstract:this.absText,InfoIconFID:this.thumbnail,SrcURL:this.url,SrcType:this.srcType,SrcDesc:this.srcDesc,ShareType:this.shareType,ShareTime:this.shareDate,CTime:this.createDate,MTime:this.updateDate,FileListNum:this.fileCount,TotalSize:this.totalSize,MainFID:this.mainFID,MainMimeID:this.mainMID,MainFileSize:this.mainSize,WordCount:this.wordCount}};
Downsha.DownshaInfo.prototype.getFileDesc=function(){var a={FileNum:this.fileCount},b=0;a.FileList=[];for(var c in this.files)a.FileList[b++]=this.files[c].getFileDesc();return a};Downsha.DownshaInfo.prototype.toLOG=function(){return{title:this.title,url:this.url,length:this.length,createDate:this.createDate,updateDate:this.updateDate}};
Downsha.DownshaInfo.prototype.toString=function(){return"Downsha.DownshaInfo ["+this.url+"] "+this.title+"; content length: "+("string"==typeof this.content?this.content.length:0)+")"};
(function(){var a=null;Downsha.Options=function(b,c){a=Downsha.Logger.getInstance();this.__defineGetter__("context",this.getContext);this.__defineSetter__("context",this.setContext);this.__defineGetter__("developerMode",this.isDeveloperMode);this.__defineSetter__("developerMode",this.setDeveloperMode);this.__defineGetter__("debugLevel",this.getDebugLevel);this.__defineSetter__("debugLevel",this.setDebugLevel);this.__defineGetter__("clipStyle",this.getClipStyle);this.__defineSetter__("clipStyle",this.setClipStyle);
this.__defineGetter__("useContextMenu",this.isUseContextMenu);this.__defineSetter__("useContextMenu",this.setUseContextMenu);this.__defineGetter__("debugEnabled",this.isDebugEnabled);this.__defineSetter__("debugEnabled",this.setDebugEnabled);this.__defineGetter__("clipNotificationEnabled",this.isClipNotificationEnabled);this.__defineSetter__("clipNotificationEnabled",this.setClipNotificationEnabled);this.__defineGetter__("clipAction",this.getClipAction);this.__defineSetter__("clipAction",this.setClipAction);
this.initialize(b,c)};Downsha.Options.FULL_PAGE_OPTIONS={NEVER:0,ALWAYS:1,REMEMBER:2};Downsha.Options.CLIP_STYLE_OPTIONS={NONE:0,TEXT:1,FULL:2};Downsha.Options.CLIP_ACTION_OPTIONS={ARTICLE:0,FULL_PAGE:1,URL:2};Downsha.Options.__defineGetter__("DEFAULTS",function(){return{developerMode:!1,debugLevel:Downsha.Logger.LOG_LEVEL_ERROR,clipStyle:Downsha.Options.CLIP_STYLE_OPTIONS.FULL,useContextMenu:!0,debugEnabled:!0,clipNotificationEnabled:!0,clipAction:Downsha.Options.CLIP_ACTION_OPTIONS.ARTICLE}});Downsha.Options.isValidClipStyleOptionValue=
function(a){return Downsha.Options.isValidOptionValue(a,Downsha.Options.CLIP_STYLE_OPTIONS)};Downsha.Options.isValidClipActionOptionValue=function(a){return Downsha.Options.isValidOptionValue(a,Downsha.Options.CLIP_ACTION_OPTIONS)};Downsha.Options.isValidOptionValue=function(a,c){if("object"==typeof c&&null!=c)for(var d in c)if(a==c[d])return!0;return!1};Downsha.Options.prototype._context=null;Downsha.Options.prototype._developerMode=Downsha.Options.DEFAULTS.developerMode;Downsha.Options.prototype._debugLevel=
Downsha.Options.DEFAULTS.debugLevel;Downsha.Options.prototype._clipStyle=Downsha.Options.DEFAULTS.clipStyle;Downsha.Options.prototype._useContextMenu=Downsha.Options.DEFAULTS.useContextMenu;Downsha.Options.prototype._debugEnabled=Downsha.Options.DEFAULTS.debugEnabled;Downsha.Options.prototype._clipNotificationEnabled=Downsha.Options.DEFAULTS.clipNotificationEnabled;Downsha.Options.prototype._clipAction=Downsha.Options.DEFAULTS.clipAction;Downsha.Options.prototype.initialize=function(a,c){a instanceof
Downsha.DownshaContext&&(this.context=a);var d="object"==typeof c&&null!=c?c:Downsha.Options.DEFAULTS,e;for(e in d)"undefined"!=typeof this[e]&&(this[e]=d[e])};Downsha.Options.prototype.setContext=function(a){a instanceof Downsha.DownshaContext?this._context=a:null==a&&(this._context=null)};Downsha.Options.prototype.getContext=function(){return this._context};Downsha.Options.prototype.setDeveloperMode=function(a){this._developerMode=a?!0:!1};Downsha.Options.prototype.isDeveloperMode=function(){return this._developerMode};
Downsha.Options.prototype.setDebugLevel=function(a){"number"==typeof a?this._debugLevel=a:"string"==typeof a?this._debugLevel=parseInt(a):null==a&&(this._debugLevel=0)};Downsha.Options.prototype.getDebugLevel=function(){return this._debugLevel};Downsha.Options.prototype.setClipStyle=function(a){Downsha.Options.isValidClipStyleOptionValue(a)?this._clipStyle=a:null==a&&(this._clipStyle=Downsha.Options.DEFAULTS.clipStyle)};Downsha.Options.prototype.getClipStyle=function(){return this._clipStyle};Downsha.Options.prototype.isUseContextMenu=
function(){return this._useContextMenu};Downsha.Options.prototype.setUseContextMenu=function(a){this._useContextMenu=a?!0:!1};Downsha.Options.prototype.isDebugEnabled=function(){return this._debugEnabled};Downsha.Options.prototype.setDebugEnabled=function(a){this._debugEnabled=a?!0:!1};Downsha.Options.prototype.isClipNotificationEnabled=function(){return this._clipNotificationEnabled};Downsha.Options.prototype.setClipNotificationEnabled=function(a){this._clipNotificationEnabled=a?!0:!1};Downsha.Options.prototype.getClipAction=
function(){return this._clipAction};Downsha.Options.prototype.setClipAction=function(a){Downsha.Options.isValidClipActionOptionValue(a)?this._clipAction=a:null==a&&(this._clipAction=Downsha.Options.DEFAULTS.clipAction)};Downsha.Options.prototype.apply=function(){a.level=this.debugLevel;Downsha.Logger.setLevel(this.debugLevel);this.context&&this.context.setOptions(this)};Downsha.Options.prototype.reset=function(){this.initialize(this.context,null)};Downsha.Options.prototype.toJSON=function(){return{debugLevel:this.debugLevel,
developerMode:this.developerMode,clipStyle:this.clipStyle,useContextMenu:this.useContextMenu,debugEnabled:this.debugEnabled,clipNotificationEnabled:this.clipNotificationEnabled,clipAction:this.clipAction}}})();
(function(){Downsha.getContext=function(){null==Downsha._context&&(Downsha._context=new Downsha.DownshaContext);return Downsha._context};Downsha.__defineGetter__("context",Downsha.getContext);Downsha.DownshaContext=function(){Downsha.Logger.getInstance();this.__defineGetter__("userId",this.getUserId);this.__defineSetter__("userId",this.setUserId);this.__defineGetter__("userName",this.getUserName);this.__defineSetter__("userName",this.setUserName);this.__defineGetter__("userPass",this.getUserPass);
this.__defineSetter__("userPass",this.setUserPass);this.__defineGetter__("sessTime",this.getSessTime);this.__defineSetter__("sessTime",this.setSessTime);this.__defineGetter__("sessId",this.getSessId);this.__defineSetter__("sessId",this.setSessId);this.__defineGetter__("hardId",this.getHardId);this.__defineSetter__("hardId",this.setHardId);this.__defineGetter__("termId",this.getTermId);this.__defineSetter__("termId",this.setTermId);this.__defineGetter__("termClass",this.getTermClass);this.__defineSetter__("termClass",
this.setTermClass);this.__defineGetter__("termType",this.getTermType);this.__defineSetter__("termType",this.setTermType);this.__defineGetter__("version",this.getVersion);this.__defineSetter__("version",this.setVersion);this.__defineGetter__("remote",this.getRemote);this.__defineSetter__("remote",this.setRemote);this.__defineGetter__("store",this.getStore);this.__defineSetter__("store",this.setStore);this.__defineGetter__("serviceProto",this.getServiceProto);this.__defineSetter__("serviceProto",this.setServiceProto);
this.__defineGetter__("serviceDomain",this.getServiceDomain);this.__defineSetter__("serviceDomain",this.setServiceDomain);this.__defineGetter__("extensionId",this.getExtensionId);this.__defineGetter__("extensionPath",this.getExtensionPath);this.__defineGetter__("options",this.getOptions);this.__defineSetter__("options",this.setOptions);this.__defineGetter__("logLevel",this.getLogLevel);this.__defineGetter__("locale",this.getLocale);this.__defineGetter__("userKnown",this.isUserKnown);this.__defineGetter__("rememberedSession",
this.isRememberedSession);this.__defineSetter__("rememberedSession",this.setRememberedSession);this.initialize()};Downsha.DownshaContext.HOME_PATH="http://www.downsha.com/";Downsha.DownshaContext.DESKTOP_PATH="http://www.downsha.com/version/YunZhaiSetup.exe";Downsha.DownshaContext.MOBILE_PATH="http://www.downsha.com/version/yunzhai_android.apk";Downsha.DownshaContext.WINDOWS8_PATH="http://apps.microsoft.com/webpdp/zh-CN/app/a6605203-4a28-46ec-8e79-abb872475d20";Downsha.DownshaContext.CHROME_PATH=
"https://chrome.google.com/webstore/detail/%E5%BD%93%E4%B8%8B%E4%BA%91%E6%91%98/fjfgeonblbdcofcokojamlcnomcdliap";Downsha.DownshaContext.FIREFOX_PATH="https://addons.mozilla.org/zh-CN/firefox/addon/yunzhai/";Downsha.DownshaContext.SERVICE_PROTO="http://";Downsha.DownshaContext.SERVICE_DOMAIN="ysync.downsha.com";Downsha.DownshaContext.YUNZHAI_PATH="/yunzhai.so";Downsha.DownshaContext.VIEW_PATH="/view";Downsha.DownshaContext.SESS_ID="0";Downsha.DownshaContext.USER_ID=0;Downsha.DownshaContext.TERM_ID=
0;Downsha.DownshaContext.DEFAULT_LOCALE="default";Downsha.DownshaContext.LOCAL_STORE_FILENAME="downsha_webclipper.sqlite";Downsha.DownshaContext.prototype._userId=null;Downsha.DownshaContext.prototype._userName=null;Downsha.DownshaContext.prototype._userPass=null;Downsha.DownshaContext.prototype._sessTime=null;Downsha.DownshaContext.prototype._sessId=null;Downsha.DownshaContext.prototype._hardId=null;Downsha.DownshaContext.prototype._termId=null;Downsha.DownshaContext.prototype._termClass=null;Downsha.DownshaContext.prototype._termType=
null;Downsha.DownshaContext.prototype._version=null;Downsha.DownshaContext.prototype._store=null;Downsha.DownshaContext.prototype._serviceProto=null;Downsha.DownshaContext.prototype._serviceDomain=null;Downsha.DownshaContext.prototype._options=null;Downsha.DownshaContext.prototype._locale=null;Downsha.DownshaContext.prototype._rememberedSession=!0;Downsha.DownshaContext.prototype._remote=null;Downsha.DownshaContext.prototype._extensionId=null;Downsha.DownshaContext.prototype.RELEASED=!0;Downsha.DownshaContext.prototype.initialize=
function(){};Downsha.DownshaContext.prototype.destroy=function(){};Downsha.DownshaContext.prototype.setServiceProto=function(a){var b=!1;"string"==typeof a&&this._serviceProto!=a?(this._serviceProto=a,b=!0):null==a&&null!=this._serviceProto&&(this._serviceProto=null,b=!0);b&&this.store&&this.store.put("serviceProto",this._serviceProto)};Downsha.DownshaContext.prototype.getServiceProto=function(){null==this._serviceProto&&this.store&&(this._serviceProto=this.store.get("serviceProto"));return null!=
this._serviceProto?this._serviceProto:Downsha.DownshaContext.SERVICE_PROTO};Downsha.DownshaContext.prototype.setServiceDomain=function(a){var b=!1;"string"==typeof a&&this._serviceDomain!=a?(this._serviceDomain=a,b=!0):null==a&&null!=this._serviceDomain&&(this._serviceDomain=null,b=!0);b&&this.store&&this.store.put("serviceDomain",this._serviceDomain)};Downsha.DownshaContext.prototype.getServiceDomain=function(){null==this._serviceDomain&&this.store&&(this._serviceDomain=this.store.get("serviceDomain"));
return null!=this._serviceDomain?this._serviceDomain:Downsha.DownshaContext.SERVICE_DOMAIN};Downsha.DownshaContext.prototype.getServiceUrl=function(){return this.serviceProto+this.serviceDomain};Downsha.DownshaContext.prototype.getHomeUrl=function(){return Downsha.DownshaContext.HOME_PATH};Downsha.DownshaContext.prototype.getDesktopUrl=function(){return Downsha.DownshaContext.DESKTOP_PATH};Downsha.DownshaContext.prototype.getMobileUrl=function(){return Downsha.DownshaContext.MOBILE_PATH};Downsha.DownshaContext.prototype.getWindows8Url=
function(){return Downsha.DownshaContext.WINDOWS8_PATH};Downsha.DownshaContext.prototype.getChromeUrl=function(){return Downsha.DownshaContext.CHROME_PATH};Downsha.DownshaContext.prototype.getFirefoxUrl=function(){return Downsha.DownshaContext.FIREFOX_PATH};Downsha.DownshaContext.prototype.getNoteListUrl=function(){return this.getServiceUrl()+Downsha.DownshaContext.VIEW_PATH+"?uid="+this.userId+"&border=0&perpage=3&topbar=0&bottombar=1&bartype=1"};Downsha.DownshaContext.prototype.getYunzhaiUrl=function(a){return"undefined"!=
typeof a?this.getServiceUrl()+Downsha.DownshaContext.YUNZHAI_PATH+"?cmdid="+a:this.getServiceUrl()+Downsha.DownshaContext.YUNZHAI_PATH};Downsha.DownshaContext.prototype.getLocale=function(){return navigator.language};Downsha.DownshaContext.prototype.isUserKnown=function(){return(this.userId||this.userName)&&this.userPass?!0:!1};Downsha.DownshaContext.prototype.getExtensionId=function(){if(null==this._extensionId){var a=Downsha.chrome.extension.getBackgroundPage().location.href;a&&(a=a.replace(/^chrome-extension:\/\/([^\/]+).*$/,
"$1"),null!=a&&"undefined"!=typeof a&&(this._extensionId=a))}return this._extensionId};Downsha.DownshaContext.prototype.getExtensionPath=function(){return"chrome-extension://"+this.extensionId+"/"};Downsha.DownshaContext.prototype.isExtensionReleased=function(){return this.RELEASED};Downsha.DownshaContext.prototype.setRemote=function(a){a instanceof Downsha.DownshaRemoteEx&&(this._remote=a)};Downsha.DownshaContext.prototype.getRemote=function(){this._remote||(this._remote=new Downsha.DownshaRemoteEx);
return this._remote};Downsha.DownshaContext.prototype.setStore=function(a){a instanceof Downsha.LocalStore?this._store=a:null==a&&(this._store=null)};Downsha.DownshaContext.prototype.getStore=function(){this._store||(this._store=this.getLocalStoreInstance());return this._store};Downsha.DownshaContext.prototype.getLocalStoreInstance=function(){try{var a=Components.classes["@mozilla.org/file/directory_service;1"].getService(Components.interfaces.nsIProperties).get("ProfD",Components.interfaces.nsIFile);
a.append(Downsha.DownshaContext.LOCAL_STORE_FILENAME);var b=Components.classes["@mozilla.org/storage/service;1"].getService(Components.interfaces.mozIStorageService).openDatabase(a);return new Downsha.LocalStore(null,new Downsha.LocalStore.SQLITE_IMPL(b))}catch(c){}return null};Downsha.DownshaContext.prototype.resetUser=function(){this.sessId=this.sessTime=this.userPass=this.userName=this.userId=null};Downsha.DownshaContext.prototype.getUserId=function(){if(null==this._userId&&null!=this.store){var a=
parseInt(this.store.get("userId"));isNaN(a)||(this._userId=a)}return null!=this._userId?this._userId:Downsha.DownshaContext.USER_ID};Downsha.DownshaContext.prototype.setUserId=function(a){null!=a?(a=parseInt(a),isNaN(a)||(this._userId=a,null!=this.store&&this.store.put("userId",this._userId))):(this._userId=null,null!=this.store&&this.store.remove("userId"))};Downsha.DownshaContext.prototype.getUserName=function(){null==this._userName&&null!=this.store&&(this._userName=this.store.get("userName"));
return this._userName};Downsha.DownshaContext.prototype.setUserName=function(a){null!=a?(this._userName=a,null!=this.store&&this.store.put("userName",this._userName)):(this._userName=null,null!=this.store&&this.store.remove("userName"))};Downsha.DownshaContext.prototype.getUserPass=function(){null==this._userPass&&null!=this.store&&(this._userPass=this.store.get("userPass"));return this._userPass};Downsha.DownshaContext.prototype.setUserPass=function(a){null!=a?(this._userPass=a,null!=this.store&&
this.store.put("userPass",this._userPass)):(this._userPass=null,null!=this.store&&this.store.remove("userPass"))};Downsha.DownshaContext.prototype.getSessId=function(){null==this._sessId&&null!=this.store&&(this._sessId=this.store.get("sessId"));return null!=this._sessId?this._sessId:Downsha.DownshaContext.SESS_ID};Downsha.DownshaContext.prototype.setSessId=function(a){null!=a?(this._sessId=a,null!=this.store&&this.store.put("sessId",this._sessId)):(this._sessId=null,null!=this.store&&this.store.remove("sessId"))};
Downsha.DownshaContext.prototype.getSessTime=function(){if(null==this._sessTime&&null!=this.store){var a=parseInt(this.store.get("sessTime"));isNaN(a)||(this._sessTime=a)}return this._sessTime};Downsha.DownshaContext.prototype.setSessTime=function(a){null!=a?(a=parseInt(a),isNaN(a)||(this._sessTime=a,null!=this.store&&this.store.put("sessTime",this._sessTime))):(this._sessTime=null,null!=this.store&&this.store.remove("sessTime"))};Downsha.DownshaContext.prototype.generateHardId=function(){for(var a=
"",b=0;32>b;b++)var c=Math.floor(16*Math.random()),c=10>c?c+48:c+55,a=a+String.fromCharCode(c);return a};Downsha.DownshaContext.prototype.getHardId=function(){null==this._hardId&&null!=this.store&&(this._hardId=this.store.get("hardId"));null==this._hardId&&(this.hardId=this.generateHardId());return this._hardId};Downsha.DownshaContext.prototype.setHardId=function(a){null!=a?(this._hardId=a,null!=this.store&&this.store.put("hardId",this._hardId)):(this._hardId=null,null!=this.store&&this.store.remove("hardId"))};
Downsha.DownshaContext.prototype.getTermId=function(){if(null==this._termId&&null!=this.store){var a=parseInt(this.store.get("termId"));isNaN(a)||(this._termId=a)}return null!=this._termId?this._termId:Downsha.DownshaContext.TERM_ID};Downsha.DownshaContext.prototype.setTermId=function(a){null!=a?(a=parseInt(a),isNaN(a)||(this._termId=a,null!=this.store&&this.store.put("termId",this._termId))):(this._termId=null,null!=this.store&&this.store.remove("termId"))};Downsha.DownshaContext.prototype.getTermClass=
function(){null==this._termClass&&(this._termClass=Downsha.DownshaTerm.TERM_CLASS.PLUGIN);return this._termClass};Downsha.DownshaContext.prototype.setTermClass=function(a){this._termClass=a};Downsha.DownshaContext.prototype.getTermType=function(){null==this._termType&&(this._termType=Downsha.DownshaTerm.TERM_TYPE.FIREFOX);return this._termType};Downsha.DownshaContext.prototype.setTermType=function(a){this._termType=a};Downsha.DownshaContext.prototype.getVersion=function(){null==this._version&&(this._version=
Downsha.chrome.version);return this._version};Downsha.DownshaContext.prototype.setVersion=function(a){this._version=a};Downsha.DownshaContext.prototype.isRememberedSession=function(){null!=this.store&&(this._rememberedSession=this.store.get("rememberedSession")?!0:!1);return this._rememberedSession};Downsha.DownshaContext.prototype.setRememberedSession=function(a){this._rememberedSession=a?!0:!1;null!=this.store&&this.store.put("rememberedSession",this._rememberedSession)};Downsha.DownshaContext.prototype.setOptions=
function(a){var b=!1;a instanceof Downsha.Options?(this._options=a,b=!0):null==a&&(this._options=null,b=!0);b&&this.store&&(this.options?this.store.put("options",this._options):this.store.remove("options"))};Downsha.DownshaContext.prototype.getOptions=function(a){if(this.store&&(null==this._options||a))if(a=this.store.get("options"))this._options=new Downsha.Options(this,a);null==this._options&&(this._options=new Downsha.Options(this,{serviceProto:this.serviceProto,serviceDomain:this.serviceDomain}));
return this._options};Downsha.DownshaContext.prototype.getLogLevel=function(){return this.options.debugLevel};Downsha.DownshaContext.prototype.getPreferredStylingStrategyName=function(){var a=this.getOptions(!0),b=null;a&&a.clipStyle==Downsha.Options.CLIP_STYLE_OPTIONS.TEXT?b="ClipTextStylingStrategy":a&&a.clipStyle==Downsha.Options.CLIP_STYLE_OPTIONS.FULL&&(b="ClipFullStylingStrategy");return b};Downsha.DownshaContext.prototype.getPreferredStylingStrategyQualifier=function(){var a=this.getPreferredStylingStrategyName();
return a?"Downsha."+a:"null"};Downsha.DownshaContext.prototype.getCookie=function(a,b,c,d,e){for(var f=this,g=Components.classes["@mozilla.org/cookiemanager;1"].getService(Ci.nsICookieManager).enumerator;g.hasMoreElements();){var h=g.getNext().QueryInterface(Ci.nsICookie);if(h.name==a){b(h);return}}"object"==typeof Downsha.chrome&&null!=Downsha.chrome&&Downsha.chrome.cookies?(g={url:this.getSecureServiceUrl(),name:a},d?(g.storeId=d,Downsha.chrome.cookies.get(g,function(d){"object"==typeof d&&null!=
d&&d.value?b(d):e instanceof Array&&0<e.length?(d=e.pop(),f.getCookie(a,b,c,d.id,e)):c()})):Downsha.chrome.cookies.getAllCookieStores(function(d){if(d instanceof Array&&0<d.length){var e=d.pop();f.getCookie(a,b,c,e.id,d)}else c()})):"function"==typeof c&&setTimeout(c,0)}})();
(function(){var a=null;Downsha.ViewManager=function(){a=Downsha.Logger.getInstance();this.__defineGetter__("containerResizeCallback",this.getContainerResizeCallback);this.__defineSetter__("containerResizeCallback",this.setContainerResizeCallback);this.__defineGetter__("globalMessage",this.getGlobalMessage);this.__defineSetter__("globalMessage",this.setGlobalMessage);this.__defineGetter__("globalErrorMessage",this.getGlobalErrorMessage);this.__defineSetter__("globalErrorMessage",this.setGlobalErrorMessage);
this.__defineGetter__("quiet",this.getQuiet)};Downsha.ViewManager._instance=null;Downsha.ViewManager.FORM_FIELD_ERROR_CLASS="error";Downsha.ViewManager.FORM_FIELD_ERROR_MESSAGE_CLASS="error";Downsha.ViewManager.FORM_FIELD_ERROR_MESSAGE_ELEMENT="div";Downsha.ViewManager.CONTAINER_MIN_SIZE=38;Downsha.ViewManager.getInstance=function(){this._instance||(this._instance=new Downsha.ViewManager);return this._instance};Downsha.ViewManager.prototype._containerResizeCallback=null;Downsha.ViewManager.prototype._globalMessage=
null;Downsha.ViewManager.prototype._globalErrorMessage=null;Downsha.ViewManager.prototype._quiet=!1;Downsha.ViewManager.prototype._animateContainerResizing=!0;Downsha.ViewManager.prototype._currentView=null;Downsha.ViewManager.prototype.getContainerResizeCallback=function(){return this._containerResizeCallback};Downsha.ViewManager.prototype.setContainerResizeCallback=function(a){"function"==typeof a&&(this._containerResizeCallback=a)};Downsha.ViewManager.prototype.getGlobalMessage=function(){return this._globalMessage};
Downsha.ViewManager.prototype.setGlobalMessage=function(a){this._globalMessage=a};Downsha.ViewManager.prototype.getGlobalErrorMessage=function(){return this._globalErrorMessage};Downsha.ViewManager.prototype.setGlobalErrorMessage=function(a){this._globalErrorMessage=a};Downsha.ViewManager.prototype.getQuiet=function(){return this._quiet};Downsha.ViewManager.prototype.getEffectiveHeight=function(){a.debug("ViewManager.getEffectiveHeight");var b=0;$("body > div").each(function(a,c){var f=$(c);"none"!=
f.css("display")&&!f.hasClass("banner")&&!f.hasClass("drawer")&&!f.hasClass("drawerHandleTitle")&&(b+=f.innerHeight())});var c=$("#spinner");c&&"none"!=c.css("display")&&(b+=c.height());this.globalErrorMessage&&"none"!=this.globalErrorMessage.container.css("display")&&(b+=this.globalErrorMessage.container.height()+18);b<this.constructor.CONTAINER_MIN_SIZE&&(b=this.constructor.CONTAINER_MIN_SIZE);return b};Downsha.ViewManager.prototype.getWindowHeight=function(){a.debug("ViewManager.getWindowHeight");
var b=0;$("body > div").each(function(a,c){var f=$(c);"none"!=f.css("display")&&!f.hasClass("banner")&&!f.hasClass("drawer")&&!f.hasClass("drawerHandleTitle")&&(b="none"!=f.css("float")?Math.max(b,f.innerHeight()):b+f.innerHeight())});var c=$("#spinner");c&&"none"!=c.css("display")&&(b+=c.height());this.globalErrorMessage&&"none"!=this.globalErrorMessage.container.css("display")&&(b+=this.globalErrorMessage.container.height());b<this.constructor.CONTAINER_MIN_SIZE&&(b=this.constructor.CONTAINER_MIN_SIZE);
return b};Downsha.ViewManager.prototype.updateBodyHeight=function(a){a="number"==typeof a?a:this.getEffectiveHeight();this._animateContainerResizing?$("body").animate({height:a+"px"},10):$("body").css({height:a+"px"});"function"==typeof this._containerResizeCallback&&this._containerResizeCallback(a)};Downsha.ViewManager.prototype.showBlock=function(a,c){a.show();c instanceof Array?a.trigger("show",c):a.trigger("show");this.updateBodyHeight()};Downsha.ViewManager.prototype.hideBlock=function(a,c){a.hide();
c instanceof Array?a.trigger("hide",c):a.trigger("hide");this.updateBodyHeight()};Downsha.ViewManager.prototype.showView=function(a,c){var d=a instanceof jQuery?a:$("#"+a);if(0==d.length)return null;this.showBlock(d,[c]);return this._currentView=d};Downsha.ViewManager.prototype.hideView=function(a){a=a instanceof jQuery?a:$("#"+a);if(0==a.length||"none"==a.css("display"))return null;this.hideBlock(a);this._currentView&&a.attr("id")==this._currentView.attr("id")&&(this._currentView=null);return a};
Downsha.ViewManager.prototype.switchView=function(b,c){a.debug("ViewManager.switchView");var d=b instanceof jQuery?b:$("#"+b);if(this._currentView&&this._currentView.attr("id")==d.attr("id"))a.debug("Already showing...");else return this._currentView&&this.hideView(this._currentView.attr("id")),this.showView(b,c)};Downsha.ViewManager.prototype.switchElements=function(a,c){a.hide();c.show()};Downsha.ViewManager.prototype.wait=function(a){var c=$("#spinner");c.find("#spinnerMessage").text(a);c.show();
this.updateBodyHeight()};Downsha.ViewManager.prototype.clearWait=function(){$("#spinner").hide();this.updateBodyHeight()};Downsha.ViewManager.prototype.showMessage=function(a){this.globalMessage&&(this.globalMessage.addMessage(a),this.globalMessage.show())};Downsha.ViewManager.prototype.hideMessage=function(a){this.globalMessage&&(this.globalMessage.removeMessage(a),0<this.globalMessage.length()?this.globalMessage.show():this.globalMessage.hide())};Downsha.ViewManager.prototype.hideAllMessages=function(){this.globalMessage&&
(this.globalMessage.removeAllMessages(),this.globalMessage.hide())};Downsha.ViewManager.prototype.extractErrorMessage=function(b,c){a.debug("ViewManager.extractErrorMessage");var d="undefined"!=typeof c?c:null;a.debug("Error: "+b);b instanceof Downsha.DownshaError&&"number"==typeof b.errorCode&&"string"==typeof b.parameter&&this.getLocalizedMessage("DSTPError_"+(0>b.errorCode?-b.errorCode:b.errorCode)+"_"+b.parameter.replace(/[^a-zA-Z0-9_]+/g,"_"))?(a.debug("Got parameterized localized message for Downsha.DownshaError"),
d=this.getLocalizedMessage("DSTPError_"+(0>b.errorCode?-b.errorCode:b.errorCode)+"_"+b.parameter.replace(/[^a-zA-Z0-9_]+/g,"_"))):b instanceof Downsha.DSTPResponseException&&"number"==typeof b.errorCode&&this.getLocalizedMessage("DSTPResponseError_"+(0>b.errorCode?-b.errorCode:b.errorCode))?(a.debug("Got localized message for Downsha.DSTPResponseException"),d="string"==typeof b.parameter?this.getLocalizedMessage("DSTPResponseError_"+(0>b.errorCode?-b.errorCode:b.errorCode),b.parameter):this.getLocalizedMessage("DSTPResponseError_"+
(0>b.errorCode?-b.errorCode:b.errorCode))):b instanceof Downsha.DownshaError&&"number"==typeof b.errorCode&&this.getLocalizedMessage("DSTPError_"+(0>b.errorCode?-b.errorCode:b.errorCode))?(a.debug("Got localized message for Downsha.DownshaError"),d="string"==typeof b.parameter?this.getLocalizedMessage("DSTPError_"+(0>b.errorCode?-b.errorCode:b.errorCode),b.parameter):this.getLocalizedMessage("DSTPError_"+(0>b.errorCode?-b.errorCode:b.errorCode))):b instanceof Downsha.DownshaError&&"string"==typeof b.message?
(a.debug("Resorting to message included in the error"),d=b.message):(b instanceof Error||b instanceof Error)&&"string"==typeof b.message?(a.debug("Resorting to standard message"),d=b.message):"string"==typeof b&&(a.debug("Error is a string, so using that..."),d=b);return d};Downsha.ViewManager.prototype.showError=function(b){a.debug("ViewManager.showError");b=this.extractErrorMessage(b,this.getLocalizedMessage("UnknownError"));null!=b&&(this.globalErrorMessage.message=b,this.globalErrorMessage.show(),
this.updateBodyHeight())};Downsha.ViewManager.prototype.showErrors=function(b){a.debug("ViewManager.showErrors");if(!this.quiet){var c=b instanceof Array?b:[b];if(1==c.length)this.showError(c[0]);else{for(var d=this.getLocalizedMessage("multipleErrorsTitle"),e=$("<ul>"),f=0;f<c.length;f++){var g=this.extractErrorMessage(b[f]);null!=g&&e.append($("<li>",{text:g}))}0<e.children().length&&(b=$("<div>",{className:"multiErrorTitle"}),b.append(d),b.append(e),this.globalErrorMessage.message=b,this.globalErrorMessage.show());
this.updateBodyHeight()}}};Downsha.ViewManager.prototype.hideError=function(){this.globalErrorMessage.hide();this.updateBodyHeight()};Downsha.ViewManager.prototype.hideErrors=function(){this.globalErrorMessage.hide();this.updateBodyHeight()};Downsha.ViewManager.prototype.showHttpError=function(b,c,d){a.debug("ViewManager.showHttpError");this.showError(Error(this.getLocalizedHttpErrorMessage(b,c,d)))};Downsha.ViewManager.prototype.getLocalizedHttpErrorMessage=function(b,c,d){a.debug("ViewManager.getLocalizedHttpErrorMessage");
return 4==b.readyState?this.getLocalizedMessage("Error_HTTP_Transport",[""+b.status,"string"==typeof d?d:""]):this.getLocalizedMessage("Error_HTTP_Transport",["readyState: "+b.readyState,""])};Downsha.ViewManager.prototype.getLocalizedMessage=function(a,c){return"undefined"!=typeof Downsha.chrome&&"function"==typeof Downsha.chrome.i18n.getMessage?Downsha.chrome.i18n.getMessage(a,c):a};Downsha.ViewManager.prototype.showFormErrors=function(b,c,d){a.debug("ViewManager.showFormErrors("+typeof b+", "+
typeof c+")");if(!this.quiet){for(var b=b instanceof jQuery?b:$(b),e=0;e<c.length;e++){var f=c[e],g=this.extractErrorMessage(f);a.debug(f.toString()+" => "+g);if("function"==typeof d)d("string"==typeof f.parameter?f.parameter:null,g);else{var h=null;"string"==typeof f.parameter&&null!=g&&(h=b.find("[name="+f.parameter+"]"),0==h.length&&(h=null));h?this.showFormFieldErrors(h,g):this.showError(g)}}this.updateBodyHeight()}};Downsha.ViewManager.prototype.showFormFieldErrors=function(b,c){a.debug("ViewManager.showFormFieldError("+
b+", "+c+")");this.quiet||"undefined"==typeof b||(b instanceof jQuery||(b=$(b)),b.hasClass(this.constructor.FORM_FIELD_ERROR_CLASS)||b.addClass(this.constructor.FORM_FIELD_ERROR_CLASS),0==b.next("."+this.constructor.FORM_FIELD_ERROR_MESSAGE_CLASS).length?b.after($("<"+this.constructor.FORM_FIELD_ERROR_MESSAGE_ELEMENT+" class='"+this.constructor.FORM_FIELD_ERROR_MESSAGE_CLASS+"'>"+c+"</"+this.constructor.FORM_FIELD_ERROR_MESSAGE_ELEMENT+">")):b.next("."+this.constructor.FORM_FIELD_ERROR_MESSAGE_CLASS).text(c))};
Downsha.ViewManager.prototype.clearFormArtifacts=function(b){a.debug("ViewManager.clearFormArtifacts");"undefined"!=typeof b&&(b instanceof jQuery||(b=$(b)),a.debug("Removing error messages..."),b.find("."+this.constructor.FORM_FIELD_ERROR_MESSAGE_CLASS).remove(),a.debug("Removing error classes from fields"),b.find("."+this.constructor.FORM_FIELD_ERROR_CLASS).removeClass(this.constructor.FORM_FIELD_ERROR_CLASS),this.updateBodyHeight())}})();
(function(){Downsha.ViewManager.SimpleMessage=function(a){Downsha.Logger.getInstance();this.initialize(a)};Downsha.ViewManager.SimpleMessage.MESSAGE_CLASS="simpleMessage";Downsha.ViewManager.SimpleMessage.prototype._container=null;Downsha.ViewManager.SimpleMessage.prototype._message=null;Downsha.ViewManager.SimpleMessage.prototype.initialize=function(a){this.__defineGetter__("container",this.getContainer);this.__defineGetter__("message",this.getMessage);this.__defineSetter__("message",this.setMessage);
"undefined"!=typeof a&&a&&(this._container=a instanceof jQuery?a:$(a))};Downsha.ViewManager.SimpleMessage.prototype.getContainer=function(){return this._container};Downsha.ViewManager.SimpleMessage.prototype.setMessage=function(a){this._message=a};Downsha.ViewManager.SimpleMessage.prototype.getMessage=function(){return this._message};Downsha.ViewManager.SimpleMessage.prototype.show=function(){if(this.message){var a=this.createMessageBlock();"string"==typeof this.message?a.text(this.message):this.message instanceof
jQuery&&a.append(this.message);this._container.empty();this._container.append(a)}else this._container.empty();this._container.show()};Downsha.ViewManager.SimpleMessage.prototype.hide=function(){this._container.hide()};Downsha.ViewManager.SimpleMessage.prototype.createMessageBlock=function(){return $("<div>",{className:this.getMessageClass()})};Downsha.ViewManager.SimpleMessage.prototype.getMessageClass=function(){return this.constructor.MESSAGE_CLASS}})();
(function(){Downsha.ViewManager.StackableMessage=function(a){Downsha.Logger.getInstance();this.initialize(a)};Downsha.inherit(Downsha.ViewManager.StackableMessage,Downsha.ViewManager.SimpleMessage);Downsha.ViewManager.StackableMessage.MESSAGE_CLASS="stackableMessage";Downsha.ViewManager.StackableMessage.prototype._messageStack=[];Downsha.ViewManager.StackableMessage.prototype.initialize=function(a){this.parent.initialize.apply(this,arguments)};Downsha.ViewManager.StackableMessage.prototype.getMessage=
function(){return 0<this._messageStack.length?this._messageStack[this._messageStack.length-1]:null};Downsha.ViewManager.StackableMessage.prototype.setMessage=function(a){this._messageStack=[];this.addMessage(a)};Downsha.ViewManager.StackableMessage.prototype.addMessage=function(a){this._messageStack.push(this._describeMessage(a))};Downsha.ViewManager.StackableMessage.prototype.removeMessage=function(a){for(var a=this._describeMessage(a),b=this._messageStack.length-1;0<=b;b--)if(this._messageStack[b]==
a){this._messageStack.splice(b,1);break}};Downsha.ViewManager.StackableMessage.prototype.removeAllMessages=function(){this._messageStack=[]};Downsha.ViewManager.StackableMessage.prototype.length=function(){return this._messageStack.length};Downsha.ViewManager.StackableMessage.prototype._describeMessage=function(a){var b="";"string"==typeof a?b=a:a instanceof jQuery&&a.each(function(a,d){b+=this._describeMessage(d)});return b};Downsha.ViewManager.StackableMessage.prototype.getMessageClass=function(){return this.parent.getMessageClass()+
" "+this.constructor.MESSAGE_CLASS}})();
