(function(){function a(){var a=null,e=0,e=(new Date).getTime(),a=setInterval(function(){"undefined"!=typeof window.overlay?(clearInterval(a),a=null,c=new Downsha.ChromeNotification,c.notify()):e+3E3<(new Date).getTime()&&(b.warn("Clearing init timer, cuz we timed out waiting for overlay"),clearInterval(a),a=null)},100)}var b=null,c=null;$(document).ready(function(){b=Downsha.Logger.getInstance();window.onerror=function(a,c,f){b.exception("\n"+c+":"+f+": "+a+"\n")};a();b.debug("-------- NOTIFICATION STARTING ------------")})})();
(function(){var a=null;Downsha.ChromeNotification=function(){a=Downsha.Logger.getInstance();this.initialize()};Downsha.ChromeNotification.DEFAULT_CLOSE_TIMEOUT=6E3;Downsha.ChromeNotification.prototype._successIconElement=null;Downsha.ChromeNotification.prototype._errorIconElement=null;Downsha.ChromeNotification.prototype.initialize=function(){a.debug("ChromeNotification initializing...");this.initViewManager();this.initOverlay();this.initChrome();this.initBindings();a.debug("ChromeNotification initialized")};
Downsha.ChromeNotification.prototype.initViewManager=function(){a.debug("ChromeNotification.initViewManager");this.viewManager=Downsha.ViewManager.getInstance();this.viewManager.globalErrorMessage=new Downsha.ViewManager.SimpleMessage($("#globalErrorMessage"));this.viewManager.globalMessage=new Downsha.ViewManager.StackableMessage($("#globalMessage"))};Downsha.ChromeNotification.prototype.initOverlay=function(){a.debug("ChromeNotification.initOverlay");this.overlay="undefined"!=typeof window.overlay?
window.overlay:null;var b=this;window.overlayContentContainer&&(a.debug(">>> Adding callback for view resizing..."),this.viewManager.containerResizeCallback=function(c){a.debug("Updating iframe's height to: "+c);var d=window.overlay.document.getElementById("popupContent");d&&(d.style.height=c+2+"px");window.sizeToContent();window.overlay.sizeToContent();b.manager.onNotificationSizeUpdate()})};Downsha.ChromeNotification.prototype.initChrome=function(){a.debug("ChromeNotification.initChrome");try{Downsha.chrome=
this.overlay.arguments[0].chrome,this.queueProcessor=this.overlay.arguments[0].QueueProcesor,this.infoItem=this.overlay.arguments[1].infoItem,this.guid=this.overlay.arguments[1].guid,this.isSuccess=this.overlay.arguments[1].isSuccess,this.manager=this.overlay.arguments[2]}catch(b){a.error("Could not intialize chrome: "+b)}};Downsha.ChromeNotification.prototype.initBindings=function(){a.debug("ChromeNotification.initBindings");var b=this;$("#close-image").click(function(){b.close()})};Downsha.ChromeNotification.prototype.notify=
function(){a.debug("ChromeNotification.notify");$(".title").text(Downsha.chrome.i18n.getMessage("BrowserActionTitle"));this.infoItem&&(this.isSuccess?this.showClipSuccess(this.infoItem):this.showClipError(this.infoItem))};Downsha.ChromeNotification.prototype.showClipSuccess=function(b){a.debug("ChromeNotification.showClipSuccess");this.clear();this.showSuccessIcon();this.setHeadline(Downsha.chrome.i18n.getMessage("desktopNotification_clipUploaded",[b&&b.title?b.title:""]));this.setDetails(Downsha.chrome.i18n.getMessage("desktopNotification_clipUploadedMessage"));
this.viewManager.updateBodyHeight(this.viewManager.getWindowHeight());var c=this;setTimeout(function(){c.close()},this.constructor.DEFAULT_CLOSE_TIMEOUT)};Downsha.ChromeNotification.prototype.showClipError=function(b){a.debug("ChromeNotification.showError");this.clear();this.showErrorIcon();this.setHeadline(Downsha.chrome.i18n.getMessage("desktopNotification_unableToSaveClip",[b&&b.title?b.title:""]));this.setDetails(Downsha.chrome.i18n.getMessage("desktopNotification_unableToSaveClipUnknownMessage"));
this.viewManager.updateBodyHeight(this.viewManager.getWindowHeight())};Downsha.ChromeNotification.prototype.clear=function(){this.getNotificationHeadline().empty();this.getNotificationDetails().empty()};Downsha.ChromeNotification.prototype.setHeadline=function(a){this.getNotificationHeadline().text(a)};Downsha.ChromeNotification.prototype.setDetails=function(a){this.getNotificationDetails().text(a)};Downsha.ChromeNotification.prototype.showSuccessIcon=function(){this.getErrorIcon().hide();this.getSuccessIcon().show()};
Downsha.ChromeNotification.prototype.showErrorIcon=function(){this.getSuccessIcon().hide();this.getErrorIcon().show()};Downsha.ChromeNotification.prototype.getNotificationHeadline=function(){return $("#notificationHeadline")};Downsha.ChromeNotification.prototype.getNotificationDetails=function(){return $("#notificationDetails")};Downsha.ChromeNotification.prototype.getSuccessIcon=function(){return $("#successIcon")};Downsha.ChromeNotification.prototype.getErrorIcon=function(){return $("#errorIcon")};
Downsha.ChromeNotification.prototype.close=function(){try{this.manager.onClose()}catch(b){a.debug("Failed to send onclose to manager "+b)}finally{window.close()}}})();
