function initDownshaButton(){var c=document.getElementById("nav-bar");if(c){var a=c.getAttribute(c.hasAttribute("currentset")?"currentset":"defaultset");if(a&&!(0<=a.indexOf("downsha-button"))){document.getElementById("downsha-button")||c.insertItem("downsha-button",null,null,!1);a=a.replace(",downsha-button","");a+=",downsha-button";c.setAttribute("currentset",a);c.currentSet=a;document.persist(c.id,"currentset");try{BrowserToolboxCustomizeDone(!0)}catch(b){}}}}
window.addEventListener("load",initDownshaButton,!1);
(function(){var c=null;Downsha.getOverlay=function(){null==Downsha._overlay&&(Downsha._overlay=new Downsha.Overlay);return Downsha._overlay};Downsha.__defineGetter__("overlay",Downsha.getOverlay);Downsha.Overlay=function(){c=Downsha.Logger.getInstance()};Downsha.Overlay.DEFAULT_POPUP_WIDTH=446;Downsha.Overlay.SEND_DELAY_TIME=10;Downsha.Overlay.prototype.popupDialog=null;Downsha.Overlay.prototype.stringBundle=null;Downsha.Overlay.prototype.rootElement=null;Downsha.Overlay.prototype.rightClick=!1;Downsha.Overlay.prototype.clip=
null;Downsha.Overlay.prototype.initChrome=function(){c.debug("Overlay.initChrome");Downsha.chrome||(Downsha.chrome=new Downsha.Chrome,Downsha.chrome.tabs=new Downsha.Chrome.Tabs,Downsha.chrome.i18n=new Downsha.Chrome.I18n);if(Downsha.chrome&&(Downsha.chrome.setVersion(),Downsha.chrome.extension=window,Downsha.chrome.tabs.selected=content,null==this.stringBundle&&(this.stringBundle=document.getElementById("downsha_i18n")),this.stringBundle))Downsha.chrome.i18n.stringBundle=this.stringBundle.stringBundle};
Downsha.Overlay.prototype.startUp=function(a,b){c.debug("Overlay.startUp");this.rootElement=a;this.rightClick=b;this.initChrome();Downsha.queueProcessor.start();var d=null,e=Downsha.getContext().getOptions(!0);e&&e.clipStyle==Downsha.Options.CLIP_STYLE_OPTIONS.FULL?(c.debug("Overlay.startUp Styling Strategy: FULL"),d=Downsha.ClipFullStylingStrategy):e&&e.clipStyle==Downsha.Options.CLIP_STYLE_OPTIONS.TEXT&&(c.debug("Overlay.startUp Styling Strategy: TEXT"),d=Downsha.ClipTextStylingStrategy);this.clip=
new Downsha.Clip(content,d);c.debug("Overlay.startUp Instantiated clip: "+this.clip);this.openPopup({clip:this.clip})};Downsha.Overlay.prototype.openPopup=function(a){var b=this.getPopupPosition(),a={downsha:Downsha,data:a,clipNotifier:this,sh:null};c.debug("Overlay.openPopup at left: "+b.left+", top: "+b.top);this.popupDialog=window.openDialog("chrome://downsha/content/popup.xul","","chrome,titlebar=no,left="+b.left+",top="+b.top+",resizable=no",a)};Downsha.Overlay.prototype.getPopupPosition=function(){var a=
0,b=0,b=window.document.getElementById("downsha-button");if(!b||0==b.boxObject.width){var a=window.screenX+window.innerWidth-this.constructor.DEFAULT_POPUP_WIDTH,b=window.screenY,d=window.document.getElementById("navigator-toolbox");d&&(b=d.boxObject.screenY+d.boxObject.height)}else a=b.boxObject.screenX+b.boxObject.width-this.constructor.DEFAULT_POPUP_WIDTH,0>a&&(a=b.boxObject.screenX),b=b.boxObject.screenY+b.boxObject.height;return{left:a,top:b}};Downsha.Overlay.prototype.startClip=function(a){var b=
this.clip,d=Downsha.Utils.generateGuid(),e=null==b.content?0:b.content.length;c.debug("Clip content length "+e);if(Downsha.Utils.isClipTooBig(b.length,e))this.onFailedClip();else setTimeout(function(){a.content=b.content;Downsha.clipStorer.saveNote(d,a);Downsha.queueProcessor.addTask(d,function(){Downsha.clipHandler.send(d)})},this.constructor.SEND_DELAY_TIME)};Downsha.Overlay.prototype.onFailedClip=function(){var a=this.clip,b=Downsha.Utils.generateGuid();Downsha.queueProcessor.addTask(b,function(){if(Downsha.Utils.isClipTooBig(a.length,
null==a.content?0:a.content.length))Downsha.Utils.alert(content,Downsha.chrome.i18n.getMessage("BrowserActionTitle"),Downsha.chrome.i18n.getMessage("quickNote_fullPageClipTooBig")),Downsha.queueProcessor.onCancel(b)})};Downsha.Overlay.prototype.onLogout=function(){Downsha.toolbarManager.clearBadge();Downsha.context.resetUser();Downsha.context.destroy()}})();
(function(){Downsha.CacheManager=function(c){this.__defineGetter__("impl",this.getImplementation);this.__defineSetter__("impl",this.setImplementation);this.initialize(c)};Downsha.CacheManager.prototype._impl=null;Downsha.CacheManager.prototype.initialize=function(c){if("undefined"==typeof c&&"object"==typeof navigator&&null!=navigator){var a=Downsha.CacheManagerImplFactory.getImplementationFor(navigator);a&&(c=new a)}this.setImplementation(c)};Downsha.CacheManager.prototype.setImplementation=function(c){c instanceof
Downsha.CacheManagerImpl?this._impl=c:null==c&&(this._impl=null)};Downsha.CacheManager.prototype.getImplementation=function(){return this._impl};Downsha.CacheManager.prototype.startCache=function(){return this._impl.startCache()};Downsha.CacheManager.prototype.isComplete=function(){return this._impl.isComplete()};Downsha.CacheManager.prototype.getCaches=function(){return this._impl.getCaches()};Downsha.CacheManager.prototype.getCache=function(c){return this._impl.getCache(c)};Downsha.CacheManager.prototype.addCaches=
function(c,a,b){return this._impl.addCaches(c,a,b)};Downsha.CacheManager.prototype.addCache=function(c,a,b){return this._impl.addCache(c,a,b)};Downsha.CacheManagerImplFactory={getImplementationFor:function(c){for(var a=Downsha.CacheManagerImpl.ClassRegistry,b=0;b<a.length;b++)if("function"==typeof a[b]&&"function"==typeof a[b].isResponsibleFor&&a[b].isResponsibleFor(c))return a[b];return null}};Downsha.CacheManagerImpl=function(){};Downsha.CacheManagerImpl.ClassRegistry=[];Downsha.CacheManagerImpl.handleInheritance=
function(c){Downsha.CacheManagerImpl.ClassRegistry.push(c)};Downsha.CacheManagerImpl.isResponsibleFor=function(){return!1};Downsha.CacheManagerImpl.prototype.startCache=function(){throw Error("Must subclass Downsha.CacheManagerImpl.startCache");};Downsha.CacheManagerImpl.prototype.isComplete=function(){throw Error("Must subclass Downsha.CacheManagerImpl.isComplete");};Downsha.CacheManagerImpl.prototype.getCaches=function(){throw Error("Must subclass Downsha.CacheManagerImpl.getCaches");};Downsha.CacheManagerImpl.prototype.getCache=
function(){throw Error("Must subclass Downsha.CacheManagerImpl.getCache");};Downsha.CacheManagerImpl.prototype.addCaches=function(){throw Error("Must subclass Downsha.CacheManagerImpl.addCache");};Downsha.CacheManagerImpl.prototype.addCache=function(){throw Error("Must subclass Downsha.CacheManagerImpl.addCache");};Downsha.Cache=function(c){this.initialize(c)};Downsha.Cache.CACHE_STATUS_LOADING=0;Downsha.Cache.CACHE_STATUS_SUCCESS=1;Downsha.Cache.CACHE_STATUS_ERROR=2;Downsha.Cache.MIME_TRANSLATIONS=
{jpg:"image/jpeg",jpeg:"image/jpeg",gif:"image/gif",png:"image/png",tif:"image/tiff",tiff:"image/tiff",wbmp:"image/vnd.wap.wbmp",ico:"image/x-icon",jng:"image/x-jng",bmp:"image/x-ms-bmp",svg:"image/svg+xml",swf:"application/x-shockwave-flash"};Downsha.Cache.guessTypeByUrl=function(c){if(c&&c.url&&0!=c.url.length){var a=c.url.lastIndexOf(".");0>a||(a=c.url.substr(a+1),"string"!=typeof a||0==a.length||(a=a.toLowerCase(),"undefined"!=typeof Downsha.Cache.MIME_TRANSLATIONS[a]&&(c.type=Downsha.Cache.MIME_TRANSLATIONS[a])))}};
Downsha.Cache.prototype.url=null;Downsha.Cache.prototype.status=Downsha.Cache.CACHE_STATUS_LOADING;Downsha.Cache.prototype.type=null;Downsha.Cache.prototype.encoding=null;Downsha.Cache.prototype.data=null;Downsha.Cache.prototype.background=null;Downsha.Cache.prototype.initialize=function(c){if("object"==typeof c&&null!=c)for(var a in this)"function"!=typeof this[a]&&"undefined"!=typeof c[a]&&(this[a]=c[a])}})();
(function(){var c=null;Downsha.FirefoxCacheManagerImpl=function(){c=Downsha.Logger.getInstance();this.__defineGetter__("cacheService",this.getCacheService);this.initialize()};Downsha.inherit(Downsha.FirefoxCacheManagerImpl,Downsha.CacheManagerImpl,!0);Downsha.FirefoxCacheManagerImpl.isResponsibleFor=function(a){return 0<=a.userAgent.toLowerCase().indexOf("firefox")};Downsha.FirefoxCacheManagerImpl.prototype.CACHE_XHR_TIMEOUT=3E3;Downsha.FirefoxCacheManagerImpl.prototype._caches=[];Downsha.FirefoxCacheManagerImpl.prototype._useCacheService=
!0;Downsha.FirefoxCacheManagerImpl.prototype._cacheService=null;Downsha.FirefoxCacheManagerImpl.prototype._clientID="HTTP";Downsha.FirefoxCacheManagerImpl.prototype._storagePolicy=Components.interfaces.nsICache.STORE_ANYWHERE;Downsha.FirefoxCacheManagerImpl.prototype._streamBased=Components.interfaces.nsICache.STREAM_BASED;Downsha.FirefoxCacheManagerImpl.prototype._accessRequested=Components.interfaces.nsICache.ACCESS_READ;Downsha.FirefoxCacheManagerImpl.prototype._blockingMode=Components.interfaces.nsICache.NON_BLOCKING;
Downsha.FirefoxCacheManagerImpl.prototype.initialize=function(){};Downsha.FirefoxCacheManagerImpl.prototype.startCache=function(){c.debug("startCache");this._caches=[];this._useCacheService&&(Downsha.platform.isLinux()?this._useCacheService=!1:this.cacheService||(this._useCacheService=!1))};Downsha.FirefoxCacheManagerImpl.prototype.isComplete=function(){var a=0,b=0,d=0,e;for(e in this._caches)this._caches[e].status==Downsha.Cache.CACHE_STATUS_LOADING?a++:this._caches[e].status==Downsha.Cache.CACHE_STATUS_SUCCESS?
b++:this._caches[e].status==Downsha.Cache.CACHE_STATUS_ERROR&&d++;c.debug("isComplete cache total: "+this._caches.length+", loading: "+a+", success: "+b+", error: "+d);return 0<a?!1:!0};Downsha.FirefoxCacheManagerImpl.prototype.getCaches=function(){var a=[],b;for(b in this._caches)this._caches[b].status==Downsha.Cache.CACHE_STATUS_SUCCESS&&this._caches[b].data&&0<this._caches[b].data.length&&a.push(this._caches[b]);return a};Downsha.FirefoxCacheManagerImpl.prototype.getCache=function(a){for(var b in this._caches)if(this._caches[b]&&
this._caches[b].url==a){if(this._caches[b].status==Downsha.Cache.CACHE_STATUS_SUCCESS&&this._caches[b].data&&0<this._caches[b].data.length)return this._caches[b];break}return null};Downsha.FirefoxCacheManagerImpl.prototype.addCaches=function(a,b,d){if(a instanceof Array){var a=[].concat(a),c;for(c in a)this.addCache(a[c].url,a[c].background,b,d)}else"string"==typeof a&&this.addCache(a,0,b,d)};Downsha.FirefoxCacheManagerImpl.prototype.addCache=function(a,b,d,e){var f=this,h=function(a){c.debug("addCache ok for url: "+
a.url+", data length: "+a.data.length);if("string"!=typeof a.type||0==a.type.length)Downsha.Cache.guessTypeByUrl(a),c.debug("guessTypeByUrl url: "+a.url+", type: "+a.type);a.status=Downsha.Cache.CACHE_STATUS_SUCCESS;"function"==typeof d&&d(a)},g=function(a){c.debug("addCache error for url: "+a.url);a.status=Downsha.Cache.CACHE_STATUS_ERROR;"function"==typeof e&&e(a)};if(!("string"!=typeof a||0==a.length)){for(var j in f._caches)if(f._caches[j]&&f._caches[j].url==a){c.debug("addCache already exists, url: "+
a);return}var i=new Downsha.Cache({url:a,background:b,status:Downsha.Cache.CACHE_STATUS_LOADING});f._caches.push(i);setTimeout(function(){f._useCacheService&&f.getCacheByCacheService(i)?h(i):f.getCacheByXHR(i,h,g)},1)}};Downsha.FirefoxCacheManagerImpl.prototype.getCacheByXHR=function(a,b,d){var e={url:a.url,type:"GET",async:!0,cache:!0,timeout:this.CACHE_XHR_TIMEOUT,mimeType:"text/plain; charset=x-user-defined",success:function(e,h,g){if(4==g.readyState&&200==g.status&&0<e.length){c.debug("cache ajax ok, url: "+
a.url+", data length: "+e.length);a.data=[];a.data.length=e.length;for(h=0;h<a.data.length;h++)a.data[h]=e.charCodeAt(h)&255;a.type=g.getResponseHeader("Content-Type");if(null!=a.type&&(e=a.type.indexOf(";"),0<e&&(a.type=a.type.substring(0,e)),0<=a.type.indexOf("text/plain")))a.type=null;a.encoding=g.getResponseHeader("Content-Encoding");null!=a.encoding&&(g=a.encoding.indexOf(";"),0<g&&(a.encoding=a.encoding.substring(0,g)));"function"==typeof b&&b(a)}else c.error("cache ajax error, url: "+a.url+
", readyState: "+g.readyState+", status: "+g.status+", data length: "+e.length),"function"==typeof d&&d(a)},error:function(b,e,g){c.error("cache ajax error, url: "+a.url+", readyState: "+b.readyState+", status: "+b.status+", error: "+(g?g:"unknown"));"function"==typeof d&&d(a)}};c.debug("cache ajax sending, url: "+a.url);Downsha.getjQuery().ajax(e)};Downsha.FirefoxCacheManagerImpl.prototype.getCacheService=function(){null==this._cacheService&&(this._cacheService=Components.classes["@mozilla.org/network/cache-service;1"].getService(Components.interfaces.nsICacheService));
return this._cacheService};Downsha.FirefoxCacheManagerImpl.prototype.openCacheEntry=function(a){try{var b=this.cacheService.createSession(this._clientID,this._storagePolicy,this._streamBased);if("object"!=typeof b||null==b)return null;b.doomEntriesIfExpired=!1;return b.openCacheEntry(a,this._accessRequested,this._blockingMode)}catch(d){return c.warn("exception occurred when creating cache session."),null}};Downsha.FirefoxCacheManagerImpl.prototype.getCacheByCacheService=function(a){var b=this.openCacheEntry(a.url);
if("object"!=typeof b||null==b)return!1;try{var d="",e="",f=b.getMetaDataElement("response-head");if("string"==typeof f&&0<f.length&&(d=f.indexOf("Content-Type: "),0<d&&(e=f.indexOf("\n",d+14),a.type=f.substring(d+14,e-1),e=a.type.indexOf(";"),0<e&&(a.type=a.type.substring(0,e))),d=f.indexOf("Content-Encoding: "),0<d))e=f.indexOf("\n",d+18),a.encoding=f.substring(d+18,e-1),e=a.encoding.indexOf(";"),0<e&&(a.encoding=a.encoding.substring(0,e))}catch(h){c.warn("exception occurred when getting content-type and content-encoding.")}try{var g=
b.openInputStream(0);if("string"==typeof a.encoding&&0<a.encoding.length){var j=Components.classes["@mozilla.org/streamConverters;1"].getService(Components.interfaces.nsIStreamConverterService).asyncConvertData(a.encoding,"uncompressed",new Downsha.StreamListener(a),null);j.onStartRequest(null,null);j.onDataAvailable(null,null,g,0,g.available());j.onStopRequest(null,null,null)}else{var i=Components.classes["@mozilla.org/binaryinputstream;1"].createInstance(Components.interfaces.nsIBinaryInputStream);
i.setInputStream(g);a.data=i.readByteArray(i.available());i.close()}}catch(k){return c.warn("exception occurred when getting content-data."),b.close(),!1}b.close();b="undefined"!=typeof a.data&&null!=a.data?a.data.length:0;c.debug("get cache url: "+a.url+", type: "+(a.type?a.type:"unknown")+", encoding: "+(a.encoding?a.encoding:"unknown")+", size: "+b);return 0>=b?!1:!0};Downsha.StreamListener=function(a){this._cache=a;this._cache.data=""};Downsha.StreamListener.prototype.onStartRequest=function(){};
Downsha.StreamListener.prototype.onStopRequest=function(){};Downsha.StreamListener.prototype.onDataAvailable=function(a,b,d){a=Components.classes["@mozilla.org/binaryinputstream;1"].createInstance(Components.interfaces.nsIBinaryInputStream);a.setInputStream(d);this._cache.data+=a.readBytes(a.available());a.close()}})();
(function(){var c=null;Downsha.ClipConverter=function(){c=Downsha.Logger.getInstance();this.__defineGetter__("dsInfo",this.getDsInfo);this.__defineSetter__("dsInfo",this.setDsInfo);this.__defineGetter__("cacheManager",this.getCacheManager);this.__definePositiveInteger__("state",0);this.initialize()};Downsha.mixin(Downsha.ClipConverter,Downsha.DefiningMixin);Downsha.ClipConverter.CACHE_CHECK_INTERVAL=300;Downsha.ClipConverter.CACHE_CHECK_TIMEOUT=3E3;Downsha.ClipConverter.STATE={INIT:0,EXTRACTING_CACHE:1,
CONVERTING_HTML:2,SUCCESS:3,ERROR:4};Downsha.ClipConverter.prototype._dsInfo=null;Downsha.ClipConverter.prototype._cacheManager=null;Downsha.ClipConverter.prototype.onConvertSuccess=null;Downsha.ClipConverter.prototype.onConvertError=null;Downsha.ClipConverter.prototype.initialize=function(){this.state=Downsha.ClipConverter.STATE.INIT;this.urlPattern="(https?://[-a-z0-9]+(?:\\.[-a-z0-9]+)*\\.[-a-z0-9]+(?::[0-9]+)?(?:/[-a-z0-9_:\\@&?=+,.!/~*%\\$]*)?)";this.foreImagePattern="<\\s*img((?:\"[^\"]*\"|'[^']*'|[^'\">])*)\\s+src\\s*=\\s*['\"]?\\s*"+
this.urlPattern+"\\s*['\"]?";this.backImagePattern="background(?:-image)?\\s*:\\s*url\\s*\\(\\s*(?:\\\\)?['\"]?\\s*"+this.urlPattern+"\\s*(?:\\\\)?['\"]?\\s*\\)"};Downsha.ClipConverter.prototype.startUp=function(a,b,d){this.dsInfo=a;this.onConvertSuccess=function(){c.debug("ClipConverter successfully converted");"function"==typeof b&&b.apply(this,arguments)};this.onConvertError=function(){c.error("ClipConverter failed to convert");"function"==typeof d&&d.apply(this,arguments)};this.extractCache()};
Downsha.ClipConverter.prototype.getDsInfo=function(){return this._dsInfo};Downsha.ClipConverter.prototype.setDsInfo=function(a){this._dsInfo=null!=a?a instanceof Downsha.DownshaInfo?a:"object"==typeof a?new Downsha.DownshaInfo(a):new Downsha.DownshaInfo:new Downsha.DownshaInfo};Downsha.ClipConverter.prototype.getCacheManager=function(){this._cacheManager||(this._cacheManager=new Downsha.CacheManager);return this._cacheManager};Downsha.ClipConverter.prototype.getMimeFromData=function(a,b){var d=[];
d.length=24;if(!a||24>b)return null;if(255==a[0]&&216==a[1]){for(var c=0;24>c;c++)d[c]=a[c];if(255==d[2]&&224==d[3]&&74==d[6]&&70==d[7]&&73==d[8]&&70==d[9]||255==d[2]&&225==d[3]&&69==d[6]&&120==d[7]&&105==d[8]&&102==d[9])for(var f=2;255==d[2]&&!(192==d[3]||193==d[3]||194==d[3]||195==d[3]||201==d[3]||202==d[3]||203==d[3]);){f+=2+(d[4]<<8)+d[5];if(f+12>b)break;for(c=0;12>c;c++)d[2+c]=a[f+c]}return 255!=d[2]?null:"image/jpeg"}return 71==a[0]&&73==a[1]&&70==a[2]?"image/gif":137==a[0]&&80==a[1]&&78==a[2]&&
71==a[3]&&13==a[4]&&10==a[5]&&26==a[6]&&10==a[7]&&73==a[12]&&72==a[13]&&68==a[14]&&82==a[15]?"image/png":null};Downsha.ClipConverter.prototype.getDimensionFromData=function(a,b){var d=[];d.length=24;if(!a||24>b)return null;if(255==a[0]&&216==a[1]){for(var c=0;24>c;c++)d[c]=a[c];if(255==d[2]&&224==d[3]&&74==d[6]&&70==d[7]&&73==d[8]&&70==d[9]||255==d[2]&&225==d[3]&&69==d[6]&&120==d[7]&&105==d[8]&&102==d[9])for(var f=2;255==d[2]&&!(192==d[3]||193==d[3]||194==d[3]||195==d[3]||201==d[3]||202==d[3]||203==
d[3]);){f+=2+(d[4]<<8)+d[5];if(f+12>b)break;for(c=0;12>c;c++)d[2+c]=a[f+c]}return 255!=d[2]?null:{width:(d[9]<<8)+d[10],height:(d[7]<<8)+d[8]}}return 71==a[0]&&73==a[1]&&70==a[2]?{width:a[6]+(a[7]<<8),height:a[8]+(a[9]<<8)}:137==a[0]&&80==a[1]&&78==a[2]&&71==a[3]&&13==a[4]&&10==a[5]&&26==a[6]&&10==a[7]&&73==a[12]&&72==a[13]&&68==a[14]&&82==a[15]?{width:(a[16]<<24)+(a[17]<<16)+(a[18]<<8)+(a[19]<<0),height:(a[20]<<24)+(a[21]<<16)+(a[22]<<8)+(a[23]<<0)}:null};Downsha.ClipConverter.prototype.extractCache=
function(){for(var a=this,b=[],d=0,e=0,f=0,f=function(a,e){var f=!1,g;for(g in b)if(b[g].url==a){f=!0;break}f?d++:(c.debug("add cache url: "+a),b.push({url:a,background:e}))},e=(new Date).getTime(),h=null,g=RegExp(this.foreImagePattern,"ig");null!=(h=g.exec(this.dsInfo.content));)f(h[2],0);h=null;for(g=RegExp(this.backImagePattern,"ig");null!=(h=g.exec(this.dsInfo.content));)f(h[1],1);f=(new Date).getTime();c.debug("RegExp search in "+(f-e)+" milliseconds, unique url: "+b.length+", repeated count: "+
d);if(0<b.length){a.cacheManager.startCache();a.cacheManager.addCaches(b);var j=(new Date).getTime(),i=setInterval(function(){if(a.cacheManager.isComplete()||j+a.constructor.CACHE_CHECK_TIMEOUT<(new Date).getTime()){clearInterval(i);i=null;var b=a.cacheManager.getCaches(),d;for(d in b)if(null==b[d].data||0==b[d].data.length)c.debug("cache "+d+" data invalid");else{var e=0,f=b[d].type;f&&(e=Downsha.DownshaMime.getMimeId(f));if(0==e&&((f=a.getMimeFromData(b[d].data,b[d].data.length))&&(e=Downsha.DownshaMime.getMimeId(f)),
0==e)){c.debug("cache "+d+" mime invalid");continue}var g=b[d].data.length,h=faultylabs.MD5(b[d].data);b[d].data.length=g;"string"!=typeof h||""==h?c.debug("cache "+d+" md5 error"):a.dsInfo.findFileByFID(h)?c.debug("cache "+d+" file already exist"):(g=parseInt(Date.now()/1E3),e=new Downsha.DownshaFile({fid:h,data:b[d].data,dataSize:b[d].data.length,mime:f,mid:e,background:b[d].background,url:b[d].url,createDate:g,updateDate:g}),0<e.mid&&(f=a.getDimensionFromData(e.data,e.dataSize),null!=f&&(e.width=
f.width,e.height=f.height)),c.debug("add file md5: "+e.fid+", size: "+e.dataSize+", mime: "+e.mime+", width: "+e.width+", height: "+e.height+", url: "+e.url),a.dsInfo.addFile(e))}return a.convertHtmlToDsml()}},a.constructor.CACHE_CHECK_INTERVAL)}else return a.convertHtmlToDsml()};Downsha.ClipConverter.prototype.convertUnicodeStringToUtf8Bytes=function(a){for(var b=[],d=0,c=0;c<a.length;++c)d=a.charCodeAt(c),128>d?b.push(d):2048>d?(b.push(d>>>6|192),b.push(d&63|128)):65536>d?(b.push(d>>>12|224),b.push(d>>
6&63|128),b.push(d&63|128)):2097152>d&&(b.push(d>>>18|240),b.push(d>>12&63|128),b.push(d>>6&63|128),b.push(d&63|128));return b};Downsha.ClipConverter.prototype.convertHtmlToDsml=function(){var a=this;if(""==this.dsInfo.content||0==this.dsInfo.content.length)c.debug("content empty");else{var b=this.dsInfo.content.replace(RegExp("<(?:\"[^\"]*\"|'[^']*'|[^'\">])*>","ig")," "),b=b.replace(RegExp("&#(\\d{1,5});","ig"),function(a,b){return String.fromCharCode(parseInt(b))}),b=b.replace(RegExp("\\s+","ig"),
" ");this.dsInfo.wordCount=b.length;this.dsInfo.absText=b.substr(0,512);b=(new Date).getTime();this.dsInfo.content=this.dsInfo.content.replace(RegExp(this.foreImagePattern,"ig"),function(b,d,c){return"string"==typeof c&&""!=c&&(c=a.dsInfo.findFileByURL(c),null!=c)?"<ds-file"+d+' hash="'+c.fid+'" type="'+c.mime+'"':b});this.dsInfo.content=this.dsInfo.content.replace(RegExp(this.backImagePattern,"ig"),function(b,d){if("string"==typeof d&&""!=d){var c=a.dsInfo.findFileByURL(d);if(null!=c)return"background-image:url("+
c.fid+")"}return b});var d=(new Date).getTime();c.debug("RegExp replace in "+(d-b)+" milliseconds");this.dsInfo.content='<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE ds-info SYSTEM "http://xml.yunzhai.cn/dsml.dtd"><ds-info>'+this.dsInfo.content+"</ds-info>";var b=this.convertUnicodeStringToUtf8Bytes(this.dsInfo.content),d=b.length,e=faultylabs.MD5(b);b.length=d;if("string"!=typeof e||""==e)c.debug("content md5 error");else{var f=parseInt(Date.now()/1E3);this.dsInfo.mainFID=e;this.dsInfo.mainMID=
Downsha.DownshaMime.getMimeId("application/dsml");this.dsInfo.mainSize=d;this.dsInfo.srcType=Downsha.DownshaInfo.SRC_TYPE.WEB_CLIP;this.dsInfo.srcDesc=navigator.userAgent;this.dsInfo.shareType=1;this.dsInfo.shareDate=f;this.dsInfo.createDate=f;this.dsInfo.updateDate=f;b=new Downsha.DownshaFile({cindex:1,fid:e,data:b,dataSize:d,mid:this.dsInfo.mainMID,mime:"application/dsml",wordCount:this.dsInfo.wordCount,createDate:this.dsInfo.createDate,updateDate:this.dsInfo.updateDate});c.debug("main file md5: "+
b.fid+", size: "+b.dataSize+", word count: "+b.wordCount);this.dsInfo.addFile(b);if("function"==typeof this.onConvertSuccess)this.onConvertSuccess()}}}})();
(function(){var c=null;Downsha.ClipSender=function(){c=Downsha.Logger.getInstance();this.__defineGetter__("dsInfo",this.getDsInfo);this.__defineSetter__("dsInfo",this.setDsInfo);this.__definePositiveInteger__("state",0);this.initialize()};Downsha.mixin(Downsha.ClipSender,Downsha.DefiningMixin);Downsha.ClipSender.STATE={INIT:0,SENDING_INFO_ITEM:1,SENDING_FILE_DESC:2,SENDING_FILE:3,SUCCESS:4,ERROR:5};Downsha.ClipSender.prototype._dsInfo=null;Downsha.ClipSender.prototype.onSendSuccess=null;Downsha.ClipSender.prototype.onSendError=
null;Downsha.ClipSender.prototype.initialize=function(){this.state=Downsha.ClipSender.STATE.INIT};Downsha.ClipSender.prototype.startUp=function(a,b,d){this.dsInfo=a;this.dsInfo instanceof Downsha.DownshaInfo?(this.onSendSuccess=function(){c.debug("ClipSender successfully sent");"function"==typeof b&&b.apply(this,arguments)},this.onSendError=function(){c.error("ClipSender failed to send");"function"==typeof d&&d.apply(this,arguments)},this.putInfoItem()):c.error("Tried to send invalid object")};Downsha.ClipSender.prototype.getDsInfo=
function(){return this._dsInfo};Downsha.ClipSender.prototype.setDsInfo=function(a){this._dsInfo=null!=a?a instanceof Downsha.DownshaInfo?a:"object"==typeof a?new Downsha.DownshaInfo(a):new Downsha.DownshaInfo:new Downsha.DownshaInfo};Downsha.ClipSender.prototype.putInfoItem=function(){c.debug("ClipSender.putInfoItem");var a=this;Downsha.context.remote.putInfoItem(this.dsInfo.getInfoItem(),function(b,d,e){c.debug("ClipSender successfully putted info item");4==e.readyState&&0!=e.status&&"success"==
d&&b.isSuccess()?(c.debug("Executing success callback"),a.handlePutInfoItemSuccess(b,d,e)):(c.debug("Executing error callback"),a.handlePutInfoItemError(e,d,null))},function(b,d,e){4==b.readyState?c.error("ClipSender encountered an error while putting info item  [readyState: "+b.readyState+"; status: "+b.status+"]"):c.error("ClipSender encountered an error while putting info item  [readyState: "+b.readyState+"]");a.handlePutInfoItemError(b,d,e)},!0)};Downsha.ClipSender.prototype.handlePutInfoItemSuccess=
function(a){c.debug("ClipSender.handlePutInfoItemSuccess");this.dsInfo.cid=a.data.CID;c.debug("cid: "+this.dsInfo.cid);var b=this;setTimeout(function(){b.putFileDesc()},0)};Downsha.ClipSender.prototype.handlePutInfoItemError=function(){c.debug("ClipSender.handlePutInfoItemError");var a=this;setTimeout(function(){a.onSendError()},0)};Downsha.ClipSender.prototype.putFileDesc=function(){c.debug("ClipSender.putFileDesc");var a=this;Downsha.context.remote.putFileDesc(this.dsInfo.getFileDesc(),function(b,
d,e){c.debug("ClipSender successfully putted file desc");4==e.readyState&&0!=e.status&&"success"==d&&b.isSuccess()?(c.debug("Executing success callback"),a.handlePutFileDescSuccess(b,d,e)):(c.debug("Executing error callback"),a.handlePutFileDescError(e,d,null))},function(b,d,e){4==b.readyState?c.error("ClipSender encountered an error while putting file desc  [readyState: "+b.readyState+"; status: "+b.status+"]"):c.error("ClipSender encountered an error while putting file desc  [readyState: "+b.readyState+
"]");a.handlePutFileDescError(b,d,e)},!0)};Downsha.ClipSender.prototype.handlePutFileDescSuccess=function(a){c.debug("ClipSender.handlePutFileDescSuccess");var b=a.data.FileNum,a=a.data.FileList;c.debug("file num: "+b);if(1<b)for(var d=0;d<b;d++){var e=a[d].FID;"string"==typeof e&&""!=e&&(e=this.dsInfo.findFileByFID(e),null!=e&&(e.cid=a[d].CID,e.cindex=a[d].CIndex,e.putState=a[d].PutState,c.debug("file: "+e.fid+" cid: "+e.cid+" cindex: "+e.cindex+" put_state: "+e.putState)))}else 1==b&&(e=a.FID,"string"==
typeof e&&""!=e&&(e=this.dsInfo.findFileByFID(e),null!=e&&(e.cid=a.CID,e.cindex=a.CIndex,e.putState=a.PutState,c.debug("file: "+e.fid+" cid: "+e.cid+" cindex: "+e.cindex+" put_state: "+e.putState))));var f=this;setTimeout(function(){f.onSendSuccess();f.putFile()},0)};Downsha.ClipSender.prototype.handlePutFileDescError=function(){c.debug("ClipSender.handlePutFileDescError");var a=this;setTimeout(function(){a.onSendError()},0)};Downsha.ClipSender.prototype.putFile=function(){c.debug("ClipSender.putFile");
var a=this.dsInfo.getNextUnputFile();if(null==a)return this.genThumbnail();var b=this;Downsha.context.remote.putFile(a.getFileData(),function(a,e,f){c.debug("ClipSender successfully putted file");4==f.readyState&&0!=f.status&&"success"==e&&a.isSuccess()?(c.debug("Executing success callback"),b.handlePutFileSuccess(a,e,f)):(c.debug("Executing error callback"),b.handlePutFileError(f,e,null))},function(a,e,f){4==a.readyState?c.error("ClipSender encountered an error while putting file  [readyState: "+
a.readyState+"; status: "+a.status+"]"):c.error("ClipSender encountered an error while putting file  [readyState: "+a.readyState+"]");b.handlePutFileError(a,e,f)},!0)};Downsha.ClipSender.prototype.handlePutFileSuccess=function(a){c.debug("ClipSender.handlePutFileSuccess");a=a.data.FID;if("string"!=typeof a||""==a)return c.debug("put file error. response fid invalid"),this.onSendError();var b=this.dsInfo.findFileByFID(a);if(null==b)return c.debug("put file error. response fid invalid. fid: "+a),this.onSendError();
b.putState=Downsha.DownshaFile.PUT_STATE.EXIST;c.debug("put file ok. fid: "+b.fid);var d=this;setTimeout(function(){d.putFile()},0)};Downsha.ClipSender.prototype.handlePutFileError=function(){c.debug("ClipSender.handlePutFileError");var a=this;setTimeout(function(){a.onSendError()},0)};Downsha.ClipSender.prototype.genThumbnail=function(){c.debug("ClipSender.genThumbnail");var a=this.dsInfo.getThumbnailFile();if(null==a)c.debug("Stop generating thumbnail, no proper source image");else{var b=this;Downsha.context.remote.genThumbnail(a.getFileAbstract(),
function(a,e,f){c.debug("ClipSender successfully generated thumbnail");4==f.readyState&&0!=f.status&&"success"==e&&a.isSuccess()?(c.debug("Executing success callback"),b.handleGenThumbnailSuccess(a,e,f)):(c.debug("Executing error callback"),b.handleGenThumbnailError(f,e,null))},function(a,e,f){4==a.readyState?c.error("ClipSender encountered an error while generating thumbnail  [readyState: "+a.readyState+"; status: "+a.status+"]"):c.error("ClipSender encountered an error while generating thumbnail  [readyState: "+
a.readyState+"]");b.handleGenThumbnailError(a,e,f)},!0)}};Downsha.ClipSender.prototype.handleGenThumbnailSuccess=function(){c.debug("ClipSender.handleGenThumbnailSuccess")};Downsha.ClipSender.prototype.handleGenThumbnailError=function(){c.debug("ClipSender.handleGenThumbnailError");var a=this;setTimeout(function(){a.onSendError()},0)}})();
(function(){var c=null;Downsha.getClipHandler=function(){null==Downsha._clipHandler&&(Downsha._clipHandler=new Downsha.ClipHandler);return Downsha._clipHandler};Downsha.__defineGetter__("clipHandler",Downsha.getClipHandler);Downsha.ClipHandler=function(){c=Downsha.Logger.getInstance()};Downsha.ClipHandler.WAIT_CONTAINER_ID="downshaContentClipperWait";Downsha.ClipHandler.WAIT_SHOW_TIME=1E3;Downsha.ClipHandler.WAIT_FADE_TIME=1E3;Downsha.ClipHandler.prototype.waitFlag=!1;Downsha.ClipHandler.prototype.actionsQueue=
[];Downsha.ClipHandler.prototype.send=function(a){var b=Downsha.clipStorer.loadNote(a);if(b){this.wait();var c=this,e=new Downsha.ClipConverter,f=new Downsha.ClipSender;e.startUp(b,function(){f.startUp(b,function(){Downsha.queueProcessor.onSuccess(a);c.onWaitClear(c.createSuccessTask(b,a))},function(){Downsha.queueProcessor.onCancel(a);c.onWaitClear(c.createFailureTask(b,a))})},function(){Downsha.queueProcessor.onCancel(a);c.onWaitClear(c.createFailureTask(b,a))})}};Downsha.ClipHandler.prototype.createFailureTask=
function(a,b){return function(){c.debug("Submit failure notification for infoItem with guid "+b);Downsha.notificationManager.notifyFailure(a,b)}};Downsha.ClipHandler.prototype.createSuccessTask=function(a,b){return function(){Downsha.context.getOptions().clipNotificationEnabled&&(c.debug("Submit success notification for infoItem with guid "+b),Downsha.notificationManager.notifySucess(a,b))}};Downsha.ClipHandler.prototype.getWaitContainer=function(){var a=content.document.getElementById(this.constructor.WAIT_CONTAINER_ID);
if(!a){a=content.document.createElement("downshadiv");a.id=this.constructor.WAIT_CONTAINER_ID;var b=content.document.createElement("div");b.id=this.constructor.WAIT_CONTAINER_ID+"Content";a.appendChild(b);var c=content.document.createElement("center");b.appendChild(c);b=content.document.createElement("img");b.setAttribute("src","resource://downsha-images/icon_scissors.png");c.appendChild(b);b=content.document.createElement("span");b.id=this.constructor.WAIT_CONTAINER_ID+"Text";c.appendChild(b);a._waitMsgBlock=
b;a.setMessage=function(a){this._waitMsgBlock.textContent=a}}return a};Downsha.ClipHandler.prototype.wait=function(){var a=this.getWaitContainer();a.style.opacity="1";a.setMessage(Downsha.chrome.i18n.getMessage("quickNote_clipping"));content.document.body.appendChild(a);var b=this;setTimeout(function(){b.clearWait()},this.constructor.WAIT_SHOW_TIME);this.waitFlag=!0};Downsha.ClipHandler.prototype.clearWait=function(){var a=content.document.getElementById(this.constructor.WAIT_CONTAINER_ID);a&&(a.style.opacity=
"0",setTimeout(function(){null!=a.parentNode&&a.parentNode.removeChild(a)},this.constructor.WAIT_FADE_TIME));this.waitFlag=!1;for(var b in this.actionsQueue)this.actionsQueue[b](),delete this.actionsQueue[b]};Downsha.ClipHandler.prototype.onWaitClear=function(a){this.waitFlag?this.actionsQueue.push(a):a()}})();
(function(){var c=null;Downsha.getClipStorer=function(){null==Downsha._clipStorer&&(Downsha._clipStorer=new Downsha.ClipStorer);return Downsha._clipStorer};Downsha.__defineGetter__("clipStorer",Downsha.getClipStorer);Downsha.ClipStorer=function(){c=Downsha.Logger.getInstance()};Downsha.ClipStorer.CLIPPER_FOLDER_NAME="downshaclips";Downsha.ClipStorer.SENT_EXT=".sent";Downsha.ClipStorer.NOTE_MATCHER=/^[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$/;Downsha.ClipStorer.prototype.init=function(){var a=
this.getProfileDir_();a.append(this.constructor.CLIPPER_FOLDER_NAME);a.exists()||a.create(Components.interfaces.nsIFile.DIRECTORY_TYPE,511);var b=this,d=this.loadNotes_(a,function(a){return-1==a.indexOf(b.constructor.SENT_EXT)&&a.match(b.constructor.NOTE_MATCHER)});0<d.length&&(c.debug("ClipStorer.init load "+d.length+" unsent notes from path: "+a.path),Downsha.queueProcessor.onStart(d))};Downsha.ClipStorer.prototype.getProfileDir_=function(){return Components.classes["@mozilla.org/file/directory_service;1"].getService(Components.interfaces.nsIProperties).get("ProfD",
Components.interfaces.nsIFile)};Downsha.ClipStorer.prototype.loadNotes_=function(a,b){for(var d=a.directoryEntries,e=[];d.hasMoreElements();){var f=d.getNext();f.QueryInterface(Components.interfaces.nsIFile);c.debug("Add infoItem with guid "+f.leafName);b(f.leafName)?e.push({guid:f.leafName}):this.deleteNote(f.leafName)}return e};Downsha.ClipStorer.prototype.deleteNote=function(a){var b=this.getNotePath_(a),c=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);
c.initWithPath(b);c.exists()?c.remove(!1):(c.initWithPath(this.getNotePath_(this.getSentNoteName_(a))),c.exists()&&c.remove(!1))};Downsha.ClipStorer.prototype.markNoteAsSent=function(a){this.renameNoteFile_(a,this.getSentNoteName_(a))};Downsha.ClipStorer.prototype.unmarkNoteAsSent=function(a){this.renameNoteFile_(this.getSentNoteName_(a),a)};Downsha.ClipStorer.prototype.renameNoteFile_=function(a,b){var c=this.getNotePath_(a),e=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);
e.initWithPath(c);e.exists()&&e.moveTo(null,b)};Downsha.ClipStorer.prototype.getSentNoteName_=function(a){return a+this.constructor.SENT_EXT};Downsha.ClipStorer.prototype.saveNote=function(a,b){var c=this.openOutputStream_(a);this.writeData_(c,b.toStorable());this.closeStream_(c)};Downsha.ClipStorer.prototype.loadNote=function(a){var a=this.openInputStream_(a),b=new Downsha.DownshaInfo(this.readData_(a));this.closeStream_(a);return b};Downsha.ClipStorer.prototype.getNotePath_=function(a){return this.getNoteDirPath()+
Downsha.Constants.SLASH+a};Downsha.ClipStorer.prototype.getNoteDirPath=function(){return this.getProfileDir_().path+Downsha.Constants.SLASH+this.constructor.CLIPPER_FOLDER_NAME};Downsha.ClipStorer.prototype.openInputStream_=function(a){var b=this.getNotePath_(a);c.debug("Loading infoItem from file "+b);a=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);a.initWithPath(b);b=Components.classes["@mozilla.org/network/file-input-stream;1"].createInstance(Components.interfaces.nsIFileInputStream);
b.init(a,-1,0,0);a=Components.classes["@mozilla.org/intl/converter-input-stream;1"].createInstance(Components.interfaces.nsIConverterInputStream);a.init(b,"UTF-8",0,0);return a};Downsha.ClipStorer.prototype.openOutputStream_=function(a){var b=this.getNotePath_(a);c.debug("Save infoItem to file "+b);a=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);a.initWithPath(b);b=Components.classes["@mozilla.org/network/file-output-stream;1"].createInstance(Components.interfaces.nsIFileOutputStream);
b.init(a,26,438,0);a=Components.classes["@mozilla.org/intl/converter-output-stream;1"].createInstance(Components.interfaces.nsIConverterOutputStream);a.init(b,"UTF-8",0,0);return a};Downsha.ClipStorer.prototype.readData_=function(a){var b="",c={},e=0;do e=a.readString(4294967295,c),b+=c.value;while(0!=e);try{return JSON.parse(b)}catch(f){return null}};Downsha.ClipStorer.prototype.writeData_=function(a,b){a.writeString(JSON.stringify(b));a.flush()};Downsha.ClipStorer.prototype.closeStream_=function(a){a.close()}})();
(function(){var c=null;Downsha.getQueueProcessor=function(){null==Downsha._queueProcessor&&(Downsha._queueProcessor=new Downsha.QueueProcessor);return Downsha._queueProcessor};Downsha.__defineGetter__("queueProcessor",Downsha.getQueueProcessor);Downsha.QueueProcessor=function(){c=Downsha.Logger.getInstance()};Downsha.QueueProcessor.WAIT_BETWEEN_TASK_PROCESSING=3E3;Downsha.QueueProcessor.prototype.tasks={};Downsha.QueueProcessor.prototype.intervalID=null;Downsha.QueueProcessor.prototype.isStarted=
!1;Downsha.QueueProcessor.prototype.addTask=function(a,b){c.debug("Adding task to queue processor");this.tasks[a]={guid:a,action:b,processed:!1};c.debug("Task successfully added to processor. Number of task in the queue : "+this.getTaskCount());c.debug("Internal state : "+this.tasks.toSource());this.updateProcess()};Downsha.QueueProcessor.prototype.onStart=function(a){c.debug("Add notes to process "+a.length);for(var b in a){var d=a[b].guid;c.debug("Add note with guid = "+d+" to process");this.addTask(d,
this.defaultAction(d))}this.start()};Downsha.QueueProcessor.prototype.defaultAction=function(a){return function(){c.debug("Start processing note with guid = "+a);Downsha.clipHandler.send(a)}};Downsha.QueueProcessor.prototype.start=function(){if(!this.isStarted){this.isStarted=!0;var a=this;this.intervalID=setInterval(function(){for(var b in a.tasks){var d=a.tasks[b];if(d&&!d.processed){d.action();d.processed=!0;c.debug("End processing task");break}}},this.constructor.WAIT_BETWEEN_TASK_PROCESSING)}};
Downsha.QueueProcessor.prototype.stop=function(){null!=this.intervalID&&clearInterval(this.intervalID)};Downsha.QueueProcessor.prototype.onSuccess=function(a){delete this.tasks[a];Downsha.clipStorer.deleteNote(a);this.updateProcess()};Downsha.QueueProcessor.prototype.onCancel=function(a){this.onSuccess(a)};Downsha.QueueProcessor.prototype.onRetry=function(a){if(this.tasks[a])Downsha.clipStorer.unmarkNoteAsSent(a),this.tasks[a].processed=!1;else this.onCancel(a)};Downsha.QueueProcessor.prototype.updateProcess=
function(){Downsha.toolbarManager.onProcess(this.getTaskCount())};Downsha.QueueProcessor.prototype.getTaskCount=function(){if(Object.keys)return Object.keys(this.tasks).length;var a=0,b;for(b in this.tasks)a++;return a}})();
(function(){var c=null;Downsha.getNotificationManager=function(){null==Downsha._notificationManager&&(Downsha._notificationManager=new Downsha.NotificationManager);return Downsha._notificationManager};Downsha.__defineGetter__("notificationManager",Downsha.getNotificationManager);Downsha.NotificationManager=function(){c=Downsha.Logger.getInstance()};Downsha.NotificationManager.DEFAULT_WAIT_TIMEOUT_BETWEEN_NOTIFICATIONS=300;Downsha.NotificationManager.DEFAULT_WIDTH_FOR_MAC=150;Downsha.NotificationManager.DEFAULT_WIDTH_FOR_OTHER=
300;Downsha.NotificationManager.DEFAULT_HEIGHT=150;Downsha.NotificationManager.DEFAULT_MARGIN_BOTTOM=45;Downsha.NotificationManager.DEFAULT_MARGIN_RIGHT=5;Downsha.NotificationManager.prototype.isShowing=!1;Downsha.NotificationManager.prototype.notifications=[];Downsha.NotificationManager.prototype.position={left:Downsha.platform.isMacOS()?screen.width-this.constructor.DEFAULT_WIDTH_FOR_MAC:screen.width-this.constructor.DEFAULT_WIDTH_FOR_OTHER,top:screen.height-this.constructor.DEFAULT_HEIGHT};Downsha.NotificationManager.prototype.init=
function(){var a=this;window.addEventListener("unload",function(){a.onFirefoxClose()},!1)};Downsha.NotificationManager.prototype.notifySucess=function(a,b){this.showNotification({infoItem:a,guid:b,isSuccess:!0})};Downsha.NotificationManager.prototype.notifyFailure=function(a,b){this.showNotification({infoItem:a,guid:b,isSuccess:!1})};Downsha.NotificationManager.prototype.showNotification=function(a){if(this.isShowing)c.debug("Notification is showing"),this.notifications.push(a);else{this.isShowing=
!0;var b=this.position;this.dlg=window.openDialog("chrome://downsha/content/notification.xul","","chrome, popup, left="+b.left+", top="+b.top+", titlebar=no, resizable=no",Downsha,a,this)}};Downsha.NotificationManager.prototype.onNotificationSizeUpdate=function(){if(this.dlg){var a=this.dlg.document.getElementById("popupContent").style.height.replace("px",""),b=this.dlg.document.getElementById("popupContent").style.width.replace("px","");this.position.top=screen.height-a-this.constructor.DEFAULT_MARGIN_BOTTOM;
this.position.left=screen.width-b-this.constructor.DEFAULT_MARGIN_RIGHT;this.dlg.moveTo(this.position.left,this.position.top)}};Downsha.NotificationManager.prototype.onClose=function(){this.isShowing=!1;var a=this;setTimeout(function(){a.showNext()},this.constructor.DEFAULT_WAIT_TIMEOUT_BETWEEN_NOTIFICATIONS)};Downsha.NotificationManager.prototype.showNext=function(){c.debug("Number of notifications in the queue: "+this.notifications.length);0<this.notifications.length&&this.showNotification(this.notifications.splice(0,
1)[0])};Downsha.NotificationManager.prototype.onFirefoxClose=function(){this.dlg&&this.dlg.close()}})();
(function(){Downsha.getToolbarManager=function(){null==Downsha._toolbarManager&&(Downsha._toolbarManager=new Downsha.ToolbarManager);return Downsha._toolbarManager};Downsha.__defineGetter__("toolbarManager",Downsha.getToolbarManager);Downsha.ToolbarManager=function(){Downsha.Logger.getInstance();this.processing=!1};Downsha.ToolbarManager.BIG_LABEL_CLASS="big";Downsha.ToolbarManager.SMALL_LABEL_CLASS="small";Downsha.ToolbarManager.PROCESSING_LABEL_CLASS="processing";Downsha.ToolbarManager.prototype.onTabSelect=
function(){};Downsha.ToolbarManager.prototype.onTabClose=function(){};Downsha.ToolbarManager.prototype.onProcess=function(c){0==c?(this.processing=!1,this.setTooltipText(this.getToolbarButton()),this.clearBadge()):(this.processing=!0,this.setTooltipText(this.getToolbarButton()),this.updateBadge(c))};Downsha.ToolbarManager.prototype.setTooltipText=function(c){var a=this.processing?"BrowserActionTitlePending":"BrowserActionTitleDefault";c&&(c.tooltipText=Downsha.chrome.i18n.getMessage(a))};Downsha.ToolbarManager.prototype.updateBadge=
function(c){this.setTooltipText(this.getToolbarButton());var a=10<c?c:" "+c,c=this.getToolbarValues(),b;for(b in c)c[b].value=a,this.removeClassName(c[b],this.constructor.PROCESSING_LABEL_CLASS),this.processing&&this.addClassName(c[b],this.constructor.PROCESSING_LABEL_CLASS);a="large"===document.getElementById("nav-bar").getAttribute("iconsize")?this.constructor.BIG_LABEL_CLASS:this.constructor.SMALL_LABEL_CLASS;for(b in c)if(c[b].className&&0<=c[b].className.indexOf(a)){c[b].style.display="block";
break}};Downsha.ToolbarManager.prototype.clearBadge=function(){var c=this.getToolbarValues(),a;for(a in c)c[a].style&&(c[a].style.display="none")};Downsha.ToolbarManager.prototype.getToolbarButton=function(){return document.getElementById("downsha-button")};Downsha.ToolbarManager.prototype.getToolbarValues=function(){return document.getElementsByClassName("downsha-toolbar-value")};Downsha.ToolbarManager.prototype.addClassName=function(c,a){c.className&&(c.className+=" "+a)};Downsha.ToolbarManager.prototype.removeClassName=
function(c,a){c.className&&(c.className=c.className.replace(RegExp(a+"?","g"),""))}})();
(function(){Downsha.getTabObserver=function(){null==Downsha._tabObserver&&(Downsha._tabObserver=new Downsha.TabObserver);return Downsha._tabObserver};Downsha.__defineGetter__("tabObserver",Downsha.getTabObserver);Downsha.TabObserver=function(){Downsha.Logger.getInstance()};Downsha.TabObserver.prototype.init=function(){var c=gBrowser.tabContainer;c.addEventListener("TabClose",this.onTabClose,!1);c.addEventListener("TabSelect",this.onTabSelect,!1)};Downsha.TabObserver.prototype.onTabClose=function(c){Downsha.toolbarManager.onTabClose(c.target.linkedPanel)};
Downsha.TabObserver.prototype.onTabSelect=function(c){Downsha.toolbarManager.onTabSelect(c.target.linkedPanel)}})();Downsha.getjQuery=function(){return this.jQuery?this.jQuery:$};
Downsha.JQueryLoader={JQUERY_PATH:"chrome://downsha/content/libs/jquery/jquery-1.6.2.js",load:function(){var c={},a=[],b=[],d=[],d=Components.classes["@mozilla.org/moz/jssubscript-loader;1"].getService(Components.interfaces.mozIJSSubScriptLoader),e;for(e in window)window.hasOwnProperty(e)&&a.push(e);d.loadSubScript(this.JQUERY_PATH);for(e in window)window.hasOwnProperty(e)&&b.push(e);d=b.filter(function(b){return 0>a.indexOf(b)});for(b=0;b<d.length;b++)c[d[b]]=window[d[b]],delete window[d[b]];Downsha.jQuery=
c.$||c.jQuery}};
