(function(){Downsha.AbstractNoteForm=function(){};Downsha.AbstractNoteForm.TITLE="title";Downsha.AbstractNoteForm.CONTENT="content";Downsha.inherit(Downsha.AbstractNoteForm,jQuery);Downsha.AbstractNoteForm.onForm=function(b,a){var d={},c;for(c in this.prototype)d[c]=this.prototype[c];var e=b.get(0);$.extend(!0,b,d);b.form=$(e);b.__defineGetter__("title",b.getTitle);b.__defineSetter__("title",b.setTitle);b.__defineGetter__("content",b.getContent);b.__defineSetter__("content",b.setContent);if("object"==
typeof a&&null!=a)for(c in a)"string"==typeof this.prototype[c+"FieldName"]&&(this[c+"FieldName"]=a[c]);return b};Downsha.AbstractNoteForm.prototype.titleFieldName=Downsha.AbstractNoteForm.TITLE;Downsha.AbstractNoteForm.prototype.contentFieldName=Downsha.AbstractNoteForm.CONTENT;Downsha.AbstractNoteForm.prototype.getField=function(b){return this.form.find("*[name="+b+"]")};Downsha.AbstractNoteForm.prototype.getLabel=function(b){return this.form.find("label[for="+b+"]")};Downsha.AbstractNoteForm.prototype.enableField=
function(b){var a=this.getField(b);a&&("input"==a.prop("tagName").toLowerCase()?a.removeAttr("disabled"):a.removeClass("disabled"),(b=this.getLabel(b))&&b.hasClass("disabled")&&b.removeClass("disabled"))};Downsha.AbstractNoteForm.prototype.disableField=function(b){var a=this.getField(b);a&&("input"==a.prop("tagName").toLowerCase()?a.attr("disabled","disabled"):a.addClass("disabled"),(b=this.getLabel(b))&&!b.hasClass("disabled")&&b.addClass("disabled"))};Downsha.AbstractNoteForm.prototype.isFieldEnabled=
function(b){return(b=this.getField(b))&&!b.hasClass("disabled")};Downsha.AbstractNoteForm.prototype.getTitle=function(){return this.getField(this.titleFieldName).val()};Downsha.AbstractNoteForm.prototype.setTitle=function(b){this.getField(this.titleFieldName).val(b)};Downsha.AbstractNoteForm.prototype.getContent=function(){return this.getField(this.contentFieldName).val()};Downsha.AbstractNoteForm.prototype.setContent=function(b){this.getField(this.contentFieldName).val(b)};Downsha.AbstractNoteForm.prototype.reset=
function(){for(var b=this.getStorableProps(),a=0;a<b.length;a++)this[b[a]]=null};Downsha.AbstractNoteForm.prototype.populateWithNote=function(b,a){if(a instanceof Downsha.DownshaModel){var d=a.toStorable(),c;for(c in d)"undefined"!=typeof this[c]&&"undefined"!=typeof a[c]&&null!=a[c]&&(this[c]=a[c])}};Downsha.AbstractNoteForm.prototype.populateWith=function(b){this.reset();if(b instanceof Downsha.DownshaModel){var a=b.toStorable(),d;for(d in a)"undefined"!=typeof this[d]&&(this[d]=b[d])}};Downsha.AbstractNoteForm.prototype.getStorableProps=
function(){return["title","content"]};Downsha.AbstractNoteForm.prototype.toStorable=function(){for(var b=this.getStorableProps(),a={},d=0;d<b.length;d++)a[b[d]]=this[b[d]];return a};Downsha.AbstractNoteForm.prototype.getModelName=function(){return"Downsha.AbstractNoteForm"};Downsha.AbstractNoteForm.prototype.getStringDescription=function(){return"'"+this.title+"'; Content length: "+("string"==typeof this.content?this.content.length:0)};Downsha.AbstractNoteForm.prototype.toString=function(){return this.getModelName()+
" "+this.getStringDescription()}})();
(function(){Downsha.ClipNoteForm=function(){};Downsha.ClipNoteForm.URL="url";Downsha.inherit(Downsha.ClipNoteForm,Downsha.AbstractNoteForm);Downsha.ClipNoteForm.onForm=function(b,a){b=this.constructor.parent.onForm.apply(this,[b,a]);b.__defineGetter__("url",b.getUrl);b.__defineSetter__("url",b.setUrl);return b};Downsha.ClipNoteForm.prototype.urlFieldName=Downsha.ClipNoteForm.URL;Downsha.ClipNoteForm.prototype.getUrl=function(){return this.getField(this.urlFieldName).val()};Downsha.ClipNoteForm.prototype.setUrl=
function(b){this.getField(this.urlFieldName).val(b)};Downsha.ClipNoteForm.prototype.getStorableProps=function(){var b=this.parent.getStorableProps.apply(this);b.push("url");return b};Downsha.ClipNoteForm.prototype.populateWithNote=function(b,a){a instanceof Downsha.DownshaInfo&&this.parent.populateWithNote.apply(this,[b,a])};Downsha.ClipNoteForm.prototype.asClipNote=function(){return new Downsha.DownshaInfo(this.toStorable())};Downsha.ClipNoteForm.prototype.getModelName=function(){return"Downsha.ClipNoteForm"};
Downsha.ClipNoteForm.prototype.getStringDescription=function(){var b=this.parent.getStringDescription.apply(this);return b+="; URL: "+this.url}})();
(function(){function b(){var b=null,c=0,c=(new Date).getTime(),b=setInterval(function(){"undefined"!=typeof window.overlay?(clearInterval(b),b=null,a()):c+3E3<(new Date).getTime()&&(d.warn("Clearing init timer, cuz we timed out waiting for overlay"),clearInterval(b),b=null)},100)}function a(){c=new Downsha.ChromePopup;c.viewManager.wait(Downsha.chrome.i18n.getMessage("loading"));setTimeout(function(){var a=Downsha.chrome.tabs.getSelected().document.location.href.match(/^(.*?):/)[1].toLowerCase();
"http"!=a&&"https"!=a?(c.viewManager.clearWait(),c.viewManager.showBlock($("#header")),c.viewManager.showError(Downsha.chrome.i18n.getMessage("unsupportedScheme"))):Downsha.context.userKnown?c.persistentLogin(function(){c.startUp()},function(a,b,e){c.popupStatus=Downsha.ChromePopup.POPUP_STATUS_CODES.STARTED;e instanceof Downsha.DSTPResponse&&e.hasAuthenticationError()?(d.info("Present login screen due to authentication error on initial login"),c.viewManager.switchView("loginView")):e instanceof Downsha.DSTPResponse&&
e.isError()?(c.viewManager.showBlock($("#header")),c.viewManager.showErrors([e.error])):Downsha.chromeExtension.offline?(c.viewManager.showBlock($("#header")),c.viewManager.showHttpError(a,b,e)):(c.viewManager.showBlock($("#header")),c.viewManager.showError(Downsha.chrome.i18n.getMessage("UnknownError")))}):(c.viewManager.clearWait(),c.viewManager.switchView("loginView"))},300)}var d=null,c=null;$(document).ready(function(){d=Downsha.Logger.getInstance();window.onerror=function(a,b,c){d.exception("\n"+
b+":"+c+": "+a+"\n")};window.onblur=function(){window.setTimeout(function(){if(document.activeElement&&"platformFrame"==document.activeElement.id){var a=document.querySelector("#quickNoteView input[type=submit]");a&&a.focus()}else c&&c.dismissPopup(!0)},100)};window.focus();b();d.debug("-------- POPUP STARTING ------------")})})();
(function(){var b=null;Downsha.ChromePopup=function(){b=Downsha.Logger.getInstance();this.initialize()};Downsha.ChromePopup.POPUP_DISMISS_TIMEOUT=300;Downsha.ChromePopup.VIEW_UPDATE_TIMEOUT=50;Downsha.ChromePopup.QUICK_NOTE_VIEW_DEFAULTS={infoItem:null,fullPageEnabled:!0,notebookGuid:null};Downsha.ChromePopup.POPUP_STATUS_CODES={STARTUP:0,STARTED:1};Downsha.ChromePopup.prototype.overlay=null;Downsha.ChromePopup.prototype.notifier=null;Downsha.ChromePopup.prototype.viewManager=null;Downsha.ChromePopup.prototype.pageInfo=
null;Downsha.ChromePopup.prototype.contentPreviewer=null;Downsha.ChromePopup.prototype.tab=null;Downsha.ChromePopup.prototype.requestListener=null;Downsha.ChromePopup.prototype.loginValidator=null;Downsha.ChromePopup.prototype.registerValidator=null;Downsha.ChromePopup.prototype.quickNoteValidator=null;Downsha.ChromePopup.prototype.quickNoteForm=null;Downsha.ChromePopup.prototype.loginProc=null;Downsha.ChromePopup.prototype._previewAdjustmentEnabled=!1;Downsha.ChromePopup.prototype.popupStatus=Downsha.ChromePopup.POPUP_STATUS_CODES.STARTUP;
Downsha.ChromePopup.prototype.initialize=function(){b.debug("ChromePopup initializing...");this.initViewManager();this.initOverlay();this.initChrome();this.tab=Downsha.chrome.tabs.getSelected();this.initListeners();this.pageInfo=new Downsha.PageInfo(this.tab);this.localizePopup();this.initForms();this.initViews();b.debug("ChromePopup initialized")};Downsha.ChromePopup.prototype.initViewManager=function(){b.debug("ChromePopup.initViewManager");this.viewManager=Downsha.ViewManager.getInstance();this.viewManager.globalErrorMessage=
new Downsha.ViewManager.SimpleMessage($("#globalErrorMessage"));this.viewManager.globalMessage=new Downsha.ViewManager.StackableMessage($("#globalMessage"))};Downsha.ChromePopup.prototype.initOverlay=function(){b.debug("ChromePopup.initOverlay");this.overlay="undefined"!=typeof window.overlay?window.overlay:null;window.overlayContentContainer&&(b.debug(">>> Adding callback for view resizing..."),this.viewManager.containerResizeCallback=function(a){b.debug("Updating iframe's height to: "+a);var d=
window.overlay.document.getElementById("popupContent");d&&(d.style.height=a+10+"px");window.sizeToContent();window.overlay.sizeToContent()})};Downsha.ChromePopup.prototype.initChrome=function(){b.debug("ChromePopup.initChrome");try{var a=this.overlay.arguments[0];Downsha.chrome=a.downsha.chrome;this.clip=a.data.clip;this.notifier=a.clipNotifier}catch(d){b.error("Could not intialize chrome: "+d)}};Downsha.ChromePopup.prototype.initListeners=function(){b.debug("ChromePopup.initListeners");var a=this;
Downsha.chrome.extension.onRequest.addListener(function(){a.requestListener.apply(a,arguments)})};Downsha.ChromePopup.prototype.localizePopup=function(){b.debug("ChromePopup.localizePopup");for(var a=$("body"),d=0;d<a.length;d++){var c=$(a.get(d));Downsha.Utils.localizeBlock(c)}};Downsha.ChromePopup.prototype.initViews=function(){b.debug("ChromePopup.initViews");this.bindViews()};Downsha.ChromePopup.prototype.initForms=function(){b.debug("ChromePopup.initForms");this.quickNoteForm=Downsha.ClipNoteForm.onForm($("form[name=quickNoteForm]"));
this.bindForms()};Downsha.ChromePopup.prototype.setTab=function(a){this.tab=a};Downsha.ChromePopup.prototype.setClip=function(a){this.clip=a};Downsha.ChromePopup.prototype.requestListener=function(a,d,c){b.debug("ChromePopup.requestListener");b.debug("Request: "+JSON.stringify(a));var e=Downsha.Utils.getKeyFrom(a,Downsha.Constants.REQUEST_TYPE,"number",Downsha.Constants.RequestType.UNKNOWN);e==Downsha.Constants.RequestType.PAGE_CLIP_SUCCESS?this.handlePageClipSuccess(a,d,c):b.info("Popup ignores request: "+
e)};Downsha.ChromePopup.prototype.handlePageClipSuccess=function(a){this.viewManager.clearWait();b.info("Popup.handlePageClipSuccess");a=new Downsha.DownshaInfo(a);b.debug("Popup received request from extension with infoItem: "+a.toString());b.debug("Has selection "+this.clip.hasSelection());b.info("Prompting for filing info for full page clip");this.viewManager.switchView("quickNoteView",{infoItem:a})};Downsha.ChromePopup.prototype.startUp=function(){var a=this.clip.toDataObject();a[Downsha.Constants.REQUEST_TYPE]=
Downsha.Constants.RequestType.PAGE_CLIP_SUCCESS;b.debug("Notifying extension with clip: "+JSON.stringify(a));Downsha.chrome.extension.sendRequest(a)};Downsha.ChromePopup.prototype.bindViews=function(){b.debug("Popup.bindViews");this.bindHeader();this.bindLoginView();this.bindRegisterView();this.bindQuickNoteView()};Downsha.ChromePopup.prototype.bindHeader=function(){var a=this;$("#header").bind("show",function(){b.debug("#header.onShow");$("#headerLogoHome").unbind("click");$("#headerLogoHome").bind("click",
function(){a.goHome()})})};Downsha.ChromePopup.prototype.bindPlatform=function(){var a=this;$(".platform_desktop").unbind("click");$(".platform_desktop").bind("click",function(){a.goDesktop()});$(".platform_mobile").unbind("click");$(".platform_mobile").bind("click",function(){a.goMobile()});$(".platform_windows8").unbind("click");$(".platform_windows8").bind("click",function(){a.goWindows8()});$(".platform_chrome").unbind("click");$(".platform_chrome").bind("click",function(){a.goChrome()});$(".platform_firefox").unbind("click");
$(".platform_firefox").bind("click",function(){a.goFirefox()});$(".platform_ie").unbind("click");$(".platform_ie").bind("click",function(){a.goDesktop()})};Downsha.ChromePopup.prototype.bindLoginView=function(){var a=this;$("#loginView").bind("show",function(d,c){b.debug("#loginView.onShow");a.viewManager.showBlock($("#header"));$("#headerUser").hide();$("#headerNoUserLogin").hide();$("#headerNoUserRegister").show();$("#headerRegister").unbind("click");$("#headerRegister").bind("click",function(){a.goRegister()});
a.bindPlatform();var e=$("#loginView").find("form[name=loginForm]");"object"==typeof c&&null!=c?("undefined"!=typeof c.username&&e.find("input[name=username]").val(c.username),"undefined"!=typeof c.password&&e.find("input[name=password]").val(c.password)):e.find("input[type=password]").val("");e.find("input[name=username]").focus();a.loginValidator.focusInvalid()});$("#loginView").bind("hide",function(){b.debug("#loginView.onHide");a.viewManager.hideBlock($("#header"))})};Downsha.ChromePopup.prototype.bindRegisterView=
function(){var a=this;$("#registerView").bind("show",function(d,c){b.debug("#registerView.onShow");a.viewManager.showBlock($("#header"));$("#headerUser").hide();$("#headerNoUserRegister").hide();$("#headerNoUserLogin").show();$("#headerLogin").unbind("click");$("#headerLogin").bind("click",function(){a.goLogin()});a.bindPlatform();var e=$("#registerView").find("form[name=registerForm]");"object"==typeof c&&null!=c&&"undefined"!=typeof c.username&&e.find("input[name=username]").val(c.username);e.find("input[type=password]").val("");
e.find("input[name=username]").focus();a.registerValidator.focusInvalid()});$("#registerView").bind("hide",function(){b.debug("#registerView.onHide");a.viewManager.hideBlock($("#header"))})};Downsha.ChromePopup.prototype.bindQuickNoteView=function(){var a=this,d=$("#quickNoteView");d.bind("show",function(c,d){b.debug("#quickNoteView.onShow");a.viewManager.showBlock($("#header"));var f=Downsha.context.userName;f&&($("#headerUsername").text(f),$("#headerSignout").unbind("click"),$("#headerSignout").bind("click",
function(){a.logout()}),$("#headerNoUserRegister").hide(),$("#headerNoUserLogin").hide(),$("#headerUser").show());a.bindPlatform();$("#platformFrame").attr("src",Downsha.context.getNoteListUrl());f=a.getQuickNoteActionElement();if(Downsha.Utils.isForbiddenUrl(a.tab.document.location.href))f.find("input").each(function(a,b){var c=$(b);c.val()!="CLIP_ACTION_URL"&&c.remove()}),f.find("label").each(function(a,b){var c=$(b);c.attr("for")!="CLIP_ACTION_URL"&&c.remove()});else{if(!a.pageInfo||!a.pageInfo.selection)f.find("input[value=CLIP_ACTION_SELECTION]").remove(),
f.find("label[for=CLIP_ACTION_SELECTION]").remove();a.isArticleSane()||(f.find("input[value=CLIP_ACTION_ARTICLE]").remove(),f.find("label[for=CLIP_ACTION_ARTICLE]").remove());if(!a.pageInfo||!(0<a.pageInfo.documentLength||a.pageInfo.containsImages))f.find("input[value=CLIP_ACTION_FULL_PAGE]").remove(),f.find("label[for=CLIP_ACTION_FULL_PAGE]").remove()}var f=(f=Downsha.context.getOptions(!0))&&f.clipAction?f.clipAction:Downsha.Options.CLIP_ACTION_OPTIONS.ARTICLE,g=null,g=Downsha.Utils.isForbiddenUrl(a.tab.document.location.href)?
"CLIP_ACTION_URL":a.pageInfo&&a.pageInfo.selection?"CLIP_ACTION_SELECTION":a.pageInfo&&a.pageInfo.article&&a.isArticleSane()&&f==Downsha.Options.CLIP_ACTION_OPTIONS.ARTICLE?"CLIP_ACTION_ARTICLE":a.pageInfo&&(0<a.pageInfo.documentLength||a.pageInfo.containsImages)&&(f==Downsha.Options.CLIP_ACTION_OPTIONS.ARTICLE||f==Downsha.Options.CLIP_ACTION_OPTIONS.FULL_PAGE)?"CLIP_ACTION_FULL_PAGE":"CLIP_ACTION_URL";a.selectQuickNoteAction(g);a.previewQuickNoteAction();f=$.extend(!0,{},Downsha.ChromePopup.QUICK_NOTE_VIEW_DEFAULTS);
a.quickNoteForm.populateWith(f);d&&"object"==typeof d?(b.debug("Overriding quick note form with passed arguments"),"object"==typeof d.infoItem?(b.debug("Using supplied infoItem object to populate quick note form"),g=d.infoItem instanceof Downsha.DownshaInfo?d.infoItem:new Downsha.DownshaInfo(d.infoItem),a.quickNoteForm.populateWithNote(Downsha.context,g)):b.debug("No infoItem object passed, using as a blank quick note"),$.extend(!0,f,d)):b.debug("No options were given, will operate as quick note with default options");
$("#quickNoteView input[type=submit]").focus()});d.bind("hide",function(){b.debug("#quickNoteView.onHide");a.viewManager.hideBlock($("#header"))})};Downsha.ChromePopup.prototype.bindForms=function(){b.debug("Adding expression method");$.validator.addMethod("mask",$.fn.validate.methods.mask,Downsha.chrome.i18n.getMessage("invalidMask"));$.validator.addMethod("trim",$.fn.validate.methods.trim,"trim error");$.validator.addMethod("totalPartsRange",$.fn.validate.methods.totalPartsRange,Downsha.chrome.i18n.getMessage("totalPartsNotInRange"));
$.validator.addMethod("partLengthRange",$.fn.validate.methods.partLengthRange,Downsha.chrome.i18n.getMessage("partLengthNotInRange"));$.validator.addMethod("partMask",$.fn.validate.methods.partMask);$.validator.addMethod("toLowerCase",$.fn.validate.methods.toLowerCase);$.validator.addMethod("anyOf",$.fn.validate.methods.toLowerCase);$.validator.prototype.invalidate=function(a,b){var c={};c[a]=b;this.showErrors(c)};this.bindLoginForm();this.bindRegisterForm();this.bindQuickNoteForm()};Downsha.ChromePopup.prototype.bindLoginForm=
function(){b.debug("Popup.bindLoginForm");var a=$("form[name=loginForm]"),d=this;if(0==a.length)b.warn("Could not find login form");else{var c={submitHandler:function(){d.submitLoginForm()},errorClass:this.viewManager.FORM_FIELD_ERROR_MESSAGE_CLASS,errorElement:"div",onkeyup:!1,onfocusout:!1,invalidHandler:function(){setTimeout(function(){d.viewManager.updateBodyHeight()},d.constructor.VIEW_UPDATE_TIMEOUT)},success:function(){d.viewManager.updateBodyHeight()},rules:{username:{required:!0,minlength:Downsha.Constants.Limits.DSTP_USER_NAME_LEN_MIN,
maxlength:Downsha.Constants.Limits.DSTP_USER_NAME_LEN_MAX,mask:Downsha.Constants.Limits.DSTP_USER_NAME_REGEX},password:{required:!0,minlength:Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MIN,maxlength:Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MAX,mask:Downsha.Constants.Limits.DSTP_USER_PWD_REGEX}},messages:{username:{required:Downsha.chrome.i18n.getMessage("valueNotPresent",Downsha.chrome.i18n.getMessage("loginForm_username")),minlength:Downsha.chrome.i18n.getMessage("valueTooShort",[Downsha.chrome.i18n.getMessage("loginForm_username"),
Downsha.Constants.Limits.DSTP_USER_NAME_LEN_MIN]),maxlength:Downsha.chrome.i18n.getMessage("valueTooLong",[Downsha.chrome.i18n.getMessage("loginForm_username"),Downsha.Constants.Limits.DSTP_USER_NAME_LEN_MAX]),mask:Downsha.chrome.i18n.getMessage("invalidUsername")},password:{required:Downsha.chrome.i18n.getMessage("valueNotPresent",Downsha.chrome.i18n.getMessage("loginForm_password")),minlength:Downsha.chrome.i18n.getMessage("valueTooShort",[Downsha.chrome.i18n.getMessage("loginForm_password"),Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MIN]),
maxlength:Downsha.chrome.i18n.getMessage("valueTooLong",[Downsha.chrome.i18n.getMessage("loginForm_password"),Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MAX]),mask:Downsha.chrome.i18n.getMessage("invalidPassword")}}};b.debug("Setting up validation on login form");this.loginValidator=a.validate(c)}};Downsha.ChromePopup.prototype.bindRegisterForm=function(){b.debug("Popup.bindRegisterForm");var a=$("form[name=registerForm]"),d=this;if(0==a.length)b.warn("Could not find register form");else{var c={submitHandler:function(){d.submitRegisterForm()},
errorClass:this.viewManager.FORM_FIELD_ERROR_MESSAGE_CLASS,errorElement:"div",onkeyup:!1,onfocusout:!1,invalidHandler:function(){setTimeout(function(){d.viewManager.updateBodyHeight()},d.constructor.VIEW_UPDATE_TIMEOUT)},success:function(){d.viewManager.updateBodyHeight()},rules:{username:{required:!0,minlength:Downsha.Constants.Limits.DSTP_USER_NAME_LEN_MIN,maxlength:Downsha.Constants.Limits.DSTP_USER_NAME_LEN_MAX,mask:Downsha.Constants.Limits.DSTP_USER_NAME_REGEX},password:{required:!0,minlength:Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MIN,
maxlength:Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MAX,mask:Downsha.Constants.Limits.DSTP_USER_PWD_REGEX},password2:{required:!0,equalTo:"#registerPassword",minlength:Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MIN,maxlength:Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MAX,mask:Downsha.Constants.Limits.DSTP_USER_PWD_REGEX}},messages:{username:{required:Downsha.chrome.i18n.getMessage("valueNotPresent",Downsha.chrome.i18n.getMessage("registerForm_username")),minlength:Downsha.chrome.i18n.getMessage("valueTooShort",
[Downsha.chrome.i18n.getMessage("registerForm_username"),Downsha.Constants.Limits.DSTP_USER_NAME_LEN_MIN]),maxlength:Downsha.chrome.i18n.getMessage("valueTooLong",[Downsha.chrome.i18n.getMessage("registerForm_username"),Downsha.Constants.Limits.DSTP_USER_NAME_LEN_MAX]),mask:Downsha.chrome.i18n.getMessage("invalidUsername")},password:{required:Downsha.chrome.i18n.getMessage("valueNotPresent",Downsha.chrome.i18n.getMessage("registerForm_password")),minlength:Downsha.chrome.i18n.getMessage("valueTooShort",
[Downsha.chrome.i18n.getMessage("registerForm_password"),Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MIN]),maxlength:Downsha.chrome.i18n.getMessage("valueTooLong",[Downsha.chrome.i18n.getMessage("registerForm_password"),Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MAX]),mask:Downsha.chrome.i18n.getMessage("invalidPassword")},password2:{required:Downsha.chrome.i18n.getMessage("valueNotPresent",Downsha.chrome.i18n.getMessage("registerForm_password")),equalTo:Downsha.chrome.i18n.getMessage("valueNotEqualTo",
Downsha.chrome.i18n.getMessage("registerForm_password")),minlength:Downsha.chrome.i18n.getMessage("valueTooShort",[Downsha.chrome.i18n.getMessage("registerForm_password"),Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MIN]),maxlength:Downsha.chrome.i18n.getMessage("valueTooLong",[Downsha.chrome.i18n.getMessage("registerForm_password"),Downsha.Constants.Limits.DSTP_USER_PWD_LEN_MAX]),mask:Downsha.chrome.i18n.getMessage("invalidPassword")}}};b.debug("Setting up validation on register form");this.registerValidator=
a.validate(c)}};Downsha.ChromePopup.prototype.bindQuickNoteForm=function(){b.debug("Popup.bindQuickNoteForm");var a=$("form[name=quickNoteForm]");if(0==a.length)b.warn("Could not find quickNoteForm");else{var d=a.find("input[name=title]");d.bind("blur",function(){d.val(d.val().trim())});var c=this;this.getQuickNoteActionElement().find("input").each(function(a,b){$(b).bind("click",function(){c.previewQuickNoteAction()})});var e={submitHandler:function(){c.submitQuickNoteForm()},errorClass:this.viewManager.FORM_FIELD_ERROR_MESSAGE_CLASS,
errorElement:"div",onkeyup:!1,onfocusin:function(){c.disablePreviewAdjustment()},onfocusout:function(){c.enablePreviewAdjustment();c.quickNoteValidator.numberOfInvalids()&&c.quickNoteValidator.form()},rules:{title:{trim:!0,required:!1,rangelength:[Downsha.Constants.Limits.DSTP_NOTE_TITLE_LEN_MIN,Downsha.Constants.Limits.DSTP_NOTE_TITLE_LEN_MAX],mask:Downsha.Constants.Limits.DSTP_NOTE_TITLE_REGEX},tagNames:{totalPartsRange:[Downsha.Constants.Limits.DSTP_NOTE_TAGS_MIN,Downsha.Constants.Limits.DSTP_NOTE_TAGS_MAX],
partLengthRange:[Downsha.Constants.Limits.DSTP_TAG_NAME_LEN_MIN,Downsha.Constants.Limits.DSTP_TAG_NAME_LEN_MAX],partMask:Downsha.Constants.Limits.DSTP_TAG_NAME_REGEX}},messages:{title:{rangelength:Downsha.chrome.i18n.getMessage("valueNotInRange",[Downsha.chrome.i18n.getMessage("quickNote_title"),Downsha.Constants.Limits.DSTP_NOTE_TITLE_LEN_MIN,Downsha.Constants.Limits.DSTP_NOTE_TITLE_LEN_MAX]),mask:Downsha.chrome.i18n.getMessage("invalidTitle")},tagNames:{totalPartsRange:Downsha.chrome.i18n.getMessage("tagNamesNotInRange",
[Downsha.Constants.Limits.DSTP_NOTE_TAGS_MIN,Downsha.Constants.Limits.DSTP_NOTE_TAGS_MAX]),partLengthRange:Downsha.chrome.i18n.getMessage("tagNameNotInRange",[Downsha.Constants.Limits.DSTP_TAG_NAME_LEN_MIN,Downsha.Constants.Limits.DSTP_TAG_NAME_LEN_MAX]),partMask:Downsha.chrome.i18n.getMessage("invalidTagName")}}};b.debug("Setting up validation on quicknote form");this.quickNoteValidator=a.validate(e)}};Downsha.ChromePopup.prototype.submitLoginForm=function(){b.debug("Popup.submitLoginForm");var a=
this.getLoginForm();this.viewManager.hideErrors();this.viewManager.clearFormArtifacts(a);this.loginWithForm(a)};Downsha.ChromePopup.prototype.getLoginForm=function(){return $("form[name=loginForm]")};Downsha.ChromePopup.prototype.loginWithForm=function(a){b.debug("ChromePopup.loginWithForm");if("object"==typeof a){this.unabort();var d=a.find("[name=username]").val(),a=a.find("[name=password]").val();this.viewManager.wait(Downsha.chrome.i18n.getMessage("loggingIn"));b.info("login as: "+d);this._login(d,
a,!0)}};Downsha.ChromePopup.prototype._login=function(a,d,c){b.debug("ChromePopup._login");var e=this;Downsha.context.rememberedSession=c;var f=this.getLoginForm();this.viewManager.wait(Downsha.chrome.i18n.getMessage("loggingIn"));this.loginProc=Downsha.context.remote.login(a,d,c,function(c){b.info("login response received...");e.viewManager.clearWait();c.isSuccess()?(b.info("Successfully logged in"),e.viewManager.hideView("loginView"),b.debug("Updating stored username and password."),Downsha.context.userId=
c.data.UID,Downsha.context.userName=a,Downsha.context.userPass=Downsha.XORCrypt.encrypt(d,a),Downsha.context.termId=c.data.TID,1!=parseInt(c.data.ResyncTerm)?e.startUp():(b.info("notify terminal information..."),Downsha.context.remote.notifyTermInfo(Downsha.platform.toJSON(),function(){b.info("notify terminal ok");e.startUp()},function(){b.info("notify terminal failed");e.startUp()},!0))):c.isError()&&(c.error?(b.info("login invalid"),e.loginValidator.resetForm(),e.viewManager.showFormErrors(f,[c.error],
null)):(b.warn("Unexpected response during login"),e.viewManager.showErrors(c.error)),e.viewManager.switchView("loginView",{username:a,password:""}))},function(a,c,d){a&&4==a.readyState?b.error("Failed to login due to transport problems (status: "+a.status+")"):a?b.error("Failed to login due to transport problems (readyState: "+a.readyState+")"):b.error("Failed to login due to unkonwn transport problems");e.viewManager.clearWait();e.viewManager.showHttpError(a,c,d)},!0)};Downsha.ChromePopup.prototype.submitRegisterForm=
function(){b.debug("Popup.submitRegisterForm");var a=this.getRegisterForm();this.viewManager.hideErrors();this.viewManager.clearFormArtifacts(a);this.registerWithForm(a)};Downsha.ChromePopup.prototype.getRegisterForm=function(){return $("form[name=registerForm]")};Downsha.ChromePopup.prototype.registerWithForm=function(a){b.debug("ChromePopup.registerWithForm");if("object"==typeof a){this.unabort();var d=a.find("[name=username]").val(),a=a.find("[name=password]").val();this.viewManager.wait(Downsha.chrome.i18n.getMessage("registering"));
b.info("register as: "+d);this._register(d,a)}};Downsha.ChromePopup.prototype._register=function(a,d){b.debug("ChromePopup._register");var c=this,e=this.getRegisterForm();this.viewManager.wait(Downsha.chrome.i18n.getMessage("registering"));this.registerProc=Downsha.context.remote.register(a,d,function(f){b.info("register response received...");c.viewManager.clearWait();f.isSuccess()?(b.info("Successfully registered"),c.viewManager.hideView("registerView"),b.debug("Updating stored username and password."),
Downsha.context.userId=f.data.UID,Downsha.context.userName=a,Downsha.context.userPass=Downsha.XORCrypt.encrypt(d,a),Downsha.context.termId=f.data.TID,1!=parseInt(f.data.ResyncTerm)?c.startUp():(b.info("notify terminal information..."),Downsha.context.remote.notifyTermInfo(Downsha.platform.toJSON(),function(){b.info("notify terminal ok");c.startUp()},function(){b.info("notify terminal failed");c.startUp()},!0))):f.isError()&&(f.error?(b.info("register invalid"),c.registerValidator.resetForm(),c.viewManager.showFormErrors(e,
[f.error],null)):(b.warn("Unexpected response during register"),c.viewManager.showErrors(f.error)),c.viewManager.switchView("registerView",{username:a,password:""}))},function(a,d,e){a&&4==a.readyState?b.error("Failed to register due to transport problems (status: "+a.status+")"):a?b.error("Failed to register due to transport problems (readyState: "+a.readyState+")"):b.error("Failed to register due to unkonwn transport problems");c.viewManager.clearWait();c.viewManager.showHttpError(a,d,e)},!0)};
Downsha.ChromePopup.prototype.logout=function(a){b.debug("ChromePopup.logout");this.viewManager.wait(Downsha.chrome.i18n.getMessage("loggingOut"));b.info("Logging out...");var d=this;"function"!=typeof a&&(a=function(){d.viewManager.clearWait();d.viewManager.switchView("loginView")});var c=function(){d.viewManager.clearWait();d.notifier.onLogout();a()};Downsha.context.remote.logout(function(a){d.viewManager.clearWait();a instanceof Downsha.DSTPResponse&&a.isSuccess()?b.info("Successfully logged out"):
b.error("Got garbage response when tried to logout");c()},function(a){a&&4==a.readyState?b.error("Failed to log out due to transport errors (status: "+a.status+")"):a?b.error("Failed to log out due to transport errors (readyState: "+a.readyState+")"):b.error("Failed to log out due to unknown transport errors");d.viewManager.clearWait();c()},!0)};Downsha.ChromePopup.prototype.persistentLogin=function(a,d){b.debug("Popup.persistentLogin");this.viewManager.wait(Downsha.chrome.i18n.getMessage("loggingIn"));
var c=this;return Downsha.context.remote.assureLogin(function(e,f,g){c.viewManager.clearWait();e instanceof Downsha.DSTPResponse&&e.isSuccess()?(b.info("Got successful result on login"),"function"==typeof a&&a(e,f)):(b.info("Got error result on login"),"function"==typeof d&&d(g,f,e))},function(a,f,g){a&&4==a.readyState?b.error("Failed to login due to transport errors (status: "+a.status+")"):a?b.error("Failed to login due to transport errors (readyState: "+a.readyState+")"):b.error("Failed to login due to unknown transport errors");
c.viewManager.clearWait();"function"==typeof d&&d(a,f,g)})};Downsha.ChromePopup.prototype.submitQuickNoteForm=function(){b.debug("Popup.submitQuickNoteForm");var a=this;if(this.quickNoteForm){b.debug("Grabbing data from form");this.viewManager.hideErrors();var d=this.quickNoteForm.asClipNote();d.title||(d.title=Downsha.chrome.i18n.getMessage("quickNote_untitledNote"));delete d.content;this.viewManager.hideView("quickNoteView");this.abortProcs();var c=this.getQuickNoteAction();b.debug("Submit quick note form with action "+
c);setTimeout(function(){if(c=="CLIP_ACTION_FULL_PAGE")if(a.clip.clipBody()){a.clip.fullPage=true;a.notifier.startClip(d)}else a.notifier.onFailedClip();else if(c=="CLIP_ACTION_SELECTION")if(a.clip.clipSelection())a.notifier.startClip(d);else a.notifier.onFailedClip();else if(c=="CLIP_ACTION_ARTICLE")if(a.clip.clipArticle())a.notifier.startClip(d);else a.notifier.onFailedClip();else c=="CLIP_ACTION_URL"?a.clip.clipUrl()&&a.notifier.startClip(d):a.viewManager.showError("Invalid Clip selection")},1);
this.dismissPopup()}else b.debug("Nothing to clip...")};Downsha.ChromePopup.prototype.getQuickNoteActionElement=function(){return $("form[name=quickNoteForm] #clipAction")};Downsha.ChromePopup.prototype.getQuickNoteAction=function(){return this.getQuickNoteActionElement().find("input:checked").first().attr("id")};Downsha.ChromePopup.prototype.selectQuickNoteAction=function(a){b.debug("ChromePopup.selectQuickNoteAction");a&&this.getQuickNoteActionElement().find("input[value="+a+"]").attr("checked",
"checked")};Downsha.ChromePopup.prototype.resetQuickNote=function(){};Downsha.ChromePopup.prototype.previewQuickNoteAction=function(){b.debug("Popup.previewQuickNoteAction");if(Downsha.Utils.isForbiddenUrl(this.tab.document.location.href))b.debug("Not previewing quickNoteAction on forbiddenUrl");else{var a=this.getQuickNoteAction();b.debug(a);a&&"undefined"!=typeof Downsha.Constants.RequestType["PREVIEW_"+a]&&(this.contentPreviewer||(this.contentPreviewer=new Downsha.ContentPreviewScript(this.tab)),
Downsha.Constants.RequestType["PREVIEW_"+a]==Downsha.Constants.RequestType.PREVIEW_CLIP_ACTION_FULL_PAGE?(b.debug("Preview full page"),this.contentPreviewer.previewFullPage()):Downsha.Constants.RequestType["PREVIEW_"+a]==Downsha.Constants.RequestType.PREVIEW_CLIP_ACTION_URL?(b.debug("Preview url"),this.contentPreviewer.previewURL()):Downsha.Constants.RequestType["PREVIEW_"+a]==Downsha.Constants.RequestType.PREVIEW_CLIP_ACTION_ARTICLE?(b.debug("Preview article"),this.contentPreviewer.previewArticle()):
Downsha.Constants.RequestType["PREVIEW_"+a]==Downsha.Constants.RequestType.PREVIEW_CLIP_ACTION_SELECTION&&(b.debug("Preview selection"),this.contentPreviewer.previewSelection()),Downsha.Constants.RequestType["PREVIEW_"+a]==Downsha.Constants.RequestType.PREVIEW_CLIP_ACTION_ARTICLE?this.enablePreviewAdjustment():this.disablePreviewAdjustment())}};Downsha.ChromePopup.prototype.enablePreviewAdjustment=function(){b.debug("Popup.enablePreviewAdjustment");this._previewAdjustmentEnabled||($("body").bind("keyup",
{popup:this},this._handlePreviewAdjustment),this._previewAdjustmentEnabled=!0)};Downsha.ChromePopup.prototype.disablePreviewAdjustment=function(){b.debug("Popup.disablePreviewAdjustment");this._previewAdjustmentEnabled&&($("body").unbind("keyup",this._handlePreviewAdjustment),this._previewAdjustmentEnabled=!1)};Downsha.ChromePopup.prototype._handlePreviewAdjustment=function(a){b.debug("Popup._handlePreviewAdjustment");var d=a.data&&a.data.popup?a.data.popup:null;if(d){var c=null;switch(a?a.keyCode:
null){case 37:c=Downsha.Constants.RequestType.PREVIEW_NUDGE_PREVIOUS_SIBLING;break;case 38:c=Downsha.Constants.RequestType.PREVIEW_NUDGE_PARENT;break;case 39:c=Downsha.Constants.RequestType.PREVIEW_NUDGE_NEXT_SIBLING;break;case 40:c=Downsha.Constants.RequestType.PREVIEW_NUDGE_CHILD;break;case 13:d.submitQuickNoteForm();return}c&&(d.contentPreviewer||(d.contentPreviewer=new Downsha.ContentPreviewScript(d.tab)),d.contentPreviewer.previewNudge(c))}};Downsha.ChromePopup.prototype.dismissPopup=function(a){b.debug("ChromePopup.dismissPopup");
var d=this,c=function(){try{d.abort(),d.contentPreviewer&&(d.contentPreviewer.clear(),d.contentPreviewer=null)}finally{window.close()}};"undefined"!=typeof a&&a?c():setTimeout(c,this.constructor.POPUP_DISMISS_TIMEOUT)};Downsha.ChromePopup.prototype.unabort=function(){b.debug("ChromePopup.unabort");this.aborted=!1;this.viewManager.quiet=!1};Downsha.ChromePopup.prototype.abort=function(){b.debug("ChromePopup.abort");this.aborted=!0;this.viewManager.quiet=!0;this.abortProcs()};Downsha.ChromePopup.prototype.abortProcs=
function(){b.debug("ChromePopup.abortProcs");this.loginProc&&"function"==typeof this.loginProc.abort&&(this.loginProc.abort(),this.loginProc=null)};Downsha.ChromePopup.prototype.goHome=function(){Downsha.chrome.tabs.create({url:Downsha.context.getHomeUrl()});this.dismissPopup()};Downsha.ChromePopup.prototype.goDesktop=function(){Downsha.chrome.tabs.create({url:Downsha.context.getDesktopUrl()});this.dismissPopup()};Downsha.ChromePopup.prototype.goMobile=function(){Downsha.chrome.tabs.create({url:Downsha.context.getMobileUrl()});
this.dismissPopup()};Downsha.ChromePopup.prototype.goWindows8=function(){Downsha.chrome.tabs.create({url:Downsha.context.getWindows8Url()});this.dismissPopup()};Downsha.ChromePopup.prototype.goChrome=function(){Downsha.chrome.tabs.create({url:Downsha.context.getChromeUrl()});this.dismissPopup()};Downsha.ChromePopup.prototype.goFirefox=function(){Downsha.chrome.tabs.create({url:Downsha.context.getFirefoxUrl()});this.dismissPopup()};Downsha.ChromePopup.prototype.goRegister=function(){this.viewManager.switchView("registerView",
{})};Downsha.ChromePopup.prototype.goLogin=function(){this.viewManager.switchView("loginView",{})};Downsha.ChromePopup.prototype.isArticleSane=function(){if(this.pageInfo&&this.pageInfo.articleBoundingClientRect){var a=Math.round(this.pageInfo.documentWidth*this.pageInfo.documentHeight),d=Math.round(this.pageInfo.articleBoundingClientRect.width*this.pageInfo.articleBoundingClientRect.height),c=Math.round(0<a?100*d/a:0);b.debug("isArticleSane() PageArea: "+a+" ArticleArea: "+d+" Ratio: "+c+"%");return Downsha.Utils.isArticleSane(this.pageInfo.documentWidth,
this.pageInfo.documentHeight,this.pageInfo.articleBoundingClientRect)}return!1}})();
