(function(){var d=null;Downsha.DownshaRemote=function(){d=Downsha.Logger.getInstance();this.initialize()};Downsha.DownshaRemote.PROTO_VERSION=1;Downsha.DownshaRemote.Command={USER_REGISTER:1,USER_REGISTER_RES:2147483649,USER_LOGIN:2,USER_LOGIN_RES:2147483650,USER_KEEP_ALIVE:3,USER_KEEP_ALIVE_RES:2147483651,USER_LOGOUT:4,USER_LOGOUT_RES:2147483652,USER_PASS_MODIFY:5,USER_PASS_MODIFY_RES:2147483653,USER_PROFILE_MODIFY:6,USER_PROFILE_MODIFY_RES:2147483654,USER_ACCOUNT_CHECK:7,USER_ACCOUNT_CHECK_RES:2147483655,
TERM_INFO_NOTIFY:16,TERM_INFO_NOTIFY_RES:2147483664,TERM_APP_NOTIFY:17,TERM_APP_NOTIFY_RES:2147483665,GET_SYNC_NO:128,GET_SYNC_NO_RES:2147483776,PUSH_SYNC_NO:2147483777,PUT_SYNC_NO:130,PUT_SYNC_NO_RES:2147483778,GET_DIR_LIST:256,GET_DIR_LIST_RES:2147483904,GET_INFO_ITEM_LIST:272,GET_INFO_ITEM_LIST_RES:2147483920,GET_TAG_LIST:288,GET_TAG_LIST_RES:2147483936,PUT_INFO_ITEM:320,PUT_INFO_ITEM_RES:2147483968,PUT_FILE_DESC:321,PUT_FILE_DESC_RES:2147483969,PUT_FILE:322,PUT_FILE_RES:2147483970,GEN_THUMBNAIL:327,
GEN_THUMBNAIL_RES:2147483975,COPY_INFO_ITEM:328,COPY_INFO_ITEM_RES:2147483976,GET_CHANNEL_LIST:4097,GET_CHANNEL_LIST_RES:2147487745,GET_CHANNEL_ITEM_LIST:4098,GET_CHANNEL_ITEM_LIST_RES:2147487746};Downsha.DownshaRemote.Error={OK:0,INVALID_USER_ACCOUNT:-100,USER_ACCOUNT_EXIST:-101,USER_ACCOUNT_NOT_EXIST:-102,USER_ACCOUNT_OPEN_FAILED:-103,USER_PASSWORD_INCORRECT:-104,TERM_INFO_OPEN_FAILED:-105,TERM_INFO_CREATE_FAILED:-106,SESSION_NOT_EXIST:-110,SESSION_CREATE_FAILED:-111,PARA_INVALID:-200,DIR_NAME_EXIST:-210,
DIRID_NOT_EXIST:-211,PARENT_DIRID_NOT_EXIST:-212,INFO_ITEM_CID_NOT_EXIST:-220,INFO_FILE_NOT_EXIST:-221,TAG_NAME_EXIST:-240,TAGID_NOT_EXIST:-241,FILE_CONTENT_NOT_ENOUGH:-300,FILE_CONTENT_NOT_CONSISTENT:-301,RESOURCE_ALLOC_FAILED:-500,CDN_OPEN_FAILED:-501};Downsha.DownshaRemote.CONTENT_TYPE_JSON="application/json";Downsha.DownshaRemote.POST_TIMEOUT=18E4;Downsha.DownshaRemote.GET_TIMEOUT=3E4;Downsha.DownshaRemote.prototype._debugRequestData=!1;Downsha.DownshaRemote.prototype.initialize=function(){this.__defineGetter__("debugRequestData",
this.setDebugRequestData);this.__defineSetter__("debugRequestData",this.isDebugRequestData)};Downsha.DownshaRemote.prototype.isDebugRequestData=function(){return this._debugRequestData};Downsha.DownshaRemote.prototype.setDebugRequestData=function(a){this._debugRequestData=a?!0:!1};Downsha.DownshaRemote.prototype.register=function(a,c,b,e,f){d.debug("DownshaRemote.register");return this.postCommand(this.constructor.Command.USER_REGISTER,{UserName:a,UserPass:c},b,e,f)};Downsha.DownshaRemote.prototype.login=
function(a,c,b,e,f,g){d.debug("DownshaRemote.login");return this.postCommand(this.constructor.Command.USER_LOGIN,{LoginType:1,UserName:a,UserPass:c},e,f,g)};Downsha.DownshaRemote.prototype.logout=function(a,c,b){d.debug("DownshaRemote.logout");return this.postCommand(this.constructor.Command.USER_LOGOUT,{},a,c,b)};Downsha.DownshaRemote.prototype.notifyTermInfo=function(a,c,b,e){d.debug("DownshaRemote.notifyTermInfo");return this.postCommand(this.constructor.Command.TERM_INFO_NOTIFY,a,c,b,e)};Downsha.DownshaRemote.prototype.putInfoItem=
function(a,c,b,e){d.debug("DownshaRemote.putInfoItem");return this.postCommand(this.constructor.Command.PUT_INFO_ITEM,a,c,b,e)};Downsha.DownshaRemote.prototype.putFileDesc=function(a,c,b,e){d.debug("DownshaRemote.putFileDesc");return this.postCommand(this.constructor.Command.PUT_FILE_DESC,a,c,b,e)};Downsha.DownshaRemote.prototype.putFile=function(a,c,b,e){d.debug("DownshaRemote.putFile");return this.postCommand(this.constructor.Command.PUT_FILE,a,c,b,e,!0)};Downsha.DownshaRemote.prototype.genThumbnail=
function(a,c,b,e){d.debug("DownshaRemote.genThumbnail");return this.postCommand(this.constructor.Command.GEN_THUMBNAIL,a,c,b,e)};Downsha.DownshaRemote.prototype.copyInfoItem=function(a,c,b,e){d.debug("DownshaRemote.copyInfoItem");return this.postCommand(this.constructor.Command.COPY_INFO_ITEM,a,c,b,e)};Downsha.DownshaRemote.prototype.getChannelList=function(a,c,b,e){d.debug("DownshaRemote.getChannelList");return this.postCommand(this.constructor.Command.GET_CHANNEL_LIST,a,c,b,e)};Downsha.DownshaRemote.prototype.getChannelItemList=
function(a,c,b,e){d.debug("DownshaRemote.getChannelItemList");return this.postCommand(this.constructor.Command.GET_CHANNEL_ITEM_LIST,a,c,b,e)};Downsha.DownshaRemote.prototype.getInfoItemList=function(a,c,b,e){d.debug("DownshaRemote.getInfoItemList");return this.postCommand(this.constructor.Command.GET_INFO_ITEM_LIST,a,c,b,e)};Downsha.DownshaRemote.prototype.postCommand=function(a,c,b,e,d,g){var h=(new Downsha.DSTPRequest(a)).toJSON();Downsha.extendObject(h,c);return this.postJson(Downsha.getContext().getYunzhaiUrl(a),
h,b,e,d,g)};Downsha.DownshaRemote.prototype.postJson=function(a,c,b,e,d,g){return this.doRequest("POST","json",a,c,b,e,d,g)};Downsha.DownshaRemote.prototype.getJson=function(a,c,b,e,d){return this.doRequest("GET","json",a,c,b,e,d)};Downsha.DownshaRemote.prototype.doRequest=function(a,c,b,e,f,g,h,j){null==a&&(a="GET");var i=this,k={meth:a,dataType:c,url:b,data:e,success:f,failure:g,processResponse:h,multipart:j};k.__defineGetter__("arguments",function(){return[this.meth,this.dataType,this.url,this.data,
this.success,this.failure,this.processResponse,this.multipart]});if(d.isDebugEnabled()){var l=this.debugAjaxDataObject(e);d.debug("doRequest("+a+", "+c+", "+b+", "+l+")")}var m=function(a,b,c){d.debug("Downsha.DownshaRemote.doRequest failed response");if(h)try{i.handleHttpError(a,b,c,k)}catch(e){throw d.error(e&&e.message?e.message:e),e;}"function"==typeof g&&g(a,b,c)},c={url:b,async:!0,cache:!1,dataType:c,error:m,success:function(a,b,c){if(0==c.status)return m(c,b,a);d.debug("Downsha.DownshaRemote.doRequest successfull response");
d.debug("response data: "+JSON.stringify(a));var e=a;if(h)try{e=i.handleHttpSuccess(a,b,c,k)}catch(g){throw g;}"function"==typeof f&&f(e,b,c)},processData:!1,type:a};if(j&&"POST"==a){var j=new FormData,n;for(n in e)if("object"==typeof e[n]&&e[n]instanceof Array){b=new Uint8Array(e[n]);l=null;try{window.BlobBuilder=window.BlobBuilder||window.WebKitBlobBuilder||window.MozBlobBuilder||window.MSBlobBuilder;var o=new BlobBuilder;o.append(b.buffer);l=o.getBlob()}catch(r){l=new Blob([b.buffer])}l&&j.append(n,
l)}else j.append(n,e[n]);c.contentType=!1;c.data=j}else c.contentType=Downsha.DownshaRemote.CONTENT_TYPE_JSON,c.data=JSON.stringify(e);c.timeout="POST"==a?this.constructor.POST_TIMEOUT:this.constructor.GET_TIMEOUT;d.debug(">>> Making request for: "+c.url);return Downsha.jQuery?Downsha.jQuery.ajax(c):$.ajax(c)};Downsha.DownshaRemote.prototype.debugAjaxDataObject=function(a){var c="";if(this._debugRequestData)try{var b={},e;for(e in a)b[e]="object"==typeof a[e]&&a[e]instanceof Array?a[e].length:a[e];
c=JSON.stringify(b)}catch(d){}else{c=[];for(e in a)c.push(e);c="{"+c.toString()+"}"}return c};Downsha.DownshaRemote.prototype.handleHttpSuccess=function(a,c,b){d.debug("Downsha.DownshaRemote.handleHttpSuccess");try{var e=Downsha.DSTPResponse.createFrom(a)}catch(f){if(a="",f instanceof Downsha.DownshaError)a=f.errorCode,d.error("Exception creating Downsha.DSTPResponse: "+a);else throw f;}d.debug("HTTP ["+b.status+", "+c+"] Status: "+e.Status);return e};Downsha.DownshaRemote.prototype.handleHttpError=
function(a,c,b){4!=a.readyState?d.error("HTTP [readyState: "+a.readyState+"]"):d.error("HTTP [readyState: "+a.readyState+", status: "+a.status+", textStatus: "+c+"] error: "+b)}})();
(function(){Downsha.MutableXMLHttpRequest=function(){Downsha.Logger.getInstance();this.initialize()};Downsha.inherit(Downsha.MutableXMLHttpRequest,XMLHttpRequest,!0);Downsha.MutableXMLHttpRequest.prototype.initialize=function(){var d=this,a;for(a in this.__proto__)if(0==a.indexOf("on")){var c=function(a){d["_"+arguments.callee._fieldName]=a};c._fieldName=a;this.__defineSetter__(a,c);c=function(){var a=arguments.callee._fieldName;return function(){if("function"==typeof d["_"+a])d["_"+a]();if("function"==
typeof d["_proto_"+a])d["_proto_"+a]()}};c._fieldName=a;this.__defineGetter__(a,c);this["_proto_"+a]=this.__proto__[a]}};Downsha.MutableXMLHttpRequest.prototype.become=function(d){if(d instanceof XMLHttpRequest){var a=this.__proto__;this.__proto__=d;this.constructor=Downsha.MutableXMLHttpRequest;for(var c in this)0==c.indexOf("on")&&this.hasOwnProperty(c)&&(a[c]=this["_proto_"+c],this["_proto_"+c]=this.__proto__[c],this.__proto__[c]=this[c]);for(c in this.constructor.prototype)if(this.constructor.prototype.hasOwnProperty(c)&&
!this.__proto__.hasOwnProperty(c))try{this.__proto__[c]=this.constructor.prototype[c]}catch(b){}}}})();
(function(){Downsha.DSTPRequest=function(d){Downsha.Logger.getInstance();this.initialize(d)};Downsha.DSTPRequest.prototype.Cmdid=null;Downsha.DSTPRequest.prototype.Seqid=null;Downsha.DSTPRequest.prototype.Protover=null;Downsha.DSTPRequest.prototype.UID=null;Downsha.DSTPRequest.prototype.SessID=null;Downsha.DSTPRequest.prototype.HID=null;Downsha.DSTPRequest.prototype.TID=null;Downsha.DSTPRequest.prototype.TermClass=null;Downsha.DSTPRequest.prototype.TermType=null;Downsha.DSTPRequest.prototype.YzVer=
null;Downsha.DSTPRequest.prototype.initialize=function(d){this.Cmdid=d;this.Seqid=Math.floor(65536*Math.random());this.Protover=Downsha.DownshaRemote.PROTO_VERSION;this.UID=Downsha.context.userId;this.SessID=Downsha.context.sessId;this.HID=Downsha.context.hardId;this.TID=Downsha.context.termId;this.TermClass=Downsha.context.termClass;this.TermType=Downsha.context.termType;this.YzVer=Downsha.context.version};Downsha.DSTPRequest.prototype.toJSON=function(){return{Cmdid:this.Cmdid,Seqid:this.Seqid,Protover:this.Protover,
UID:this.UID,SessID:this.SessID,HID:this.HID,TID:this.TID,TermClass:this.TermClass,TermType:this.TermType,YzVer:this.YzVer}}})();
(function(){var d=null;Downsha.DSTPResponse=function(a){d=Downsha.Logger.getInstance();this.__defineGetter__("data",this.getData);this.__defineSetter__("data",this.setData);this.__defineGetter__("error",this.getError);this.__defineSetter__("error",this.setError);this.initialize(a)};Downsha.DSTPResponse.fromObject=function(a){return a instanceof Downsha.DSTPResponse?a:new Downsha.DSTPResponse(a)};Downsha.DSTPResponse.prototype.Cmdid=null;Downsha.DSTPResponse.prototype.Seqid=null;Downsha.DSTPResponse.prototype.Protover=
null;Downsha.DSTPResponse.prototype.SessID=null;Downsha.DSTPResponse.prototype.NatIP=null;Downsha.DSTPResponse.prototype.SyncNo=null;Downsha.DSTPResponse.prototype.Status=null;Downsha.DSTPResponse.prototype._data=null;Downsha.DSTPResponse.prototype._error=null;Downsha.DSTPResponse.prototype.initialize=function(a){if("object"==typeof a&&("undefined"!=typeof a.Cmdid&&(this.Cmdid=a.Cmdid),"undefined"!=typeof a.Seqid&&(this.Seqid=a.Seqid),"undefined"!=typeof a.Protover&&(this.Protover=a.Protover),"undefined"!=
typeof a.SessID&&(this.SessID=a.SessID),"undefined"!=typeof a.NatIP&&(this.NatIP=a.NatIP),"undefined"!=typeof a.SyncNo&&(this.SyncNo=a.SyncNo),"undefined"!=typeof a.Status&&(this.Status=a.Status),this.data=a,null!=this.Status&&0>this.Status))this.error=new Downsha.DownshaError(this.Status)};Downsha.DSTPResponse.prototype.isError=function(){return null==this.Status||0>this.Status};Downsha.DSTPResponse.prototype.isSuccess=function(){return null!=this.Status&&0<=this.Status};Downsha.DSTPResponse.prototype.isErrorCode=
function(a){return null!=this.Status&&this.Status==a};Downsha.DSTPResponse.prototype.isInvalidUserAccountError=function(){return this.isErrorCode(Downsha.DownshaRemote.Error.INVALID_USER_ACCOUNT)};Downsha.DSTPResponse.prototype.isUserAccountExistError=function(){return this.isErrorCode(Downsha.DownshaRemote.Error.USER_ACCOUNT_EXIST)};Downsha.DSTPResponse.prototype.isUserAccountNotExistError=function(){return this.isErrorCode(Downsha.DownshaRemote.Error.USER_ACCOUNT_NOT_EXIST)};Downsha.DSTPResponse.prototype.isUserAccountOpenFailedError=
function(){return this.isErrorCode(Downsha.DownshaRemote.Error.USER_ACCOUNT_OPEN_FAILED)};Downsha.DSTPResponse.prototype.isUserPasswordIncorrectError=function(){return this.isErrorCode(Downsha.DownshaRemote.Error.USER_PASSWORD_INCORRECT)};Downsha.DSTPResponse.prototype.isTermInfoOpenFailedError=function(){return this.isErrorCode(Downsha.DownshaRemote.Error.TERM_INFO_OPEN_FAILED)};Downsha.DSTPResponse.prototype.isTermInfoCreateFailedError=function(){return this.isErrorCode(Downsha.DownshaRemote.Error.TERM_INFO_CREATE_FAILED)};
Downsha.DSTPResponse.prototype.isSessionNotExistError=function(){return this.isErrorCode(Downsha.DownshaRemote.Error.SESSION_NOT_EXIST)};Downsha.DSTPResponse.prototype.isSessionCreateFailedError=function(){return this.isErrorCode(Downsha.DownshaRemote.Error.SESSION_CREATE_FAILED)};Downsha.DSTPResponse.prototype.hasAuthenticationError=function(){return this.isInvalidUserAccountError()||this.isUserAccountExistError()||this.isUserAccountNotExistError()||this.isUserAccountOpenFailedError()||this.isUserPasswordIncorrectError()||
this.isTermInfoOpenFailedError()||this.isTermInfoCreateFailedError()||this.isSessionNotExistError()||this.isSessionCreateFailedError()};Downsha.DSTPResponse.prototype.getData=function(){return this._data};Downsha.DSTPResponse.prototype.setData=function(a){this._data=a};Downsha.DSTPResponse.prototype.getError=function(){return this._error};Downsha.DSTPResponse.prototype.setError=function(a){this._error=a};Downsha.DSTPResponse.createFrom=function(a){d=d||Downsha.Logger.getInstance(Downsha.DSTPResponse);
d.debug("Downsha.DSTPResponse.createFrom");return new Downsha.DSTPResponse(a)}})();
(function(){var d=null;Downsha.DownshaRemoteEx=function(){d=Downsha.Logger.getInstance();this.initialize()};Downsha.inherit(Downsha.DownshaRemoteEx,Downsha.DownshaRemote,!0);Downsha.DownshaRemoteEx.SESS_EXPIRATION=6E5;Downsha.DownshaRemoteEx.prototype.initialize=function(){this.parent.initialize.apply(this,[])};Downsha.DownshaRemoteEx.prototype._reloginAttempted=!1;Downsha.DownshaRemoteEx.prototype.register=function(a,c,b,e,f){d.debug("DownshaRemoteEx.register");return this.parent.register.apply(this,
arguments)};Downsha.DownshaRemoteEx.prototype.login=function(a,c,b,e,f,g){d.debug("DownshaRemoteEx.login");return this.parent.login.apply(this,arguments)};Downsha.DownshaRemoteEx.prototype.logout=function(a,c,b){d.debug("DownshaRemoteEx.logout");return this.parent.logout.apply(this,arguments)};Downsha.DownshaRemoteEx.prototype.putInfoItem=function(a,c,b,e){d.debug("DownshaRemoteEx.putInfoItem");return this.parent.putInfoItem.apply(this,arguments)};Downsha.DownshaRemoteEx.prototype.putFileDesc=function(a,
c,b,e){d.debug("DownshaRemoteEx.putFileDesc");return this.parent.putFileDesc.apply(this,arguments)};Downsha.DownshaRemoteEx.prototype.putFile=function(a,c,b,e){d.debug("DownshaRemoteEx.putFile");return this.parent.putFile.apply(this,arguments)};Downsha.DownshaRemoteEx.prototype.genThumbnail=function(a,c,b,e){d.debug("DownshaRemoteEx.genThumbnail");return this.parent.genThumbnail.apply(this,arguments)};Downsha.DownshaRemoteEx.prototype.getInfoItemList=function(a,c,b,e){d.debug("DownshaRemoteEx.getInfoItemList");
return this.parent.getInfoItemList.apply(this,arguments)};Downsha.DownshaRemoteEx.prototype.assureLogin=function(a,c){d.debug("DownshaRemoteEx.assureLogin");if(Downsha.context.userKnown)if(Downsha.context.sessTime+this.constructor.SESS_EXPIRATION>Date.now()){var b=new Downsha.DSTPResponse({Status:0});"function"==typeof a&&(d.debug("re-using existing login session"),setTimeout(function(){a(b,null,null)},1))}else return d.debug("Attempting to login using stored credentials for: "+Downsha.context.userName),
this.login(Downsha.context.userName,Downsha.XORCrypt.decrypt(Downsha.context.userPass,Downsha.context.userName),!0,a,c,!0);else"function"==typeof c&&c({readyState:0,status:0},null,null)};Downsha.DownshaRemoteEx.prototype._relogin=function(a){d.debug("DownshaRemoteEx._relogin");var c=this;Downsha.context.userKnown&&(d.debug("Attempting to relogin using stored credentials for: "+Downsha.context.userName),this.login(Downsha.context.userName,Downsha.XORCrypt.decrypt(Downsha.context.userPass,Downsha.context.userName),
!0,function(b,e,f){var g=a.success,h=a.failure;a.success=function(a,b,e){c._reloginAttempted=false;typeof g=="function"&&g(a,b,e)};a.failure=function(a,b,e){c._reloginAttempted=false;typeof h=="function"&&h(a,b,e)};if(b instanceof Downsha.DSTPResponse&&b.hasAuthenticationError()){d.debug("Handling original success callback due to soft-failed authentication");a.success(b,e,f)}else if(typeof g=="function"){d.debug("Retrying original request after successful relogin");c.doRequest.apply(c,a.arguments)}},
function(b,e,f){d.debug("Failed to relogin, handling original request's failure callback");c._reloginAttempted=false;typeof a.failure=="function"&&a.failure(b,e,f)},!0),d.debug("Making reloginAttempted"),this._reloginAttempted=!0)};Downsha.DownshaRemoteEx.prototype.handleHttpSuccess=function(a,c,b,e){d.debug("DownshaRemoteEx.handleHttpSuccess");c=this.parent.handleHttpSuccess.apply(this,[a,c,b,e]);if((c.isSessionNotExistError()||c.isSessionCreateFailedError())&&!this._reloginAttempted&&e.data.Cmdid!=
Downsha.DownshaRemote.Command.USER_LOGIN&&e.data.Cmdid!=Downsha.DownshaRemote.Command.USER_REGISTER&&e.data.Cmdid!=Downsha.DownshaRemote.Command.USER_LOGOUT)this._relogin(e);else if(c.isSuccess()&&(e.data.Cmdid==Downsha.DownshaRemote.Command.USER_LOGIN||e.data.Cmdid==Downsha.DownshaRemote.Command.USER_REGISTER))Downsha.context.sessId=a.SessID,Downsha.context.sessTime=Date.now();return c};Downsha.DownshaRemoteEx.prototype.handleHttpError=function(a,c,b,e){d.debug("DownshaRemoteEx.handleHttpError");
this.parent.handleHttpError.apply(this,Array.prototype.slice.call(arguments))}})();if("undefined"==typeof ExtractContentJS)var ExtractContentJS={};"undefined"==typeof ExtractContentJS.Lib&&(ExtractContentJS.Lib={});
ExtractContentJS.Lib.Util=function(){var d={BenchmarkTimer:function(){var a=function(){var a=new Date,b=0,b=a.getHours(),b=b*60+a.getMinutes(),b=b*60+a.getSeconds();return b=b*1E3+a.getMilliseconds()},c=function(){var b={elapsed:0,reset:function(){b.elapsed=0;return b},start:function(){b.msec=a();return b},stop:function(){b.elapsed=b.elapsed+(a()-b.msec);return b}};return b.start()},b={timers:{},get:function(a){b.timers[a]||(b.timers[a]=new c);return b.timers[a]},reset:function(a){return b.get(a).reset()},
start:function(a){return b.get(a).start()},stop:function(a){return b.get(a).stop()}};return b},Token:function(a){var c={hiragana:/[\u3042-\u3093\u304C-\u307C\u3041-\u3087\u308E\u3063\u30FC]/,katakana:/[\u30A2-\u30F3\u30AC-\u30DC\u30A1-\u30E7\u30EE\u30C3\u30FC]/,kanji:{test:function(a){return"\u4e00"<=a&&a<="\u9fa0"||a==="\u3005"}},alphabet:/[a-zA-Z]/,digit:/[0-9]/},b=function(a){var b={},e;for(e in c)c[e].test(a)&&(b[e]=c[e]);return b},e={first:b(a.charAt(0)),last:b(a.charAt(a.length-1)),isTokenized:function(a,
b){var c=a.length?a.charAt(a.length-1):"",d=b.length?b.charAt(0):"",i=function(a,b){if(a.length)for(var c in b)if(b[c].test(a))return false;return true};return i(c,e.first)&&i(d,e.last)}};return e},inherit:function(a,c){var b=a||{},e;for(e in c)typeof b[e]=="undefined"&&(b[e]=c[e]);return b},countMatch:function(a,c){return a.split(c).length-1},countMatchTokenized:function(a,c){for(var b=0,e=null,f=new d.Token(c),g=a.split(c),h=g.length,j=0;j<h;j++){e&&f.isTokenized(e,g[j])&&b++;e=g[j]}return b},indexOfTokenized:function(a,
c){var b=a.indexOf(c);if(b>=0){var e=new d.Token(c),f=b>1?a.substr(b-1,1):"",g=a.substr(b+c.length,1);if(e.isTokenized(f,g))return b}return-1},dump:function(a){if(typeof a=="undefined")return"undefined";if(typeof a=="string")return'"'+a+'"';if(typeof a!="object")return""+a;if(a===null)return"null";if(a instanceof Array)return"["+a.map(function(){return"obj"}).join(",")+"]";var c=[],b;for(b in a)c.push(b+":obj");return"{"+c.join(",")+"}"}};return d}();
ExtractContentJS.Lib.A=function(){var d={};d.indexOf=Array.indexOf||function(a,c){var b=2,e=a.length,b=Number(arguments[b++])||0,b=b<0?Math.ceil(b):Math.floor(b);for(b<0&&(b=b+e);b<e;b++)if(b in a&&a[b]===c)return b;return-1};d.filter=Array.filter||function(a,c){var b=2,e=a.length;if(typeof c!="function")throw new TypeError("A.filter: not a function");for(var d=[],b=arguments[b++],g=0;g<e;g++)if(g in a){var h=a[g];c.call(b,h,g,a)&&d.push(h)}return d};d.forEach=Array.forEach||function(a,c){var b=2,
e=a.length;if(typeof c!="function")throw new TypeError("A.forEach: not a function");for(var b=arguments[b++],d=0;d<e;d++)d in a&&c.call(b,a[d],d,a)};d.every=Array.every||function(a,c){var b=2,e=a.length;if(typeof c!="function")throw new TypeError("A.every: not a function");for(var b=arguments[b++],d=0;d<e;d++)if(d in a&&!c.call(b,a[d],d,a))return false;return true};d.map=Array.map||function(a,c){var b=2,e=a.length;if(typeof c!="function")throw new TypeError("A.map: not a function");for(var d=Array(e),
b=arguments[b++],g=0;g<e;g++)g in a&&(d[g]=c.call(b,a[g],g,a));return d};d.some=Array.some||function(a,c){var b=2,e=a.length;if(typeof c!="function")throw new TypeError("A.some: not a function");for(var b=arguments[b++],d=0;d<e;d++)if(d in a&&c.call(b,a[d],d,a))return true;return false};d.reduce=Array.reduce||function(a,c){var b=2,e=a.length;if(typeof c!="function")throw TypeError("A.reduce: not a function ");var d=0;if(arguments.length>b)var g=arguments[b++];else{do{if(d in a){g=a[d++];break}if(++d>=
e)throw new TypeError("A.reduce: empty array");}while(1)}for(;d<e;d++)d in a&&(g=c.call(null,g,a[d],d,a));return g};d.zip=function(a){if(a[0]instanceof Array){for(var c=a[0].length,b=a.length,e=Array(c),d=0;d<c;d++){e[d]=[];for(var g=0;g<b;g++)e[d].push(a[g][d])}return e}return[]};d.first=function(a){return a?a[0]:null};d.last=function(a){return a?a[a.length-1]:null};d.push=function(a,c){return Array.prototype.push.apply(a,c)};return d}();
ExtractContentJS.Lib.DOM=function(){var d=ExtractContentJS.Lib.A,a={getElementStyle:function(a,b){var e=a.style?a.style[b]:null;if(!e){var d=a.ownerDocument.defaultView;if(d&&d.getComputedStyle){try{var g=d.getComputedStyle(a,null)}catch(h){return null}b=b.replace(/([A-Z])/g,"-$1").toLowerCase();e=g?g.getPropertyValue(b):null}else a.currentStyle&&(e=a.currentStyle[b])}return e},text:function(a){return typeof a.textContent!="undefined"?a.textContent:a.nodeName=="#text"?a.nodeValue:typeof a.innerText!=
"undefined"?a.innerText:null},ancestors:function(a){for(var b=a.ownerDocument.body,e=[];a!=b;){e.push(a);a=a.parentNode}e.push(b);return e},commonAncestor:function(c,b){for(var e=a.ancestors(c).reverse(),d=a.ancestors(b).reverse(),g=null,h=0;e[h]&&d[h]&&e[h]==d[h];h++)g=e[h];return g},countMatchTagAttr:function(c,b,e,f){var g=function(a){return a.test(c[e])};if((c.tagName||"").toLowerCase()==b&&d.some(f,g))return 1;for(var g=0,h=c.childNodes,j=0,i=h.length;j<i;j++)g=g+a.countMatchTagAttr(h[j],b,e,
f);return g},matchTag:function(c,b){return d.some(b,function(b){return typeof b=="string"?b==(c.tagName||"").toLowerCase():b instanceof Array?b[0]==(c.tagName||"").toLowerCase()&&a.matchAttr(c,b[1]):false})},matchAttr:function(c,b){var e=function(b,f){if(typeof b=="string")return b==f;if(b instanceof RegExp)return b.test(f);if(b instanceof Array)return d.some(b,function(a){return e(a,f)});if(b instanceof Object)for(var g in b){var h=c[g];if(h&&a.matchAttr(h,b[g]))return true}return false},f;for(f in b){var g=
c[f],h=b[f];if(g)return e(h,g)}return false},matchStyle:function(c,b){var e=function(a,b){return typeof a=="string"?a==b:a instanceof RegExp?a.test(b):a instanceof Array?d.some(a,function(a){return e(a,b)}):false},f;for(f in b)if(e(b[f],a.getElementStyle(c,f)))return true;return false}};return a}();"undefined"==typeof ExtractContentJS&&(ExtractContentJS={});
(function(d){var a=d.Lib.Util,c=d.Lib.A,b=d.Lib.DOM,e=a.inherit(function(a,c,d,e){var f=d||{},g=e||1048576;return{node:a,depth:c||0,inside:f,statistics:function(){var c=(b.text(a)||"").replace(/\s+/g," "),d=c.length;return{text:c.substr(0,g),noLinkText:f.link||f.form?"":c,listTextLength:f.list?d:0,noListTextLength:f.list?0:d,linkCount:f.link?1:0,listCount:f.li?1:0,linkListCount:f.li&&f.link?1:0}}}},{commonAncestor:function(){var a=c.map(arguments,function(a){return a.node});return a.length<2?a[0]:
c.reduce(a,function(a,c){return b.commonAncestor(a,c)})},mergeStatistics:function(a,b){var c={},d;for(d in a)c[d]=a[d]+b[d];return c}}),f=function(a){var a=c.filter(a,function(a){a=b.text(a.node)||"";a=a.replace(/\s+/g,"");return a.length!=0}),d={score:0,leaves:a,commonAncestor:function(){return e.commonAncestor.apply(null,d.leaves)}};return d},g=function(a){var d={_content:a,asLeaves:function(){return d._content},asNode:function(){if(d._node)return d._node;d._node=e.commonAncestor.apply(null,d._content);
return d._node},asTextFragment:function(){if(d._textFragment)return d._textFragment;if(d._content.length<1)return"";d._textFragment=c.reduce(d._content,function(a,c){var d=b.text(c.node),d=d.replace(/^\s+/g,"").replace(/\s+$/g,""),d=d.replace(/\s+/g," ");return a+d},"");return d._textFragment},asText:function(){if(d._text)return d._text;var a=d.asNode();d._text=a?b.text(a):"";return d._text},toString:function(){return d.asTextFragment()}};return d};d.LayeredExtractor=function(a,b){var c={handler:a||
[],filter:b||{},factory:{getHandler:function(a){return typeof d.LayeredExtractor.Handler!="undefined"?new d.LayeredExtractor.Handler[a]:null}},addHandler:function(a){typeof a!="undefined"&&c.handler.push(a);return c},filterFor:function(){},extract:function(a){for(var b=a.location.href,d={title:a.title,url:a.location.href},e=c.handler.length,f=0;f<e;f++){var h=c.handler[f].extract(a,b,d);if(h){var j=c.filterFor(b);j&&(h=j.filter(h));h=new g(h);if(h.toString().length){d.content=h;d.isSuccess=true;d.engine=
d.engine||c.handler[f];break}}}return d}};return c};d.LayeredExtractor.Handler={};d.LayeredExtractor.Handler.Heuristics=function(d,g){var i={name:"Heuristics",content:[],opt:a.inherit(d,{threshold:60,minLength:30,factor:{decay:0.75,noBody:0.72,continuous:1.16},punctuationWeight:10,minNoLink:8,noListRatio:0.2,limit:{leaves:800,recursion:20,text:1048576},debug:false}),pat:a.inherit(g,{sep:["div","center","td","h1","h2"],waste:[/Copyright|All\s*Rights?\s*Reserved?/i],affiliate:[/amazon[a-z0-9\.\/\-\?&]+-22/i],
list:["ul","dl","ol"],li:["li","dd"],a:["a"],form:["form"],noContent:["frameset"],ignore:["iframe","img","script","style","select","noscript",["div",{id:[/more/,/menu/,/side/,/navi/],className:[/more/,/menu/,/side/,/navi/]}]],ignoreStyle:{display:"none",visibility:"hidden"},punctuations:/[\u3002\u3001\uFF0E\uFF0C\uFF01\uFF1F]|\.[^A-Za-z0-9]|,[^0-9]|!|\?/})},k=a.inherit(function(d){var g=new f(d);g.eliminateLinks=function(){var a=c.map(g.leaves,function(a){return a.statistics()});if(!a.length)return"";
var a=a.length==1?a[0]:c.reduce(a,function(a,b){return e.mergeStatistics(a,b)}),b=a.noLinkText.length,d=a.listTextLength;if(b<i.opt.minNoLink*a.linkCount)return"";var f=a.linkListCount/(a.listCount||1);return b<i.opt.noListRatio*f*f*d?"":a.noLinkText};g.noBodyRate=function(){var d=0;g.leaves.length>0&&(d=d+c.reduce(g.leaves,function(a,c){return a+b.countMatchTagAttr(c.node,"a","href",i.pat.affiliate)},0));return d=d/2+c.reduce(i.pat.waste,function(b,c){return b+a.countMatch(g._nolink,c)},0)};g.calcScore=
function(b,c){g._nolink=g.eliminateLinks();if(g._nolink.length<i.opt.minLength)return 0;var d=a.countMatch(g._nolink,i.pat.punctuations),d=d*i.opt.punctuationWeight,d=d+g._nolink.length,d=d*b,e=g.noBodyRate(),d=d*Math.pow(i.opt.factor.noBody,e);g._c=g.score=d;g._c1=d*c;return d};g.isAccepted=function(){return g._c>i.opt.threshold};g.isContinuous=function(){return g._c1>i.opt.threshold};g.merge=function(a){g.score=g.score+a._c1;g.depth=Math.min(g.depth,a.depth);c.push(g.leaves,a.leaves);return g};
return g},{split:function(a){var c=[],d=[],f=0,g=i.opt.limit.text,h=function(a){if(a&&d.length){c.push(new k(d));d=[]}},j=function(a,l,k){if(f>=i.opt.limit.leaves||l>=i.opt.limit.recursion||a.nodeName=="#comment"||b.matchTag(a,i.pat.ignore)||b.matchStyle(a,i.pat.ignoreStyle))return c;for(var u=a.childNodes,y=i.pat.sep,v=u.length,k={form:k.form||b.matchTag(a,i.pat.form),link:k.link||b.matchTag(a,i.pat.a),list:k.list||b.matchTag(a,i.pat.list),li:k.li||b.matchTag(a,i.pat.li)},t=0;t<v;t++){var w=u[t],
x=b.matchTag(w,y);h(x);j(w,l+1,k);h(x)}if(!v){f++;d.push(new e(a,l,k,g))}return c};j(a,0,{});h(true);return c}});i.extract=function(a){if(c.some(i.pat.noContent,function(b){return a.getElementsByTagName(b).length!=0}))return i;for(var b=1,d=1,e=[],f=k.split(a.body),g,h=f.length,j=0;j<h;j++){var p=f[j];g&&(d=d/i.opt.factor.continuous);if(p.calcScore(b,d)){b=b*i.opt.factor.decay;if(p.isAccepted()){if(p.isContinuous()&&g)g.merge(p);else{g=p;e.push(p)}d=i.opt.factor.continuous}else g||(b=1)}}i.blocks=
e.sort(function(a,b){return b.score-a.score});if(b=c.first(i.blocks))i.content=b.leaves;return i.content};return i};d.LayeredExtractor.Handler.GoogleAdSection=function(b){var d={name:"GoogleAdSection",content:[],state:[],opt:a.inherit(b,{limit:{leaves:800,recursion:20},debug:false})},g=/google_ad_section_start\(weight=ignore\)/i,k=/google_ad_section_start/i,l=/google_ad_section_end/i;d.inSection=function(){return c.last(d.state)==2};d.ignore=function(){d.state.push(1)};d.section=function(){d.state.push(2)};
d.end=function(){d.state.length&&d.state.pop()};d.parse=function(a,b){var c=b||0;if(a.nodeName=="#comment")g.test(a.nodeValue)?d.ignore():k.test(a.nodeValue)?d.section():l.test(a.nodeValue)&&d.end();else if(!(d.content.length>=d.opt.limit.leaves)&&!(c>=d.opt.limit.recursion)){for(var f=a.childNodes,h=f.length,s=0;s<h;s++)d.parse(f[s],c+1);!h&&d.inSection()&&d.content.push(new e(a,c))}};d.extract=function(a){d.parse(a);d.blocks=[new f(d.content)];return d.content};return d}})(ExtractContentJS);
(function(){var d=null;Downsha.SelectionFinder=function(a){d=Downsha.Logger.getInstance();this.initDocument=this.document=a?a:document};Downsha.SelectionFinder.prototype.initDocument=null;Downsha.SelectionFinder.prototype.document=null;Downsha.SelectionFinder.prototype.selection=null;Downsha.SelectionFinder.prototype.reset=function(){this.document=this.initDocument;this.selection=null};Downsha.SelectionFinder.prototype.hasSelection=function(){var a=this.getRange();return a&&(a.startContainer!=a.endContainer||
a.startContainer==a.endContainer&&a.startOffset!=a.endOffset)?true:false};Downsha.SelectionFinder.prototype.find=function(a){a=this._findSelectionInDocument(this.document,a);this.document=a.document;this.selection=a.selection};Downsha.SelectionFinder.prototype.getRange=function(){if(!this.selection||this.selection.rangeCount==0)return null;if(typeof this.selection.getRangeAt=="function")return this.selection.getRangeAt(0);var a=this.document.createRange();a.setStart(this.selection.anchorNode,this.selection.anchorOffset);
a.setEnd(this.selection.focusNode,this.selection.focusOffset);return a};Downsha.SelectionFinder.prototype._findSelectionInDocument=function(a,c){var b=null,e=false,f=null;try{f=a.defaultView?a.defaultView:window}catch(g){this._verboseLog&&d.debug("Could not retrieve default view... using default window");f=window}if(typeof f.getSelection=="function")(b=f.getSelection())&&typeof b.rangeCount!="undefined"&&b.rangeCount>0&&(e=true);else if(f.selection&&typeof f.selection.createRange=="function"){b=f.selection.createRange();
typeof f.selection.type=="Text"&&typeof b.htmlText=="string"&&b.htmlText.length>0&&(e=true)}else if(a.selection&&a.selection.createRange){b=a.selection.createRange();typeof a.selection.type=="Text"&&typeof b.htmlText=="string"&&b.htmlText.length>0&&(e=true)}if(b&&!e&&c){e=Downsha.Utils.findDocuments(a);if(e.length>0){this._verboseLog&&d.debug("find selection range empty, trying frames, count: "+e.length);for(f=0;f<e.length;f++)if(e[f]){this._verboseLog&&d.debug("trying nested doc: "+e[f]);var h=this._findSelectionInDocument(e[f],
c);if(h&&h.selection&&h.selection.rangeCount>0)return h}}}return{document:a,selection:b}}})();
(function(){Downsha.ClipStyle=function(d,a){this.__defineGetter__("styleFilter",this.getFilter);this.__defineSetter__("styleFilter",this.setFilter);this.initialize(d,a)};Downsha.ClipStyle.stylePrefix=function(d){if(typeof d=="string"){var a=0;if((a=d.indexOf("-"))>0)return d.substring(0,a)}return d};Downsha.ClipStyle.findFontFaceRules=function(d){for(var d=(d||document).styleSheets,a=[],c=0;c<d.length;c++){var b=d[c];if(b.cssRules)for(var e=0;e<b.cssRules.length;e++){var f=b.cssRules[e];f instanceof
CSSFontFaceRule&&a.push(f)}}return a};Downsha.ClipStyle.prototype.length=0;Downsha.ClipStyle.prototype._filter=null;Downsha.ClipStyle.prototype.initialize=function(d,a){this.styleFilter=a;if(d instanceof CSSRuleList||d instanceof Array){if(d.length>0)for(var c=0;c<d.length;c++)this.addStyle(d[c].style)}else d instanceof CSSStyleRule?this.addStyle(d.style):d instanceof CSSStyleDeclaration?this.addStyle(d):typeof d=="object"&&d!=null&&this.addStyle(d)};Downsha.ClipStyle.prototype._addSimpleStyle=function(d,
a){typeof this[d]=="undefined"&&this.length++;this[d]=a};Downsha.ClipStyle.STYLES=["background-attachment","background-clip","background-color","background-image","background-origin","background-position","background-repeat","background-size","border-bottom-color","border-bottom-left-radius","border-bottom-right-radius","border-bottom-style","border-bottom-width","border-collapse","border-left-color","border-left-style","border-left-width","border-right-color","border-right-style","border-right-width",
"border-spacing","border-top-color","border-top-left-radius","border-top-right-radius","border-top-style","border-top-width","bottom","box-shadow","caption-side","clear","clip","color","content","counter-increment","counter-reset","cursor","direction","display","empty-cells","float","font-family","font-size","font-size-adjust","font-stretch","font-style","font-variant","font-weight","height","ime-mode","left","letter-spacing","line-height","list-style-image","list-style-position","list-style-type",
"margin-bottom","margin-left","margin-right","margin-top","marker-offset","max-height","max-width","min-height","min-width","opacity","outline-color","outline-offset","outline-style","outline-width","overflow","overflow-x","overflow-y","padding-bottom","padding-left","padding-right","padding-top","page-break-after","page-break-before","pointer-events","position","resize","right","table-layout","text-align","text-decoration","text-indent","text-overflow","text-shadow","text-transform","top","vertical-align",
"visibility","white-space","width","word-spacing","word-wrap","z-index","text-anchor"];Downsha.ClipStyle.prototype.addStyle=function(d){if(d instanceof CSSStyleDeclaration&&d.length>0)for(var a=0;a<Downsha.ClipStyle.STYLES.length;a++){var c=Downsha.ClipStyle.STYLES[a],b=d.getPropertyValue(c);(!this.styleFilter||this.styleFilter(c,b))&&this._addSimpleStyle(c,b)}else if(d instanceof Downsha.ClipStyle)for(c in d){if(typeof this.constructor.prototype[c]=="undefined"&&(!this.styleFilter||this.styleFilter(c,
d[c]))){b=d[c];this._addSimpleStyle(c,b)}}else if(typeof d=="object"&&d!=null)for(c in d)if((!this.styleFilter||this.styleFilter(c,d[c]))&&typeof d[c]!="function"&&typeof this.constructor.prototype[c]=="undefined"){b=d[c];this._addSimpleStyle(c,b)}};Downsha.ClipStyle.prototype.removeStyle=function(d,a){function c(c,d){if(typeof b[c]!="undefined"&&typeof b.constructor.prototype[c]=="undefined"&&(typeof a=="function"||b[c]==d))(typeof a!="function"||typeof a=="function"&&a(c,b[c],d))&&delete b[c]&&
b.length--}var b=this;if(d instanceof CSSStyleDeclaration&&d.length>0)for(var e=0;e<d.length;e++){var f=d[e];c(f,d.getPropertyValue(f))}else if(d instanceof Downsha.ClipStyle&&d.length>0)for(f in d)c(f,d[f]);else if(d instanceof Array)for(e=0;e<d.length;e++)c(d[e],this[d[e]]);else typeof d=="string"&&c(d,this[d])};Downsha.ClipStyle.prototype.removeStyleIgnoreValue=function(d){this.removeStyle(d,function(){return true})};Downsha.ClipStyle.styleInArray=function(d,a){if(typeof d!="string"||!(a instanceof
Array))return false;for(var c=-1,b=d.toLowerCase(),e=(c=b.indexOf("-"))>0?b.substring(0,c):b,c=0;c<a.length;c++)if(a[c]==b||a[c]==e)return true;return false};Downsha.ClipStyle.prototype.deriveStyle=function(d,a,c){this.removeStyle(d,function(b,d,f){return c instanceof Array&&Downsha.ClipStyle.styleInArray(b,c)?false:typeof a[b]!="undefined"&&d==f})};Downsha.ClipStyle.prototype.setFilter=function(d){if(typeof d=="function")this._filter=d;else if(d==null)this._filter=null};Downsha.ClipStyle.prototype.getFilter=
function(){return this._filter};Downsha.ClipStyle.prototype.mergeStyle=function(d,a){if(d instanceof Downsha.ClipStyle&&d.length>0){var c=true,b;for(b in d)if(!(typeof this.constructor.prototype[b]!="undefined"||typeof this.__lookupSetter__(b)!="undefined"))if((c=typeof this[b]=="undefined")||a){this[b]=d[b];c&&this.length++}}};Downsha.ClipStyle.prototype.clone=function(){var d=new Downsha.ClipStyle,a;for(a in this)typeof this.constructor.prototype[a]=="undefined"&&(d[a]=this[a]);d.length=this.length;
return d};Downsha.ClipStyle.prototype.toString=function(){var d="",a={};if(this["background-image"]){d=d+("background-image:"+this["background-image"]+";");a["background-image"]=true}if(this["background-position"])d=d+("background-position:"+this["background-position"]+";");else if(this["background-position-x"]||this["background-position-y"])d=d+("background-position:"+(this["background-position-x"]?this["background-position-x"]:"0%")+" "+(this["background-position-y"]?this["background-position-y"]:
"0%")+";");a["background-position-x"]=true;a["background-position-y"]=true;a["background-position"]=true;var c=this["background-repeat-x"]?this["background-repeat-x"]:"initial",b=this["background-repeat-y"]?this["background-repeat-y"]:"initial",d=c=="initial"&&b=="initial"?d+("background-repeat:"+this["background-repeat"]+";"):d+("background-repeat:"+c+" "+b+";");a["background-repeat-x"]=true;a["background-repeat-y"]=true;a["background-repeat"]=true;if(this.length>0)for(var e in this)typeof this[e]!=
"string"||typeof this.constructor.prototype[e]!="undefined"||this[e].length==0||typeof a[e]!="undefined"||(d=d+(e+":"+this[e]+";"));return d}})();
(function(){Downsha.ClipStylingStrategy=function(d){this.initialize(d)};Downsha.ClipStylingStrategy.prototype.initialize=function(d){this.window=d};Downsha.ClipStylingStrategy.prototype.cleanUp=function(){return true};Downsha.ClipStylingStrategy.prototype.styleForNode=function(){return null};Downsha.ClipStylingStrategy.prototype.getNodeView=function(d){d=d.ownerDocument;return d.defaultView?d.defaultView:this.window};Downsha.ClipStylingStrategy.prototype.getFontFaceRules=function(d){return Downsha.ClipStyle.findFontFaceRules(d)};
Downsha.ClipStylingStrategy.prototype.getNodeStyle=function(d,a){var c=new Downsha.ClipStyle;if(d&&typeof d.nodeType=="number"&&d.nodeType==1){c=d.ownerDocument;c=new Downsha.ClipStyle((c.defaultView?c.defaultView:this.window).getComputedStyle(d,null),a)}return c}})();
(function(){Downsha.ClipTextStylingStrategy=function(d){this.initialize(d)};Downsha.inherit(Downsha.ClipTextStylingStrategy,Downsha.ClipStylingStrategy);Downsha.ClipTextStylingStrategy.COLOR_THRESH=50;Downsha.ClipTextStylingStrategy.FORMAT_NODE_NAMES={b:null,big:null,em:null,i:null,small:null,strong:null,sub:null,sup:null,ins:null,del:null,s:null,strike:null,u:null,code:null,kbd:null,samp:null,tt:null,"var":null,pre:null,listing:null,plaintext:null,xmp:null,abbr:null,acronym:null,address:null,bdo:null,
blockquote:null,q:null,cite:null,dfn:null};Downsha.ClipTextStylingStrategy.STYLE_ATTRS={font:null,text:null,color:null};Downsha.ClipTextStylingStrategy.prototype.isFormatNode=function(d){return d&&d.nodeType==1&&typeof Downsha.ClipTextStylingStrategy.FORMAT_NODE_NAMES[d.nodeName.toLowerCase()]!="undefined"};Downsha.ClipTextStylingStrategy.prototype.hasTextNodes=function(d){if(d&&d.nodeType==1&&d.childNodes.length>0)for(var a=0;a<d.childNodes.length;a++)if(d.childNodes[a].nodeType==3)return true;return false};
Downsha.ClipTextStylingStrategy.prototype.styleFilter=function(d){d=Downsha.ClipStyle.stylePrefix(d.toLowerCase());if(typeof Downsha.ClipTextStylingStrategy.STYLE_ATTRS[d]!="undefined")return true};Downsha.ClipTextStylingStrategy.prototype.styleForNode=function(d){var a=null;if(this.isFormatNode(d)||this.hasTextNodes(d))a=this.getNodeStyle(d,this.styleFilter);if(a&&a.color){var d=a.color.replace(/[^0-9,\s]+/g,"").replace(/[,\s]+/g," ").split(/\s+/),c=parseInt(d[0]),c=isNaN(c)?0:c,b=parseInt(d[1]),
b=isNaN(b)?0:c,e=parseInt(d[2]),e=isNaN(e)?0:e;if(c+b+e>(255-Downsha.ClipTextStylingStrategy.COLOR_THRESH)*3){c=Math.max(0,c-Downsha.ClipTextStylingStrategy.COLOR_THRESH);b=Math.max(0,b-Downsha.ClipTextStylingStrategy.COLOR_THRESH);e=Math.max(0,e-Downsha.ClipTextStylingStrategy.COLOR_THRESH)}a.color=d.length==4?"rgba("+[c,b,e,1].join(", ")+")":"rgb("+[c,b,e].join(", ")+")"}return a}})();
(function(){var d=null;Downsha.ClipFullStylingStrategy=function(a){d=Downsha.Logger.getInstance();this.initialize(a)};Downsha.inherit(Downsha.ClipFullStylingStrategy,Downsha.ClipStylingStrategy);Downsha.ClipFullStylingStrategy.ALWAYS_KEEP={"*":["quotes","height","width","margin","padding","top","left","right","bottom","float","clear","background","background-image","background-color","background-position","background-repeat","border-bottom-color","border-collapse","border-bottom-left-radius","border-bottom-right-radius",
"border-bottom-style","border-bottom-width","border-left-color","border-left-style","border-left-width","border-right-color","border-right-style","border-right-width","border-spacing","border-top-color","border-top-left-radius","border-top-right-radius","border-top-style","border-top-width","display","font","font-size","color","text-decoration","list-style-type","margin-bottom","margin-left","margin-right","margin-top"],img:["width","height"]};Downsha.ClipFullStylingStrategy.prototype.styleForNode=
function(a,c,b,e){var f=this.getNodeStyle(a,null);!e&&a.parentNode&&(e=this.getNodeStyle(a.parentNode,null));f.deriveStyle(e,f,Downsha.ClipFullStylingStrategy.ALWAYS_KEEP["*"]);b&&this.evaluateWidth(c,a,f,e);if(a==c||a.nodeName=="BODY"){d.debug("Handling extra styles for root element");f._addSimpleStyle("padding","0px");f._addSimpleStyle("margin","0px");f.position?f.position="relative":f._addSimpleStyle("position","relative");b||this.processRootNodeStyles(a,f,false)}if(!b){b=this.getOffsetRect(c);
c._downsha_absolute_xOffset=b.left;c._downsha_absolute_yOffset=b.top;f.position=="absolute"&&this.evaluateAbsolutePosition(c,a,f)}if(typeof a.style!="undefined"){a=a.style;for(c=0;c<a.length;c++)f._addSimpleStyle(a[c],a.getPropertyValue(a[c]))}f.removeStyle("quotes");return f};Downsha.ClipFullStylingStrategy.prototype.evaluateWidth=function(a,c,b,d){if(parseInt(b["margin-left"])==0&&parseInt(b["margin-right"])==0&&(parseInt(d.width)-parseInt(c.offsetWidth))/2==parseInt(c.offsetLeft)){b._addSimpleStyle("margin-left",
"auto");b._addSimpleStyle("margin-right","auto")}};Downsha.ClipFullStylingStrategy.prototype.processRootNodeStyles=function(a,c,b){d.debug("Handling extra styles for root element");c._addSimpleStyle("padding","0px");c._addSimpleStyle("margin","0px");c._addSimpleStyle("position","relative");if(b){b=this._inhBackgroundForNode(a,true);if(c["background-image"]=="none"){c.removeStyle("background-image");c.removeStyle("background-repeat");c.removeStyle("background-position")}c["background-color"]=="transparent"&&
c.removeStyle("background-color");b.length>0&&c.mergeStyle(b,false);a=this._inhFontForNode(a,true);a.length>0&&c.mergeStyle(a,false);c["float"]&&c.removeStyle("float")}};Downsha.ClipFullStylingStrategy.prototype.evaluateAbsolutePosition=function(a,c,b){b||(b=this.getNodeStyle(c,null));var d=this.getOffsetRect(c),c=d.left,d=d.top;if(typeof a._downsha_absolute_xOffset=="number"&&typeof a._downsha_absolute_yOffset=="number"){c=Math.max(0,c-a._downsha_absolute_xOffset);d=Math.max(0,d-a._downsha_absolute_yOffset);
b._addSimpleStyle("left",c+"px");b._addSimpleStyle("top",d+"px")}else{a._downsha_absolute_xOffset=c;a._downsha_absolute_yOffset=d;b._addSimpleStyle("top","0px");b._addSimpleStyle("left","0px")}b.removeStyle("right");b.removeStyle("bottom")};Downsha.ClipFullStylingStrategy.prototype.getOffsetRect=function(a){var c=a.getBoundingClientRect(),b=a.ownerDocument.body,a=a.ownerDocument.documentElement,d=c.left+(window.pageXOffset||a.scrollLeft||b.scrollLeft)-(a.clientLeft||b.clientLeft||0);return{top:Math.round(c.top+
(window.pageYOffset||a.scrollTop||b.scrollTop)-(a.clientTop||b.clientTop||0)),left:Math.round(d)}};Downsha.ClipFullStylingStrategy.prototype._inhBackgroundForNode=function(a,c){d.debug("ClipFullStylingStrategy._inhBackgroundForNode()");for(var b=a.parentNode,e=[],f=[],g=["background-repeat-x","background-repeat-y","background-position-x","background-position-y","background-origin","background-size"],h=this.window.document.body.parentNode?this.window.document.body.parentNode:this.window.document.body;b;){f.push(b);
e.push(this.getNodeStyle(b,function(a,b){return a=="background-color"||a=="background-image"&&b!="none"||g.indexOf(a)>=0||a=="opacity"||a=="filter"?true:false}));if(!c||b==h)break;else b=b.parentNode}d.debug("Retracted "+e.length+" styles");for(var b=new Downsha.ClipStyle,j=h=0;j<e.length;j++){var i=e[j],k=f[j];if(i["background-color"]&&i["background-color"]!="transparent"&&!i["background-color"].match(/rgba\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*,\s*0\s*\)/)&&!b["background-color"]){d.debug("Setting background-color: "+
i["background-color"]);h=j;b._addSimpleStyle("background-color",i["background-color"])}if(i["background-image"]&&!b["background-image"]&&(j==h||!b["background-color"])){d.debug("Adding background-image: "+i["background-image"]);b._addSimpleStyle("background-image",i["background-image"]);for(var l=0;l<g.length;l++){var m=g[l];if(i[m]&&m.indexOf("background-repeat")<0){d.debug("Adding "+m);b._addSimpleStyle(m,i[m])}}l=i["background-repeat-x"]&&i["background-repeat-x"]!="initial"?i["background-repeat-x"]:
"no-repeat";m=i["background-repeat-y"]&&i["background-repeat=y"]!="initial"?i["background-repeat-y"]:"no-repeat";b._addSimpleStyle("background-repeat-x",l);b._addSimpleStyle("background-repeat-y",l);b._addSimpleStyle("background-repeat",l+" "+m);if(k){d.debug("Dettermining background image offset");var m=this.getOffsetRect(k),n=this.getOffsetRect(a),l=n.top-m.top,n=n.left-m.left;d.debug("xDelta: "+n+"; yDelta: "+l);var o=this.getNodeView(k).getComputedStyle(k,null).getPropertyValue("background-position").split(" "),
k=o[0],r=o[1];d.debug("bg position: "+k+" "+r);var q=0,o=0,q=k.indexOf("%")>0?m.width*(parseInt(k)/100):parseInt(k),o=r.indexOf("%")>0?m.height*(parseInt(r)/100):parseInt(r);isNaN(q)&&(q=0);isNaN(o)&&(o=0);d.debug("origPosX: "+q+"; origPosY: "+o);m=0-n+q;l=0-l+o;d.debug("xOffset: "+m+"; yOffset: "+l);b._addSimpleStyle("background-position",m+"px "+l+"px")}}i.opacity&&!b.opacity&&!isNaN(parseFloat(i.opacity))&&(typeof b.opacity=="undefined"||parseFloat(i.opacity)<parseFloat(b.opacity))&&b._addSimpleStyle("opacity",
i.opacity);i.filter&&!b.filter&&(typeof b.filter=="undefined"||parseFloat(i.filter.replace(/[^0-9]+/g,""))<parseFloat(b.filter.replace(/[^0-9]+/g,"")))&&b._addSimpleStyle("filter",i.filter)}return b};Downsha.ClipFullStylingStrategy.prototype._inhFontForNode=function(a,c){for(var b=a.parentNode,e=[],f=[],g=["font-family","color","line-height"];b;){f.push(b);e.push(this.getNodeStyle(b,function(a){return g.indexOf(a)>=0?true:false}));if(!c||b==this.window.document.body)break;else b=b.parentElement}b=
new Downsha.ClipStyle;for(f=0;f<e.length;f++)for(var h=e[f],j=0;j<g.length;j++)if(!b[g[j]]&&h[g[j]]){d.debug("Adding "+g[j]+": "+h[g[j]]);b._addSimpleStyle(g[j],h[g[j]])}return b};Downsha.ClipFullStylingStrategy.prototype.styleForFloatClearingNode=function(a){if(a){a=new Downsha.ClipStyle;a._addSimpleStyle("clear","both");a._addSimpleStyle("width","0px");a._addSimpleStyle("height","0px");return a}return null}})();
(function(){var d=null;Downsha.Clip=function(a,c,b){d=Downsha.Logger.getInstance();this.__defineGetter__("fullPage",this.isFullPage);this.__defineGetter__("length",this.getLength);this.__defineGetter__("stylingStrategy",this.getStylingStrategy);this.__defineSetter__("stylingStrategy",this.setStylingStrategy);this.__defineGetter__("documentBase",this.getDocumentBase);this.__defineSetter__("documentBase",this.setDocumentBase);this.__defineGetter__("maxSize",this.getMaxSize);this.__defineSetter__("maxSize",
this.setMaxSize);this.initialize(a,c,b)};Downsha.Clip.NOKEEP_NODE_ATTRIBUTES={style:null,tabindex:null,"class":null,id:null,_downshaPreviewRect:null};Downsha.Clip.CONDITIONAL_NODES={EMBED:null,OBJECT:null};Downsha.Clip.NODE_NAME_TRANSLATIONS={HTML:"DIV",BODY:"DIV",FORM:"DIV",LABEL:"SPAN",FIELDSET:"DIV",LEGEND:"SPAN",SECTION:"DIV",CANVAS:"DIV",CUFON:"DIV","*":"DIV"};Downsha.Clip.SUPPORTED_NODES={A:null,ABBR:null,ACRONYM:null,ADDRESS:null,AREA:null,B:null,BASE:null,BASEFONT:null,BDO:null,BIG:null,BLOCKQUOTE:null,
BR:null,BUTTON:null,CAPTION:null,CENTER:null,CITE:null,CODE:null,COL:null,COLGROUP:null,DD:null,DEL:null,DFN:null,DIR:null,DIV:null,DL:null,DT:null,EM:null,EMBED:null,FIELDSET:null,FONT:null,FORM:null,FRAME:null,FRAMESET:null,H1:null,H2:null,H3:null,H4:null,H5:null,H6:null,HEAD:null,HR:null,HTML:null,I:null,IFRAME:null,IMG:null,INPUT:null,INS:null,KBD:null,LABEL:null,LEGEND:null,LI:null,LINK:null,MAP:null,MENU:null,META:null,NOBR:null,NOFRAMES:null,NOSCRIPT:null,OBJECT:null,OL:null,OPTGROUP:null,
OPTION:null,P:null,PARAM:null,PRE:null,Q:null,QUOTE:null,S:null,SAMP:null,SCRIPT:null,SELECT:null,SMALL:null,SPAN:null,STRIKE:null,STRONG:null,STYLE:null,SUB:null,SUP:null,TABLE:null,TBODY:null,TD:null,TEXTAREA:null,TFOOT:null,TH:null,THEAD:null,TITLE:null,TR:null,TT:null,U:null,UL:null,VAR:null,VIDEO:null};Downsha.Clip.REJECT_NODES={SCRIPT:null,STYLE:null,INPUT:null,SELECT:null,OPTION:null,OPTGROUP:null,TEXTAREA:null,NOSCRIPT:null,HEAD:null,DOWNSHADIV:null,CUFONTEXT:null,NOEMBED:null};Downsha.Clip.NON_ANCESTOR_NODES=
{OL:null,UL:null,LI:null};Downsha.Clip.SELF_CLOSING_NODES={IMG:null,INPUT:null,BR:null};Downsha.Clip.HTMLEncode=function(a){for(var c="",b=0;b<a.length;b++)var d=a.charCodeAt(b),f=a[b],c=d>127?c+("&#"+d+";"):f==">"?c+"&gt;":f=="<"?c+"&lt;":f=="&"?c+"&amp;":c+a[b];return c};Downsha.Clip.prototype.title=null;Downsha.Clip.prototype.location=null;Downsha.Clip.prototype.window=null;Downsha.Clip.prototype.selectionFinder=null;Downsha.Clip.prototype.deep=true;Downsha.Clip.prototype.content=null;Downsha.Clip.prototype.range=
null;Downsha.Clip.prototype._stylingStrategy=null;Downsha.Clip.prototype._documentBase=null;Downsha.Clip.prototype._maxSize=0;Downsha.Clip.prototype._verboseLog=false;Downsha.Clip.prototype.PREVIEW_ARTICLE_CLASS="downshaPreviewArticleContainer";Downsha.Clip.prototype.initialize=function(a,c,b){this.window=a?a:window;this.title=this.window.document.title;this.location=this.window.location;this.selectionFinder=new Downsha.SelectionFinder(this.window.document);this.range=null;if(c)this.stylingStrategy=
c;this.maxSize=b};Downsha.Clip.prototype.getDocumentBase=function(){if(this._documentBase==null){var a=this.window.document.getElementsByTagName("base");if(a.length>0)for(var c=0;c<a.length;c++){this.setDocumentBase(a[c].href);if(this._documentBase)break}if(!this._documentBase)this._documentBase=this.window.location.protocol+"//"+this.window.location.host+this.location.pathname.replace(/[^\/]+$/,"")}return this._documentBase};Downsha.Clip.prototype.setDocumentBase=function(a){this._documentBase=typeof a==
"string"&&a.indexOf("http")==0?a:null};Downsha.Clip.prototype.getMaxSize=function(){return this._maxSize};Downsha.Clip.prototype.setMaxSize=function(a){this._maxSize=parseInt(a);if(isNaN(this._maxSize)||a<0)this._maxSize=0};Downsha.Clip.prototype.getNodeStyle=function(a,c){var b=new Downsha.ClipStyle;this._verboseLog&&d.debug(">>> NODE: "+a.nodeName+"/"+a.nodeType);if(a&&typeof a.nodeType=="number"&&a.nodeType==1){var e=a.ownerDocument,e=e.defaultView?e.defaultView:this.window,f=typeof e.getMatchedCSSRules==
"function"?true:false;if(c){if(this._verboseLog){d.debug(">>> Getting computed style");d.debug("... "+e.getComputedStyle(a,null).length)}b=new Downsha.ClipStyle(e.getComputedStyle(a,null))}else if(f){this._verboseLog&&d.debug(">>> Getting matched rules");b=new Downsha.ClipStyle(e.getMatchedCSSRules(a))}}this._verboseLog&&d.debug(">>> "+a.nodeName+" style: "+b.toString());return b};Downsha.Clip.prototype.getNodeStylePropertyValue=function(a,c){if(a&&a.nodeType==Node.ELEMENT_NODE&&typeof c=="string"){var b=
a.ownerDocument;return(b.defaultView?b.defaultView:this.window).getComputedStyle(a,null).getPropertyValue(c)}return null};Downsha.Clip.prototype.setStylingStrategy=function(a){if(typeof a=="function"&&Downsha.inherits(a,Downsha.ClipStylingStrategy))this._stylingStrategy=new a(this.window);else if(a instanceof Downsha.ClipStylingStrategy)this._stylingStrategy=a;else if(a==null)this._stylingStrategy=null};Downsha.Clip.prototype.getStylingStrategy=function(){return this._stylingStrategy};Downsha.Clip.prototype.clipUrl=
function(){this.content=Downsha.Utils.createUrlClipContent(this.title,this.location.href,"http://www.google.com/s2/favicons?domain="+Downsha.Utils.urlDomain(this.location.href).toLowerCase());return true};Downsha.Clip.prototype.isFullPage=function(){return!this.hasSelection()};Downsha.Clip.prototype.hasSelection=function(){if(this.selectionFinder.hasSelection())return true;this.selectionFinder.find(this.deep);return this.selectionFinder.hasSelection()};Downsha.Clip.prototype.getSelection=function(){return this.hasSelection()?
this.selectionFinder.selection:null};Downsha.Clip.prototype.getRange=function(){return this.hasSelection()?this.selectionFinder.getRange():null};Downsha.Clip.prototype.hasBody=function(){return this.window&&this.window.document&&this.window.document.body&&this.window.document.body.tagName.toLowerCase()=="body"};Downsha.Clip.prototype.hasContentToClip=function(){return this.hasBody()||this.hasSelection()};Downsha.Clip.prototype.clipArticle=function(){d.debug("Clip.clipArticle");var a=0,c=0;d.isDebugEnabled()&&
(a=(new Date).getTime());var c=null,b=this.window.document.getElementsByClassName(this.PREVIEW_ARTICLE_CLASS);if(b&&b.length>0)c=b[0];else{b=new ExtractContentJS.LayeredExtractor;b.addHandler(b.factory.getHandler("Heuristics"));b=b.extract(this.window.document);if(b.isSuccess){c=b.content.asNode();Downsha.Utils.addElementClass(c,this.PREVIEW_ARTICLE_CLASS)}}if(!c){d.debug("Document has no article...");return false}this.content=this.serializeDOMNode(c,true);if(d.isDebugEnabled()){c=(new Date).getTime();
d.debug("Clipped article in "+(c-a)+" milliseconds")}return typeof this.content=="string"};Downsha.Clip.prototype.clipBody=function(){if(!this.hasBody()){d.debug("Document has no body...");return false}var a=0,c=0;if(d.isDebugEnabled()){d.debug("Getting body text: "+this);a=(new Date).getTime()}this.content=this.serializeDOMNode(this.window.document.body,true);if(d.isDebugEnabled()){c=(new Date).getTime();d.debug("Clipped body in "+(c-a)+" milliseconds")}return typeof this.content!="string"?false:
true};Downsha.Clip.prototype.clipSelection=function(){if(!this.hasSelection()){d.debug("Document has no selection...");return false}var a=0,c=0;if(this.range=this.getRange()){d.isDebugEnabled()&&(a=(new Date).getTime());for(var b=this.stylingStrategy&&this.range.commonAncestorContainer.nodeType==Node.TEXT_NODE&&this.range.commonAncestorContainer.parentNode?this.range.commonAncestorContainer.parentNode:this.range.commonAncestorContainer;typeof Downsha.Clip.NON_ANCESTOR_NODES[b.nodeName]!="undefined"&&
b.parentNode;){if(b.nodeName=="BODY")break;b=b.parentNode}this.content=this.serializeDOMNode(b,false);d.isDebugEnabled()&&(c=(new Date).getTime());this.range=null;if(d.isDebugEnabled()){d.debug("Success...");d.debug("Clipped selection in "+(c-a)+" milliseconds")}return true}this.range=null;d.debug("Failed to clip selection");return false};Downsha.Clip.prototype.rangeIntersectsNode=function(a){if(this.range){var c=a.ownerDocument.createRange();try{c.selectNode(a)}catch(b){c.selectNodeContents(a)}return this.range.compareBoundaryPoints(Range.START_TO_END,
c)==1&&this.range.compareBoundaryPoints(Range.END_TO_START,c)==-1}return false};Downsha.Clip.prototype.serializeDOMNode=function(a,c){var b="";if(this._includeFontFaceDescriptions&&this.stylingStrategy){var e=this.stylingStrategy.getFontFaceRules();if(e){for(var b=b+"<style>\n",f=0;f<e.length;f++)b=b+(e[f].cssText+"\n");b=b+"</style>\n"}}e=a;for(f=null;e;){if(this.maxSize>0&&b.length>this.maxSize){d.debug("Length of serialized content exceeds "+this.maxSize);this.sizeExceeded=true;if(typeof this.onsizeexceed==
"function")this.onsizeexceed();break}var g=this.range&&!this.rangeIntersectsNode(e)?false:true;this.isRejectedNode(e)&&(g=false);if(g&&e.nodeType==Node.TEXT_NODE)this.range?this.range.startContainer==e&&this.range.startContainer==this.range.endContainer?b=b+this.constructor.HTMLEncode(e.nodeValue.substring(this.range.startOffset,this.range.endOffset)):this.range.startContainer==e?b=b+this.constructor.HTMLEncode(e.nodeValue.substring(this.range.startOffset)):this.range.endContainer==e?b=b+this.constructor.HTMLEncode(e.nodeValue.substring(0,
this.range.endOffset)):this.range.commonAncestorContainer!=e&&(b=b+this.constructor.HTMLEncode(e.nodeValue)):b=b+this.constructor.HTMLEncode(e.nodeValue);else if(g&&e.nodeType==Node.ELEMENT_NODE&&this.isConditionalNode(e)){if(this.isNodeVisible(e)){g=null;this.stylingStrategy&&(g=this.stylingStrategy.styleForNode(e,a,c,f));g=this.serializeConditionalElement(e,g);typeof g=="string"&&g&&(b=b+g)}}else if(g&&e.nodeType==Node.ELEMENT_NODE&&!this.isConditionalNode(e)&&this.isNodeVisible(e)){var h=this.translateNodeName(e),
b=b+("<"+h),j=this.nodeAttributesToString(e);if(this.stylingStrategy){f=g=this.stylingStrategy.styleForNode(e,a,c,f);if(g instanceof Downsha.ClipStyle&&g.length>0){if(g["float"]&&g["float"]!="none"&&e.parentElement)e.parentElement._downsha_float_=true;j=j+(' style="'+g.toString().replace(/\"/g,"")+'"')}else typeof g=="string"&&(j=j+(' style="'+g.replace(/\"/g,"")+'"'))}j.length>0&&(b=b+(" "+j));if(e.hasChildNodes()){b=b+">";e=e.childNodes[0];continue}else b=this.isSelfClosingNode(e)?b+"/>":b+("></"+
h+">")}if(e.nextSibling)e=e.nextSibling;else if(e!=a){if(e.parentElement&&e.parentElement._downsha_float_){b=b+this._getFloatClearingElementString(e.parentElement);delete e.parentElement._downsha_float_}for(;e.parentNode;){e=e.parentNode;e==a&&(b=b+"<div style='clear: both'></div>");nodeName=this.translateNodeName(e);b=b+("</"+nodeName+">");if(e==a)break;else if(e.nextSibling){e=e.nextSibling;break}else if(e.parentElement&&e.parentElement._downsha_float_){b=b+this._getFloatClearingElementString(e.parentElement);
delete e.parentElement._downsha_float_}}if(e==a)break;else if(e.nodeName=="#document"||e.nodeType==Node.DOCUMENT_NODE)break}else break}return b};Downsha.Clip.prototype.getNodeString=function(a){var c=null;if(typeof a!="object"||a==null)c="[null]";else if(a&&a.nodeType==Node.TEXT_NODE)c=typeof a.nodeValue=="string"&&a.nodeValue.length>0?a.nodeName+" "+a.nodeValue:a.nodeName+" [empty]";else if(a&&a.nodeType==Node.ELEMENT_NODE){for(var c="<"+a.nodeName,a=a.attributes,b=0;b<a.length;b++)a[b]&&a[b].name&&
a[b].specified&&(c=a[b].value?c+(" "+a[b].name+'="'+a[b].value+'"'):c+(" "+a[b].name));c=c+">"}else{c="node";typeof a.nodeName=="string"&&a.nodeName.length>0&&(c=c+(" name: "+a.nodeName));typeof a.nodeType=="number"&&(c=c+(" type: "+a.nodeType));typeof a.nodeValue=="string"&&a.nodeValue.length>0&&(c=c+(" value: "+a.nodeValue))}return c};Downsha.Clip.prototype._getFloatClearingElementString=function(a){var c="";if(a&&this.stylingStrategy){var b=this.stylingStrategy.styleForFloatClearingNode(a);if(b&&
b.length>0){c="div";a.nodeName=="UL"||a.nodeName=="OL"?c="li":a.nodeName=="DL"&&(c="dd");c="<"+c+' style="'+b.toString()+'"></'+c+">"}}return c};Downsha.Clip.prototype.serializeConditionalElement=function(a,c){var b="";if(a&&a.nodeType==Node.ELEMENT_NODE){var d=a.ownerDocument||document,f=null;if(f=this.articleRules){var g=null,h=null;if(f.d){var j=Downsha.Utils.querySelectors(f.d,d);if(j)g=j.textContent}if(f.t)for(j=0;j<f.t.length;j++){var i=f.t[j],k=d;i.b==="relative"&&(k=a);var l=Downsha.Utils.querySelectors(i.s,
k);if(l){k="";if(i.d==="value")k=l.value;else if(i.d==="textContent")k=l.textContent;else if(i.d){k=l.getAttribute(i.d);if(i.d==="src"||i.d==="href")k=decodeURIComponent(k)}if(k){if(i.p){l=RegExp(i.p,"i");(k=k.match(l))&&k[1]&&(h=k[1])}else h=k;if(h&&i.m&&typeof i.r=="string"){l=RegExp(i.m,"i");h=h.replace(l,i.r)}if(h)break}}}if(g||h){b=b+'<div style="display:none;">';g&&(b=b+("<span>"+g+"</span>"));h&&(b=b+('<img src="'+h+'" />'));b=b+"</div>"}}}return b=b+this.serializePluginElement(a,c)};Downsha.Clip.prototype.serializePluginElement=
function(a,c){for(var b=function(a){for(var b="",a=a.attributes,c=0;c<a.length;c++)if(a[c]&&a[c].name&&a[c].specified&&typeof Downsha.Clip.NOKEEP_NODE_ATTRIBUTES[a[c].name]=="undefined"&&a[c].name.substring(0,2).toLowerCase()!="on"&&!(a[c].name=="href"&&a[c].value.substring(0,11).toLowerCase()=="javascript:")){b=b+(" "+a[c].name);a[c].value&&(b=b+('="'+a[c].value.replace('"',"&quot;")+'"'))}return b},d=c instanceof Downsha.ClipStyle?'style="'+c.toString()+'"':"",d="<"+a.nodeName+b(a)+" "+d+">",f=
a.children,g=0;g<f.length;g++)d=d+("<"+f[g].nodeName+b(f[g])+" />");return d=d+("</"+a.nodeName+">")};Downsha.Clip.prototype.isRejectedNode=function(a){return typeof Downsha.Clip.REJECT_NODES[a.nodeName.toUpperCase()]!="undefined"};Downsha.Clip.prototype.isConditionalNode=function(a){return typeof Downsha.Clip.CONDITIONAL_NODES[a.nodeName.toUpperCase()]!="undefined"};Downsha.Clip.prototype.isNodeVisible=function(a){var c=window.getComputedStyle(a,null),a=c.getPropertyValue("display"),b=c.getPropertyValue("visibility"),
c=c.getPropertyValue("position");return a!="none"&&!(b=="hidden"&&c=="absolute")?true:false};Downsha.Clip.prototype.isSelfClosingNode=function(a){return a&&typeof Downsha.Clip.SELF_CLOSING_NODES[a.nodeName.toUpperCase()]!="undefined"};Downsha.Clip.prototype.nodeAttributesToString=function(a){var c="",a=a.attributes;if(a!=null)for(var b=0;b<a.length;b++)if(typeof a[b].name=="string"&&typeof Downsha.Clip.NOKEEP_NODE_ATTRIBUTES[a[b].name.toLowerCase()]=="undefined"&&a[b].name.substring(0,2).toLowerCase()!=
"on"&&!(a[b].name.toLowerCase()=="href"&&a[b].value!=null&&a[b].value.length>0&&a[b].value.substring(0,11).toLowerCase()=="javascript:")){var d=a[b].value?a[b].value:"";if(a[b].name.toLowerCase()=="src"||a[b].name.toLowerCase()=="href"){typeof d=="string"&&d.length>0&&d.substring(0,4).toLowerCase().indexOf("http")!=0&&d.substring(0,11).toLowerCase().indexOf("data:image/")!=0&&(d=Downsha.Utils.absoluteUrl(d,this.getDocumentBase()));d.substring(0,4).toLowerCase().indexOf("http")==0&&(d=encodeURI(d))}else d=
Downsha.Utils.escapeXML(d);c=d?c+(" "+a[b].name+'="'+d+'"'):c+(" "+a[b].name)}return c.replace(/\s+$/,"")};Downsha.Clip.prototype.translateNodeName=function(a){a=Downsha.Clip.NODE_NAME_TRANSLATIONS[a.nodeName.toUpperCase()]||a.nodeName;return typeof Downsha.Clip.SUPPORTED_NODES[a.toUpperCase()]!="undefined"?a:Downsha.Clip.NODE_NAME_TRANSLATIONS["*"]};Downsha.Clip.prototype.toString=function(){return"Clip["+this.location+"] "+this.title};Downsha.Clip.prototype.getLength=function(){var a=0,c=this.toDataObject(),
b;for(b in c)a=a+((""+c[b]).length+b.length+2);return a-1};Downsha.Clip.prototype.toDataObject=function(){return{content:this.content,title:this.title,url:this.location.href,fullPage:this.fullPage}}})();
(function(){Downsha.AbstractStyleScript=function(){Downsha.Logger.getInstance();this.initialize()};Downsha.AbstractStyleScript.prototype.initialize=function(d){var a=this.getInitialStyleSheetUrls();a&&a.length>0&&this.injectStyleSheets(a,d)};Downsha.AbstractStyleScript.prototype.getInitialStyleSheetUrls=function(){return[]};Downsha.AbstractStyleScript.prototype.injectStyleSheets=function(d,a){for(var c=Downsha.Utils.getDocumentHead(a),b=0;b<d.length;b++){var e=d[b],f=a.createElement("link");f.setAttribute("rel",
"stylesheet");f.setAttribute("type","text/css");f.setAttribute("href",e);c&&c.appendChild(f)}}})();
(function(){var d=null;Downsha.ContentPreviewScript=function(a){d=Downsha.Logger.getInstance();this.initialize(a)};Downsha.inherit(Downsha.ContentPreviewScript,Downsha.AbstractStyleScript);Downsha.ContentPreviewScript._instance=null;Downsha.ContentPreviewScript.getInstance=function(){if(!this._instance)this._instance=new Downsha.ContentPreviewScript;return this._instance};Downsha.ContentPreviewScript.removeInstance=function(){this._instance=null};Downsha.ContentPreviewScript.prototype.window=null;
Downsha.ContentPreviewScript.prototype._contentVeil=null;Downsha.ContentPreviewScript.prototype._selectionFinder=null;Downsha.ContentPreviewScript.prototype.SELECTION_CTX_ATTRS={fillStyle:"rgba(255, 255, 0, 0.3)"};Downsha.ContentPreviewScript.prototype.PREVIEW_CTX_ATTRS={fillStyle:"rgba(255, 255, 255, 0)",strokeStyle:"rgba(255, 255, 0, 0.3)"};Downsha.ContentPreviewScript.prototype.URL_MAX_LENGTH=100;Downsha.ContentPreviewScript.prototype.PREVIEW_SCROLL_TOTAL_TIME=120;Downsha.ContentPreviewScript.prototype.PREVIEW_SCROLL_STEP_INTERVAL=
20;Downsha.ContentPreviewScript.prototype.PREVIEW_CONTENT_ID="downshaPreviewContainerID";Downsha.ContentPreviewScript.prototype.PREVIEW_CONTENT_CLASS="downshaPreviewContainer";Downsha.ContentPreviewScript.prototype.PREVIEW_CONTENT_URL_CLASS="downshaPreviewUrlContainer";Downsha.ContentPreviewScript.prototype.PREVIEW_ARTICLE_CLASS="downshaPreviewArticleContainer";Downsha.ContentPreviewScript.prototype._children=null;Downsha.ContentPreviewScript.prototype._parents=null;Downsha.ContentPreviewScript.prototype.initialStyleSheetUrls=
["resource://downsha-styles/contentpreview.css","resource://downsha-styles/contentclipper.css","resource://downsha-styles/contentveil.css"];Downsha.ContentPreviewScript.prototype.initialize=function(a){this.window=a?a:window;this.__defineGetter__("contentVeil",this.getContentVeil);this.__defineGetter__("selectionFinder",this.getSelectionFinder);Downsha.ContentPreviewScript.prototype.parent.initialize.apply(this,[this.window.document]);this._children=[];this._parents=[]};Downsha.ContentPreviewScript.prototype.getInitialStyleSheetUrls=
function(){return this.initialStyleSheetUrls};Downsha.ContentPreviewScript.prototype.previewFullPage=function(){d.debug("ContentPreviewScript.previewFullPage");this.clear()};Downsha.ContentPreviewScript.prototype.previewSelection=function(){d.debug("ContentPreviewScript.previewSelection");this.clear();var a=this.getSelectionRange();if(a){this.contentVeil.resetVeil();try{var c=a.getClientRects(),b;for(b in c)if(c[b]&&c[b].right>c[b].left&&c[b].bottom>c[b].top){d.debug("selection client rect: ("+c[b].left+
","+c[b].top+") * ("+c[b].right+","+c[b].bottom+")");c[b].width=c[b].right-c[b].left;c[b].height=c[b].top-c[b].bottom;this.outlineRect(Downsha.Utils.makeAbsoluteClientRect(c[b],this.window),false,this.SELECTION_CTX_ATTRS)}}catch(e){}}else{d.debug("Could not find selection");this.previewFullPage()}};Downsha.ContentPreviewScript.prototype.previewArticle=function(){d.debug("ContentPreviewScript.previewArticle");this.clear();this.contentVeil.resetVeil();var a=this.getRememberedPreview();if(a)this.outlinePreviewElement(a,
true);else{a=new ExtractContentJS.LayeredExtractor;a.addHandler(a.factory.getHandler("Heuristics"));a=a.extract(this.window.document);d.debug("extractRes.isSuccess "+a.isSuccess);if(a.isSuccess){a=a.content.asNode();d.debug("articleNode.nodeType == Node.ELEMENT_NODE : "+(a.nodeType==Node.ELEMENT_NODE));a=Downsha.Utils.getElementForNode(a);this.rememberPreview(a);this.outlinePreviewElement(a,true)}}};Downsha.ContentPreviewScript.prototype.previewURL=function(a,c,b){d.debug("ContentPreviewScript.previewURL");
this.clear();this.contentVeil.resetVeil();this.contentVeil.show();var a=a?a:this.window.document.title,c=c?c:this.window.location.href,b=b?b:"http://www.google.com/s2/favicons?domain="+Downsha.Utils.urlDomain(c).toLowerCase(),e=this.createContentElement(Downsha.Utils.createUrlClipElement(this.window.document,a,Downsha.Utils.shortWord(c,this.URL_MAX_LENGTH),b)),f=this;this.window.setTimeout(function(){f.showContentElement();var a=f.window.getComputedStyle(e,""),b=parseInt(a.getPropertyValue("width")),
c=parseInt(a.getPropertyValue("height"));if(b&&c){e.style.marginLeft=0-b/2+"px";e.style.marginTop=0-c/2+"px";e.style.setProperty("top",parseInt(a.getPropertyValue("top"))+f.window.document.documentElement.scrollTop+"px","important")}},100)};Downsha.ContentPreviewScript.prototype.getPreviousElementSibling=function(a){d.debug("ContentPreviewScript.getPreviousElementSibling");for(a=a&&a.previousElementSibling?a.previousElementSibling:a.previousSibling;a;){var c=a.nodeType==Node.ELEMENT_NODE&&(a.textContent.trim().length>
0||a.getElementsByTagName("IMG").length>0)?a.getBoundingClientRect():null,b=0;c&&(b=typeof c.width!="undefined"&&typeof c.height!="undefined"?c.width*c.height:(c.right-c.left)*(c.bottom-c.top));if(b>0)return a;a=a&&a.previousElementSibling?a.previousElementSibling:a.previousSibling}return null};Downsha.ContentPreviewScript.prototype.getNextElementSibling=function(a){d.debug("ContentPreviewScript.getNextElementSibling");for(a=a&&a.nextElementSibling?a.nextElementSibling:a.nextSibling;a;){var c=a.nodeType==
Node.ELEMENT_NODE&&(a.textContent.trim().length>0||a.getElementsByTagName("IMG").length>0)?a.getBoundingClientRect():null,b=0;c&&(b=typeof c.width!="undefined"&&typeof c.height!="undefined"?c.width*c.height:(c.right-c.left)*(c.bottom-c.top));if(b>0)return a;a=a&&a.nextElementSibling?a.nextElementSibling:a.nextSibling}return null};Downsha.ContentPreviewScript.prototype.getParentElement=function(a){d.debug("ContentPreviewScript.getParentElement");var c=a?a.getBoundingClientRect():null,b=0;c&&(b=typeof c.width!=
"undefined"&&typeof c.height!="undefined"?c.width*c.height:(c.right-c.left)*(c.bottom-c.top));for(c=a&&a.parentElement?a.parentElement:a.parentNode;c;){var e=c.nodeType==Node.ELEMENT_NODE&&(c.textContent.trim().length>0||c.getElementsByTagName("IMG").length>0)?c.getBoundingClientRect():null,f=0;e&&(f=typeof e.width!="undefined"&&typeof e.height!="undefined"?e.width*e.height:(e.right-e.left)*(e.bottom-e.top));if(f>0&&f>b){b=this._parents.indexOf(c);if(b>=0){this._parents.splice(b,1);this._children.splice(b,
1)}return this._parents[this._children.push(a)-1]=c}c=c&&c.parentElement?c.parentElement:c.parentNode}return null};Downsha.ContentPreviewScript.prototype.getChildElement=function(a){d.debug("ContentPreviewScript.getChildElement");var c=this._parents.indexOf(a);if(c>=0)return this._children[c];var b=a?a.getBoundingClientRect():null,c=0;b&&(c=typeof b.width!="undefined"&&typeof b.height!="undefined"?b.width*b.height:(b.right-b.left)*(b.bottom-b.top));if(a.children.length>0)for(b=0;b<a.children.length;b++){var e=
a.children[b],f=e.nodeType==Node.ELEMENT_NODE&&(e.textContent.trim().length>0||e.getElementsByTagName("IMG").length>0)?e.getBoundingClientRect():null,g=0;f&&(g=typeof f.width!="undefined"&&typeof f.height!="undefined"?f.width*f.height:(f.right-f.left)*(f.bottom-f.top));if(g>0&&g<c)return e}return null};Downsha.ContentPreviewScript.prototype.previewNudge=function(a){d.debug("ContentPreviewScript.previewNudge direction: "+a);var c=this.getRememberedPreview();if(c){var b=null;a==Downsha.Constants.RequestType.PREVIEW_NUDGE_PREVIOUS_SIBLING?
b=this.getPreviousElementSibling(c):a==Downsha.Constants.RequestType.PREVIEW_NUDGE_NEXT_SIBLING?b=this.getNextElementSibling(c):a==Downsha.Constants.RequestType.PREVIEW_NUDGE_PARENT?b=this.getParentElement(c):a==Downsha.Constants.RequestType.PREVIEW_NUDGE_CHILD&&(b=this.getChildElement(c));if(b){this.forgetPreview(c);this.contentVeil.resetVeil();this.outlinePreviewElement(b,true);this.rememberPreview(b)}}};Downsha.ContentPreviewScript.prototype.rememberPreview=function(a){this.forgetPreview();Downsha.Utils.addElementClass(a,
this.PREVIEW_ARTICLE_CLASS)};Downsha.ContentPreviewScript.prototype.forgetPreview=function(){var a=this.window.document.getElementsByClassName(this.PREVIEW_ARTICLE_CLASS);if(a&&a.length>0)for(var c=0;c<a.length;c++)Downsha.Utils.removeElementClass(a[c],this.PREVIEW_ARTICLE_CLASS)};Downsha.ContentPreviewScript.prototype.getRememberedPreview=function(){var a=this.window.document.getElementsByClassName(this.PREVIEW_ARTICLE_CLASS);return a&&a.length>0?a[0]:null};Downsha.ContentPreviewScript.prototype.createContentElement=
function(a){d.debug("ContentPreviewScript.createContentElement");var c=this.window.document,b=c.getElementById(this.PREVIEW_CONTENT_ID);if(!b){b=c.createElement("div");b.setAttribute("id",this.PREVIEW_CONTENT_ID);b.setAttribute("class",this.PREVIEW_CONTENT_CLASS+" "+this.PREVIEW_CONTENT_URL_CLASS);b.style.display="none";b.style.position="absolute";(c.body.parentNode||c.body).appendChild(b)}b.appendChild(a);return b};Downsha.ContentPreviewScript.prototype.removeContentElement=function(){d.debug("ContentPreviewScript.removeContentElement");
var a=this.window.document.getElementById(this.PREVIEW_CONTENT_ID);a&&a.parentNode&&a.parentNode.removeChild(a)};Downsha.ContentPreviewScript.prototype.getContentElement=function(){return this.window.document.getElementById(this.PREVIEW_CONTENT_ID)};Downsha.ContentPreviewScript.prototype.showContentElement=function(){d.debug("ContentPreviewScript.showContentElement");var a=this.getContentElement();if(a)a.style.display=""};Downsha.ContentPreviewScript.prototype.hideContentElement=function(){d.debug("ContentPreviewScript.hideContentElement");
var a=this.getContentElement();if(a)a.style.display="none"};Downsha.ContentPreviewScript.prototype.clear=function(){d.debug("ContentPreviewScript.clear");if(this._contentVeil){this.contentVeil.hide();this.contentVeil.clear()}this.removeContentElement()};Downsha.ContentPreviewScript.prototype.getContentVeil=function(){if(!this._contentVeil)this._contentVeil=new Downsha.ContentVeil(this.window);return this._contentVeil};Downsha.ContentPreviewScript.prototype.outlinePreviewElement=function(a,c){var b=
a._downshaPreviewRect;if(!b){for(var b=Downsha.Utils.getAbsoluteBoundingClientRect(a),e=a.getElementsByTagName("*"),f=0;f<e.length;f++){var g=e[f],h=g._downshaPreviewRect;if(!h){h=Downsha.Utils.getAbsoluteBoundingClientRect(g);if(g.childElementCount==0)g._downshaPreviewRect=h}h&&h.width*h.height!=0&&Downsha.Utils.expandRect(b,h)}b.width=b.right-b.left;b.height=b.bottom-b.top;a._downshaPreviewRect=b;a.className=a.className+" _downshaPreviewRect"}this.outlineRect(b,true,this.PREVIEW_CTX_ATTRS);if(c&&
b){e=b.left-this.window.innerWidth/2;b=b.top-this.window.innerHeight/2;d.debug("ContentPreviewScript.outlinePreviewElement scroll x: "+e+" y: "+b);Downsha.Scroller.scrollTo(this.window,e,b,this.PREVIEW_SCROLL_TOTAL_TIME,this.PREVIEW_SCROLL_STEP_INTERVAL)}};Downsha.ContentPreviewScript.prototype.outlineRect=function(a,c,b){d.debug("ContentPreviewScript.outlineRect");if(b){this.contentVeil.revealRect(a,c,b);this.contentVeil.show()}};Downsha.ContentPreviewScript.prototype.getSelectionFinder=function(){if(!this._selectionFinder)this._selectionFinder=
new Downsha.SelectionFinder(this.window.document);return this._selectionFinder};Downsha.ContentPreviewScript.prototype.getSelectionRange=function(){this.selectionFinder.find(true);return this.selectionFinder.hasSelection()?this.selectionFinder.getRange():null}})();
(function(){Downsha.Scroller=function(d){Downsha.Logger.getInstance();this.initialize(d)};Downsha.Scroller.scrollTo=function(d,a,c,b,e){b||(b=300);e||(e=10);this._instance&&this._instance.abort();this._instance=new Downsha.Scroller(d);this._instance.scrollTo({x:a,y:c},b,e)};Downsha.Scroller.prototype.window=null;Downsha.Scroller.prototype.initialize=function(d){this.window=d?d:window;this.initialPoint={x:this.window.pageXOffset?this.window.pageXOffset:this.window.document.body.scrollLeft,y:this.window.pageYOffset?
this.window.pageYOffset:this.window.document.body.scrollTop}};Downsha.Scroller.prototype.scrollTo=function(d,a,c){this.endPoint=d;this.step=0;this.calculatePath(a,c);var b=this;this.proc=this.window.setInterval(function(){b.doScroll()||b.abort()},c)};Downsha.Scroller.prototype.calculatePath=function(d,a){this.path=[];for(var c=this.initialPoint.x,b=this.initialPoint.y,e=this.endPoint.x,f=this.endPoint.y,g=Math.PI*a/d,h=-(Math.PI/2);h<Math.PI/2;h=h+g){var j=(1+Math.sin(h))/2;this.path.push({x:c+j*
(e-c),y:b+j*(f-b)})}};Downsha.Scroller.prototype.doScroll=function(){var d=this.path[++this.step];if(!d)return false;this.window.scrollTo(d.x,d.y);return true};Downsha.Scroller.prototype.abort=function(){if(this.proc){clearInterval(this.proc);this.proc=null}}})();
(function(){var d=null;Downsha.ContentVeil=function(a){d=Downsha.Logger.getInstance();this.initialize(a)};Downsha.ContentVeil.prototype.window=null;Downsha.ContentVeil.prototype.VEIL_ID="downshaContentVeil";Downsha.ContentVeil.prototype.VEIL_CLASS="downshaContentVeil";Downsha.ContentVeil.prototype.FILL_STYLE="rgba(0, 0, 0, 0.7)";Downsha.ContentVeil.prototype.FILL_HIGHLIGHT_STYLE="rgba(255, 255, 255, 0.3)";Downsha.ContentVeil.prototype.STROKE_STYLE="rgba(255, 255, 255, 0.9)";Downsha.ContentVeil.prototype.STROKE_WIDTH=
6;Downsha.ContentVeil.prototype.STROKE_CAP="round";Downsha.ContentVeil.prototype.STROKE_JOIN="round";Downsha.ContentVeil.prototype.ELEMENT_STYLE={position:"absolute",top:"0px",left:"0px",zIndex:"9999999999999990"};Downsha.ContentVeil.prototype.EMBED_TRANS_MARKER="downshaTransparent";Downsha.ContentVeil.prototype.EMBED_TRANS_PREVIEW_MARKER="downshaEmbedTransparent";Downsha.ContentVeil.prototype.initialize=function(a){this.window=a?a:window;this.veil=this.createVeilElement()};Downsha.ContentVeil.prototype.createVeilElement=
function(){var a=this.window.document.createElement("CANVAS");a.setAttribute("id",this.VEIL_ID);a.setAttribute("class",this.VEIL_CLASS);a.height=this.getBodyHeight();a.width=this.getBodyWidth();for(var c in this.ELEMENT_STYLE)a.style[c]=this.ELEMENT_STYLE[c];return a};Downsha.ContentVeil.prototype.revealElement=function(a){this.revealRect(Downsha.Utils.getAbsoluteBoundingClientRect(a))};Downsha.ContentVeil.prototype.revealRect=function(a,c,b){var d=this.getVeilContext(),f=0;if(c){f=Math.max(2,Math.min(a.bottom-
a.top,a.right-a.left)/8);f=Math.min(b&&b.lineWidth?b.lineWidth:this.STROKE_WIDTH,f)}var g=a.left-f,h=a.top-f,j=a.right-a.left+f*2,a=a.bottom-a.top+f*2;d.clearRect(g,h,j,a);d.fillStyle=b&&b.fillStyle?b.fillStyle:this.FILL_HIGHLIGHT_STYLE;d.fillRect(g,h,j,a);if(c){d.lineWidth=f;d.strokeStyle=b&&b.strokeStyle?b.strokeStyle:this.STROKE_STYLE;d.lineCap=b&&b.lineCap?b.lineCap:this.STROKE_CAP;d.lineJoin=b&&b.lineJoin?b.lineJoin:this.STROKE_JOIN;d.strokeRect(g,h,j,a)}};Downsha.ContentVeil.prototype.resetVeil=
function(){var a=this.getVeilContext();a.clearRect(0,0,this.getBodyWidth(),this.getBodyHeight());a.fillStyle=this.FILL_STYLE;a.lineWidth=0;a.moveTo(0,0);a.beginPath();a.lineTo(this.getBodyWidth(),0);a.lineTo(this.getBodyWidth(),this.getBodyHeight());a.lineTo(0,this.getBodyHeight());a.lineTo(0,0);a.closePath();a.fill()};Downsha.ContentVeil.prototype.getVeilElement=function(){if(!this._veil){this._veil=this.window.document.getElementById(this.VEIL_ID);if(!this._veil)this._veil=this.createVeilElement()}return this._veil};
Downsha.ContentVeil.prototype.getVeilContext=function(){if(!this._veilContext)this._veilContext=this.getVeilElement().getContext("2d");return this._veilContext};Downsha.ContentVeil.prototype.removeVeilElement=function(){this._veil&&this._veil.parentNode&&this._veil.parentNode.removeChild(this._veil)};Downsha.ContentVeil.prototype.getDefaultVeilParentElement=function(){return this.window.document.body.parentNode?this.window.document.body.parentNode:this.window.document.body};Downsha.ContentVeil.prototype.show=
function(){this.hideEmbeds(this.window.document,true);var a=this.getVeilElement();if(!a.parentNode){var c=this.getDefaultVeilParentElement();c&&c.appendChild(a)}a.style.display=""};Downsha.ContentVeil.prototype.hide=function(){this.unhideEmbeds(this.window.document,true);this.getVeilElement().style.display="none"};Downsha.ContentVeil.prototype.clear=function(){this.clearEmbeds(this.window.document,true)};Downsha.ContentVeil.prototype.getBodyHeight=function(){return Math.max(this.window.document.body.parentNode.scrollHeight,
this.window.document.body.scrollHeight)};Downsha.ContentVeil.prototype.getBodyWidth=function(){return this.window.document.body.parentNode.scrollWidth};Downsha.ContentVeil.prototype.hideEmbeds=function(a,c){var b=Downsha.Utils.findEmbeds(a);if(b&&b.length>0){d.debug("ContentVeil.hideEmbeds find "+b.length+" <object> and <embed> nodes");for(var e=a.defaultView?a.defaultView:this.window,f=0;f<b.length;f++){var g=b[f];if(typeof g[this.EMBED_TRANS_MARKER]!="undefined")this._hideEmbed(g);else{var h=e.getComputedStyle(g,
""),j=h.getPropertyValue("display"),h=h.getPropertyValue("visibility");if(!(j=="none"||h=="hidden")){j=g.classList?Array.prototype.slice.call(g.classList,0):[];j.push(this.EMBED_TRANS_MARKER);g.setAttribute("class",j.join(" "));g[this.EMBED_TRANS_MARKER]=null;this._hideEmbed(g)}}}}if(c)if((b=Downsha.Utils.findDocuments(a))&&b.length>0){d.debug("ContentVeil.hideEmbeds find "+b.length+" <frame> and <iframe> nodes");for(f=0;f<b.length;f++)b[f]&&this.hideEmbeds(b[f],c)}};Downsha.ContentVeil.prototype.unhideEmbeds=
function(a,c){var b=a.getElementsByClassName(this.EMBED_TRANS_MARKER);if(b&&b.length>0){d.debug("ContentVeil.unhideEmbeds find "+b.length+" <object> and <embed> nodes");for(var e=0;e<b.length;e++)b[e]&&this._unhideEmbed(b[e])}if(c)if((b=Downsha.Utils.findDocuments(a))&&b.length>0){d.debug("ContentVeil.unhideEmbeds find "+b.length+" <frame> and <iframe> nodes");for(e=0;e<b.length;e++)b[e]&&this.unhideEmbeds(b[e],c)}};Downsha.ContentVeil.prototype.clearEmbeds=function(a,c){var b=a.getElementsByClassName(this.EMBED_TRANS_MARKER);
if(b&&b.length>0){d.debug("ContentVeil.clearEmbeds find "+b.length+" <object> and <embed> nodes");for(var e=0;e<b.length;e++)b[e]&&this._clearEmbed(b[e])}if(c)if((b=Downsha.Utils.findDocuments(a))&&b.length>0){d.debug("ContentVeil.clearEmbeds find "+b.length+" <frame> and <iframe> nodes");for(e=0;e<b.length;e++)b[e]&&this.clearEmbeds(b[e],c)}};Downsha.ContentVeil.prototype._hideEmbed=function(a){var c=a[this.EMBED_TRANS_MARKER];if(c)c.style.display="block";a.style.visibility="hidden"};Downsha.ContentVeil.prototype._unhideEmbed=
function(a){var c=a[this.EMBED_TRANS_MARKER];if(c)c.style.display="none";a.style.visibility="visible"};Downsha.ContentVeil.prototype._clearEmbed=function(a){var c=a[this.EMBED_TRANS_MARKER];c&&c.parentNode&&c.parentNode.removeChild(c);a.style.visibility="visible";var c=a.classList?Array.prototype.slice.call(a.classList,0):[],b=-1;(b=c.indexOf(this.EMBED_TRANS_MARKER)>=0)&&c.splice(b,1);c.length>0?a.setAttribute("class",c.join(" ")):a.removeAttribute("class");try{delete a[this.EMBED_TRANS_MARKER]}catch(d){}}})();
(function(){var d=null;Downsha.PageInfo=function(a){d=Downsha.Logger.getInstance();this.initialize(a)};Downsha.PageInfo.prototype.article=null;Downsha.PageInfo.prototype.articleBoundingClientRect=null;Downsha.PageInfo.prototype.documentWidth=null;Downsha.PageInfo.prototype.documentHeight=null;Downsha.PageInfo.prototype.initialize=function(a){this.window=a?a:window;this.profile()};Downsha.PageInfo.prototype.profile=function(){d.debug("PageInfo.profile");this.profilePage();this.profileSelection();this.profileArticle()};
Downsha.PageInfo.prototype.profilePage=function(){d.debug("PageInfo.profilePage");this.documentWidth=Downsha.Utils.getDocumentWidth(this.window.document);this.documentHeight=Downsha.Utils.getDocumentHeight(this.window.document);this.documentLength=0;try{this.documentLength=this.window.document.body.textContent.length}catch(a){d.warn("Could not determine document's text length")}this.containsImages=false;try{var c=this.window.document.getElementsByTagName("IMG");if(c&&c.length>0)this.containsImages=
true}catch(b){d.warn("Could not determine whether document contains images")}};Downsha.PageInfo.prototype.profileSelection=function(){d.debug("PageInfo.profileSelection");var a=new Downsha.SelectionFinder(this.window.document);a.find(true);this.selection=a.hasSelection()?true:false};Downsha.PageInfo.prototype.profileArticle=function(){d.debug("PageInfo.profileArticle");var a=new ExtractContentJS.LayeredExtractor;a.addHandler(a.factory.getHandler("Heuristics"));a=a.extract(this.window.document);if(a.isSuccess){var c=
a.content.asNode();if(c){d.debug("articleNode is "+c);if(c=Downsha.Utils.getAbsoluteBoundingClientRect(c.parentNode)){this.articleBoundingClientRect=c;this.article=a.content.asNode()}}}}})();
